[WARNING] [2021-06-13 22:30:35,006] [2494:140046214436672] - data_io.py[line:855]: DataIO is deprecated, and will be removed in 1.7, use DataTransform module instead
[ERROR] [2021-06-13 22:30:35,008] [2494:140046214436672] - task_executor.py[line:191]: not enough values to unpack (expected 4, got 2)
Traceback (most recent call last):
  File "/fate/python/fate_flow/operation/task_executor.py", line 168, in run_task
    run_object.run(component_parameters_on_party, task_run_args)
  File "/fate/python/federatedml/model_base.py", line 87, in run
    running_funcs = self.component_properties.extract_running_rules(args, self)
  File "/fate/python/federatedml/util/component_properties.py", line 238, in extract_running_rules
    train_data, validate_data, test_data, data = self.extract_input_data(args, model)
ValueError: not enough values to unpack (expected 4, got 2)
[WARNING] [2021-06-13 22:31:13,839] [2738:139936069863232] - data_io.py[line:855]: DataIO is deprecated, and will be removed in 1.7, use DataTransform module instead
[ERROR] [2021-06-13 22:31:13,840] [2738:139936069863232] - task_executor.py[line:191]: not enough values to unpack (expected 4, got 2)
Traceback (most recent call last):
  File "/fate/python/fate_flow/operation/task_executor.py", line 168, in run_task
    run_object.run(component_parameters_on_party, task_run_args)
  File "/fate/python/federatedml/model_base.py", line 87, in run
    running_funcs = self.component_properties.extract_running_rules(args, self)
  File "/fate/python/federatedml/util/component_properties.py", line 238, in extract_running_rules
    train_data, validate_data, test_data, data = self.extract_input_data(args, model)
ValueError: not enough values to unpack (expected 4, got 2)
