[INFO] [2021-06-13 16:51:35,588] [8:139726518462208] - dag_scheduler.py[line:40]: submit job, job_id 202106131651355868977, body {'job_dsl': {'components': {'reader_0': {'module': 'Reader', 'output': {'data': ['data']}}, 'dataio_0': {'module': 'DataIO', 'input': {'data': {'data': ['reader_0.data']}}, 'output': {'data': ['data'], 'model': ['model']}}, 'intersection_0': {'module': 'Intersection', 'input': {'data': {'data': ['dataio_0.data']}}, 'output': {'data': ['data']}}, 'hetero_secure_boost_0': {'module': 'HeteroSecureBoost', 'input': {'data': {'train_data': ['intersection_0.data']}}, 'output': {'data': ['data'], 'model': ['model']}}}}, 'job_runtime_conf': {'dsl_version': 2, 'initiator': {'role': 'guest', 'party_id': 9999}, 'role': {'host': [9998], 'guest': [9999]}, 'job_parameters': {'common': {'job_type': 'train', 'backend': 0, 'work_mode': 0}}, 'component_parameters': {'common': {'hetero_secure_boost_0': {'task_type': 'classification', 'objective_param': {'objective': 'cross_entropy'}, 'num_trees': 3, 'cv_param': {'need_cv': True, 'n_splits': 5, 'shuffle': False, 'random_seed': 103}, 'validation_freqs': 1, 'encrypt_param': {'method': 'iterativeAffine'}, 'tree_param': {'max_depth': 3}}}, 'role': {'guest': {'0': {'reader_0': {'table': {'name': 'breast_hetero_guest', 'namespace': 'experiment'}}, 'dataio_0': {'with_label': True, 'output_format': 'dense'}}}, 'host': {'0': {'reader_0': {'table': {'name': 'breast_hetero_host', 'namespace': 'experiment'}}, 'dataio_0': {'with_label': False}}}}}, 'conf_path': 'test_secureboost_cross_validation_binary_conf.json', 'dsl_path': 'test_secureboost_cross_validation_dsl.json'}}
[INFO] [2021-06-13 16:51:35,648] [8:139727092389632] - job_controller.py[line:52]: job parameters:{'job_type': 'train', 'work_mode': 0, 'backend': 0, 'computing_engine': 'STANDALONE', 'federation_engine': 'STANDALONE', 'storage_engine': 'STANDALONE', 'engines_address': {}, 'federated_mode': 'SINGLE', 'task_parallelism': 1, 'computing_partitions': 4, 'federated_status_collect_type': 'PULL', 'model_id': 'guest-9999#host-9998#model', 'model_version': '202106131651355868977', 'eggroll_run': {}, 'spark_run': {}, 'rabbitmq_run': {}, 'pulsar_run': {}, 'adaptation_parameters': {'task_nodes': 1, 'task_cores_per_node': 4, 'task_memory_per_node': 0, 'request_task_cores': 4, 'if_initiator_baseline': True}}
[INFO] [2021-06-13 16:51:35,780] [8:139727092389632] - job_controller.py[line:52]: job parameters:{'job_type': 'train', 'work_mode': 0, 'backend': 0, 'computing_engine': 'STANDALONE', 'federation_engine': 'STANDALONE', 'storage_engine': 'STANDALONE', 'engines_address': {}, 'federated_mode': 'SINGLE', 'task_parallelism': 1, 'computing_partitions': 4, 'federated_status_collect_type': 'PULL', 'model_id': 'guest-9999#host-9998#model', 'model_version': '202106131651355868977', 'eggroll_run': {}, 'spark_run': {}, 'rabbitmq_run': {}, 'pulsar_run': {}, 'adaptation_parameters': {'task_nodes': 1, 'task_cores_per_node': 4, 'task_memory_per_node': 0, 'request_task_cores': 4, 'if_initiator_baseline': True}}
[INFO] [2021-06-13 16:51:35,890] [8:139726518462208] - dag_scheduler.py[line:122]: submit job successfully, job id is 202106131651355868977, model id is guest-9999#host-9998#model
[INFO] [2021-06-13 16:51:37,514] [8:139726560425728] - federated_scheduler.py[line:39]: try to apply job 202106131651355868977 resource
[INFO] [2021-06-13 16:51:37,541] [8:139726518462208] - resource_manager.py[line:176]: apply job 202106131651355868977 resource(cores 4 memory 0) on host 9998 successfully, remaining cores: 16 remaining memory: 0
[INFO] [2021-06-13 16:51:37,567] [8:139726518462208] - resource_manager.py[line:176]: apply job 202106131651355868977 resource(cores 4 memory 0) on guest 9999 successfully, remaining cores: 12 remaining memory: 0
[INFO] [2021-06-13 16:51:37,575] [8:139726560425728] - federated_scheduler.py[line:42]: apply job 202106131651355868977 resource successfully
[INFO] [2021-06-13 16:51:37,575] [8:139726560425728] - dag_scheduler.py[line:279]: try to start job 202106131651355868977 on initiator guest 9999
[INFO] [2021-06-13 16:51:37,595] [8:139726518462208] - job_controller.py[line:261]: try to start job 202106131651355868977 on host 9998
[INFO] [2021-06-13 16:51:37,595] [8:139726518462208] - job_saver.py[line:45]: try to update job 202106131651355868977 status to running
[INFO] [2021-06-13 16:51:37,618] [8:139726518462208] - job_saver.py[line:48]: update job 202106131651355868977 status successfully
[INFO] [2021-06-13 16:51:37,618] [8:139726518462208] - job_saver.py[line:61]: try to update job 202106131651355868977
[INFO] [2021-06-13 16:51:37,635] [8:139726518462208] - job_saver.py[line:64]: job 202106131651355868977 update successfully: {'job_id': '202106131651355868977', 'role': 'host', 'party_id': 9998, 'status': 'running', 'start_time': 1623603097595}
[INFO] [2021-06-13 16:51:37,635] [8:139726518462208] - job_controller.py[line:275]: start job 202106131651355868977 on host 9998 successfully
[INFO] [2021-06-13 16:51:37,645] [8:139726518462208] - job_controller.py[line:261]: try to start job 202106131651355868977 on guest 9999
[INFO] [2021-06-13 16:51:37,645] [8:139726518462208] - job_saver.py[line:45]: try to update job 202106131651355868977 status to running
[INFO] [2021-06-13 16:51:37,665] [8:139726518462208] - job_saver.py[line:48]: update job 202106131651355868977 status successfully
[INFO] [2021-06-13 16:51:37,665] [8:139726518462208] - job_saver.py[line:61]: try to update job 202106131651355868977
[INFO] [2021-06-13 16:51:37,686] [8:139726518462208] - job_saver.py[line:64]: job 202106131651355868977 update successfully: {'job_id': '202106131651355868977', 'role': 'guest', 'party_id': 9999, 'status': 'running', 'start_time': 1623603097645}
[INFO] [2021-06-13 16:51:37,686] [8:139726518462208] - job_controller.py[line:275]: start job 202106131651355868977 on guest 9999 successfully
[INFO] [2021-06-13 16:51:37,690] [8:139726560425728] - dag_scheduler.py[line:292]: start job 202106131651355868977 on initiator guest 9999
[INFO] [2021-06-13 16:51:37,702] [8:139726560425728] - dag_scheduler.py[line:247]: reset job 202106131651355868977 ready signal True
[INFO] [2021-06-13 16:51:37,712] [8:139726560425728] - dag_scheduler.py[line:298]: scheduling job 202106131651355868977
[INFO] [2021-06-13 16:51:37,728] [8:139726560425728] - task_scheduler.py[line:28]: scheduling job 202106131651355868977 tasks
[INFO] [2021-06-13 16:51:37,746] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131651355868977 task 202106131651355868977_reader_0 0 status is waiting, calculate by task party status list: ['waiting', 'waiting']
[INFO] [2021-06-13 16:51:37,757] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131651355868977 task 202106131651355868977_dataio_0 0 status is waiting, calculate by task party status list: ['waiting', 'waiting']
[INFO] [2021-06-13 16:51:37,767] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131651355868977 task 202106131651355868977_intersection_0 0 status is waiting, calculate by task party status list: ['waiting', 'waiting']
[INFO] [2021-06-13 16:51:37,777] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131651355868977 task 202106131651355868977_hetero_secure_boost_0 0 status is waiting, calculate by task party status list: ['waiting', 'waiting']
[INFO] [2021-06-13 16:51:37,777] [8:139726560425728] - task_scheduler.py[line:80]: try to start job 202106131651355868977 task 202106131651355868977_reader_0 0 on guest 9999
[INFO] [2021-06-13 16:51:37,791] [8:139726560425728] - resource_manager.py[line:286]: task 202106131651355868977_reader_0 0 apply resource successfully
[INFO] [2021-06-13 16:51:37,791] [8:139726560425728] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0 status
[INFO] [2021-06-13 16:51:37,807] [8:139726560425728] - job_saver.py[line:74]: update job 202106131651355868977 task 202106131651355868977_reader_0 0 status successfully: {'job_id': '202106131651355868977', 'task_id': '202106131651355868977_reader_0', 'task_version': 0, 'role': 'guest', 'party_id': '9999', 'status': 'running'}
[INFO] [2021-06-13 16:51:37,807] [8:139726560425728] - task_scheduler.py[line:93]: start job 202106131651355868977 task 202106131651355868977_reader_0 0 on guest 9999
[INFO] [2021-06-13 16:51:37,807] [8:139726560425728] - federated_scheduler.py[line:192]: job 202106131651355868977 task 202106131651355868977_reader_0 0 is running, sync to all party
[INFO] [2021-06-13 16:51:37,830] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0 status
[INFO] [2021-06-13 16:51:37,848] [8:139726518462208] - job_saver.py[line:74]: update job 202106131651355868977 task 202106131651355868977_reader_0 0 status successfully: {'job_id': '202106131651355868977', 'task_id': '202106131651355868977_reader_0', 'task_version': '0', 'role': 'host', 'party_id': '9998', 'status': 'running'}
[INFO] [2021-06-13 16:51:37,865] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0 status
[INFO] [2021-06-13 16:51:37,874] [8:139726518462208] - job_saver.py[line:76]: update job 202106131651355868977 task 202106131651355868977_reader_0 0 status update does not take effect: {'job_id': '202106131651355868977', 'task_id': '202106131651355868977_reader_0', 'task_version': '0', 'role': 'guest', 'party_id': '9999', 'status': 'running'}
[WARNING] [2021-06-13 16:51:37,887] [8:139726560425728] - federated_scheduler.py[line:260]: an error occurred while status/running the task to role guest party 9999: 
update task status failed
[INFO] [2021-06-13 16:51:37,888] [8:139726560425728] - federated_scheduler.py[line:197]: sync job 202106131651355868977 task 202106131651355868977_reader_0 0 status running to all party failed: 
{'host': {9998: {'retcode': 0, 'retmsg': 'success'}}, 'guest': {9999: {'retcode': 103, 'retmsg': 'update task status failed'}}}
[INFO] [2021-06-13 16:51:37,915] [8:139726518462208] - task_controller.py[line:71]: try to start job 202106131651355868977 task 202106131651355868977_reader_0 0 on host 9998 executor subprocess
[INFO] [2021-06-13 16:51:37,921] [8:139726518462208] - task_controller.py[line:90]: use computing engine STANDALONE
[INFO] [2021-06-13 16:51:37,921] [8:139726518462208] - task_controller.py[line:145]: job 202106131651355868977 task 202106131651355868977_reader_0 0 on host 9998 executor subprocess is ready
[INFO] [2021-06-13 16:51:37,921] [8:139726518462208] - job_utils.py[line:310]: start process command: /usr/local/bin/python /fate/python/fate_flow/operation/task_executor.py -j 202106131651355868977 -n reader_0 -t 202106131651355868977_reader_0 -v 0 -r host -p 9998 -c /fate/jobs/202106131651355868977/host/9998/reader_0/202106131651355868977_reader_0/0/task_parameters.json --run_ip 127.0.0.1 --job_server 127.0.0.1:9380
[INFO] [2021-06-13 16:51:37,929] [8:139726518462208] - job_utils.py[line:334]: start process command: /usr/local/bin/python /fate/python/fate_flow/operation/task_executor.py -j 202106131651355868977 -n reader_0 -t 202106131651355868977_reader_0 -v 0 -r host -p 9998 -c /fate/jobs/202106131651355868977/host/9998/reader_0/202106131651355868977_reader_0/0/task_parameters.json --run_ip 127.0.0.1 --job_server 127.0.0.1:9380 successfully, pid is 3817
[INFO] [2021-06-13 16:51:37,930] [8:139726518462208] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0
[INFO] [2021-06-13 16:51:37,952] [8:139726518462208] - job_saver.py[line:84]: job 202106131651355868977 task 202106131651355868977_reader_0 0 update successfully
[INFO] [2021-06-13 16:51:37,957] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0 status
[INFO] [2021-06-13 16:51:37,972] [8:139726518462208] - job_saver.py[line:74]: update job 202106131651355868977 task 202106131651355868977_reader_0 0 status successfully: {'job_id': '202106131651355868977', 'task_id': '202106131651355868977_reader_0', 'task_version': '0', 'role': 'host', 'party_id': '9998', 'party_status': 'running', 'start_time': 1623603097930}
[INFO] [2021-06-13 16:51:37,979] [8:139726518462208] - task_controller.py[line:164]: job 202106131651355868977 task 202106131651355868977_reader_0 0 on host 9998 executor subprocess start success
[INFO] [2021-06-13 16:51:37,999] [8:139726518462208] - task_controller.py[line:71]: try to start job 202106131651355868977 task 202106131651355868977_reader_0 0 on guest 9999 executor subprocess
[INFO] [2021-06-13 16:51:38,004] [8:139726518462208] - task_controller.py[line:90]: use computing engine STANDALONE
[INFO] [2021-06-13 16:51:38,005] [8:139726518462208] - task_controller.py[line:145]: job 202106131651355868977 task 202106131651355868977_reader_0 0 on guest 9999 executor subprocess is ready
[INFO] [2021-06-13 16:51:38,005] [8:139726518462208] - job_utils.py[line:310]: start process command: /usr/local/bin/python /fate/python/fate_flow/operation/task_executor.py -j 202106131651355868977 -n reader_0 -t 202106131651355868977_reader_0 -v 0 -r guest -p 9999 -c /fate/jobs/202106131651355868977/guest/9999/reader_0/202106131651355868977_reader_0/0/task_parameters.json --run_ip 127.0.0.1 --job_server 127.0.0.1:9380
[INFO] [2021-06-13 16:51:38,011] [8:139726518462208] - job_utils.py[line:334]: start process command: /usr/local/bin/python /fate/python/fate_flow/operation/task_executor.py -j 202106131651355868977 -n reader_0 -t 202106131651355868977_reader_0 -v 0 -r guest -p 9999 -c /fate/jobs/202106131651355868977/guest/9999/reader_0/202106131651355868977_reader_0/0/task_parameters.json --run_ip 127.0.0.1 --job_server 127.0.0.1:9380 successfully, pid is 3819
[INFO] [2021-06-13 16:51:38,012] [8:139726518462208] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0
[INFO] [2021-06-13 16:51:38,033] [8:139726518462208] - job_saver.py[line:84]: job 202106131651355868977 task 202106131651355868977_reader_0 0 update successfully
[INFO] [2021-06-13 16:51:38,038] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0 status
[INFO] [2021-06-13 16:51:38,055] [8:139726518462208] - job_saver.py[line:74]: update job 202106131651355868977 task 202106131651355868977_reader_0 0 status successfully: {'job_id': '202106131651355868977', 'task_id': '202106131651355868977_reader_0', 'task_version': '0', 'role': 'guest', 'party_id': '9999', 'party_status': 'running', 'start_time': 1623603098012}
[INFO] [2021-06-13 16:51:38,059] [8:139726518462208] - task_controller.py[line:164]: job 202106131651355868977 task 202106131651355868977_reader_0 0 on guest 9999 executor subprocess start success
[INFO] [2021-06-13 16:51:38,064] [8:139726560425728] - task_scheduler.py[line:75]: finish scheduling job 202106131651355868977 tasks
[INFO] [2021-06-13 16:51:38,065] [8:139726560425728] - dag_scheduler.py[line:310]: Job 202106131651355868977 status is running, calculate by task status list: ['running', 'waiting', 'waiting', 'waiting']
[INFO] [2021-06-13 16:51:38,065] [8:139726560425728] - dag_scheduler.py[line:325]: finish scheduling job 202106131651355868977
[INFO] [2021-06-13 16:51:39,853] [3817:140379247499072] - task_executor.py[line:56]: enter task process
[INFO] [2021-06-13 16:51:39,854] [3817:140379247499072] - task_executor.py[line:57]: Namespace(component_name='reader_0', config='/fate/jobs/202106131651355868977/host/9998/reader_0/202106131651355868977_reader_0/0/task_parameters.json', job_id='202106131651355868977', job_server='127.0.0.1:9380', party_id=9998, role='host', run_ip='127.0.0.1', task_id='202106131651355868977_reader_0', task_version=0)
[INFO] [2021-06-13 16:51:39,916] [3819:139878658987840] - task_executor.py[line:56]: enter task process
[INFO] [2021-06-13 16:51:39,917] [3819:139878658987840] - task_executor.py[line:57]: Namespace(component_name='reader_0', config='/fate/jobs/202106131651355868977/guest/9999/reader_0/202106131651355868977_reader_0/0/task_parameters.json', job_id='202106131651355868977', job_server='127.0.0.1:9380', party_id=9999, role='guest', run_ip='127.0.0.1', task_id='202106131651355868977_reader_0', task_version=0)
[INFO] [2021-06-13 16:51:40,029] [8:139726518462208] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0
[INFO] [2021-06-13 16:51:40,044] [8:139726518462208] - job_saver.py[line:84]: job 202106131651355868977 task 202106131651355868977_reader_0 0 update successfully
[INFO] [2021-06-13 16:51:40,048] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0 status
[INFO] [2021-06-13 16:51:40,052] [8:139726518462208] - job_saver.py[line:76]: update job 202106131651355868977 task 202106131651355868977_reader_0 0 status update does not take effect: {'job_id': '202106131651355868977', 'component_name': 'reader_0', 'task_id': '202106131651355868977_reader_0', 'task_version': '0', 'role': 'host', 'party_id': '9998', 'run_ip': '127.0.0.1', 'run_pid': 3817, 'party_status': 'running'}
[INFO] [2021-06-13 16:51:40,097] [8:139726518462208] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0
[INFO] [2021-06-13 16:51:40,113] [8:139726560425728] - dag_scheduler.py[line:298]: scheduling job 202106131651355868977
[INFO] [2021-06-13 16:51:40,126] [8:139726518462208] - job_saver.py[line:84]: job 202106131651355868977 task 202106131651355868977_reader_0 0 update successfully
[INFO] [2021-06-13 16:51:40,136] [8:139726560425728] - task_scheduler.py[line:28]: scheduling job 202106131651355868977 tasks
[INFO] [2021-06-13 16:51:40,141] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0 status
[INFO] [2021-06-13 16:51:40,154] [8:139726518462208] - job_saver.py[line:76]: update job 202106131651355868977 task 202106131651355868977_reader_0 0 status update does not take effect: {'job_id': '202106131651355868977', 'component_name': 'reader_0', 'task_id': '202106131651355868977_reader_0', 'task_version': '0', 'role': 'guest', 'party_id': '9999', 'run_ip': '127.0.0.1', 'run_pid': 3819, 'party_status': 'running'}
[INFO] [2021-06-13 16:51:40,208] [8:139726560425728] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0 status
[INFO] [2021-06-13 16:51:40,214] [8:139726560425728] - job_saver.py[line:76]: update job 202106131651355868977 task 202106131651355868977_reader_0 0 status update does not take effect: {'elapsed': None, 'end_time': None, 'job_id': '202106131651355868977', 'party_id': '9998', 'party_status': 'running', 'role': 'host', 'start_time': 1623603097930, 'status': 'running', 'task_id': '202106131651355868977_reader_0', 'task_version': 0, 'update_time': 1623603095671}
[INFO] [2021-06-13 16:51:40,214] [8:139726560425728] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0
[INFO] [2021-06-13 16:51:40,231] [8:139726560425728] - job_saver.py[line:84]: job 202106131651355868977 task 202106131651355868977_reader_0 0 update successfully
[INFO] [2021-06-13 16:51:40,231] [8:139726560425728] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0 status
[INFO] [2021-06-13 16:51:40,239] [8:139726560425728] - job_saver.py[line:76]: update job 202106131651355868977 task 202106131651355868977_reader_0 0 status update does not take effect: {'elapsed': None, 'end_time': None, 'job_id': '202106131651355868977', 'party_id': '9999', 'party_status': 'running', 'role': 'guest', 'start_time': 1623603098012, 'status': 'running', 'task_id': '202106131651355868977_reader_0', 'task_version': 0, 'update_time': 1623603095800}
[INFO] [2021-06-13 16:51:40,239] [8:139726560425728] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0
[INFO] [2021-06-13 16:51:40,260] [8:139726560425728] - job_saver.py[line:84]: job 202106131651355868977 task 202106131651355868977_reader_0 0 update successfully
[INFO] [2021-06-13 16:51:40,268] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131651355868977 task 202106131651355868977_reader_0 0 status is running, calculate by task party status list: ['running', 'running']
[INFO] [2021-06-13 16:51:40,280] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131651355868977 task 202106131651355868977_dataio_0 0 status is waiting, calculate by task party status list: ['waiting', 'waiting']
[INFO] [2021-06-13 16:51:40,294] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131651355868977 task 202106131651355868977_intersection_0 0 status is waiting, calculate by task party status list: ['waiting', 'waiting']
[INFO] [2021-06-13 16:51:40,303] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131651355868977 task 202106131651355868977_hetero_secure_boost_0 0 status is waiting, calculate by task party status list: ['waiting', 'waiting']
[INFO] [2021-06-13 16:51:40,303] [8:139726560425728] - task_scheduler.py[line:75]: finish scheduling job 202106131651355868977 tasks
[INFO] [2021-06-13 16:51:40,303] [8:139726560425728] - dag_scheduler.py[line:310]: Job 202106131651355868977 status is running, calculate by task status list: ['running', 'waiting', 'waiting', 'waiting']
[INFO] [2021-06-13 16:51:40,304] [8:139726560425728] - dag_scheduler.py[line:325]: finish scheduling job 202106131651355868977
[INFO] [2021-06-13 16:51:40,514] [8:139726518462208] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0
[INFO] [2021-06-13 16:51:40,530] [8:139726518462208] - job_saver.py[line:84]: job 202106131651355868977 task 202106131651355868977_reader_0 0 update successfully
[INFO] [2021-06-13 16:51:40,535] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0 status
[INFO] [2021-06-13 16:51:40,557] [8:139726518462208] - job_saver.py[line:74]: update job 202106131651355868977 task 202106131651355868977_reader_0 0 status successfully: {'job_id': '202106131651355868977', 'component_name': 'reader_0', 'task_id': '202106131651355868977_reader_0', 'task_version': '0', 'role': 'host', 'party_id': '9998', 'run_ip': '127.0.0.1', 'run_pid': 3817, 'party_status': 'failed', 'end_time': 1623603100509, 'elapsed': 655}
[INFO] [2021-06-13 16:51:40,572] [8:139726518462208] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0
[INFO] [2021-06-13 16:51:40,584] [8:139726518462208] - job_saver.py[line:84]: job 202106131651355868977 task 202106131651355868977_reader_0 0 update successfully
[INFO] [2021-06-13 16:51:40,592] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0 status
[INFO] [2021-06-13 16:51:40,597] [8:139726518462208] - job_saver.py[line:76]: update job 202106131651355868977 task 202106131651355868977_reader_0 0 status update does not take effect: {'job_id': '202106131651355868977', 'component_name': 'reader_0', 'task_id': '202106131651355868977_reader_0', 'task_version': '0', 'role': 'host', 'party_id': '9998', 'run_ip': '127.0.0.1', 'run_pid': 3817, 'party_status': 'failed', 'end_time': 1623603100509, 'elapsed': 655}
[INFO] [2021-06-13 16:51:40,686] [8:139726518462208] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0
[INFO] [2021-06-13 16:51:40,703] [8:139726518462208] - job_saver.py[line:84]: job 202106131651355868977 task 202106131651355868977_reader_0 0 update successfully
[INFO] [2021-06-13 16:51:40,709] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0 status
[INFO] [2021-06-13 16:51:40,723] [8:139726518462208] - job_saver.py[line:74]: update job 202106131651355868977 task 202106131651355868977_reader_0 0 status successfully: {'job_id': '202106131651355868977', 'component_name': 'reader_0', 'task_id': '202106131651355868977_reader_0', 'task_version': '0', 'role': 'guest', 'party_id': '9999', 'run_ip': '127.0.0.1', 'run_pid': 3819, 'party_status': 'failed', 'end_time': 1623603100678, 'elapsed': 761}
[INFO] [2021-06-13 16:51:40,736] [8:139726518462208] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0
[INFO] [2021-06-13 16:51:40,751] [8:139726518462208] - job_saver.py[line:84]: job 202106131651355868977 task 202106131651355868977_reader_0 0 update successfully
[INFO] [2021-06-13 16:51:40,756] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0 status
[INFO] [2021-06-13 16:51:40,760] [8:139726518462208] - job_saver.py[line:76]: update job 202106131651355868977 task 202106131651355868977_reader_0 0 status update does not take effect: {'job_id': '202106131651355868977', 'component_name': 'reader_0', 'task_id': '202106131651355868977_reader_0', 'task_version': '0', 'role': 'guest', 'party_id': '9999', 'run_ip': '127.0.0.1', 'run_pid': 3819, 'party_status': 'failed', 'end_time': 1623603100678, 'elapsed': 761}
[INFO] [2021-06-13 16:51:42,345] [8:139726560425728] - dag_scheduler.py[line:298]: scheduling job 202106131651355868977
[INFO] [2021-06-13 16:51:42,361] [8:139726560425728] - task_scheduler.py[line:28]: scheduling job 202106131651355868977 tasks
[INFO] [2021-06-13 16:51:42,422] [8:139726560425728] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0 status
[INFO] [2021-06-13 16:51:42,429] [8:139726560425728] - job_saver.py[line:76]: update job 202106131651355868977 task 202106131651355868977_reader_0 0 status update does not take effect: {'elapsed': 655, 'end_time': 1623603100509, 'job_id': '202106131651355868977', 'party_id': '9998', 'party_status': 'failed', 'role': 'host', 'start_time': 1623603097930, 'status': 'running', 'task_id': '202106131651355868977_reader_0', 'task_version': 0, 'update_time': 1623603095671}
[INFO] [2021-06-13 16:51:42,430] [8:139726560425728] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0
[INFO] [2021-06-13 16:51:42,451] [8:139726560425728] - job_saver.py[line:84]: job 202106131651355868977 task 202106131651355868977_reader_0 0 update successfully
[INFO] [2021-06-13 16:51:42,452] [8:139726560425728] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0 status
[INFO] [2021-06-13 16:51:42,457] [8:139726560425728] - job_saver.py[line:76]: update job 202106131651355868977 task 202106131651355868977_reader_0 0 status update does not take effect: {'elapsed': 761, 'end_time': 1623603100678, 'job_id': '202106131651355868977', 'party_id': '9999', 'party_status': 'failed', 'role': 'guest', 'start_time': 1623603098012, 'status': 'running', 'task_id': '202106131651355868977_reader_0', 'task_version': 0, 'update_time': 1623603095800}
[INFO] [2021-06-13 16:51:42,458] [8:139726560425728] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0
[INFO] [2021-06-13 16:51:42,474] [8:139726560425728] - job_saver.py[line:84]: job 202106131651355868977 task 202106131651355868977_reader_0 0 update successfully
[INFO] [2021-06-13 16:51:42,480] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131651355868977 task 202106131651355868977_reader_0 0 status is failed, calculate by task party status list: ['failed', 'failed']
[INFO] [2021-06-13 16:51:42,480] [8:139726560425728] - federated_scheduler.py[line:192]: job 202106131651355868977 task 202106131651355868977_reader_0 0 is failed, sync to all party
[INFO] [2021-06-13 16:51:42,499] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0 status
[INFO] [2021-06-13 16:51:42,518] [8:139726518462208] - job_saver.py[line:74]: update job 202106131651355868977 task 202106131651355868977_reader_0 0 status successfully: {'job_id': '202106131651355868977', 'task_id': '202106131651355868977_reader_0', 'task_version': '0', 'role': 'host', 'party_id': '9998', 'status': 'failed'}
[INFO] [2021-06-13 16:51:42,534] [8:139726518462208] - resource_manager.py[line:286]: task 202106131651355868977_reader_0 0 return resource successfully
[INFO] [2021-06-13 16:51:42,542] [8:139726518462208] - job_tracker.py[line:424]: clean task 202106131651355868977_reader_0 0 on host 9998
[ERROR] [2021-06-13 16:51:42,544] [8:139726518462208] - job_tracker.py[line:475]: namespace dir /fate/data/202106131651355868977_reader_0_0_host_9998 does not exist
Traceback (most recent call last):
  File "/fate/python/fate_flow/operation/job_tracker.py", line 437, in clean_task
    sess.computing.cleanup(namespace=computing_temp_namespace, name="*")
  File "/fate/python/fate_arch/computing/standalone/_csession.py", line 73, in cleanup
    return self._session.cleanup(name=name, namespace=namespace)
  File "/fate/python/fate_arch/_standalone.py", line 383, in cleanup
    raise EnvironmentError(f"namespace dir {namespace_dir} does not exist")
OSError: namespace dir /fate/data/202106131651355868977_reader_0_0_host_9998 does not exist
[INFO] [2021-06-13 16:51:42,563] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0 status
[INFO] [2021-06-13 16:51:42,582] [8:139726518462208] - job_saver.py[line:74]: update job 202106131651355868977 task 202106131651355868977_reader_0 0 status successfully: {'job_id': '202106131651355868977', 'task_id': '202106131651355868977_reader_0', 'task_version': '0', 'role': 'guest', 'party_id': '9999', 'status': 'failed'}
[INFO] [2021-06-13 16:51:42,600] [8:139726518462208] - resource_manager.py[line:286]: task 202106131651355868977_reader_0 0 return resource successfully
[INFO] [2021-06-13 16:51:42,608] [8:139726518462208] - job_tracker.py[line:424]: clean task 202106131651355868977_reader_0 0 on guest 9999
[ERROR] [2021-06-13 16:51:42,612] [8:139726518462208] - job_tracker.py[line:475]: namespace dir /fate/data/202106131651355868977_reader_0_0_guest_9999 does not exist
Traceback (most recent call last):
  File "/fate/python/fate_flow/operation/job_tracker.py", line 437, in clean_task
    sess.computing.cleanup(namespace=computing_temp_namespace, name="*")
  File "/fate/python/fate_arch/computing/standalone/_csession.py", line 73, in cleanup
    return self._session.cleanup(name=name, namespace=namespace)
  File "/fate/python/fate_arch/_standalone.py", line 383, in cleanup
    raise EnvironmentError(f"namespace dir {namespace_dir} does not exist")
OSError: namespace dir /fate/data/202106131651355868977_reader_0_0_guest_9999 does not exist
[INFO] [2021-06-13 16:51:42,641] [8:139726560425728] - federated_scheduler.py[line:195]: sync job 202106131651355868977 task 202106131651355868977_reader_0 0 status failed to all party success
[INFO] [2021-06-13 16:51:42,642] [8:139726560425728] - federated_scheduler.py[line:202]: try to stop job 202106131651355868977 task 202106131651355868977_reader_0 0
[INFO] [2021-06-13 16:51:42,696] [8:139726518462208] - job_utils.py[line:397]: try to stop job 202106131651355868977 task 202106131651355868977_reader_0 host 9998 with failed party status process pid:3817
[INFO] [2021-06-13 16:51:42,696] [8:139726518462208] - job_utils.py[line:400]: can not found job 202106131651355868977 task 202106131651355868977_reader_0 host 9998 with failed party status process pid:3817
[INFO] [2021-06-13 16:51:42,702] [8:139726518462208] - job_utils.py[line:424]: start run subprocess to stop task session 202106131651355868977_reader_0_0_host_9998
[INFO] [2021-06-13 16:51:42,703] [8:139726518462208] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106131651355868977_reader_0_0_host_9998 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c kill
[INFO] [2021-06-13 16:51:42,710] [8:139726518462208] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106131651355868977_reader_0_0_host_9998 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c kill successfully, pid is 3849
[INFO] [2021-06-13 16:51:42,711] [8:139726518462208] - task_controller.py[line:255]: job 202106131651355868977 task 202106131651355868977_reader_0 0 on host 9998 process 3817 kill success
[INFO] [2021-06-13 16:51:42,712] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0 status
[INFO] [2021-06-13 16:51:42,721] [8:139726518462208] - job_saver.py[line:76]: update job 202106131651355868977 task 202106131651355868977_reader_0 0 status update does not take effect: {'job_id': '202106131651355868977', 'task_id': '202106131651355868977_reader_0', 'task_version': 0, 'role': 'host', 'party_id': '9998', 'party_status': 'failed'}
[INFO] [2021-06-13 16:51:42,731] [8:139726518462208] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0
[WARNING] [2021-06-13 16:51:42,738] [8:139726518462208] - job_saver.py[line:86]: job 202106131651355868977 task 202106131651355868977_reader_0 0 update does not take effect
[INFO] [2021-06-13 16:51:42,764] [8:139726518462208] - job_utils.py[line:397]: try to stop job 202106131651355868977 task 202106131651355868977_reader_0 guest 9999 with failed party status process pid:3819
[INFO] [2021-06-13 16:51:42,764] [8:139726518462208] - job_utils.py[line:400]: can not found job 202106131651355868977 task 202106131651355868977_reader_0 guest 9999 with failed party status process pid:3819
[INFO] [2021-06-13 16:51:42,767] [8:139726518462208] - job_utils.py[line:424]: start run subprocess to stop task session 202106131651355868977_reader_0_0_guest_9999
[INFO] [2021-06-13 16:51:42,767] [8:139726518462208] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106131651355868977_reader_0_0_guest_9999 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c kill
[INFO] [2021-06-13 16:51:42,775] [8:139726518462208] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106131651355868977_reader_0_0_guest_9999 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c kill successfully, pid is 3851
[INFO] [2021-06-13 16:51:42,776] [8:139726518462208] - task_controller.py[line:255]: job 202106131651355868977 task 202106131651355868977_reader_0 0 on guest 9999 process 3819 kill success
[INFO] [2021-06-13 16:51:42,776] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0 status
[INFO] [2021-06-13 16:51:42,781] [8:139726518462208] - job_saver.py[line:76]: update job 202106131651355868977 task 202106131651355868977_reader_0 0 status update does not take effect: {'job_id': '202106131651355868977', 'task_id': '202106131651355868977_reader_0', 'task_version': 0, 'role': 'guest', 'party_id': '9999', 'party_status': 'failed'}
[INFO] [2021-06-13 16:51:42,788] [8:139726518462208] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0
[WARNING] [2021-06-13 16:51:42,795] [8:139726518462208] - job_saver.py[line:86]: job 202106131651355868977 task 202106131651355868977_reader_0 0 update does not take effect
[INFO] [2021-06-13 16:51:42,807] [8:139726560425728] - federated_scheduler.py[line:206]: stop job 202106131651355868977 task 202106131651355868977_reader_0 0 success
[INFO] [2021-06-13 16:51:42,817] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131651355868977 task 202106131651355868977_dataio_0 0 status is waiting, calculate by task party status list: ['waiting', 'waiting']
[INFO] [2021-06-13 16:51:42,830] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131651355868977 task 202106131651355868977_intersection_0 0 status is waiting, calculate by task party status list: ['waiting', 'waiting']
[INFO] [2021-06-13 16:51:42,845] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131651355868977 task 202106131651355868977_hetero_secure_boost_0 0 status is waiting, calculate by task party status list: ['waiting', 'waiting']
[INFO] [2021-06-13 16:51:42,845] [8:139726560425728] - task_scheduler.py[line:75]: finish scheduling job 202106131651355868977 tasks
[INFO] [2021-06-13 16:51:42,846] [8:139726560425728] - dag_scheduler.py[line:310]: Job 202106131651355868977 status is failed, calculate by task status list: ['failed', 'waiting', 'waiting', 'waiting']
[INFO] [2021-06-13 16:51:42,846] [8:139726560425728] - federated_scheduler.py[line:58]: sync job 202106131651355868977 info to all party
[INFO] [2021-06-13 16:51:42,853] [8:139726518462208] - job_saver.py[line:61]: try to update job 202106131651355868977
[INFO] [2021-06-13 16:51:42,869] [8:139726518462208] - job_saver.py[line:64]: job 202106131651355868977 update successfully: {'job_id': '202106131651355868977', 'role': 'host', 'party_id': '9998', 'progress': 25.0}
[INFO] [2021-06-13 16:51:42,877] [8:139726518462208] - job_saver.py[line:61]: try to update job 202106131651355868977
[INFO] [2021-06-13 16:51:42,888] [8:139726518462208] - job_saver.py[line:64]: job 202106131651355868977 update successfully: {'job_id': '202106131651355868977', 'role': 'guest', 'party_id': '9999', 'progress': 25.0}
[INFO] [2021-06-13 16:51:42,891] [8:139726560425728] - federated_scheduler.py[line:61]: sync job 202106131651355868977 info to all party successfully
[INFO] [2021-06-13 16:51:42,897] [8:139726560425728] - job_saver.py[line:45]: try to update job 202106131651355868977 status to None
[INFO] [2021-06-13 16:51:42,904] [8:139726560425728] - job_saver.py[line:56]: update job 202106131651355868977 status does not take effect
[INFO] [2021-06-13 16:51:42,904] [8:139726560425728] - job_saver.py[line:61]: try to update job 202106131651355868977
[INFO] [2021-06-13 16:51:42,920] [8:139726560425728] - job_saver.py[line:64]: job 202106131651355868977 update successfully: {'job_id': '202106131651355868977', 'role': 'host', 'party_id': '9998', 'progress': 25.0}
[INFO] [2021-06-13 16:51:42,920] [8:139726560425728] - job_saver.py[line:45]: try to update job 202106131651355868977 status to None
[INFO] [2021-06-13 16:51:42,931] [8:139726560425728] - job_saver.py[line:56]: update job 202106131651355868977 status does not take effect
[INFO] [2021-06-13 16:51:42,932] [8:139726560425728] - job_saver.py[line:61]: try to update job 202106131651355868977
[INFO] [2021-06-13 16:51:42,952] [8:139726560425728] - job_saver.py[line:64]: job 202106131651355868977 update successfully: {'job_id': '202106131651355868977', 'role': 'guest', 'party_id': '9999', 'progress': 25.0}
[INFO] [2021-06-13 16:51:42,952] [8:139726560425728] - federated_scheduler.py[line:78]: try to save job 202106131651355868977 pipelined model
[INFO] [2021-06-13 16:51:42,957] [8:139726518462208] - job_controller.py[line:331]: job 202106131651355868977 on host 9998 start to save pipeline
[INFO] [2021-06-13 16:51:43,021] [8:139726518462208] - job_tracker.py[line:517]: save 202106131651355868977 model info done. model id: guest-9999#host-9998#model, model version: 202106131651355868977.
[INFO] [2021-06-13 16:51:43,022] [8:139726518462208] - job_controller.py[line:374]: job 202106131651355868977 on host 9998 save pipeline successfully
[INFO] [2021-06-13 16:51:43,030] [8:139726518462208] - job_controller.py[line:331]: job 202106131651355868977 on guest 9999 start to save pipeline
[INFO] [2021-06-13 16:51:43,139] [8:139726518462208] - job_tracker.py[line:517]: save 202106131651355868977 model info done. model id: guest-9999#host-9998#model, model version: 202106131651355868977.
[INFO] [2021-06-13 16:51:43,140] [8:139726518462208] - job_controller.py[line:374]: job 202106131651355868977 on guest 9999 save pipeline successfully
[INFO] [2021-06-13 16:51:43,144] [8:139726560425728] - federated_scheduler.py[line:81]: save job 202106131651355868977 pipelined model success
[INFO] [2021-06-13 16:51:43,144] [8:139726560425728] - federated_scheduler.py[line:68]: job 202106131651355868977 is failed, sync to all party
[INFO] [2021-06-13 16:51:43,159] [8:139726518462208] - job_saver.py[line:45]: try to update job 202106131651355868977 status to failed
[INFO] [2021-06-13 16:51:43,346] [8:139726518462208] - job_saver.py[line:48]: update job 202106131651355868977 status successfully
[INFO] [2021-06-13 16:51:43,380] [8:139726518462208] - resource_manager.py[line:176]: return job 202106131651355868977 resource(cores 4 memory 0) on host 9998 successfully, remaining cores: 16 remaining memory: 0
[INFO] [2021-06-13 16:51:43,390] [8:139726518462208] - job_saver.py[line:45]: try to update job 202106131651355868977 status to failed
[INFO] [2021-06-13 16:51:43,407] [8:139726518462208] - job_saver.py[line:48]: update job 202106131651355868977 status successfully
[INFO] [2021-06-13 16:51:43,411] [3849:140044622202688] - session_utils.py[line:38]: start kill session 202106131651355868977_reader_0_0_host_9998
[INFO] [2021-06-13 16:51:43,412] [3849:140044622202688] - session_utils.py[line:47]: kill session 202106131651355868977_reader_0_0_host_9998 success
[INFO] [2021-06-13 16:51:43,446] [8:139726518462208] - resource_manager.py[line:176]: return job 202106131651355868977 resource(cores 4 memory 0) on guest 9999 successfully, remaining cores: 20 remaining memory: 0
[INFO] [2021-06-13 16:51:43,450] [8:139726560425728] - federated_scheduler.py[line:71]: sync job 202106131651355868977 status failed to all party success
[INFO] [2021-06-13 16:51:43,458] [8:139726560425728] - job_saver.py[line:45]: try to update job 202106131651355868977 status to failed
[INFO] [2021-06-13 16:51:43,468] [8:139726560425728] - job_saver.py[line:56]: update job 202106131651355868977 status does not take effect
[INFO] [2021-06-13 16:51:43,468] [8:139726560425728] - job_saver.py[line:61]: try to update job 202106131651355868977
[WARNING] [2021-06-13 16:51:43,477] [8:139726560425728] - job_saver.py[line:66]: job 202106131651355868977 update does not take effect: {'job_id': '202106131651355868977', 'role': 'host', 'party_id': '9998', 'status': 'failed'}
[INFO] [2021-06-13 16:51:43,477] [8:139726560425728] - job_saver.py[line:45]: try to update job 202106131651355868977 status to failed
[INFO] [2021-06-13 16:51:43,484] [8:139726560425728] - job_saver.py[line:56]: update job 202106131651355868977 status does not take effect
[INFO] [2021-06-13 16:51:43,485] [8:139726560425728] - job_saver.py[line:61]: try to update job 202106131651355868977
[WARNING] [2021-06-13 16:51:43,492] [8:139726560425728] - job_saver.py[line:66]: job 202106131651355868977 update does not take effect: {'job_id': '202106131651355868977', 'role': 'guest', 'party_id': '9999', 'status': 'failed'}
[INFO] [2021-06-13 16:51:43,493] [8:139726560425728] - dag_scheduler.py[line:502]: Job 202106131651355868977 finished with failed, do something...
[INFO] [2021-06-13 16:51:43,493] [8:139726560425728] - dag_scheduler.py[line:436]: request stop job 202106131651355868977 with failed
[INFO] [2021-06-13 16:51:43,499] [8:139726560425728] - dag_scheduler.py[line:445]: request stop job 202106131651355868977 with failed to all party
[INFO] [2021-06-13 16:51:43,499] [8:139726560425728] - federated_scheduler.py[line:88]: try to stop job 202106131651355868977
[INFO] [2021-06-13 16:51:43,517] [8:139726518462208] - job_utils.py[line:393]: job 202106131651355868977 task 202106131651355868977_hetero_secure_boost_0 host 9998 with waiting party status no process pid
[INFO] [2021-06-13 16:51:43,517] [8:139726518462208] - task_controller.py[line:255]: job 202106131651355868977 task 202106131651355868977_hetero_secure_boost_0 0 on host 9998 process None kill success
[INFO] [2021-06-13 16:51:43,517] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_hetero_secure_boost_0 0 status
[INFO] [2021-06-13 16:51:43,521] [8:139726518462208] - job_saver.py[line:76]: update job 202106131651355868977 task 202106131651355868977_hetero_secure_boost_0 0 status update does not take effect: {'job_id': '202106131651355868977', 'task_id': '202106131651355868977_hetero_secure_boost_0', 'task_version': 0, 'role': 'host', 'party_id': '9998', 'party_status': 'failed'}
[INFO] [2021-06-13 16:51:43,527] [8:139726518462208] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_hetero_secure_boost_0 0
[WARNING] [2021-06-13 16:51:43,532] [8:139726518462208] - job_saver.py[line:86]: job 202106131651355868977 task 202106131651355868977_hetero_secure_boost_0 0 update does not take effect
[INFO] [2021-06-13 16:51:43,536] [3851:140390970570560] - session_utils.py[line:38]: start kill session 202106131651355868977_reader_0_0_guest_9999
[INFO] [2021-06-13 16:51:43,537] [3851:140390970570560] - session_utils.py[line:47]: kill session 202106131651355868977_reader_0_0_guest_9999 success
[INFO] [2021-06-13 16:51:43,537] [8:139726518462208] - job_utils.py[line:393]: job 202106131651355868977 task 202106131651355868977_intersection_0 host 9998 with waiting party status no process pid
[INFO] [2021-06-13 16:51:43,538] [8:139726518462208] - task_controller.py[line:255]: job 202106131651355868977 task 202106131651355868977_intersection_0 0 on host 9998 process None kill success
[INFO] [2021-06-13 16:51:43,538] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_intersection_0 0 status
[INFO] [2021-06-13 16:51:43,543] [8:139726518462208] - job_saver.py[line:76]: update job 202106131651355868977 task 202106131651355868977_intersection_0 0 status update does not take effect: {'job_id': '202106131651355868977', 'task_id': '202106131651355868977_intersection_0', 'task_version': 0, 'role': 'host', 'party_id': '9998', 'party_status': 'failed'}
[INFO] [2021-06-13 16:51:43,548] [8:139726518462208] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_intersection_0 0
[WARNING] [2021-06-13 16:51:43,552] [8:139726518462208] - job_saver.py[line:86]: job 202106131651355868977 task 202106131651355868977_intersection_0 0 update does not take effect
[INFO] [2021-06-13 16:51:43,557] [8:139726518462208] - job_utils.py[line:393]: job 202106131651355868977 task 202106131651355868977_dataio_0 host 9998 with waiting party status no process pid
[INFO] [2021-06-13 16:51:43,557] [8:139726518462208] - task_controller.py[line:255]: job 202106131651355868977 task 202106131651355868977_dataio_0 0 on host 9998 process None kill success
[INFO] [2021-06-13 16:51:43,557] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_dataio_0 0 status
[INFO] [2021-06-13 16:51:43,561] [8:139726518462208] - job_saver.py[line:76]: update job 202106131651355868977 task 202106131651355868977_dataio_0 0 status update does not take effect: {'job_id': '202106131651355868977', 'task_id': '202106131651355868977_dataio_0', 'task_version': 0, 'role': 'host', 'party_id': '9998', 'party_status': 'failed'}
[INFO] [2021-06-13 16:51:43,567] [8:139726518462208] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_dataio_0 0
[WARNING] [2021-06-13 16:51:43,572] [8:139726518462208] - job_saver.py[line:86]: job 202106131651355868977 task 202106131651355868977_dataio_0 0 update does not take effect
[INFO] [2021-06-13 16:51:43,578] [8:139726518462208] - job_utils.py[line:397]: try to stop job 202106131651355868977 task 202106131651355868977_reader_0 host 9998 with failed party status process pid:3817
[INFO] [2021-06-13 16:51:43,578] [8:139726518462208] - job_utils.py[line:400]: can not found job 202106131651355868977 task 202106131651355868977_reader_0 host 9998 with failed party status process pid:3817
[INFO] [2021-06-13 16:51:43,582] [8:139726518462208] - job_utils.py[line:424]: start run subprocess to stop task session 202106131651355868977_reader_0_0_host_9998
[INFO] [2021-06-13 16:51:43,583] [8:139726518462208] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106131651355868977_reader_0_0_host_9998 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c kill
[INFO] [2021-06-13 16:51:43,589] [8:139726518462208] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106131651355868977_reader_0_0_host_9998 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c kill successfully, pid is 3875
[INFO] [2021-06-13 16:51:43,590] [8:139726518462208] - task_controller.py[line:255]: job 202106131651355868977 task 202106131651355868977_reader_0 0 on host 9998 process 3817 kill success
[INFO] [2021-06-13 16:51:43,590] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0 status
[INFO] [2021-06-13 16:51:43,597] [8:139726518462208] - job_saver.py[line:76]: update job 202106131651355868977 task 202106131651355868977_reader_0 0 status update does not take effect: {'job_id': '202106131651355868977', 'task_id': '202106131651355868977_reader_0', 'task_version': 0, 'role': 'host', 'party_id': '9998', 'party_status': 'failed'}
[INFO] [2021-06-13 16:51:43,604] [8:139726518462208] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0
[WARNING] [2021-06-13 16:51:43,609] [8:139726518462208] - job_saver.py[line:86]: job 202106131651355868977 task 202106131651355868977_reader_0 0 update does not take effect
[INFO] [2021-06-13 16:51:43,614] [8:139726518462208] - job_saver.py[line:45]: try to update job 202106131651355868977 status to failed
[INFO] [2021-06-13 16:51:43,621] [8:139726518462208] - job_saver.py[line:56]: update job 202106131651355868977 status does not take effect
[INFO] [2021-06-13 16:51:43,644] [8:139726518462208] - job_utils.py[line:393]: job 202106131651355868977 task 202106131651355868977_hetero_secure_boost_0 guest 9999 with waiting party status no process pid
[INFO] [2021-06-13 16:51:43,645] [8:139726518462208] - task_controller.py[line:255]: job 202106131651355868977 task 202106131651355868977_hetero_secure_boost_0 0 on guest 9999 process None kill success
[INFO] [2021-06-13 16:51:43,645] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_hetero_secure_boost_0 0 status
[INFO] [2021-06-13 16:51:43,649] [8:139726518462208] - job_saver.py[line:76]: update job 202106131651355868977 task 202106131651355868977_hetero_secure_boost_0 0 status update does not take effect: {'job_id': '202106131651355868977', 'task_id': '202106131651355868977_hetero_secure_boost_0', 'task_version': 0, 'role': 'guest', 'party_id': '9999', 'party_status': 'failed'}
[INFO] [2021-06-13 16:51:43,653] [8:139726518462208] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_hetero_secure_boost_0 0
[WARNING] [2021-06-13 16:51:43,657] [8:139726518462208] - job_saver.py[line:86]: job 202106131651355868977 task 202106131651355868977_hetero_secure_boost_0 0 update does not take effect
[INFO] [2021-06-13 16:51:43,662] [8:139726518462208] - job_utils.py[line:393]: job 202106131651355868977 task 202106131651355868977_intersection_0 guest 9999 with waiting party status no process pid
[INFO] [2021-06-13 16:51:43,662] [8:139726518462208] - task_controller.py[line:255]: job 202106131651355868977 task 202106131651355868977_intersection_0 0 on guest 9999 process None kill success
[INFO] [2021-06-13 16:51:43,662] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_intersection_0 0 status
[INFO] [2021-06-13 16:51:43,668] [8:139726518462208] - job_saver.py[line:76]: update job 202106131651355868977 task 202106131651355868977_intersection_0 0 status update does not take effect: {'job_id': '202106131651355868977', 'task_id': '202106131651355868977_intersection_0', 'task_version': 0, 'role': 'guest', 'party_id': '9999', 'party_status': 'failed'}
[INFO] [2021-06-13 16:51:43,673] [8:139726518462208] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_intersection_0 0
[WARNING] [2021-06-13 16:51:43,678] [8:139726518462208] - job_saver.py[line:86]: job 202106131651355868977 task 202106131651355868977_intersection_0 0 update does not take effect
[INFO] [2021-06-13 16:51:43,682] [8:139726518462208] - job_utils.py[line:393]: job 202106131651355868977 task 202106131651355868977_dataio_0 guest 9999 with waiting party status no process pid
[INFO] [2021-06-13 16:51:43,682] [8:139726518462208] - task_controller.py[line:255]: job 202106131651355868977 task 202106131651355868977_dataio_0 0 on guest 9999 process None kill success
[INFO] [2021-06-13 16:51:43,682] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_dataio_0 0 status
[INFO] [2021-06-13 16:51:43,686] [8:139726518462208] - job_saver.py[line:76]: update job 202106131651355868977 task 202106131651355868977_dataio_0 0 status update does not take effect: {'job_id': '202106131651355868977', 'task_id': '202106131651355868977_dataio_0', 'task_version': 0, 'role': 'guest', 'party_id': '9999', 'party_status': 'failed'}
[INFO] [2021-06-13 16:51:43,689] [8:139726518462208] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_dataio_0 0
[WARNING] [2021-06-13 16:51:43,695] [8:139726518462208] - job_saver.py[line:86]: job 202106131651355868977 task 202106131651355868977_dataio_0 0 update does not take effect
[INFO] [2021-06-13 16:51:43,700] [8:139726518462208] - job_utils.py[line:397]: try to stop job 202106131651355868977 task 202106131651355868977_reader_0 guest 9999 with failed party status process pid:3819
[INFO] [2021-06-13 16:51:43,700] [8:139726518462208] - job_utils.py[line:400]: can not found job 202106131651355868977 task 202106131651355868977_reader_0 guest 9999 with failed party status process pid:3819
[INFO] [2021-06-13 16:51:43,704] [8:139726518462208] - job_utils.py[line:424]: start run subprocess to stop task session 202106131651355868977_reader_0_0_guest_9999
[INFO] [2021-06-13 16:51:43,704] [8:139726518462208] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106131651355868977_reader_0_0_guest_9999 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c kill
[INFO] [2021-06-13 16:51:43,713] [8:139726518462208] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106131651355868977_reader_0_0_guest_9999 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c kill successfully, pid is 3877
[INFO] [2021-06-13 16:51:43,714] [8:139726518462208] - task_controller.py[line:255]: job 202106131651355868977 task 202106131651355868977_reader_0 0 on guest 9999 process 3819 kill success
[INFO] [2021-06-13 16:51:43,714] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0 status
[INFO] [2021-06-13 16:51:43,720] [8:139726518462208] - job_saver.py[line:76]: update job 202106131651355868977 task 202106131651355868977_reader_0 0 status update does not take effect: {'job_id': '202106131651355868977', 'task_id': '202106131651355868977_reader_0', 'task_version': 0, 'role': 'guest', 'party_id': '9999', 'party_status': 'failed'}
[INFO] [2021-06-13 16:51:43,728] [8:139726518462208] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0
[WARNING] [2021-06-13 16:51:43,734] [8:139726518462208] - job_saver.py[line:86]: job 202106131651355868977 task 202106131651355868977_reader_0 0 update does not take effect
[INFO] [2021-06-13 16:51:43,740] [8:139726518462208] - job_saver.py[line:45]: try to update job 202106131651355868977 status to failed
[INFO] [2021-06-13 16:51:43,751] [8:139726518462208] - job_saver.py[line:56]: update job 202106131651355868977 status does not take effect
[INFO] [2021-06-13 16:51:43,762] [8:139726560425728] - federated_scheduler.py[line:92]: stop job 202106131651355868977 success
[INFO] [2021-06-13 16:51:43,762] [8:139726560425728] - dag_scheduler.py[line:448]: stop job 202106131651355868977 with failed successfully
[INFO] [2021-06-13 16:51:43,763] [8:139726560425728] - federated_scheduler.py[line:107]: try to clean job 202106131651355868977
[INFO] [2021-06-13 16:51:43,769] [8:139726518462208] - job_controller.py[line:379]: Job 202106131651355868977 on host 9998 start to clean
[INFO] [2021-06-13 16:51:43,769] [8:139726518462208] - job_controller.py[line:382]: job 202106131651355868977 on host 9998 clean done
[INFO] [2021-06-13 16:51:43,776] [8:139726518462208] - job_controller.py[line:379]: Job 202106131651355868977 on guest 9999 start to clean
[INFO] [2021-06-13 16:51:43,776] [8:139726518462208] - job_controller.py[line:382]: job 202106131651355868977 on guest 9999 clean done
[INFO] [2021-06-13 16:51:43,780] [8:139726560425728] - federated_scheduler.py[line:110]: clean job 202106131651355868977 success
[INFO] [2021-06-13 16:51:43,780] [8:139726560425728] - dag_scheduler.py[line:505]: Job 202106131651355868977 finished with failed, done
[INFO] [2021-06-13 16:51:43,780] [8:139726560425728] - dag_scheduler.py[line:325]: finish scheduling job 202106131651355868977
[INFO] [2021-06-13 16:51:43,811] [8:139726560425728] - dag_scheduler.py[line:298]: scheduling job 202106131651355868977
[INFO] [2021-06-13 16:51:43,826] [8:139726560425728] - task_scheduler.py[line:28]: scheduling job 202106131651355868977 tasks
[INFO] [2021-06-13 16:51:43,845] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131651355868977 task 202106131651355868977_reader_0 0 status is failed, calculate by task party status list: ['failed', 'failed']
[INFO] [2021-06-13 16:51:43,854] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131651355868977 task 202106131651355868977_dataio_0 0 status is waiting, calculate by task party status list: ['waiting', 'waiting']
[INFO] [2021-06-13 16:51:43,862] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131651355868977 task 202106131651355868977_intersection_0 0 status is waiting, calculate by task party status list: ['waiting', 'waiting']
[INFO] [2021-06-13 16:51:43,872] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131651355868977 task 202106131651355868977_hetero_secure_boost_0 0 status is waiting, calculate by task party status list: ['waiting', 'waiting']
[INFO] [2021-06-13 16:51:43,872] [8:139726560425728] - task_scheduler.py[line:75]: finish scheduling job 202106131651355868977 tasks
[INFO] [2021-06-13 16:51:43,872] [8:139726560425728] - dag_scheduler.py[line:310]: Job 202106131651355868977 status is failed, calculate by task status list: ['failed', 'waiting', 'waiting', 'waiting']
[INFO] [2021-06-13 16:51:43,872] [8:139726560425728] - dag_scheduler.py[line:502]: Job 202106131651355868977 finished with failed, do something...
[INFO] [2021-06-13 16:51:43,872] [8:139726560425728] - dag_scheduler.py[line:436]: request stop job 202106131651355868977 with failed
[INFO] [2021-06-13 16:51:43,879] [8:139726560425728] - dag_scheduler.py[line:445]: request stop job 202106131651355868977 with failed to all party
[INFO] [2021-06-13 16:51:43,880] [8:139726560425728] - federated_scheduler.py[line:88]: try to stop job 202106131651355868977
[INFO] [2021-06-13 16:51:43,897] [8:139726518462208] - job_utils.py[line:393]: job 202106131651355868977 task 202106131651355868977_hetero_secure_boost_0 host 9998 with waiting party status no process pid
[INFO] [2021-06-13 16:51:43,897] [8:139726518462208] - task_controller.py[line:255]: job 202106131651355868977 task 202106131651355868977_hetero_secure_boost_0 0 on host 9998 process None kill success
[INFO] [2021-06-13 16:51:43,897] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_hetero_secure_boost_0 0 status
[INFO] [2021-06-13 16:51:43,903] [8:139726518462208] - job_saver.py[line:76]: update job 202106131651355868977 task 202106131651355868977_hetero_secure_boost_0 0 status update does not take effect: {'job_id': '202106131651355868977', 'task_id': '202106131651355868977_hetero_secure_boost_0', 'task_version': 0, 'role': 'host', 'party_id': '9998', 'party_status': 'failed'}
[INFO] [2021-06-13 16:51:43,909] [8:139726518462208] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_hetero_secure_boost_0 0
[WARNING] [2021-06-13 16:51:43,915] [8:139726518462208] - job_saver.py[line:86]: job 202106131651355868977 task 202106131651355868977_hetero_secure_boost_0 0 update does not take effect
[INFO] [2021-06-13 16:51:43,920] [8:139726518462208] - job_utils.py[line:393]: job 202106131651355868977 task 202106131651355868977_intersection_0 host 9998 with waiting party status no process pid
[INFO] [2021-06-13 16:51:43,921] [8:139726518462208] - task_controller.py[line:255]: job 202106131651355868977 task 202106131651355868977_intersection_0 0 on host 9998 process None kill success
[INFO] [2021-06-13 16:51:43,921] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_intersection_0 0 status
[INFO] [2021-06-13 16:51:43,926] [8:139726518462208] - job_saver.py[line:76]: update job 202106131651355868977 task 202106131651355868977_intersection_0 0 status update does not take effect: {'job_id': '202106131651355868977', 'task_id': '202106131651355868977_intersection_0', 'task_version': 0, 'role': 'host', 'party_id': '9998', 'party_status': 'failed'}
[INFO] [2021-06-13 16:51:43,932] [8:139726518462208] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_intersection_0 0
[WARNING] [2021-06-13 16:51:43,937] [8:139726518462208] - job_saver.py[line:86]: job 202106131651355868977 task 202106131651355868977_intersection_0 0 update does not take effect
[INFO] [2021-06-13 16:51:43,944] [8:139726518462208] - job_utils.py[line:393]: job 202106131651355868977 task 202106131651355868977_dataio_0 host 9998 with waiting party status no process pid
[INFO] [2021-06-13 16:51:43,944] [8:139726518462208] - task_controller.py[line:255]: job 202106131651355868977 task 202106131651355868977_dataio_0 0 on host 9998 process None kill success
[INFO] [2021-06-13 16:51:43,944] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_dataio_0 0 status
[INFO] [2021-06-13 16:51:43,950] [8:139726518462208] - job_saver.py[line:76]: update job 202106131651355868977 task 202106131651355868977_dataio_0 0 status update does not take effect: {'job_id': '202106131651355868977', 'task_id': '202106131651355868977_dataio_0', 'task_version': 0, 'role': 'host', 'party_id': '9998', 'party_status': 'failed'}
[INFO] [2021-06-13 16:51:43,956] [8:139726518462208] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_dataio_0 0
[WARNING] [2021-06-13 16:51:43,967] [8:139726518462208] - job_saver.py[line:86]: job 202106131651355868977 task 202106131651355868977_dataio_0 0 update does not take effect
[INFO] [2021-06-13 16:51:43,974] [8:139726518462208] - job_utils.py[line:397]: try to stop job 202106131651355868977 task 202106131651355868977_reader_0 host 9998 with failed party status process pid:3817
[INFO] [2021-06-13 16:51:43,974] [8:139726518462208] - job_utils.py[line:400]: can not found job 202106131651355868977 task 202106131651355868977_reader_0 host 9998 with failed party status process pid:3817
[INFO] [2021-06-13 16:51:43,979] [8:139726518462208] - job_utils.py[line:424]: start run subprocess to stop task session 202106131651355868977_reader_0_0_host_9998
[INFO] [2021-06-13 16:51:43,979] [8:139726518462208] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106131651355868977_reader_0_0_host_9998 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c kill
[INFO] [2021-06-13 16:51:43,991] [8:139726518462208] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106131651355868977_reader_0_0_host_9998 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c kill successfully, pid is 3890
[INFO] [2021-06-13 16:51:43,992] [8:139726518462208] - task_controller.py[line:255]: job 202106131651355868977 task 202106131651355868977_reader_0 0 on host 9998 process 3817 kill success
[INFO] [2021-06-13 16:51:43,992] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0 status
[INFO] [2021-06-13 16:51:43,999] [8:139726518462208] - job_saver.py[line:76]: update job 202106131651355868977 task 202106131651355868977_reader_0 0 status update does not take effect: {'job_id': '202106131651355868977', 'task_id': '202106131651355868977_reader_0', 'task_version': 0, 'role': 'host', 'party_id': '9998', 'party_status': 'failed'}
[INFO] [2021-06-13 16:51:44,006] [8:139726518462208] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0
[WARNING] [2021-06-13 16:51:44,013] [8:139726518462208] - job_saver.py[line:86]: job 202106131651355868977 task 202106131651355868977_reader_0 0 update does not take effect
[INFO] [2021-06-13 16:51:44,023] [8:139726518462208] - job_saver.py[line:45]: try to update job 202106131651355868977 status to failed
[INFO] [2021-06-13 16:51:44,032] [8:139726518462208] - job_saver.py[line:56]: update job 202106131651355868977 status does not take effect
[INFO] [2021-06-13 16:51:44,061] [8:139726518462208] - job_utils.py[line:393]: job 202106131651355868977 task 202106131651355868977_hetero_secure_boost_0 guest 9999 with waiting party status no process pid
[INFO] [2021-06-13 16:51:44,061] [8:139726518462208] - task_controller.py[line:255]: job 202106131651355868977 task 202106131651355868977_hetero_secure_boost_0 0 on guest 9999 process None kill success
[INFO] [2021-06-13 16:51:44,061] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_hetero_secure_boost_0 0 status
[INFO] [2021-06-13 16:51:44,067] [8:139726518462208] - job_saver.py[line:76]: update job 202106131651355868977 task 202106131651355868977_hetero_secure_boost_0 0 status update does not take effect: {'job_id': '202106131651355868977', 'task_id': '202106131651355868977_hetero_secure_boost_0', 'task_version': 0, 'role': 'guest', 'party_id': '9999', 'party_status': 'failed'}
[INFO] [2021-06-13 16:51:44,072] [8:139726518462208] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_hetero_secure_boost_0 0
[WARNING] [2021-06-13 16:51:44,078] [8:139726518462208] - job_saver.py[line:86]: job 202106131651355868977 task 202106131651355868977_hetero_secure_boost_0 0 update does not take effect
[INFO] [2021-06-13 16:51:44,084] [8:139726518462208] - job_utils.py[line:393]: job 202106131651355868977 task 202106131651355868977_intersection_0 guest 9999 with waiting party status no process pid
[INFO] [2021-06-13 16:51:44,084] [8:139726518462208] - task_controller.py[line:255]: job 202106131651355868977 task 202106131651355868977_intersection_0 0 on guest 9999 process None kill success
[INFO] [2021-06-13 16:51:44,084] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_intersection_0 0 status
[INFO] [2021-06-13 16:51:44,089] [8:139726518462208] - job_saver.py[line:76]: update job 202106131651355868977 task 202106131651355868977_intersection_0 0 status update does not take effect: {'job_id': '202106131651355868977', 'task_id': '202106131651355868977_intersection_0', 'task_version': 0, 'role': 'guest', 'party_id': '9999', 'party_status': 'failed'}
[INFO] [2021-06-13 16:51:44,095] [8:139726518462208] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_intersection_0 0
[WARNING] [2021-06-13 16:51:44,100] [8:139726518462208] - job_saver.py[line:86]: job 202106131651355868977 task 202106131651355868977_intersection_0 0 update does not take effect
[INFO] [2021-06-13 16:51:44,105] [8:139726518462208] - job_utils.py[line:393]: job 202106131651355868977 task 202106131651355868977_dataio_0 guest 9999 with waiting party status no process pid
[INFO] [2021-06-13 16:51:44,106] [8:139726518462208] - task_controller.py[line:255]: job 202106131651355868977 task 202106131651355868977_dataio_0 0 on guest 9999 process None kill success
[INFO] [2021-06-13 16:51:44,106] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_dataio_0 0 status
[INFO] [2021-06-13 16:51:44,111] [8:139726518462208] - job_saver.py[line:76]: update job 202106131651355868977 task 202106131651355868977_dataio_0 0 status update does not take effect: {'job_id': '202106131651355868977', 'task_id': '202106131651355868977_dataio_0', 'task_version': 0, 'role': 'guest', 'party_id': '9999', 'party_status': 'failed'}
[INFO] [2021-06-13 16:51:44,117] [8:139726518462208] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_dataio_0 0
[WARNING] [2021-06-13 16:51:44,128] [8:139726518462208] - job_saver.py[line:86]: job 202106131651355868977 task 202106131651355868977_dataio_0 0 update does not take effect
[INFO] [2021-06-13 16:51:44,135] [8:139726518462208] - job_utils.py[line:397]: try to stop job 202106131651355868977 task 202106131651355868977_reader_0 guest 9999 with failed party status process pid:3819
[INFO] [2021-06-13 16:51:44,135] [8:139726518462208] - job_utils.py[line:400]: can not found job 202106131651355868977 task 202106131651355868977_reader_0 guest 9999 with failed party status process pid:3819
[INFO] [2021-06-13 16:51:44,139] [8:139726518462208] - job_utils.py[line:424]: start run subprocess to stop task session 202106131651355868977_reader_0_0_guest_9999
[INFO] [2021-06-13 16:51:44,139] [8:139726518462208] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106131651355868977_reader_0_0_guest_9999 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c kill
[INFO] [2021-06-13 16:51:44,169] [8:139726518462208] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106131651355868977_reader_0_0_guest_9999 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c kill successfully, pid is 3899
[INFO] [2021-06-13 16:51:44,170] [8:139726518462208] - task_controller.py[line:255]: job 202106131651355868977 task 202106131651355868977_reader_0 0 on guest 9999 process 3819 kill success
[INFO] [2021-06-13 16:51:44,170] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0 status
[INFO] [2021-06-13 16:51:44,181] [8:139726518462208] - job_saver.py[line:76]: update job 202106131651355868977 task 202106131651355868977_reader_0 0 status update does not take effect: {'job_id': '202106131651355868977', 'task_id': '202106131651355868977_reader_0', 'task_version': 0, 'role': 'guest', 'party_id': '9999', 'party_status': 'failed'}
[INFO] [2021-06-13 16:51:44,193] [8:139726518462208] - job_saver.py[line:81]: try to update job 202106131651355868977 task 202106131651355868977_reader_0 0
[WARNING] [2021-06-13 16:51:44,201] [8:139726518462208] - job_saver.py[line:86]: job 202106131651355868977 task 202106131651355868977_reader_0 0 update does not take effect
[INFO] [2021-06-13 16:51:44,207] [8:139726518462208] - job_saver.py[line:45]: try to update job 202106131651355868977 status to failed
[INFO] [2021-06-13 16:51:44,216] [8:139726518462208] - job_saver.py[line:56]: update job 202106131651355868977 status does not take effect
[INFO] [2021-06-13 16:51:44,223] [8:139726560425728] - federated_scheduler.py[line:92]: stop job 202106131651355868977 success
[INFO] [2021-06-13 16:51:44,223] [8:139726560425728] - dag_scheduler.py[line:448]: stop job 202106131651355868977 with failed successfully
[INFO] [2021-06-13 16:51:44,224] [8:139726560425728] - federated_scheduler.py[line:107]: try to clean job 202106131651355868977
[INFO] [2021-06-13 16:51:44,235] [8:139726518462208] - job_controller.py[line:379]: Job 202106131651355868977 on host 9998 start to clean
[INFO] [2021-06-13 16:51:44,235] [8:139726518462208] - job_controller.py[line:382]: job 202106131651355868977 on host 9998 clean done
[INFO] [2021-06-13 16:51:44,250] [8:139726518462208] - job_controller.py[line:379]: Job 202106131651355868977 on guest 9999 start to clean
[INFO] [2021-06-13 16:51:44,251] [8:139726518462208] - job_controller.py[line:382]: job 202106131651355868977 on guest 9999 clean done
[INFO] [2021-06-13 16:51:44,257] [8:139726560425728] - federated_scheduler.py[line:110]: clean job 202106131651355868977 success
[INFO] [2021-06-13 16:51:44,257] [8:139726560425728] - dag_scheduler.py[line:505]: Job 202106131651355868977 finished with failed, done
[INFO] [2021-06-13 16:51:44,258] [8:139726560425728] - dag_scheduler.py[line:325]: finish scheduling job 202106131651355868977
[INFO] [2021-06-13 16:51:44,500] [3875:140493275424576] - session_utils.py[line:38]: start kill session 202106131651355868977_reader_0_0_host_9998
[INFO] [2021-06-13 16:51:44,501] [3875:140493275424576] - session_utils.py[line:47]: kill session 202106131651355868977_reader_0_0_host_9998 success
[INFO] [2021-06-13 16:51:44,530] [3877:139917313263424] - session_utils.py[line:38]: start kill session 202106131651355868977_reader_0_0_guest_9999
[INFO] [2021-06-13 16:51:44,531] [3877:139917313263424] - session_utils.py[line:47]: kill session 202106131651355868977_reader_0_0_guest_9999 success
[INFO] [2021-06-13 16:51:44,808] [3890:140163919710016] - session_utils.py[line:38]: start kill session 202106131651355868977_reader_0_0_host_9998
[INFO] [2021-06-13 16:51:44,808] [3890:140163919710016] - session_utils.py[line:47]: kill session 202106131651355868977_reader_0_0_host_9998 success
[INFO] [2021-06-13 16:51:44,908] [3899:140675366422336] - session_utils.py[line:38]: start kill session 202106131651355868977_reader_0_0_guest_9999
[INFO] [2021-06-13 16:51:44,909] [3899:140675366422336] - session_utils.py[line:47]: kill session 202106131651355868977_reader_0_0_guest_9999 success
[INFO] [2021-06-13 16:51:46,291] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:51:48,335] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:51:50,384] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:51:52,427] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:51:54,476] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:51:56,519] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:51:59,142] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:52:01,424] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:52:04,819] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:52:07,363] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:52:09,412] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:52:11,457] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:52:13,510] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:52:15,556] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:52:17,604] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:52:19,650] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:52:21,691] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:52:23,748] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:52:25,791] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:52:27,823] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:52:29,885] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:52:31,922] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:52:33,978] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:52:36,017] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:52:38,075] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:52:40,125] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:52:42,166] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:52:44,213] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:52:46,262] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:52:48,312] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:52:50,363] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:52:52,414] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:52:54,466] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:52:56,515] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:52:58,582] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:53:00,638] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:53:02,690] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:53:04,741] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:53:06,795] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:53:08,869] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:53:10,920] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:53:12,964] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:53:15,020] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:53:17,073] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:53:19,127] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:53:21,181] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:53:23,265] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:53:25,315] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:53:27,368] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:53:29,417] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:53:31,470] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:53:33,528] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:53:35,564] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:53:37,610] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:53:39,662] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:53:41,712] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:53:43,769] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:53:45,821] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:53:47,865] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:53:49,916] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:53:51,965] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:53:54,016] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:53:56,069] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:53:58,120] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:00,168] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:02,230] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:04,279] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:06,333] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:08,383] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:10,439] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:12,480] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:14,537] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:16,589] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:18,640] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:20,693] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:22,750] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:24,813] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:26,869] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:28,925] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:30,987] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:33,047] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:35,100] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:37,134] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:39,188] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:41,235] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:43,286] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:45,338] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:47,394] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:49,441] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:51,492] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:53,541] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:55,584] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:57,649] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:54:59,701] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:55:01,755] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:55:03,828] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:55:05,877] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:55:07,926] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:55:09,966] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:55:12,027] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:55:14,094] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:55:16,134] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:55:18,175] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:55:20,216] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:55:22,256] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:55:24,323] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:55:26,376] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:55:28,424] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:55:30,474] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:55:32,526] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:55:34,579] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:55:36,650] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:55:38,699] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:55:40,755] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:55:42,809] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:55:44,861] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:55:46,917] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:55:48,982] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:55:51,048] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:55:53,098] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:55:55,142] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:55:57,192] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:55:59,282] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:56:01,345] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:56:03,396] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:56:05,455] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:56:07,506] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:56:09,560] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:56:11,629] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:56:13,688] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:56:15,739] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:56:17,791] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:56:19,837] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:56:21,899] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:56:23,948] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:56:25,983] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:56:28,023] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:56:30,070] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:56:32,121] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:56:34,181] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:56:36,226] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:56:38,276] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:56:40,321] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:56:42,372] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
