[INFO] [2021-06-13 16:40:33,648] [8:139727100782336] - dag_scheduler.py[line:40]: submit job, job_id 202106131640336474715, body {'job_dsl': {'components': {'reader_0': {'module': 'Reader', 'output': {'data': ['data']}}, 'dataio_0': {'module': 'DataIO', 'input': {'data': {'data': ['reader_0.data']}}, 'output': {'data': ['data'], 'model': ['model']}}, 'intersection_0': {'module': 'Intersection', 'input': {'data': {'data': ['dataio_0.data']}}, 'output': {'data': ['data']}}, 'hetero_secureboost_0': {'module': 'HeteroSecureBoost', 'input': {'data': {'train_data': ['intersection_0.data']}}, 'output': {'data': ['data'], 'model': ['model']}}, 'evaluation_0': {'module': 'Evaluation', 'input': {'data': {'data': ['hetero_secureboost_0.data']}}, 'output': {'data': ['data']}}}}, 'job_runtime_conf': {'dsl_version': 2, 'initiator': {'role': 'guest', 'party_id': 9999}, 'role': {'host': [10000], 'guest': [9999]}, 'job_parameters': {'common': {'backend': 0, 'work_mode': 0, 'job_type': 'train'}}, 'component_parameters': {'role': {'host': {'0': {'dataio_0': {'with_label': False}, 'reader_0': {'table': {'name': 'breast_hetero_host', 'namespace': 'experiment'}}}}, 'guest': {'0': {'reader_0': {'table': {'name': 'breast_hetero_guest', 'namespace': 'experiment'}}}}}, 'common': {'dataio_0': {'with_label': True}, 'hetero_secureboost_0': {'task_type': 'classification', 'objective_param': {'objective': 'cross_entropy'}, 'num_trees': 5, 'bin_num': 16, 'encrypt_param': {'method': 'iterativeAffine'}, 'tree_param': {'max_depth': 3}}, 'evaluation_0': {'eval_type': 'binary'}}}, 'dsl_path': '/tmp/tmp_1gss6w2/job_dsl.json', 'conf_path': '/tmp/tmp_1gss6w2/job_runtime_conf.json'}}
[INFO] [2021-06-13 16:40:33,713] [8:139727092389632] - job_controller.py[line:52]: job parameters:{'job_type': 'train', 'work_mode': 0, 'backend': 0, 'computing_engine': 'STANDALONE', 'federation_engine': 'STANDALONE', 'storage_engine': 'STANDALONE', 'engines_address': {}, 'federated_mode': 'SINGLE', 'task_parallelism': 1, 'computing_partitions': 4, 'federated_status_collect_type': 'PULL', 'model_id': 'guest-9999#host-10000#model', 'model_version': '202106131640336474715', 'eggroll_run': {}, 'spark_run': {}, 'rabbitmq_run': {}, 'pulsar_run': {}, 'adaptation_parameters': {'task_nodes': 1, 'task_cores_per_node': 4, 'task_memory_per_node': 0, 'request_task_cores': 4, 'if_initiator_baseline': True}}
[INFO] [2021-06-13 16:40:33,890] [8:139727092389632] - job_controller.py[line:52]: job parameters:{'job_type': 'train', 'work_mode': 0, 'backend': 0, 'computing_engine': 'STANDALONE', 'federation_engine': 'STANDALONE', 'storage_engine': 'STANDALONE', 'engines_address': {}, 'federated_mode': 'SINGLE', 'task_parallelism': 1, 'computing_partitions': 4, 'federated_status_collect_type': 'PULL', 'model_id': 'guest-9999#host-10000#model', 'model_version': '202106131640336474715', 'eggroll_run': {}, 'spark_run': {}, 'rabbitmq_run': {}, 'pulsar_run': {}, 'adaptation_parameters': {'task_nodes': 1, 'task_cores_per_node': 4, 'task_memory_per_node': 0, 'request_task_cores': 4, 'if_initiator_baseline': True}}
[INFO] [2021-06-13 16:40:34,031] [8:139727100782336] - dag_scheduler.py[line:122]: submit job successfully, job id is 202106131640336474715, model id is guest-9999#host-10000#model
[INFO] [2021-06-13 16:40:34,177] [8:139726560425728] - federated_scheduler.py[line:39]: try to apply job 202106131640336474715 resource
[INFO] [2021-06-13 16:40:34,259] [8:139727092389632] - resource_manager.py[line:176]: apply job 202106131640336474715 resource(cores 4 memory 0) on host 10000 successfully, remaining cores: 16 remaining memory: 0
[INFO] [2021-06-13 16:40:34,289] [8:139727092389632] - resource_manager.py[line:176]: apply job 202106131640336474715 resource(cores 4 memory 0) on guest 9999 successfully, remaining cores: 12 remaining memory: 0
[INFO] [2021-06-13 16:40:34,293] [8:139726560425728] - federated_scheduler.py[line:42]: apply job 202106131640336474715 resource successfully
[INFO] [2021-06-13 16:40:34,294] [8:139726560425728] - dag_scheduler.py[line:279]: try to start job 202106131640336474715 on initiator guest 9999
[INFO] [2021-06-13 16:40:34,303] [8:139727092389632] - job_controller.py[line:261]: try to start job 202106131640336474715 on host 10000
[INFO] [2021-06-13 16:40:34,304] [8:139727092389632] - job_saver.py[line:45]: try to update job 202106131640336474715 status to running
[INFO] [2021-06-13 16:40:34,318] [8:139727092389632] - job_saver.py[line:48]: update job 202106131640336474715 status successfully
[INFO] [2021-06-13 16:40:34,318] [8:139727092389632] - job_saver.py[line:61]: try to update job 202106131640336474715
[INFO] [2021-06-13 16:40:34,331] [8:139727092389632] - job_saver.py[line:64]: job 202106131640336474715 update successfully: {'job_id': '202106131640336474715', 'role': 'host', 'party_id': 10000, 'status': 'running', 'start_time': 1623602434304}
[INFO] [2021-06-13 16:40:34,331] [8:139727092389632] - job_controller.py[line:275]: start job 202106131640336474715 on host 10000 successfully
[INFO] [2021-06-13 16:40:34,339] [8:139727092389632] - job_controller.py[line:261]: try to start job 202106131640336474715 on guest 9999
[INFO] [2021-06-13 16:40:34,339] [8:139727092389632] - job_saver.py[line:45]: try to update job 202106131640336474715 status to running
[INFO] [2021-06-13 16:40:34,353] [8:139727092389632] - job_saver.py[line:48]: update job 202106131640336474715 status successfully
[INFO] [2021-06-13 16:40:34,354] [8:139727092389632] - job_saver.py[line:61]: try to update job 202106131640336474715
[INFO] [2021-06-13 16:40:34,370] [8:139727092389632] - job_saver.py[line:64]: job 202106131640336474715 update successfully: {'job_id': '202106131640336474715', 'role': 'guest', 'party_id': 9999, 'status': 'running', 'start_time': 1623602434339}
[INFO] [2021-06-13 16:40:34,370] [8:139727092389632] - job_controller.py[line:275]: start job 202106131640336474715 on guest 9999 successfully
[INFO] [2021-06-13 16:40:34,374] [8:139726560425728] - dag_scheduler.py[line:292]: start job 202106131640336474715 on initiator guest 9999
[INFO] [2021-06-13 16:40:34,382] [8:139726560425728] - dag_scheduler.py[line:247]: reset job 202106131640336474715 ready signal True
[INFO] [2021-06-13 16:40:34,389] [8:139726560425728] - dag_scheduler.py[line:298]: scheduling job 202106131640336474715
[INFO] [2021-06-13 16:40:34,400] [8:139726560425728] - task_scheduler.py[line:28]: scheduling job 202106131640336474715 tasks
[INFO] [2021-06-13 16:40:34,413] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131640336474715 task 202106131640336474715_reader_0 0 status is waiting, calculate by task party status list: ['waiting', 'waiting']
[INFO] [2021-06-13 16:40:34,423] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131640336474715 task 202106131640336474715_dataio_0 0 status is waiting, calculate by task party status list: ['waiting', 'waiting']
[INFO] [2021-06-13 16:40:34,433] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131640336474715 task 202106131640336474715_intersection_0 0 status is waiting, calculate by task party status list: ['waiting', 'waiting']
[INFO] [2021-06-13 16:40:34,442] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131640336474715 task 202106131640336474715_hetero_secureboost_0 0 status is waiting, calculate by task party status list: ['waiting', 'waiting']
[INFO] [2021-06-13 16:40:34,452] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131640336474715 task 202106131640336474715_evaluation_0 0 status is waiting, calculate by task party status list: ['waiting', 'waiting']
[INFO] [2021-06-13 16:40:34,452] [8:139726560425728] - task_scheduler.py[line:80]: try to start job 202106131640336474715 task 202106131640336474715_reader_0 0 on guest 9999
[INFO] [2021-06-13 16:40:34,473] [8:139726560425728] - resource_manager.py[line:286]: task 202106131640336474715_reader_0 0 apply resource successfully
[INFO] [2021-06-13 16:40:34,474] [8:139726560425728] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0 status
[INFO] [2021-06-13 16:40:34,488] [8:139726560425728] - job_saver.py[line:74]: update job 202106131640336474715 task 202106131640336474715_reader_0 0 status successfully: {'job_id': '202106131640336474715', 'task_id': '202106131640336474715_reader_0', 'task_version': 0, 'role': 'guest', 'party_id': '9999', 'status': 'running'}
[INFO] [2021-06-13 16:40:34,488] [8:139726560425728] - task_scheduler.py[line:93]: start job 202106131640336474715 task 202106131640336474715_reader_0 0 on guest 9999
[INFO] [2021-06-13 16:40:34,489] [8:139726560425728] - federated_scheduler.py[line:192]: job 202106131640336474715 task 202106131640336474715_reader_0 0 is running, sync to all party
[INFO] [2021-06-13 16:40:34,511] [8:139727092389632] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0 status
[INFO] [2021-06-13 16:40:34,524] [8:139727092389632] - job_saver.py[line:74]: update job 202106131640336474715 task 202106131640336474715_reader_0 0 status successfully: {'job_id': '202106131640336474715', 'task_id': '202106131640336474715_reader_0', 'task_version': '0', 'role': 'host', 'party_id': '10000', 'status': 'running'}
[INFO] [2021-06-13 16:40:34,535] [8:139727092389632] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0 status
[INFO] [2021-06-13 16:40:34,540] [8:139727092389632] - job_saver.py[line:76]: update job 202106131640336474715 task 202106131640336474715_reader_0 0 status update does not take effect: {'job_id': '202106131640336474715', 'task_id': '202106131640336474715_reader_0', 'task_version': '0', 'role': 'guest', 'party_id': '9999', 'status': 'running'}
[WARNING] [2021-06-13 16:40:34,547] [8:139726560425728] - federated_scheduler.py[line:260]: an error occurred while status/running the task to role guest party 9999: 
update task status failed
[INFO] [2021-06-13 16:40:34,547] [8:139726560425728] - federated_scheduler.py[line:197]: sync job 202106131640336474715 task 202106131640336474715_reader_0 0 status running to all party failed: 
{'host': {10000: {'retcode': 0, 'retmsg': 'success'}}, 'guest': {9999: {'retcode': 103, 'retmsg': 'update task status failed'}}}
[INFO] [2021-06-13 16:40:34,567] [8:139727092389632] - task_controller.py[line:71]: try to start job 202106131640336474715 task 202106131640336474715_reader_0 0 on host 10000 executor subprocess
[INFO] [2021-06-13 16:40:34,569] [8:139727092389632] - task_controller.py[line:90]: use computing engine STANDALONE
[INFO] [2021-06-13 16:40:34,570] [8:139727092389632] - task_controller.py[line:145]: job 202106131640336474715 task 202106131640336474715_reader_0 0 on host 10000 executor subprocess is ready
[INFO] [2021-06-13 16:40:34,570] [8:139727092389632] - job_utils.py[line:310]: start process command: /usr/local/bin/python /fate/python/fate_flow/operation/task_executor.py -j 202106131640336474715 -n reader_0 -t 202106131640336474715_reader_0 -v 0 -r host -p 10000 -c /fate/jobs/202106131640336474715/host/10000/reader_0/202106131640336474715_reader_0/0/task_parameters.json --run_ip 127.0.0.1 --job_server 127.0.0.1:9380
[INFO] [2021-06-13 16:40:34,586] [8:139727092389632] - job_utils.py[line:334]: start process command: /usr/local/bin/python /fate/python/fate_flow/operation/task_executor.py -j 202106131640336474715 -n reader_0 -t 202106131640336474715_reader_0 -v 0 -r host -p 10000 -c /fate/jobs/202106131640336474715/host/10000/reader_0/202106131640336474715_reader_0/0/task_parameters.json --run_ip 127.0.0.1 --job_server 127.0.0.1:9380 successfully, pid is 3506
[INFO] [2021-06-13 16:40:34,587] [8:139727092389632] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0
[INFO] [2021-06-13 16:40:34,896] [8:139727092389632] - job_saver.py[line:84]: job 202106131640336474715 task 202106131640336474715_reader_0 0 update successfully
[INFO] [2021-06-13 16:40:34,900] [8:139727092389632] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0 status
[INFO] [2021-06-13 16:40:34,913] [8:139727092389632] - job_saver.py[line:74]: update job 202106131640336474715 task 202106131640336474715_reader_0 0 status successfully: {'job_id': '202106131640336474715', 'task_id': '202106131640336474715_reader_0', 'task_version': '0', 'role': 'host', 'party_id': '10000', 'party_status': 'running', 'start_time': 1623602434586}
[INFO] [2021-06-13 16:40:34,921] [8:139727092389632] - task_controller.py[line:164]: job 202106131640336474715 task 202106131640336474715_reader_0 0 on host 10000 executor subprocess start success
[INFO] [2021-06-13 16:40:34,944] [8:139727100782336] - task_controller.py[line:71]: try to start job 202106131640336474715 task 202106131640336474715_reader_0 0 on guest 9999 executor subprocess
[INFO] [2021-06-13 16:40:34,955] [8:139727100782336] - task_controller.py[line:90]: use computing engine STANDALONE
[INFO] [2021-06-13 16:40:34,955] [8:139727100782336] - task_controller.py[line:145]: job 202106131640336474715 task 202106131640336474715_reader_0 0 on guest 9999 executor subprocess is ready
[INFO] [2021-06-13 16:40:34,955] [8:139727100782336] - job_utils.py[line:310]: start process command: /usr/local/bin/python /fate/python/fate_flow/operation/task_executor.py -j 202106131640336474715 -n reader_0 -t 202106131640336474715_reader_0 -v 0 -r guest -p 9999 -c /fate/jobs/202106131640336474715/guest/9999/reader_0/202106131640336474715_reader_0/0/task_parameters.json --run_ip 127.0.0.1 --job_server 127.0.0.1:9380
[INFO] [2021-06-13 16:40:34,962] [8:139727100782336] - job_utils.py[line:334]: start process command: /usr/local/bin/python /fate/python/fate_flow/operation/task_executor.py -j 202106131640336474715 -n reader_0 -t 202106131640336474715_reader_0 -v 0 -r guest -p 9999 -c /fate/jobs/202106131640336474715/guest/9999/reader_0/202106131640336474715_reader_0/0/task_parameters.json --run_ip 127.0.0.1 --job_server 127.0.0.1:9380 successfully, pid is 3511
[INFO] [2021-06-13 16:40:34,962] [8:139727100782336] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0
[INFO] [2021-06-13 16:40:34,977] [8:139727100782336] - job_saver.py[line:84]: job 202106131640336474715 task 202106131640336474715_reader_0 0 update successfully
[INFO] [2021-06-13 16:40:34,983] [8:139727100782336] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0 status
[INFO] [2021-06-13 16:40:35,014] [8:139727100782336] - job_saver.py[line:74]: update job 202106131640336474715 task 202106131640336474715_reader_0 0 status successfully: {'job_id': '202106131640336474715', 'task_id': '202106131640336474715_reader_0', 'task_version': '0', 'role': 'guest', 'party_id': '9999', 'party_status': 'running', 'start_time': 1623602434962}
[INFO] [2021-06-13 16:40:35,019] [8:139727100782336] - task_controller.py[line:164]: job 202106131640336474715 task 202106131640336474715_reader_0 0 on guest 9999 executor subprocess start success
[INFO] [2021-06-13 16:40:35,025] [8:139726560425728] - task_scheduler.py[line:75]: finish scheduling job 202106131640336474715 tasks
[INFO] [2021-06-13 16:40:35,025] [8:139726560425728] - dag_scheduler.py[line:310]: Job 202106131640336474715 status is running, calculate by task status list: ['running', 'waiting', 'waiting', 'waiting', 'waiting']
[INFO] [2021-06-13 16:40:35,025] [8:139726560425728] - dag_scheduler.py[line:325]: finish scheduling job 202106131640336474715
[INFO] [2021-06-13 16:40:36,564] [3506:140620115568448] - task_executor.py[line:56]: enter task process
[INFO] [2021-06-13 16:40:36,564] [3506:140620115568448] - task_executor.py[line:57]: Namespace(component_name='reader_0', config='/fate/jobs/202106131640336474715/host/10000/reader_0/202106131640336474715_reader_0/0/task_parameters.json', job_id='202106131640336474715', job_server='127.0.0.1:9380', party_id=10000, role='host', run_ip='127.0.0.1', task_id='202106131640336474715_reader_0', task_version=0)
[INFO] [2021-06-13 16:40:36,705] [8:139727100782336] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0
[INFO] [2021-06-13 16:40:36,728] [8:139727100782336] - job_saver.py[line:84]: job 202106131640336474715 task 202106131640336474715_reader_0 0 update successfully
[INFO] [2021-06-13 16:40:36,736] [8:139727100782336] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0 status
[INFO] [2021-06-13 16:40:36,742] [8:139727100782336] - job_saver.py[line:76]: update job 202106131640336474715 task 202106131640336474715_reader_0 0 status update does not take effect: {'job_id': '202106131640336474715', 'component_name': 'reader_0', 'task_id': '202106131640336474715_reader_0', 'task_version': '0', 'role': 'host', 'party_id': '10000', 'run_ip': '127.0.0.1', 'run_pid': 3506, 'party_status': 'running'}
[INFO] [2021-06-13 16:40:37,005] [3511:140712065173312] - task_executor.py[line:56]: enter task process
[INFO] [2021-06-13 16:40:37,006] [3511:140712065173312] - task_executor.py[line:57]: Namespace(component_name='reader_0', config='/fate/jobs/202106131640336474715/guest/9999/reader_0/202106131640336474715_reader_0/0/task_parameters.json', job_id='202106131640336474715', job_server='127.0.0.1:9380', party_id=9999, role='guest', run_ip='127.0.0.1', task_id='202106131640336474715_reader_0', task_version=0)
[INFO] [2021-06-13 16:40:37,008] [8:139727100782336] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0
[INFO] [2021-06-13 16:40:37,025] [8:139727100782336] - job_saver.py[line:84]: job 202106131640336474715 task 202106131640336474715_reader_0 0 update successfully
[INFO] [2021-06-13 16:40:37,031] [8:139727100782336] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0 status
[INFO] [2021-06-13 16:40:37,044] [8:139727100782336] - job_saver.py[line:74]: update job 202106131640336474715 task 202106131640336474715_reader_0 0 status successfully: {'job_id': '202106131640336474715', 'component_name': 'reader_0', 'task_id': '202106131640336474715_reader_0', 'task_version': '0', 'role': 'host', 'party_id': '10000', 'run_ip': '127.0.0.1', 'run_pid': 3506, 'party_status': 'failed', 'end_time': 1623602437003, 'elapsed': 439}
[INFO] [2021-06-13 16:40:37,074] [8:139727100782336] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0
[INFO] [2021-06-13 16:40:37,093] [8:139726560425728] - dag_scheduler.py[line:298]: scheduling job 202106131640336474715
[INFO] [2021-06-13 16:40:37,113] [8:139727100782336] - job_saver.py[line:84]: job 202106131640336474715 task 202106131640336474715_reader_0 0 update successfully
[INFO] [2021-06-13 16:40:37,123] [8:139727100782336] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0 status
[INFO] [2021-06-13 16:40:37,128] [8:139726560425728] - task_scheduler.py[line:28]: scheduling job 202106131640336474715 tasks
[INFO] [2021-06-13 16:40:37,132] [8:139727100782336] - job_saver.py[line:76]: update job 202106131640336474715 task 202106131640336474715_reader_0 0 status update does not take effect: {'job_id': '202106131640336474715', 'component_name': 'reader_0', 'task_id': '202106131640336474715_reader_0', 'task_version': '0', 'role': 'host', 'party_id': '10000', 'run_ip': '127.0.0.1', 'run_pid': 3506, 'party_status': 'failed', 'end_time': 1623602437003, 'elapsed': 439}
[INFO] [2021-06-13 16:40:37,197] [8:139726560425728] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0 status
[INFO] [2021-06-13 16:40:37,203] [8:139726560425728] - job_saver.py[line:76]: update job 202106131640336474715 task 202106131640336474715_reader_0 0 status update does not take effect: {'elapsed': 439, 'end_time': 1623602437003, 'job_id': '202106131640336474715', 'party_id': '10000', 'party_status': 'failed', 'role': 'host', 'start_time': 1623602434586, 'status': 'running', 'task_id': '202106131640336474715_reader_0', 'task_version': 0, 'update_time': 1623602433740}
[INFO] [2021-06-13 16:40:37,203] [8:139726560425728] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0
[INFO] [2021-06-13 16:40:37,216] [8:139726560425728] - job_saver.py[line:84]: job 202106131640336474715 task 202106131640336474715_reader_0 0 update successfully
[INFO] [2021-06-13 16:40:37,216] [8:139726560425728] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0 status
[INFO] [2021-06-13 16:40:37,221] [8:139726560425728] - job_saver.py[line:76]: update job 202106131640336474715 task 202106131640336474715_reader_0 0 status update does not take effect: {'elapsed': None, 'end_time': None, 'job_id': '202106131640336474715', 'party_id': '9999', 'party_status': 'running', 'role': 'guest', 'start_time': 1623602434962, 'status': 'running', 'task_id': '202106131640336474715_reader_0', 'task_version': 0, 'update_time': 1623602433906}
[INFO] [2021-06-13 16:40:37,221] [8:139726560425728] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0
[INFO] [2021-06-13 16:40:37,238] [8:139726560425728] - job_saver.py[line:84]: job 202106131640336474715 task 202106131640336474715_reader_0 0 update successfully
[INFO] [2021-06-13 16:40:37,244] [8:139727100782336] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0
[INFO] [2021-06-13 16:40:37,250] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131640336474715 task 202106131640336474715_reader_0 0 status is failed, calculate by task party status list: ['failed', 'running']
[INFO] [2021-06-13 16:40:37,250] [8:139726560425728] - federated_scheduler.py[line:192]: job 202106131640336474715 task 202106131640336474715_reader_0 0 is failed, sync to all party
[INFO] [2021-06-13 16:40:37,270] [8:139727100782336] - job_saver.py[line:84]: job 202106131640336474715 task 202106131640336474715_reader_0 0 update successfully
[INFO] [2021-06-13 16:40:37,280] [8:139727100782336] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0 status
[INFO] [2021-06-13 16:40:37,286] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0 status
[INFO] [2021-06-13 16:40:37,290] [8:139727100782336] - job_saver.py[line:76]: update job 202106131640336474715 task 202106131640336474715_reader_0 0 status update does not take effect: {'job_id': '202106131640336474715', 'component_name': 'reader_0', 'task_id': '202106131640336474715_reader_0', 'task_version': '0', 'role': 'guest', 'party_id': '9999', 'run_ip': '127.0.0.1', 'run_pid': 3511, 'party_status': 'running'}
[INFO] [2021-06-13 16:40:37,311] [8:139726518462208] - job_saver.py[line:74]: update job 202106131640336474715 task 202106131640336474715_reader_0 0 status successfully: {'job_id': '202106131640336474715', 'task_id': '202106131640336474715_reader_0', 'task_version': '0', 'role': 'host', 'party_id': '10000', 'status': 'failed'}
[INFO] [2021-06-13 16:40:37,325] [8:139726518462208] - resource_manager.py[line:286]: task 202106131640336474715_reader_0 0 return resource successfully
[INFO] [2021-06-13 16:40:37,329] [8:139726518462208] - job_tracker.py[line:424]: clean task 202106131640336474715_reader_0 0 on host 10000
[ERROR] [2021-06-13 16:40:37,330] [8:139726518462208] - job_tracker.py[line:475]: namespace dir /fate/data/202106131640336474715_reader_0_0_host_10000 does not exist
Traceback (most recent call last):
  File "/fate/python/fate_flow/operation/job_tracker.py", line 437, in clean_task
    sess.computing.cleanup(namespace=computing_temp_namespace, name="*")
  File "/fate/python/fate_arch/computing/standalone/_csession.py", line 73, in cleanup
    return self._session.cleanup(name=name, namespace=namespace)
  File "/fate/python/fate_arch/_standalone.py", line 383, in cleanup
    raise EnvironmentError(f"namespace dir {namespace_dir} does not exist")
OSError: namespace dir /fate/data/202106131640336474715_reader_0_0_host_10000 does not exist
[INFO] [2021-06-13 16:40:37,344] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0 status
[INFO] [2021-06-13 16:40:37,359] [8:139726518462208] - job_saver.py[line:74]: update job 202106131640336474715 task 202106131640336474715_reader_0 0 status successfully: {'job_id': '202106131640336474715', 'task_id': '202106131640336474715_reader_0', 'task_version': '0', 'role': 'guest', 'party_id': '9999', 'status': 'failed'}
[INFO] [2021-06-13 16:40:37,371] [8:139726518462208] - resource_manager.py[line:286]: task 202106131640336474715_reader_0 0 return resource successfully
[INFO] [2021-06-13 16:40:37,377] [8:139726518462208] - job_tracker.py[line:424]: clean task 202106131640336474715_reader_0 0 on guest 9999
[ERROR] [2021-06-13 16:40:37,378] [8:139726518462208] - job_tracker.py[line:475]: namespace dir /fate/data/202106131640336474715_reader_0_0_guest_9999 does not exist
Traceback (most recent call last):
  File "/fate/python/fate_flow/operation/job_tracker.py", line 437, in clean_task
    sess.computing.cleanup(namespace=computing_temp_namespace, name="*")
  File "/fate/python/fate_arch/computing/standalone/_csession.py", line 73, in cleanup
    return self._session.cleanup(name=name, namespace=namespace)
  File "/fate/python/fate_arch/_standalone.py", line 383, in cleanup
    raise EnvironmentError(f"namespace dir {namespace_dir} does not exist")
OSError: namespace dir /fate/data/202106131640336474715_reader_0_0_guest_9999 does not exist
[INFO] [2021-06-13 16:40:37,388] [8:139726560425728] - federated_scheduler.py[line:195]: sync job 202106131640336474715 task 202106131640336474715_reader_0 0 status failed to all party success
[INFO] [2021-06-13 16:40:37,388] [8:139726560425728] - federated_scheduler.py[line:202]: try to stop job 202106131640336474715 task 202106131640336474715_reader_0 0
[INFO] [2021-06-13 16:40:37,413] [8:139726518462208] - job_utils.py[line:397]: try to stop job 202106131640336474715 task 202106131640336474715_reader_0 host 10000 with failed party status process pid:3506
[INFO] [2021-06-13 16:40:37,413] [8:139726518462208] - job_utils.py[line:400]: can not found job 202106131640336474715 task 202106131640336474715_reader_0 host 10000 with failed party status process pid:3506
[INFO] [2021-06-13 16:40:37,416] [8:139726518462208] - job_utils.py[line:424]: start run subprocess to stop task session 202106131640336474715_reader_0_0_host_10000
[INFO] [2021-06-13 16:40:37,416] [8:139726518462208] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106131640336474715_reader_0_0_host_10000 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c kill
[INFO] [2021-06-13 16:40:37,422] [8:139726518462208] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106131640336474715_reader_0_0_host_10000 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c kill successfully, pid is 3544
[INFO] [2021-06-13 16:40:37,423] [8:139726518462208] - task_controller.py[line:255]: job 202106131640336474715 task 202106131640336474715_reader_0 0 on host 10000 process 3506 kill success
[INFO] [2021-06-13 16:40:37,424] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0 status
[INFO] [2021-06-13 16:40:37,428] [8:139726518462208] - job_saver.py[line:76]: update job 202106131640336474715 task 202106131640336474715_reader_0 0 status update does not take effect: {'job_id': '202106131640336474715', 'task_id': '202106131640336474715_reader_0', 'task_version': 0, 'role': 'host', 'party_id': '10000', 'party_status': 'failed'}
[INFO] [2021-06-13 16:40:37,433] [8:139726518462208] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0
[WARNING] [2021-06-13 16:40:37,438] [8:139726518462208] - job_saver.py[line:86]: job 202106131640336474715 task 202106131640336474715_reader_0 0 update does not take effect
[INFO] [2021-06-13 16:40:37,462] [8:139726518462208] - job_utils.py[line:397]: try to stop job 202106131640336474715 task 202106131640336474715_reader_0 guest 9999 with running party status process pid:3511
[INFO] [2021-06-13 16:40:37,463] [8:139726518462208] - job_utils.py[line:372]: ['/usr/local/bin/python', '/fate/python/fate_flow/operation/task_executor.py', '-j', '202106131640336474715', '-n', 'reader_0', '-t', '202106131640336474715_reader_0', '-v', '0', '-r', 'guest', '-p', '9999', '-c', '/fate/jobs/202106131640336474715/guest/9999/reader_0/202106131640336474715_reader_0/0/task_parameters.json', '--run_ip', '127.0.0.1', '--job_server', '127.0.0.1:9380']
[INFO] [2021-06-13 16:40:37,463] [8:139726518462208] - job_utils.py[line:372]: ['/usr/local/bin/python', '/fate/python/fate_flow/operation/task_executor.py', '-j', '202106131640336474715', '-n', 'reader_0', '-t', '202106131640336474715_reader_0', '-v', '0', '-r', 'guest', '-p', '9999', '-c', '/fate/jobs/202106131640336474715/guest/9999/reader_0/202106131640336474715_reader_0/0/task_parameters.json', '--run_ip', '127.0.0.1', '--job_server', '127.0.0.1:9380']
[INFO] [2021-06-13 16:40:37,464] [8:139726518462208] - job_utils.py[line:414]: successfully stop job 202106131640336474715 task 202106131640336474715_reader_0 guest 9999 process pid:3511
[INFO] [2021-06-13 16:40:37,470] [8:139726518462208] - job_utils.py[line:424]: start run subprocess to stop task session 202106131640336474715_reader_0_0_guest_9999
[INFO] [2021-06-13 16:40:37,471] [8:139726518462208] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106131640336474715_reader_0_0_guest_9999 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c kill
[INFO] [2021-06-13 16:40:37,479] [8:139726518462208] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106131640336474715_reader_0_0_guest_9999 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c kill successfully, pid is 3546
[INFO] [2021-06-13 16:40:37,480] [8:139726518462208] - task_controller.py[line:255]: job 202106131640336474715 task 202106131640336474715_reader_0 0 on guest 9999 process 3511 kill success
[INFO] [2021-06-13 16:40:37,480] [8:139726518462208] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0 status
[INFO] [2021-06-13 16:40:37,864] [8:139726518462208] - job_saver.py[line:74]: update job 202106131640336474715 task 202106131640336474715_reader_0 0 status successfully: {'job_id': '202106131640336474715', 'task_id': '202106131640336474715_reader_0', 'task_version': 0, 'role': 'guest', 'party_id': '9999', 'party_status': 'failed'}
[INFO] [2021-06-13 16:40:37,872] [8:139726518462208] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0
[WARNING] [2021-06-13 16:40:37,884] [8:139726518462208] - job_saver.py[line:86]: job 202106131640336474715 task 202106131640336474715_reader_0 0 update does not take effect
[INFO] [2021-06-13 16:40:37,902] [8:139726560425728] - federated_scheduler.py[line:206]: stop job 202106131640336474715 task 202106131640336474715_reader_0 0 success
[INFO] [2021-06-13 16:40:37,932] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131640336474715 task 202106131640336474715_dataio_0 0 status is waiting, calculate by task party status list: ['waiting', 'waiting']
[INFO] [2021-06-13 16:40:38,017] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131640336474715 task 202106131640336474715_intersection_0 0 status is waiting, calculate by task party status list: ['waiting', 'waiting']
[INFO] [2021-06-13 16:40:38,053] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131640336474715 task 202106131640336474715_hetero_secureboost_0 0 status is waiting, calculate by task party status list: ['waiting', 'waiting']
[INFO] [2021-06-13 16:40:38,071] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131640336474715 task 202106131640336474715_evaluation_0 0 status is waiting, calculate by task party status list: ['waiting', 'waiting']
[INFO] [2021-06-13 16:40:38,072] [8:139726560425728] - task_scheduler.py[line:75]: finish scheduling job 202106131640336474715 tasks
[INFO] [2021-06-13 16:40:38,072] [8:139726560425728] - dag_scheduler.py[line:310]: Job 202106131640336474715 status is failed, calculate by task status list: ['failed', 'waiting', 'waiting', 'waiting', 'waiting']
[INFO] [2021-06-13 16:40:38,073] [8:139726560425728] - federated_scheduler.py[line:58]: sync job 202106131640336474715 info to all party
[INFO] [2021-06-13 16:40:38,083] [8:139727100782336] - job_saver.py[line:61]: try to update job 202106131640336474715
[INFO] [2021-06-13 16:40:38,104] [8:139727100782336] - job_saver.py[line:64]: job 202106131640336474715 update successfully: {'job_id': '202106131640336474715', 'role': 'host', 'party_id': '10000', 'progress': 20.0}
[INFO] [2021-06-13 16:40:38,114] [8:139727100782336] - job_saver.py[line:61]: try to update job 202106131640336474715
[INFO] [2021-06-13 16:40:38,131] [8:139727100782336] - job_saver.py[line:64]: job 202106131640336474715 update successfully: {'job_id': '202106131640336474715', 'role': 'guest', 'party_id': '9999', 'progress': 20.0}
[INFO] [2021-06-13 16:40:38,135] [8:139726560425728] - federated_scheduler.py[line:61]: sync job 202106131640336474715 info to all party successfully
[INFO] [2021-06-13 16:40:38,142] [8:139726560425728] - job_saver.py[line:45]: try to update job 202106131640336474715 status to None
[INFO] [2021-06-13 16:40:38,149] [8:139726560425728] - job_saver.py[line:56]: update job 202106131640336474715 status does not take effect
[INFO] [2021-06-13 16:40:38,149] [8:139726560425728] - job_saver.py[line:61]: try to update job 202106131640336474715
[INFO] [2021-06-13 16:40:38,164] [8:139726560425728] - job_saver.py[line:64]: job 202106131640336474715 update successfully: {'job_id': '202106131640336474715', 'role': 'host', 'party_id': '10000', 'progress': 20.0}
[INFO] [2021-06-13 16:40:38,164] [8:139726560425728] - job_saver.py[line:45]: try to update job 202106131640336474715 status to None
[INFO] [2021-06-13 16:40:38,170] [8:139726560425728] - job_saver.py[line:56]: update job 202106131640336474715 status does not take effect
[INFO] [2021-06-13 16:40:38,171] [8:139726560425728] - job_saver.py[line:61]: try to update job 202106131640336474715
[INFO] [2021-06-13 16:40:38,184] [8:139726560425728] - job_saver.py[line:64]: job 202106131640336474715 update successfully: {'job_id': '202106131640336474715', 'role': 'guest', 'party_id': '9999', 'progress': 20.0}
[INFO] [2021-06-13 16:40:38,184] [8:139726560425728] - federated_scheduler.py[line:78]: try to save job 202106131640336474715 pipelined model
[INFO] [2021-06-13 16:40:38,188] [8:139727100782336] - job_controller.py[line:331]: job 202106131640336474715 on host 10000 start to save pipeline
[INFO] [2021-06-13 16:40:38,235] [8:139727100782336] - job_tracker.py[line:517]: save 202106131640336474715 model info done. model id: guest-9999#host-10000#model, model version: 202106131640336474715.
[INFO] [2021-06-13 16:40:38,236] [8:139727100782336] - job_controller.py[line:374]: job 202106131640336474715 on host 10000 save pipeline successfully
[INFO] [2021-06-13 16:40:38,246] [8:139727100782336] - job_controller.py[line:331]: job 202106131640336474715 on guest 9999 start to save pipeline
[INFO] [2021-06-13 16:40:38,319] [3544:140565725665088] - session_utils.py[line:38]: start kill session 202106131640336474715_reader_0_0_host_10000
[INFO] [2021-06-13 16:40:38,319] [3544:140565725665088] - session_utils.py[line:47]: kill session 202106131640336474715_reader_0_0_host_10000 success
[INFO] [2021-06-13 16:40:38,368] [3546:140167193139008] - session_utils.py[line:38]: start kill session 202106131640336474715_reader_0_0_guest_9999
[INFO] [2021-06-13 16:40:38,368] [3546:140167193139008] - session_utils.py[line:47]: kill session 202106131640336474715_reader_0_0_guest_9999 success
[INFO] [2021-06-13 16:40:38,387] [8:139727100782336] - job_tracker.py[line:517]: save 202106131640336474715 model info done. model id: guest-9999#host-10000#model, model version: 202106131640336474715.
[INFO] [2021-06-13 16:40:38,388] [8:139727100782336] - job_controller.py[line:374]: job 202106131640336474715 on guest 9999 save pipeline successfully
[INFO] [2021-06-13 16:40:38,392] [8:139726560425728] - federated_scheduler.py[line:81]: save job 202106131640336474715 pipelined model success
[INFO] [2021-06-13 16:40:38,393] [8:139726560425728] - federated_scheduler.py[line:68]: job 202106131640336474715 is failed, sync to all party
[INFO] [2021-06-13 16:40:38,400] [8:139727100782336] - job_saver.py[line:45]: try to update job 202106131640336474715 status to failed
[INFO] [2021-06-13 16:40:38,418] [8:139727100782336] - job_saver.py[line:48]: update job 202106131640336474715 status successfully
[INFO] [2021-06-13 16:40:38,456] [8:139727100782336] - resource_manager.py[line:176]: return job 202106131640336474715 resource(cores 4 memory 0) on host 10000 successfully, remaining cores: 16 remaining memory: 0
[INFO] [2021-06-13 16:40:38,467] [8:139727100782336] - job_saver.py[line:45]: try to update job 202106131640336474715 status to failed
[INFO] [2021-06-13 16:40:38,481] [8:139727100782336] - job_saver.py[line:48]: update job 202106131640336474715 status successfully
[INFO] [2021-06-13 16:40:38,505] [8:139727100782336] - resource_manager.py[line:176]: return job 202106131640336474715 resource(cores 4 memory 0) on guest 9999 successfully, remaining cores: 20 remaining memory: 0
[INFO] [2021-06-13 16:40:38,509] [8:139726560425728] - federated_scheduler.py[line:71]: sync job 202106131640336474715 status failed to all party success
[INFO] [2021-06-13 16:40:38,515] [8:139726560425728] - job_saver.py[line:45]: try to update job 202106131640336474715 status to failed
[INFO] [2021-06-13 16:40:38,520] [8:139726560425728] - job_saver.py[line:56]: update job 202106131640336474715 status does not take effect
[INFO] [2021-06-13 16:40:38,520] [8:139726560425728] - job_saver.py[line:61]: try to update job 202106131640336474715
[WARNING] [2021-06-13 16:40:38,525] [8:139726560425728] - job_saver.py[line:66]: job 202106131640336474715 update does not take effect: {'job_id': '202106131640336474715', 'role': 'host', 'party_id': '10000', 'status': 'failed'}
[INFO] [2021-06-13 16:40:38,526] [8:139726560425728] - job_saver.py[line:45]: try to update job 202106131640336474715 status to failed
[INFO] [2021-06-13 16:40:38,529] [8:139726560425728] - job_saver.py[line:56]: update job 202106131640336474715 status does not take effect
[INFO] [2021-06-13 16:40:38,530] [8:139726560425728] - job_saver.py[line:61]: try to update job 202106131640336474715
[WARNING] [2021-06-13 16:40:38,534] [8:139726560425728] - job_saver.py[line:66]: job 202106131640336474715 update does not take effect: {'job_id': '202106131640336474715', 'role': 'guest', 'party_id': '9999', 'status': 'failed'}
[INFO] [2021-06-13 16:40:38,534] [8:139726560425728] - dag_scheduler.py[line:502]: Job 202106131640336474715 finished with failed, do something...
[INFO] [2021-06-13 16:40:38,534] [8:139726560425728] - dag_scheduler.py[line:436]: request stop job 202106131640336474715 with failed
[INFO] [2021-06-13 16:40:38,538] [8:139726560425728] - dag_scheduler.py[line:445]: request stop job 202106131640336474715 with failed to all party
[INFO] [2021-06-13 16:40:38,538] [8:139726560425728] - federated_scheduler.py[line:88]: try to stop job 202106131640336474715
[INFO] [2021-06-13 16:40:38,549] [8:139727100782336] - job_utils.py[line:393]: job 202106131640336474715 task 202106131640336474715_evaluation_0 host 10000 with waiting party status no process pid
[INFO] [2021-06-13 16:40:38,549] [8:139727100782336] - task_controller.py[line:255]: job 202106131640336474715 task 202106131640336474715_evaluation_0 0 on host 10000 process None kill success
[INFO] [2021-06-13 16:40:38,549] [8:139727100782336] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_evaluation_0 0 status
[INFO] [2021-06-13 16:40:38,559] [8:139727100782336] - job_saver.py[line:76]: update job 202106131640336474715 task 202106131640336474715_evaluation_0 0 status update does not take effect: {'job_id': '202106131640336474715', 'task_id': '202106131640336474715_evaluation_0', 'task_version': 0, 'role': 'host', 'party_id': '10000', 'party_status': 'failed'}
[INFO] [2021-06-13 16:40:38,565] [8:139727100782336] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_evaluation_0 0
[WARNING] [2021-06-13 16:40:38,570] [8:139727100782336] - job_saver.py[line:86]: job 202106131640336474715 task 202106131640336474715_evaluation_0 0 update does not take effect
[INFO] [2021-06-13 16:40:38,574] [8:139727100782336] - job_utils.py[line:393]: job 202106131640336474715 task 202106131640336474715_hetero_secureboost_0 host 10000 with waiting party status no process pid
[INFO] [2021-06-13 16:40:38,574] [8:139727100782336] - task_controller.py[line:255]: job 202106131640336474715 task 202106131640336474715_hetero_secureboost_0 0 on host 10000 process None kill success
[INFO] [2021-06-13 16:40:38,574] [8:139727100782336] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_hetero_secureboost_0 0 status
[INFO] [2021-06-13 16:40:38,579] [8:139727100782336] - job_saver.py[line:76]: update job 202106131640336474715 task 202106131640336474715_hetero_secureboost_0 0 status update does not take effect: {'job_id': '202106131640336474715', 'task_id': '202106131640336474715_hetero_secureboost_0', 'task_version': 0, 'role': 'host', 'party_id': '10000', 'party_status': 'failed'}
[INFO] [2021-06-13 16:40:38,586] [8:139727100782336] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_hetero_secureboost_0 0
[WARNING] [2021-06-13 16:40:38,602] [8:139727100782336] - job_saver.py[line:86]: job 202106131640336474715 task 202106131640336474715_hetero_secureboost_0 0 update does not take effect
[INFO] [2021-06-13 16:40:38,606] [8:139727100782336] - job_utils.py[line:393]: job 202106131640336474715 task 202106131640336474715_intersection_0 host 10000 with waiting party status no process pid
[INFO] [2021-06-13 16:40:38,606] [8:139727100782336] - task_controller.py[line:255]: job 202106131640336474715 task 202106131640336474715_intersection_0 0 on host 10000 process None kill success
[INFO] [2021-06-13 16:40:38,606] [8:139727100782336] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_intersection_0 0 status
[INFO] [2021-06-13 16:40:38,610] [8:139727100782336] - job_saver.py[line:76]: update job 202106131640336474715 task 202106131640336474715_intersection_0 0 status update does not take effect: {'job_id': '202106131640336474715', 'task_id': '202106131640336474715_intersection_0', 'task_version': 0, 'role': 'host', 'party_id': '10000', 'party_status': 'failed'}
[INFO] [2021-06-13 16:40:38,616] [8:139727100782336] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_intersection_0 0
[WARNING] [2021-06-13 16:40:38,621] [8:139727100782336] - job_saver.py[line:86]: job 202106131640336474715 task 202106131640336474715_intersection_0 0 update does not take effect
[INFO] [2021-06-13 16:40:38,626] [8:139727100782336] - job_utils.py[line:393]: job 202106131640336474715 task 202106131640336474715_dataio_0 host 10000 with waiting party status no process pid
[INFO] [2021-06-13 16:40:38,626] [8:139727100782336] - task_controller.py[line:255]: job 202106131640336474715 task 202106131640336474715_dataio_0 0 on host 10000 process None kill success
[INFO] [2021-06-13 16:40:38,626] [8:139727100782336] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_dataio_0 0 status
[INFO] [2021-06-13 16:40:38,630] [8:139727100782336] - job_saver.py[line:76]: update job 202106131640336474715 task 202106131640336474715_dataio_0 0 status update does not take effect: {'job_id': '202106131640336474715', 'task_id': '202106131640336474715_dataio_0', 'task_version': 0, 'role': 'host', 'party_id': '10000', 'party_status': 'failed'}
[INFO] [2021-06-13 16:40:38,634] [8:139727100782336] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_dataio_0 0
[WARNING] [2021-06-13 16:40:38,639] [8:139727100782336] - job_saver.py[line:86]: job 202106131640336474715 task 202106131640336474715_dataio_0 0 update does not take effect
[INFO] [2021-06-13 16:40:38,643] [8:139727100782336] - job_utils.py[line:397]: try to stop job 202106131640336474715 task 202106131640336474715_reader_0 host 10000 with failed party status process pid:3506
[INFO] [2021-06-13 16:40:38,643] [8:139727100782336] - job_utils.py[line:400]: can not found job 202106131640336474715 task 202106131640336474715_reader_0 host 10000 with failed party status process pid:3506
[INFO] [2021-06-13 16:40:38,647] [8:139727100782336] - job_utils.py[line:424]: start run subprocess to stop task session 202106131640336474715_reader_0_0_host_10000
[INFO] [2021-06-13 16:40:38,647] [8:139727100782336] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106131640336474715_reader_0_0_host_10000 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c kill
[INFO] [2021-06-13 16:40:38,653] [8:139727100782336] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106131640336474715_reader_0_0_host_10000 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c kill successfully, pid is 3573
[INFO] [2021-06-13 16:40:38,654] [8:139727100782336] - task_controller.py[line:255]: job 202106131640336474715 task 202106131640336474715_reader_0 0 on host 10000 process 3506 kill success
[INFO] [2021-06-13 16:40:38,654] [8:139727100782336] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0 status
[INFO] [2021-06-13 16:40:38,659] [8:139727100782336] - job_saver.py[line:76]: update job 202106131640336474715 task 202106131640336474715_reader_0 0 status update does not take effect: {'job_id': '202106131640336474715', 'task_id': '202106131640336474715_reader_0', 'task_version': 0, 'role': 'host', 'party_id': '10000', 'party_status': 'failed'}
[INFO] [2021-06-13 16:40:38,664] [8:139727100782336] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0
[WARNING] [2021-06-13 16:40:38,667] [8:139727100782336] - job_saver.py[line:86]: job 202106131640336474715 task 202106131640336474715_reader_0 0 update does not take effect
[INFO] [2021-06-13 16:40:38,671] [8:139727100782336] - job_saver.py[line:45]: try to update job 202106131640336474715 status to failed
[INFO] [2021-06-13 16:40:38,679] [8:139727100782336] - job_saver.py[line:56]: update job 202106131640336474715 status does not take effect
[INFO] [2021-06-13 16:40:38,702] [8:139727100782336] - job_utils.py[line:393]: job 202106131640336474715 task 202106131640336474715_evaluation_0 guest 9999 with waiting party status no process pid
[INFO] [2021-06-13 16:40:38,702] [8:139727100782336] - task_controller.py[line:255]: job 202106131640336474715 task 202106131640336474715_evaluation_0 0 on guest 9999 process None kill success
[INFO] [2021-06-13 16:40:38,702] [8:139727100782336] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_evaluation_0 0 status
[INFO] [2021-06-13 16:40:38,707] [8:139727100782336] - job_saver.py[line:76]: update job 202106131640336474715 task 202106131640336474715_evaluation_0 0 status update does not take effect: {'job_id': '202106131640336474715', 'task_id': '202106131640336474715_evaluation_0', 'task_version': 0, 'role': 'guest', 'party_id': '9999', 'party_status': 'failed'}
[INFO] [2021-06-13 16:40:38,712] [8:139727100782336] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_evaluation_0 0
[WARNING] [2021-06-13 16:40:38,717] [8:139727100782336] - job_saver.py[line:86]: job 202106131640336474715 task 202106131640336474715_evaluation_0 0 update does not take effect
[INFO] [2021-06-13 16:40:38,721] [8:139727100782336] - job_utils.py[line:393]: job 202106131640336474715 task 202106131640336474715_hetero_secureboost_0 guest 9999 with waiting party status no process pid
[INFO] [2021-06-13 16:40:38,722] [8:139727100782336] - task_controller.py[line:255]: job 202106131640336474715 task 202106131640336474715_hetero_secureboost_0 0 on guest 9999 process None kill success
[INFO] [2021-06-13 16:40:38,722] [8:139727100782336] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_hetero_secureboost_0 0 status
[INFO] [2021-06-13 16:40:38,728] [8:139727100782336] - job_saver.py[line:76]: update job 202106131640336474715 task 202106131640336474715_hetero_secureboost_0 0 status update does not take effect: {'job_id': '202106131640336474715', 'task_id': '202106131640336474715_hetero_secureboost_0', 'task_version': 0, 'role': 'guest', 'party_id': '9999', 'party_status': 'failed'}
[INFO] [2021-06-13 16:40:38,733] [8:139727100782336] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_hetero_secureboost_0 0
[WARNING] [2021-06-13 16:40:38,738] [8:139727100782336] - job_saver.py[line:86]: job 202106131640336474715 task 202106131640336474715_hetero_secureboost_0 0 update does not take effect
[INFO] [2021-06-13 16:40:38,745] [8:139727100782336] - job_utils.py[line:393]: job 202106131640336474715 task 202106131640336474715_intersection_0 guest 9999 with waiting party status no process pid
[INFO] [2021-06-13 16:40:38,746] [8:139727100782336] - task_controller.py[line:255]: job 202106131640336474715 task 202106131640336474715_intersection_0 0 on guest 9999 process None kill success
[INFO] [2021-06-13 16:40:38,746] [8:139727100782336] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_intersection_0 0 status
[INFO] [2021-06-13 16:40:38,751] [8:139727100782336] - job_saver.py[line:76]: update job 202106131640336474715 task 202106131640336474715_intersection_0 0 status update does not take effect: {'job_id': '202106131640336474715', 'task_id': '202106131640336474715_intersection_0', 'task_version': 0, 'role': 'guest', 'party_id': '9999', 'party_status': 'failed'}
[INFO] [2021-06-13 16:40:38,757] [8:139727100782336] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_intersection_0 0
[WARNING] [2021-06-13 16:40:38,763] [8:139727100782336] - job_saver.py[line:86]: job 202106131640336474715 task 202106131640336474715_intersection_0 0 update does not take effect
[INFO] [2021-06-13 16:40:38,769] [8:139727100782336] - job_utils.py[line:393]: job 202106131640336474715 task 202106131640336474715_dataio_0 guest 9999 with waiting party status no process pid
[INFO] [2021-06-13 16:40:38,769] [8:139727100782336] - task_controller.py[line:255]: job 202106131640336474715 task 202106131640336474715_dataio_0 0 on guest 9999 process None kill success
[INFO] [2021-06-13 16:40:38,769] [8:139727100782336] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_dataio_0 0 status
[INFO] [2021-06-13 16:40:38,775] [8:139727100782336] - job_saver.py[line:76]: update job 202106131640336474715 task 202106131640336474715_dataio_0 0 status update does not take effect: {'job_id': '202106131640336474715', 'task_id': '202106131640336474715_dataio_0', 'task_version': 0, 'role': 'guest', 'party_id': '9999', 'party_status': 'failed'}
[INFO] [2021-06-13 16:40:38,780] [8:139727100782336] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_dataio_0 0
[WARNING] [2021-06-13 16:40:38,784] [8:139727100782336] - job_saver.py[line:86]: job 202106131640336474715 task 202106131640336474715_dataio_0 0 update does not take effect
[INFO] [2021-06-13 16:40:38,788] [8:139727100782336] - job_utils.py[line:397]: try to stop job 202106131640336474715 task 202106131640336474715_reader_0 guest 9999 with failed party status process pid:3511
[INFO] [2021-06-13 16:40:38,789] [8:139727100782336] - job_utils.py[line:400]: can not found job 202106131640336474715 task 202106131640336474715_reader_0 guest 9999 with failed party status process pid:3511
[INFO] [2021-06-13 16:40:38,792] [8:139727100782336] - job_utils.py[line:424]: start run subprocess to stop task session 202106131640336474715_reader_0_0_guest_9999
[INFO] [2021-06-13 16:40:38,793] [8:139727100782336] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106131640336474715_reader_0_0_guest_9999 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c kill
[INFO] [2021-06-13 16:40:38,800] [8:139727100782336] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106131640336474715_reader_0_0_guest_9999 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c kill successfully, pid is 3575
[INFO] [2021-06-13 16:40:38,802] [8:139727100782336] - task_controller.py[line:255]: job 202106131640336474715 task 202106131640336474715_reader_0 0 on guest 9999 process 3511 kill success
[INFO] [2021-06-13 16:40:38,802] [8:139727100782336] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0 status
[INFO] [2021-06-13 16:40:38,807] [8:139727100782336] - job_saver.py[line:76]: update job 202106131640336474715 task 202106131640336474715_reader_0 0 status update does not take effect: {'job_id': '202106131640336474715', 'task_id': '202106131640336474715_reader_0', 'task_version': 0, 'role': 'guest', 'party_id': '9999', 'party_status': 'failed'}
[INFO] [2021-06-13 16:40:38,812] [8:139727100782336] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0
[WARNING] [2021-06-13 16:40:38,817] [8:139727100782336] - job_saver.py[line:86]: job 202106131640336474715 task 202106131640336474715_reader_0 0 update does not take effect
[INFO] [2021-06-13 16:40:38,825] [8:139727100782336] - job_saver.py[line:45]: try to update job 202106131640336474715 status to failed
[INFO] [2021-06-13 16:40:38,848] [8:139727100782336] - job_saver.py[line:56]: update job 202106131640336474715 status does not take effect
[INFO] [2021-06-13 16:40:38,857] [8:139726560425728] - federated_scheduler.py[line:92]: stop job 202106131640336474715 success
[INFO] [2021-06-13 16:40:38,858] [8:139726560425728] - dag_scheduler.py[line:448]: stop job 202106131640336474715 with failed successfully
[INFO] [2021-06-13 16:40:38,858] [8:139726560425728] - federated_scheduler.py[line:107]: try to clean job 202106131640336474715
[INFO] [2021-06-13 16:40:38,865] [8:139727100782336] - job_controller.py[line:379]: Job 202106131640336474715 on host 10000 start to clean
[INFO] [2021-06-13 16:40:38,865] [8:139727100782336] - job_controller.py[line:382]: job 202106131640336474715 on host 10000 clean done
[INFO] [2021-06-13 16:40:38,876] [8:139727100782336] - job_controller.py[line:379]: Job 202106131640336474715 on guest 9999 start to clean
[INFO] [2021-06-13 16:40:38,876] [8:139727100782336] - job_controller.py[line:382]: job 202106131640336474715 on guest 9999 clean done
[INFO] [2021-06-13 16:40:38,882] [8:139726560425728] - federated_scheduler.py[line:110]: clean job 202106131640336474715 success
[INFO] [2021-06-13 16:40:38,882] [8:139726560425728] - dag_scheduler.py[line:505]: Job 202106131640336474715 finished with failed, done
[INFO] [2021-06-13 16:40:38,882] [8:139726560425728] - dag_scheduler.py[line:325]: finish scheduling job 202106131640336474715
[INFO] [2021-06-13 16:40:38,918] [8:139726560425728] - dag_scheduler.py[line:298]: scheduling job 202106131640336474715
[INFO] [2021-06-13 16:40:38,936] [8:139726560425728] - task_scheduler.py[line:28]: scheduling job 202106131640336474715 tasks
[INFO] [2021-06-13 16:40:38,957] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131640336474715 task 202106131640336474715_reader_0 0 status is failed, calculate by task party status list: ['failed', 'failed']
[INFO] [2021-06-13 16:40:38,969] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131640336474715 task 202106131640336474715_dataio_0 0 status is waiting, calculate by task party status list: ['waiting', 'waiting']
[INFO] [2021-06-13 16:40:38,982] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131640336474715 task 202106131640336474715_intersection_0 0 status is waiting, calculate by task party status list: ['waiting', 'waiting']
[INFO] [2021-06-13 16:40:38,993] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131640336474715 task 202106131640336474715_hetero_secureboost_0 0 status is waiting, calculate by task party status list: ['waiting', 'waiting']
[INFO] [2021-06-13 16:40:39,006] [8:139726560425728] - task_scheduler.py[line:143]: job 202106131640336474715 task 202106131640336474715_evaluation_0 0 status is waiting, calculate by task party status list: ['waiting', 'waiting']
[INFO] [2021-06-13 16:40:39,007] [8:139726560425728] - task_scheduler.py[line:75]: finish scheduling job 202106131640336474715 tasks
[INFO] [2021-06-13 16:40:39,008] [8:139726560425728] - dag_scheduler.py[line:310]: Job 202106131640336474715 status is failed, calculate by task status list: ['failed', 'waiting', 'waiting', 'waiting', 'waiting']
[INFO] [2021-06-13 16:40:39,009] [8:139726560425728] - dag_scheduler.py[line:502]: Job 202106131640336474715 finished with failed, do something...
[INFO] [2021-06-13 16:40:39,009] [8:139726560425728] - dag_scheduler.py[line:436]: request stop job 202106131640336474715 with failed
[INFO] [2021-06-13 16:40:39,019] [8:139726560425728] - dag_scheduler.py[line:445]: request stop job 202106131640336474715 with failed to all party
[INFO] [2021-06-13 16:40:39,019] [8:139726560425728] - federated_scheduler.py[line:88]: try to stop job 202106131640336474715
[INFO] [2021-06-13 16:40:39,045] [8:139727100782336] - job_utils.py[line:393]: job 202106131640336474715 task 202106131640336474715_evaluation_0 host 10000 with waiting party status no process pid
[INFO] [2021-06-13 16:40:39,046] [8:139727100782336] - task_controller.py[line:255]: job 202106131640336474715 task 202106131640336474715_evaluation_0 0 on host 10000 process None kill success
[INFO] [2021-06-13 16:40:39,047] [8:139727100782336] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_evaluation_0 0 status
[INFO] [2021-06-13 16:40:39,055] [8:139727100782336] - job_saver.py[line:76]: update job 202106131640336474715 task 202106131640336474715_evaluation_0 0 status update does not take effect: {'job_id': '202106131640336474715', 'task_id': '202106131640336474715_evaluation_0', 'task_version': 0, 'role': 'host', 'party_id': '10000', 'party_status': 'failed'}
[INFO] [2021-06-13 16:40:39,073] [8:139727100782336] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_evaluation_0 0
[WARNING] [2021-06-13 16:40:39,088] [8:139727100782336] - job_saver.py[line:86]: job 202106131640336474715 task 202106131640336474715_evaluation_0 0 update does not take effect
[INFO] [2021-06-13 16:40:39,094] [8:139727100782336] - job_utils.py[line:393]: job 202106131640336474715 task 202106131640336474715_hetero_secureboost_0 host 10000 with waiting party status no process pid
[INFO] [2021-06-13 16:40:39,103] [8:139727100782336] - task_controller.py[line:255]: job 202106131640336474715 task 202106131640336474715_hetero_secureboost_0 0 on host 10000 process None kill success
[INFO] [2021-06-13 16:40:39,104] [8:139727100782336] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_hetero_secureboost_0 0 status
[INFO] [2021-06-13 16:40:39,118] [8:139727100782336] - job_saver.py[line:76]: update job 202106131640336474715 task 202106131640336474715_hetero_secureboost_0 0 status update does not take effect: {'job_id': '202106131640336474715', 'task_id': '202106131640336474715_hetero_secureboost_0', 'task_version': 0, 'role': 'host', 'party_id': '10000', 'party_status': 'failed'}
[INFO] [2021-06-13 16:40:39,126] [8:139727100782336] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_hetero_secureboost_0 0
[WARNING] [2021-06-13 16:40:39,132] [8:139727100782336] - job_saver.py[line:86]: job 202106131640336474715 task 202106131640336474715_hetero_secureboost_0 0 update does not take effect
[INFO] [2021-06-13 16:40:39,144] [8:139727100782336] - job_utils.py[line:393]: job 202106131640336474715 task 202106131640336474715_intersection_0 host 10000 with waiting party status no process pid
[INFO] [2021-06-13 16:40:39,145] [8:139727100782336] - task_controller.py[line:255]: job 202106131640336474715 task 202106131640336474715_intersection_0 0 on host 10000 process None kill success
[INFO] [2021-06-13 16:40:39,145] [8:139727100782336] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_intersection_0 0 status
[INFO] [2021-06-13 16:40:39,154] [8:139727100782336] - job_saver.py[line:76]: update job 202106131640336474715 task 202106131640336474715_intersection_0 0 status update does not take effect: {'job_id': '202106131640336474715', 'task_id': '202106131640336474715_intersection_0', 'task_version': 0, 'role': 'host', 'party_id': '10000', 'party_status': 'failed'}
[INFO] [2021-06-13 16:40:39,166] [8:139727100782336] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_intersection_0 0
[WARNING] [2021-06-13 16:40:39,174] [8:139727100782336] - job_saver.py[line:86]: job 202106131640336474715 task 202106131640336474715_intersection_0 0 update does not take effect
[INFO] [2021-06-13 16:40:39,186] [8:139727100782336] - job_utils.py[line:393]: job 202106131640336474715 task 202106131640336474715_dataio_0 host 10000 with waiting party status no process pid
[INFO] [2021-06-13 16:40:39,186] [8:139727100782336] - task_controller.py[line:255]: job 202106131640336474715 task 202106131640336474715_dataio_0 0 on host 10000 process None kill success
[INFO] [2021-06-13 16:40:39,186] [8:139727100782336] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_dataio_0 0 status
[INFO] [2021-06-13 16:40:39,200] [8:139727100782336] - job_saver.py[line:76]: update job 202106131640336474715 task 202106131640336474715_dataio_0 0 status update does not take effect: {'job_id': '202106131640336474715', 'task_id': '202106131640336474715_dataio_0', 'task_version': 0, 'role': 'host', 'party_id': '10000', 'party_status': 'failed'}
[INFO] [2021-06-13 16:40:39,207] [8:139727100782336] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_dataio_0 0
[WARNING] [2021-06-13 16:40:39,217] [8:139727100782336] - job_saver.py[line:86]: job 202106131640336474715 task 202106131640336474715_dataio_0 0 update does not take effect
[INFO] [2021-06-13 16:40:39,224] [8:139727100782336] - job_utils.py[line:397]: try to stop job 202106131640336474715 task 202106131640336474715_reader_0 host 10000 with failed party status process pid:3506
[INFO] [2021-06-13 16:40:39,224] [8:139727100782336] - job_utils.py[line:400]: can not found job 202106131640336474715 task 202106131640336474715_reader_0 host 10000 with failed party status process pid:3506
[INFO] [2021-06-13 16:40:39,228] [8:139727100782336] - job_utils.py[line:424]: start run subprocess to stop task session 202106131640336474715_reader_0_0_host_10000
[INFO] [2021-06-13 16:40:39,229] [8:139727100782336] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106131640336474715_reader_0_0_host_10000 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c kill
[INFO] [2021-06-13 16:40:39,237] [8:139727100782336] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106131640336474715_reader_0_0_host_10000 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c kill successfully, pid is 3588
[INFO] [2021-06-13 16:40:39,238] [8:139727100782336] - task_controller.py[line:255]: job 202106131640336474715 task 202106131640336474715_reader_0 0 on host 10000 process 3506 kill success
[INFO] [2021-06-13 16:40:39,238] [8:139727100782336] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0 status
[INFO] [2021-06-13 16:40:39,252] [8:139727100782336] - job_saver.py[line:76]: update job 202106131640336474715 task 202106131640336474715_reader_0 0 status update does not take effect: {'job_id': '202106131640336474715', 'task_id': '202106131640336474715_reader_0', 'task_version': 0, 'role': 'host', 'party_id': '10000', 'party_status': 'failed'}
[INFO] [2021-06-13 16:40:39,260] [8:139727100782336] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0
[WARNING] [2021-06-13 16:40:39,266] [8:139727100782336] - job_saver.py[line:86]: job 202106131640336474715 task 202106131640336474715_reader_0 0 update does not take effect
[INFO] [2021-06-13 16:40:39,278] [8:139727100782336] - job_saver.py[line:45]: try to update job 202106131640336474715 status to failed
[INFO] [2021-06-13 16:40:39,290] [8:139727100782336] - job_saver.py[line:56]: update job 202106131640336474715 status does not take effect
[INFO] [2021-06-13 16:40:39,374] [8:139727100782336] - job_utils.py[line:393]: job 202106131640336474715 task 202106131640336474715_evaluation_0 guest 9999 with waiting party status no process pid
[INFO] [2021-06-13 16:40:39,374] [8:139727100782336] - task_controller.py[line:255]: job 202106131640336474715 task 202106131640336474715_evaluation_0 0 on guest 9999 process None kill success
[INFO] [2021-06-13 16:40:39,375] [8:139727100782336] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_evaluation_0 0 status
[INFO] [2021-06-13 16:40:39,418] [8:139727100782336] - job_saver.py[line:76]: update job 202106131640336474715 task 202106131640336474715_evaluation_0 0 status update does not take effect: {'job_id': '202106131640336474715', 'task_id': '202106131640336474715_evaluation_0', 'task_version': 0, 'role': 'guest', 'party_id': '9999', 'party_status': 'failed'}
[INFO] [2021-06-13 16:40:39,435] [8:139727100782336] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_evaluation_0 0
[WARNING] [2021-06-13 16:40:39,443] [8:139727100782336] - job_saver.py[line:86]: job 202106131640336474715 task 202106131640336474715_evaluation_0 0 update does not take effect
[INFO] [2021-06-13 16:40:39,455] [8:139727100782336] - job_utils.py[line:393]: job 202106131640336474715 task 202106131640336474715_hetero_secureboost_0 guest 9999 with waiting party status no process pid
[INFO] [2021-06-13 16:40:39,455] [8:139727100782336] - task_controller.py[line:255]: job 202106131640336474715 task 202106131640336474715_hetero_secureboost_0 0 on guest 9999 process None kill success
[INFO] [2021-06-13 16:40:39,456] [8:139727100782336] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_hetero_secureboost_0 0 status
[INFO] [2021-06-13 16:40:39,462] [8:139727100782336] - job_saver.py[line:76]: update job 202106131640336474715 task 202106131640336474715_hetero_secureboost_0 0 status update does not take effect: {'job_id': '202106131640336474715', 'task_id': '202106131640336474715_hetero_secureboost_0', 'task_version': 0, 'role': 'guest', 'party_id': '9999', 'party_status': 'failed'}
[INFO] [2021-06-13 16:40:39,477] [8:139727100782336] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_hetero_secureboost_0 0
[WARNING] [2021-06-13 16:40:39,493] [8:139727100782336] - job_saver.py[line:86]: job 202106131640336474715 task 202106131640336474715_hetero_secureboost_0 0 update does not take effect
[INFO] [2021-06-13 16:40:39,507] [8:139727100782336] - job_utils.py[line:393]: job 202106131640336474715 task 202106131640336474715_intersection_0 guest 9999 with waiting party status no process pid
[INFO] [2021-06-13 16:40:39,507] [8:139727100782336] - task_controller.py[line:255]: job 202106131640336474715 task 202106131640336474715_intersection_0 0 on guest 9999 process None kill success
[INFO] [2021-06-13 16:40:39,508] [8:139727100782336] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_intersection_0 0 status
[INFO] [2021-06-13 16:40:39,516] [8:139727100782336] - job_saver.py[line:76]: update job 202106131640336474715 task 202106131640336474715_intersection_0 0 status update does not take effect: {'job_id': '202106131640336474715', 'task_id': '202106131640336474715_intersection_0', 'task_version': 0, 'role': 'guest', 'party_id': '9999', 'party_status': 'failed'}
[INFO] [2021-06-13 16:40:39,524] [8:139727100782336] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_intersection_0 0
[WARNING] [2021-06-13 16:40:39,530] [8:139727100782336] - job_saver.py[line:86]: job 202106131640336474715 task 202106131640336474715_intersection_0 0 update does not take effect
[INFO] [2021-06-13 16:40:39,537] [8:139727100782336] - job_utils.py[line:393]: job 202106131640336474715 task 202106131640336474715_dataio_0 guest 9999 with waiting party status no process pid
[INFO] [2021-06-13 16:40:39,537] [8:139727100782336] - task_controller.py[line:255]: job 202106131640336474715 task 202106131640336474715_dataio_0 0 on guest 9999 process None kill success
[INFO] [2021-06-13 16:40:39,537] [8:139727100782336] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_dataio_0 0 status
[INFO] [2021-06-13 16:40:39,545] [8:139727100782336] - job_saver.py[line:76]: update job 202106131640336474715 task 202106131640336474715_dataio_0 0 status update does not take effect: {'job_id': '202106131640336474715', 'task_id': '202106131640336474715_dataio_0', 'task_version': 0, 'role': 'guest', 'party_id': '9999', 'party_status': 'failed'}
[INFO] [2021-06-13 16:40:39,551] [8:139727100782336] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_dataio_0 0
[WARNING] [2021-06-13 16:40:39,559] [8:139727100782336] - job_saver.py[line:86]: job 202106131640336474715 task 202106131640336474715_dataio_0 0 update does not take effect
[INFO] [2021-06-13 16:40:39,567] [8:139727100782336] - job_utils.py[line:397]: try to stop job 202106131640336474715 task 202106131640336474715_reader_0 guest 9999 with failed party status process pid:3511
[INFO] [2021-06-13 16:40:39,568] [8:139727100782336] - job_utils.py[line:400]: can not found job 202106131640336474715 task 202106131640336474715_reader_0 guest 9999 with failed party status process pid:3511
[INFO] [2021-06-13 16:40:39,574] [8:139727100782336] - job_utils.py[line:424]: start run subprocess to stop task session 202106131640336474715_reader_0_0_guest_9999
[INFO] [2021-06-13 16:40:39,574] [8:139727100782336] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106131640336474715_reader_0_0_guest_9999 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c kill
[INFO] [2021-06-13 16:40:39,582] [8:139727100782336] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106131640336474715_reader_0_0_guest_9999 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c kill successfully, pid is 3597
[INFO] [2021-06-13 16:40:39,583] [8:139727100782336] - task_controller.py[line:255]: job 202106131640336474715 task 202106131640336474715_reader_0 0 on guest 9999 process 3511 kill success
[INFO] [2021-06-13 16:40:39,583] [8:139727100782336] - job_saver.py[line:71]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0 status
[INFO] [2021-06-13 16:40:39,589] [8:139727100782336] - job_saver.py[line:76]: update job 202106131640336474715 task 202106131640336474715_reader_0 0 status update does not take effect: {'job_id': '202106131640336474715', 'task_id': '202106131640336474715_reader_0', 'task_version': 0, 'role': 'guest', 'party_id': '9999', 'party_status': 'failed'}
[INFO] [2021-06-13 16:40:39,603] [8:139727100782336] - job_saver.py[line:81]: try to update job 202106131640336474715 task 202106131640336474715_reader_0 0
[WARNING] [2021-06-13 16:40:39,610] [8:139727100782336] - job_saver.py[line:86]: job 202106131640336474715 task 202106131640336474715_reader_0 0 update does not take effect
[INFO] [2021-06-13 16:40:39,621] [8:139727100782336] - job_saver.py[line:45]: try to update job 202106131640336474715 status to failed
[INFO] [2021-06-13 16:40:39,628] [8:139727100782336] - job_saver.py[line:56]: update job 202106131640336474715 status does not take effect
[INFO] [2021-06-13 16:40:39,634] [8:139726560425728] - federated_scheduler.py[line:92]: stop job 202106131640336474715 success
[INFO] [2021-06-13 16:40:39,634] [8:139726560425728] - dag_scheduler.py[line:448]: stop job 202106131640336474715 with failed successfully
[INFO] [2021-06-13 16:40:39,634] [8:139726560425728] - federated_scheduler.py[line:107]: try to clean job 202106131640336474715
[INFO] [2021-06-13 16:40:39,639] [8:139727100782336] - job_controller.py[line:379]: Job 202106131640336474715 on host 10000 start to clean
[INFO] [2021-06-13 16:40:39,639] [8:139727100782336] - job_controller.py[line:382]: job 202106131640336474715 on host 10000 clean done
[INFO] [2021-06-13 16:40:39,649] [8:139727100782336] - job_controller.py[line:379]: Job 202106131640336474715 on guest 9999 start to clean
[INFO] [2021-06-13 16:40:39,650] [8:139727100782336] - job_controller.py[line:382]: job 202106131640336474715 on guest 9999 clean done
[INFO] [2021-06-13 16:40:39,655] [8:139726560425728] - federated_scheduler.py[line:110]: clean job 202106131640336474715 success
[INFO] [2021-06-13 16:40:39,655] [8:139726560425728] - dag_scheduler.py[line:505]: Job 202106131640336474715 finished with failed, done
[INFO] [2021-06-13 16:40:39,655] [8:139726560425728] - dag_scheduler.py[line:325]: finish scheduling job 202106131640336474715
[INFO] [2021-06-13 16:40:39,722] [3573:139981043021632] - session_utils.py[line:38]: start kill session 202106131640336474715_reader_0_0_host_10000
[INFO] [2021-06-13 16:40:39,723] [3573:139981043021632] - session_utils.py[line:47]: kill session 202106131640336474715_reader_0_0_host_10000 success
[INFO] [2021-06-13 16:40:39,939] [3575:140367619131200] - session_utils.py[line:38]: start kill session 202106131640336474715_reader_0_0_guest_9999
[INFO] [2021-06-13 16:40:39,939] [3575:140367619131200] - session_utils.py[line:47]: kill session 202106131640336474715_reader_0_0_guest_9999 success
[INFO] [2021-06-13 16:40:40,207] [3588:139970617657152] - session_utils.py[line:38]: start kill session 202106131640336474715_reader_0_0_host_10000
[INFO] [2021-06-13 16:40:40,207] [3588:139970617657152] - session_utils.py[line:47]: kill session 202106131640336474715_reader_0_0_host_10000 success
[INFO] [2021-06-13 16:40:40,393] [3597:140008827352896] - session_utils.py[line:38]: start kill session 202106131640336474715_reader_0_0_guest_9999
[INFO] [2021-06-13 16:40:40,394] [3597:140008827352896] - session_utils.py[line:47]: kill session 202106131640336474715_reader_0_0_guest_9999 success
[INFO] [2021-06-13 16:40:41,706] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:40:43,769] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:40:45,828] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:40:47,884] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:40:49,943] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:40:51,981] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:40:54,064] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:40:56,107] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:40:58,198] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:41:00,270] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:41:02,325] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:41:04,377] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:41:06,430] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:41:08,476] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:41:10,525] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:41:12,576] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:41:14,633] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:41:17,356] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:41:19,578] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:41:21,773] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:41:25,646] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:41:28,328] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:41:30,406] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:41:32,448] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:41:34,506] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:41:36,565] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:41:38,615] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:41:40,672] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:41:42,726] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:41:44,773] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:41:46,854] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:41:48,922] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:41:50,980] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:41:53,035] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:41:55,086] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:41:57,140] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:41:59,193] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:42:01,266] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:42:03,319] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:42:05,384] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:42:07,448] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:42:09,511] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:42:11,567] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:42:13,620] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:42:15,701] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:42:17,763] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:42:19,859] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:42:21,927] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:42:23,968] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:42:26,021] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:42:28,075] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:42:30,123] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:42:32,183] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:42:34,239] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:42:36,303] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:42:38,357] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:42:40,409] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:42:42,466] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:42:44,521] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:42:46,600] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:42:48,659] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:42:50,726] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:42:52,761] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:42:54,812] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:42:56,874] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:42:59,580] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:43:01,626] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:43:03,681] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:43:05,762] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:43:07,831] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:43:09,877] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:43:11,919] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:43:13,974] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:43:16,028] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:43:18,082] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:43:20,135] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:43:22,188] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:43:24,250] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:43:26,302] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:43:28,370] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:43:30,434] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:43:32,491] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:43:34,562] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:43:36,622] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:43:38,723] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:43:40,795] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:43:42,872] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:43:44,932] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:43:46,985] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:43:49,060] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:43:51,110] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:43:53,162] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:43:55,217] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:43:57,270] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:43:59,326] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:44:01,390] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:44:03,444] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:44:05,496] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:44:07,547] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:44:09,578] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:44:11,604] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:44:13,665] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:44:15,718] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:44:17,771] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:44:19,826] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:44:22,017] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:44:24,071] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:44:26,124] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:44:28,184] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:44:30,240] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:44:32,274] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:44:34,326] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:44:36,382] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:44:38,418] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:44:40,476] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:44:42,530] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:44:44,582] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:44:46,635] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:44:48,687] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:44:50,740] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:44:52,798] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:44:54,832] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:44:56,878] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:44:58,932] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:45:00,987] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:45:03,029] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:45:05,077] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:45:07,128] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:45:09,187] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:45:11,241] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:45:13,293] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:45:15,354] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:45:17,403] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:45:19,473] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:45:21,523] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:45:23,569] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:45:25,618] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:45:27,666] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:45:29,720] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:45:31,770] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:45:33,826] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:45:35,883] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 16:45:37,930] [8:139726560425728] - dag_scheduler.py[line:193]: the number of updates has been exceeded
