[INFO] [2021-06-15 21:41:09,694] [7:140197278750464] - dag_scheduler.py[line:40]: submit job, job_id 2021061521410943464816, body {'job_dsl': {'components': {'upload_0': {'module': 'Upload'}}}, 'job_runtime_conf': {'initiator': {'role': 'local', 'party_id': 0}, 'job_parameters': {'common': {'backend': 0, 'work_mode': 0}}, 'role': {'local': [0]}, 'component_parameters': {'role': {'local': {'0': {'upload_0': {'partition': 16, 'file': '/fate/jobs/2021061521410943464816/fate_upload_tmp/default_credit_hetero_guest.csv', 'namespace': 'experiment', 'head': 1, 'name': 'default_credit_hetero_guest', 'destroy': True}}}}}, 'dsl_version': 2}}
[INFO] [2021-06-15 21:41:09,713] [7:140196691556096] - job_controller.py[line:52]: job parameters:{'job_type': 'train', 'work_mode': 0, 'backend': 0, 'computing_engine': 'STANDALONE', 'federation_engine': 'STANDALONE', 'storage_engine': 'STANDALONE', 'engines_address': {}, 'federated_mode': 'SINGLE', 'task_parallelism': 1, 'computing_partitions': 4, 'federated_status_collect_type': 'PULL', 'model_id': 'local-0#model', 'model_version': '2021061521410943464816', 'eggroll_run': {}, 'spark_run': {}, 'rabbitmq_run': {}, 'pulsar_run': {}, 'adaptation_parameters': {'task_nodes': 1, 'task_cores_per_node': 4, 'task_memory_per_node': 0, 'request_task_cores': 4, 'if_initiator_baseline': True}}
[INFO] [2021-06-15 21:41:09,777] [7:140197278750464] - dag_scheduler.py[line:122]: submit job successfully, job id is 2021061521410943464816, model id is local-0#model
[INFO] [2021-06-15 21:41:11,382] [7:140197562341120] - federated_scheduler.py[line:39]: try to apply job 2021061521410943464816 resource
[INFO] [2021-06-15 21:41:11,415] [7:140197278750464] - resource_manager.py[line:176]: apply job 2021061521410943464816 resource(cores 4 memory 0) on local 0 successfully, remaining cores: 16 remaining memory: 0
[INFO] [2021-06-15 21:41:11,420] [7:140197562341120] - federated_scheduler.py[line:42]: apply job 2021061521410943464816 resource successfully
[INFO] [2021-06-15 21:41:11,420] [7:140197562341120] - dag_scheduler.py[line:279]: try to start job 2021061521410943464816 on initiator local 0
[INFO] [2021-06-15 21:41:11,440] [7:140197278750464] - job_controller.py[line:261]: try to start job 2021061521410943464816 on local 0
[INFO] [2021-06-15 21:41:11,440] [7:140197278750464] - job_saver.py[line:45]: try to update job 2021061521410943464816 status to running
[INFO] [2021-06-15 21:41:11,461] [7:140197278750464] - job_saver.py[line:48]: update job 2021061521410943464816 status successfully
[INFO] [2021-06-15 21:41:11,462] [7:140197278750464] - job_saver.py[line:61]: try to update job 2021061521410943464816
[INFO] [2021-06-15 21:41:11,481] [7:140197278750464] - job_saver.py[line:64]: job 2021061521410943464816 update successfully: {'job_id': '2021061521410943464816', 'role': 'local', 'party_id': 0, 'status': 'running', 'start_time': 1623793271440}
[INFO] [2021-06-15 21:41:11,482] [7:140197278750464] - job_controller.py[line:275]: start job 2021061521410943464816 on local 0 successfully
[INFO] [2021-06-15 21:41:11,486] [7:140197562341120] - dag_scheduler.py[line:292]: start job 2021061521410943464816 on initiator local 0
[INFO] [2021-06-15 21:41:11,500] [7:140197562341120] - dag_scheduler.py[line:247]: reset job 2021061521410943464816 ready signal True
[INFO] [2021-06-15 21:41:11,512] [7:140197562341120] - dag_scheduler.py[line:298]: scheduling job 2021061521410943464816
[INFO] [2021-06-15 21:41:11,514] [7:140197562341120] - task_scheduler.py[line:28]: scheduling job 2021061521410943464816 tasks
[INFO] [2021-06-15 21:41:11,536] [7:140197562341120] - task_scheduler.py[line:143]: job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status is waiting, calculate by task party status list: ['waiting']
[INFO] [2021-06-15 21:41:11,536] [7:140197562341120] - task_scheduler.py[line:80]: try to start job 2021061521410943464816 task 2021061521410943464816_upload_0 0 on local 0
[INFO] [2021-06-15 21:41:11,556] [7:140197562341120] - resource_manager.py[line:286]: task 2021061521410943464816_upload_0 0 apply resource successfully
[INFO] [2021-06-15 21:41:11,557] [7:140197562341120] - job_saver.py[line:71]: try to update job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status
[INFO] [2021-06-15 21:41:11,577] [7:140197562341120] - job_saver.py[line:74]: update job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status successfully: {'job_id': '2021061521410943464816', 'task_id': '2021061521410943464816_upload_0', 'task_version': 0, 'role': 'local', 'party_id': '0', 'status': 'running'}
[INFO] [2021-06-15 21:41:11,577] [7:140197562341120] - task_scheduler.py[line:93]: start job 2021061521410943464816 task 2021061521410943464816_upload_0 0 on local 0
[INFO] [2021-06-15 21:41:11,577] [7:140197562341120] - federated_scheduler.py[line:192]: job 2021061521410943464816 task 2021061521410943464816_upload_0 0 is running, sync to all party
[INFO] [2021-06-15 21:41:11,585] [7:140197278750464] - job_saver.py[line:71]: try to update job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status
[INFO] [2021-06-15 21:41:11,594] [7:140197278750464] - job_saver.py[line:76]: update job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status update does not take effect: {'job_id': '2021061521410943464816', 'task_id': '2021061521410943464816_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'status': 'running'}
[WARNING] [2021-06-15 21:41:11,605] [7:140197562341120] - federated_scheduler.py[line:260]: an error occurred while status/running the task to role local party 0: 
update task status failed
[INFO] [2021-06-15 21:41:11,606] [7:140197562341120] - federated_scheduler.py[line:197]: sync job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status running to all party failed: 
{'local': {0: {'retcode': 103, 'retmsg': 'update task status failed'}}}
[INFO] [2021-06-15 21:41:11,618] [7:140197278750464] - task_controller.py[line:71]: try to start job 2021061521410943464816 task 2021061521410943464816_upload_0 0 on local 0 executor subprocess
[INFO] [2021-06-15 21:41:11,624] [7:140197278750464] - task_controller.py[line:90]: use computing engine STANDALONE
[INFO] [2021-06-15 21:41:11,624] [7:140197278750464] - task_controller.py[line:145]: job 2021061521410943464816 task 2021061521410943464816_upload_0 0 on local 0 executor subprocess is ready
[INFO] [2021-06-15 21:41:11,624] [7:140197278750464] - job_utils.py[line:310]: start process command: /usr/local/bin/python /fate/python/fate_flow/operation/task_executor.py -j 2021061521410943464816 -n upload_0 -t 2021061521410943464816_upload_0 -v 0 -r local -p 0 -c /fate/jobs/2021061521410943464816/local/0/upload_0/2021061521410943464816_upload_0/0/task_parameters.json --run_ip 127.0.0.1 --job_server 127.0.0.1:9380
[INFO] [2021-06-15 21:41:11,634] [7:140197278750464] - job_utils.py[line:334]: start process command: /usr/local/bin/python /fate/python/fate_flow/operation/task_executor.py -j 2021061521410943464816 -n upload_0 -t 2021061521410943464816_upload_0 -v 0 -r local -p 0 -c /fate/jobs/2021061521410943464816/local/0/upload_0/2021061521410943464816_upload_0/0/task_parameters.json --run_ip 127.0.0.1 --job_server 127.0.0.1:9380 successfully, pid is 2864
[INFO] [2021-06-15 21:41:11,635] [7:140197278750464] - job_saver.py[line:81]: try to update job 2021061521410943464816 task 2021061521410943464816_upload_0 0
[INFO] [2021-06-15 21:41:11,658] [7:140197278750464] - job_saver.py[line:84]: job 2021061521410943464816 task 2021061521410943464816_upload_0 0 update successfully
[INFO] [2021-06-15 21:41:11,666] [7:140197278750464] - job_saver.py[line:71]: try to update job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status
[INFO] [2021-06-15 21:41:11,687] [7:140197278750464] - job_saver.py[line:74]: update job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status successfully: {'job_id': '2021061521410943464816', 'task_id': '2021061521410943464816_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'party_status': 'running', 'start_time': 1623793271635}
[INFO] [2021-06-15 21:41:11,694] [7:140197278750464] - task_controller.py[line:164]: job 2021061521410943464816 task 2021061521410943464816_upload_0 0 on local 0 executor subprocess start success
[INFO] [2021-06-15 21:41:11,701] [7:140197562341120] - task_scheduler.py[line:75]: finish scheduling job 2021061521410943464816 tasks
[INFO] [2021-06-15 21:41:11,701] [7:140197562341120] - dag_scheduler.py[line:310]: Job 2021061521410943464816 status is running, calculate by task status list: ['running']
[INFO] [2021-06-15 21:41:11,701] [7:140197562341120] - dag_scheduler.py[line:325]: finish scheduling job 2021061521410943464816
[INFO] [2021-06-15 21:41:13,377] [2864:140640813619008] - task_executor.py[line:56]: enter task process
[INFO] [2021-06-15 21:41:13,378] [2864:140640813619008] - task_executor.py[line:57]: Namespace(component_name='upload_0', config='/fate/jobs/2021061521410943464816/local/0/upload_0/2021061521410943464816_upload_0/0/task_parameters.json', job_id='2021061521410943464816', job_server='127.0.0.1:9380', party_id=0, role='local', run_ip='127.0.0.1', task_id='2021061521410943464816_upload_0', task_version=0)
[INFO] [2021-06-15 21:41:13,395] [7:140197278750464] - job_saver.py[line:81]: try to update job 2021061521410943464816 task 2021061521410943464816_upload_0 0
[INFO] [2021-06-15 21:41:13,417] [7:140197278750464] - job_saver.py[line:84]: job 2021061521410943464816 task 2021061521410943464816_upload_0 0 update successfully
[INFO] [2021-06-15 21:41:13,429] [7:140197278750464] - job_saver.py[line:71]: try to update job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status
[INFO] [2021-06-15 21:41:13,438] [7:140197278750464] - job_saver.py[line:76]: update job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status update does not take effect: {'job_id': '2021061521410943464816', 'component_name': 'upload_0', 'task_id': '2021061521410943464816_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'run_ip': '127.0.0.1', 'run_pid': 2864, 'party_status': 'running'}
[INFO] [2021-06-15 21:41:13,733] [7:140197562341120] - dag_scheduler.py[line:298]: scheduling job 2021061521410943464816
[INFO] [2021-06-15 21:41:13,735] [7:140197562341120] - task_scheduler.py[line:28]: scheduling job 2021061521410943464816 tasks
[INFO] [2021-06-15 21:41:13,756] [7:140197562341120] - job_saver.py[line:71]: try to update job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status
[INFO] [2021-06-15 21:41:13,762] [7:140197562341120] - job_saver.py[line:76]: update job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status update does not take effect: {'elapsed': None, 'end_time': None, 'job_id': '2021061521410943464816', 'party_id': '0', 'party_status': 'running', 'role': 'local', 'start_time': 1623793271635, 'status': 'running', 'task_id': '2021061521410943464816_upload_0', 'task_version': 0, 'update_time': 1623793269729}
[INFO] [2021-06-15 21:41:13,762] [7:140197562341120] - job_saver.py[line:81]: try to update job 2021061521410943464816 task 2021061521410943464816_upload_0 0
[INFO] [2021-06-15 21:41:13,786] [7:140197562341120] - job_saver.py[line:84]: job 2021061521410943464816 task 2021061521410943464816_upload_0 0 update successfully
[INFO] [2021-06-15 21:41:13,791] [7:140197562341120] - task_scheduler.py[line:143]: job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status is running, calculate by task party status list: ['running']
[INFO] [2021-06-15 21:41:13,792] [7:140197562341120] - task_scheduler.py[line:75]: finish scheduling job 2021061521410943464816 tasks
[INFO] [2021-06-15 21:41:13,792] [7:140197562341120] - dag_scheduler.py[line:310]: Job 2021061521410943464816 status is running, calculate by task status list: ['running']
[INFO] [2021-06-15 21:41:13,792] [7:140197562341120] - dag_scheduler.py[line:325]: finish scheduling job 2021061521410943464816
[INFO] [2021-06-15 21:41:14,296] [7:140197278750464] - job_saver.py[line:61]: try to update job 2021061521410943464816
[INFO] [2021-06-15 21:41:14,316] [7:140197278750464] - job_saver.py[line:64]: job 2021061521410943464816 update successfully: {'progress': 100.0, 'job_id': '2021061521410943464816', 'role': 'local', 'party_id': '0'}
[INFO] [2021-06-15 21:41:15,034] [7:140197278750464] - job_tracker.py[line:74]: save job 2021061521410943464816 component upload_0 on local 0 upload data_access metric data
[INFO] [2021-06-15 21:41:15,062] [7:140197278750464] - job_tracker.py[line:97]: save job 2021061521410943464816 component upload_0 on local 0 upload data_access metric meta
[INFO] [2021-06-15 21:41:15,117] [2864:140640813619008] - job_tracker.py[line:159]: task id 2021061521410943464816_upload_0 output data table is none
[INFO] [2021-06-15 21:41:15,122] [7:140197278750464] - job_saver.py[line:81]: try to update job 2021061521410943464816 task 2021061521410943464816_upload_0 0
[INFO] [2021-06-15 21:41:15,137] [7:140197278750464] - job_saver.py[line:84]: job 2021061521410943464816 task 2021061521410943464816_upload_0 0 update successfully
[INFO] [2021-06-15 21:41:15,143] [7:140197278750464] - job_saver.py[line:71]: try to update job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status
[INFO] [2021-06-15 21:41:15,158] [7:140197278750464] - job_saver.py[line:74]: update job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status successfully: {'job_id': '2021061521410943464816', 'component_name': 'upload_0', 'task_id': '2021061521410943464816_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'run_ip': '127.0.0.1', 'run_pid': 2864, 'party_status': 'success', 'end_time': 1623793275117, 'elapsed': 1739}
[INFO] [2021-06-15 21:41:15,177] [7:140197278750464] - job_saver.py[line:81]: try to update job 2021061521410943464816 task 2021061521410943464816_upload_0 0
[INFO] [2021-06-15 21:41:15,196] [7:140197278750464] - job_saver.py[line:84]: job 2021061521410943464816 task 2021061521410943464816_upload_0 0 update successfully
[INFO] [2021-06-15 21:41:15,204] [7:140197278750464] - job_saver.py[line:71]: try to update job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status
[INFO] [2021-06-15 21:41:15,211] [7:140197278750464] - job_saver.py[line:76]: update job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status update does not take effect: {'job_id': '2021061521410943464816', 'component_name': 'upload_0', 'task_id': '2021061521410943464816_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'run_ip': '127.0.0.1', 'run_pid': 2864, 'party_status': 'success', 'end_time': 1623793275117, 'elapsed': 1739}
[INFO] [2021-06-15 21:41:15,847] [7:140197562341120] - dag_scheduler.py[line:298]: scheduling job 2021061521410943464816
[INFO] [2021-06-15 21:41:15,849] [7:140197562341120] - task_scheduler.py[line:28]: scheduling job 2021061521410943464816 tasks
[INFO] [2021-06-15 21:41:15,887] [7:140197562341120] - job_saver.py[line:71]: try to update job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status
[INFO] [2021-06-15 21:41:15,899] [7:140197562341120] - job_saver.py[line:76]: update job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status update does not take effect: {'elapsed': 1739, 'end_time': 1623793275117, 'job_id': '2021061521410943464816', 'party_id': '0', 'party_status': 'success', 'role': 'local', 'start_time': 1623793271635, 'status': 'running', 'task_id': '2021061521410943464816_upload_0', 'task_version': 0, 'update_time': 1623793269729}
[INFO] [2021-06-15 21:41:15,899] [7:140197562341120] - job_saver.py[line:81]: try to update job 2021061521410943464816 task 2021061521410943464816_upload_0 0
[INFO] [2021-06-15 21:41:15,928] [7:140197562341120] - job_saver.py[line:84]: job 2021061521410943464816 task 2021061521410943464816_upload_0 0 update successfully
[INFO] [2021-06-15 21:41:15,936] [7:140197562341120] - task_scheduler.py[line:143]: job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status is success, calculate by task party status list: ['success']
[INFO] [2021-06-15 21:41:15,936] [7:140197562341120] - federated_scheduler.py[line:192]: job 2021061521410943464816 task 2021061521410943464816_upload_0 0 is success, sync to all party
[INFO] [2021-06-15 21:41:15,943] [7:140197278750464] - job_saver.py[line:71]: try to update job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status
[INFO] [2021-06-15 21:41:15,962] [7:140197278750464] - job_saver.py[line:74]: update job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status successfully: {'job_id': '2021061521410943464816', 'task_id': '2021061521410943464816_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'status': 'success'}
[INFO] [2021-06-15 21:41:15,974] [7:140197278750464] - resource_manager.py[line:286]: task 2021061521410943464816_upload_0 0 return resource successfully
[INFO] [2021-06-15 21:41:15,980] [7:140197278750464] - job_tracker.py[line:424]: clean task 2021061521410943464816_upload_0 0 on local 0
[ERROR] [2021-06-15 21:41:15,982] [7:140197278750464] - job_tracker.py[line:475]: namespace dir /fate/data/2021061521410943464816_upload_0_0_local_0 does not exist
Traceback (most recent call last):
  File "/fate/python/fate_flow/operation/job_tracker.py", line 437, in clean_task
    sess.computing.cleanup(namespace=computing_temp_namespace, name="*")
  File "/fate/python/fate_arch/computing/standalone/_csession.py", line 73, in cleanup
    return self._session.cleanup(name=name, namespace=namespace)
  File "/fate/python/fate_arch/_standalone.py", line 383, in cleanup
    raise EnvironmentError(f"namespace dir {namespace_dir} does not exist")
OSError: namespace dir /fate/data/2021061521410943464816_upload_0_0_local_0 does not exist
[INFO] [2021-06-15 21:41:15,994] [7:140197562341120] - federated_scheduler.py[line:195]: sync job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status success to all party success
[INFO] [2021-06-15 21:41:15,994] [7:140197562341120] - federated_scheduler.py[line:202]: try to stop job 2021061521410943464816 task 2021061521410943464816_upload_0 0
[INFO] [2021-06-15 21:41:16,006] [7:140197278750464] - job_utils.py[line:397]: try to stop job 2021061521410943464816 task 2021061521410943464816_upload_0 local 0 with success party status process pid:2864
[INFO] [2021-06-15 21:41:16,006] [7:140197278750464] - job_utils.py[line:400]: can not found job 2021061521410943464816 task 2021061521410943464816_upload_0 local 0 with success party status process pid:2864
[INFO] [2021-06-15 21:41:16,009] [7:140197278750464] - job_utils.py[line:424]: start run subprocess to stop task session 2021061521410943464816_upload_0_0_local_0
[INFO] [2021-06-15 21:41:16,009] [7:140197278750464] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061521410943464816_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop
[INFO] [2021-06-15 21:41:16,017] [7:140197278750464] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061521410943464816_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop successfully, pid is 2884
[INFO] [2021-06-15 21:41:16,018] [7:140197278750464] - task_controller.py[line:255]: job 2021061521410943464816 task 2021061521410943464816_upload_0 0 on local 0 process 2864 kill success
[INFO] [2021-06-15 21:41:16,018] [7:140197278750464] - job_saver.py[line:71]: try to update job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status
[INFO] [2021-06-15 21:41:16,029] [7:140197278750464] - job_saver.py[line:76]: update job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status update does not take effect: {'job_id': '2021061521410943464816', 'task_id': '2021061521410943464816_upload_0', 'task_version': 0, 'role': 'local', 'party_id': '0', 'party_status': 'success'}
[INFO] [2021-06-15 21:41:16,035] [7:140197278750464] - job_saver.py[line:81]: try to update job 2021061521410943464816 task 2021061521410943464816_upload_0 0
[WARNING] [2021-06-15 21:41:16,042] [7:140197278750464] - job_saver.py[line:86]: job 2021061521410943464816 task 2021061521410943464816_upload_0 0 update does not take effect
[INFO] [2021-06-15 21:41:16,053] [7:140197562341120] - federated_scheduler.py[line:206]: stop job 2021061521410943464816 task 2021061521410943464816_upload_0 0 success
[INFO] [2021-06-15 21:41:16,054] [7:140197562341120] - task_scheduler.py[line:75]: finish scheduling job 2021061521410943464816 tasks
[INFO] [2021-06-15 21:41:16,054] [7:140197562341120] - dag_scheduler.py[line:310]: Job 2021061521410943464816 status is success, calculate by task status list: ['success']
[INFO] [2021-06-15 21:41:16,054] [7:140197562341120] - federated_scheduler.py[line:78]: try to save job 2021061521410943464816 pipelined model
[INFO] [2021-06-15 21:41:16,059] [7:140197278750464] - job_controller.py[line:331]: job 2021061521410943464816 on local 0 start to save pipeline
[INFO] [2021-06-15 21:41:16,076] [7:140197278750464] - job_controller.py[line:374]: job 2021061521410943464816 on local 0 save pipeline successfully
[INFO] [2021-06-15 21:41:16,081] [7:140197562341120] - federated_scheduler.py[line:81]: save job 2021061521410943464816 pipelined model success
[INFO] [2021-06-15 21:41:16,081] [7:140197562341120] - federated_scheduler.py[line:68]: job 2021061521410943464816 is success, sync to all party
[INFO] [2021-06-15 21:41:16,087] [7:140197278750464] - job_saver.py[line:45]: try to update job 2021061521410943464816 status to success
[INFO] [2021-06-15 21:41:16,102] [7:140197278750464] - job_saver.py[line:48]: update job 2021061521410943464816 status successfully
[INFO] [2021-06-15 21:41:16,133] [7:140197278750464] - resource_manager.py[line:176]: return job 2021061521410943464816 resource(cores 4 memory 0) on local 0 successfully, remaining cores: 20 remaining memory: 0
[INFO] [2021-06-15 21:41:16,136] [7:140197562341120] - federated_scheduler.py[line:71]: sync job 2021061521410943464816 status success to all party success
[INFO] [2021-06-15 21:41:16,143] [7:140197562341120] - job_saver.py[line:45]: try to update job 2021061521410943464816 status to success
[INFO] [2021-06-15 21:41:16,149] [7:140197562341120] - job_saver.py[line:56]: update job 2021061521410943464816 status does not take effect
[INFO] [2021-06-15 21:41:16,150] [7:140197562341120] - job_saver.py[line:61]: try to update job 2021061521410943464816
[WARNING] [2021-06-15 21:41:16,156] [7:140197562341120] - job_saver.py[line:66]: job 2021061521410943464816 update does not take effect: {'job_id': '2021061521410943464816', 'role': 'local', 'party_id': '0', 'status': 'success'}
[INFO] [2021-06-15 21:41:16,156] [7:140197562341120] - dag_scheduler.py[line:502]: Job 2021061521410943464816 finished with success, do something...
[INFO] [2021-06-15 21:41:16,156] [7:140197562341120] - dag_scheduler.py[line:436]: request stop job 2021061521410943464816 with success
[INFO] [2021-06-15 21:41:16,166] [7:140197562341120] - dag_scheduler.py[line:445]: request stop job 2021061521410943464816 with success to all party
[INFO] [2021-06-15 21:41:16,166] [7:140197562341120] - federated_scheduler.py[line:88]: try to stop job 2021061521410943464816
[INFO] [2021-06-15 21:41:16,180] [7:140197278750464] - job_utils.py[line:397]: try to stop job 2021061521410943464816 task 2021061521410943464816_upload_0 local 0 with success party status process pid:2864
[INFO] [2021-06-15 21:41:16,180] [7:140197278750464] - job_utils.py[line:400]: can not found job 2021061521410943464816 task 2021061521410943464816_upload_0 local 0 with success party status process pid:2864
[INFO] [2021-06-15 21:41:16,183] [7:140197278750464] - job_utils.py[line:424]: start run subprocess to stop task session 2021061521410943464816_upload_0_0_local_0
[INFO] [2021-06-15 21:41:16,183] [7:140197278750464] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061521410943464816_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop
[INFO] [2021-06-15 21:41:16,191] [7:140197278750464] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061521410943464816_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop successfully, pid is 2888
[INFO] [2021-06-15 21:41:16,191] [7:140197278750464] - task_controller.py[line:255]: job 2021061521410943464816 task 2021061521410943464816_upload_0 0 on local 0 process 2864 kill success
[INFO] [2021-06-15 21:41:16,191] [7:140197278750464] - job_saver.py[line:71]: try to update job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status
[INFO] [2021-06-15 21:41:16,197] [7:140197278750464] - job_saver.py[line:76]: update job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status update does not take effect: {'job_id': '2021061521410943464816', 'task_id': '2021061521410943464816_upload_0', 'task_version': 0, 'role': 'local', 'party_id': '0', 'party_status': 'success'}
[INFO] [2021-06-15 21:41:16,202] [7:140197278750464] - job_saver.py[line:81]: try to update job 2021061521410943464816 task 2021061521410943464816_upload_0 0
[WARNING] [2021-06-15 21:41:16,208] [7:140197278750464] - job_saver.py[line:86]: job 2021061521410943464816 task 2021061521410943464816_upload_0 0 update does not take effect
[INFO] [2021-06-15 21:41:16,216] [7:140197278750464] - job_saver.py[line:45]: try to update job 2021061521410943464816 status to success
[INFO] [2021-06-15 21:41:16,225] [7:140197278750464] - job_saver.py[line:56]: update job 2021061521410943464816 status does not take effect
[INFO] [2021-06-15 21:41:16,232] [7:140197562341120] - federated_scheduler.py[line:92]: stop job 2021061521410943464816 success
[INFO] [2021-06-15 21:41:16,233] [7:140197562341120] - dag_scheduler.py[line:448]: stop job 2021061521410943464816 with success successfully
[INFO] [2021-06-15 21:41:16,233] [7:140197562341120] - federated_scheduler.py[line:107]: try to clean job 2021061521410943464816
[INFO] [2021-06-15 21:41:16,238] [7:140197278750464] - job_controller.py[line:379]: Job 2021061521410943464816 on local 0 start to clean
[INFO] [2021-06-15 21:41:16,239] [7:140197278750464] - job_controller.py[line:382]: job 2021061521410943464816 on local 0 clean done
[INFO] [2021-06-15 21:41:16,245] [7:140197562341120] - federated_scheduler.py[line:110]: clean job 2021061521410943464816 success
[INFO] [2021-06-15 21:41:16,245] [7:140197562341120] - dag_scheduler.py[line:505]: Job 2021061521410943464816 finished with success, done
[INFO] [2021-06-15 21:41:16,245] [7:140197562341120] - dag_scheduler.py[line:325]: finish scheduling job 2021061521410943464816
[INFO] [2021-06-15 21:41:16,284] [7:140197562341120] - dag_scheduler.py[line:298]: scheduling job 2021061521410943464816
[INFO] [2021-06-15 21:41:16,286] [7:140197562341120] - task_scheduler.py[line:28]: scheduling job 2021061521410943464816 tasks
[INFO] [2021-06-15 21:41:16,301] [7:140197562341120] - task_scheduler.py[line:143]: job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status is success, calculate by task party status list: ['success']
[INFO] [2021-06-15 21:41:16,301] [7:140197562341120] - task_scheduler.py[line:75]: finish scheduling job 2021061521410943464816 tasks
[INFO] [2021-06-15 21:41:16,301] [7:140197562341120] - dag_scheduler.py[line:310]: Job 2021061521410943464816 status is success, calculate by task status list: ['success']
[INFO] [2021-06-15 21:41:16,301] [7:140197562341120] - dag_scheduler.py[line:502]: Job 2021061521410943464816 finished with success, do something...
[INFO] [2021-06-15 21:41:16,302] [7:140197562341120] - dag_scheduler.py[line:436]: request stop job 2021061521410943464816 with success
[INFO] [2021-06-15 21:41:16,308] [7:140197562341120] - dag_scheduler.py[line:445]: request stop job 2021061521410943464816 with success to all party
[INFO] [2021-06-15 21:41:16,308] [7:140197562341120] - federated_scheduler.py[line:88]: try to stop job 2021061521410943464816
[INFO] [2021-06-15 21:41:16,325] [7:140197278750464] - job_utils.py[line:397]: try to stop job 2021061521410943464816 task 2021061521410943464816_upload_0 local 0 with success party status process pid:2864
[INFO] [2021-06-15 21:41:16,326] [7:140197278750464] - job_utils.py[line:400]: can not found job 2021061521410943464816 task 2021061521410943464816_upload_0 local 0 with success party status process pid:2864
[INFO] [2021-06-15 21:41:16,330] [7:140197278750464] - job_utils.py[line:424]: start run subprocess to stop task session 2021061521410943464816_upload_0_0_local_0
[INFO] [2021-06-15 21:41:16,330] [7:140197278750464] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061521410943464816_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop
[INFO] [2021-06-15 21:41:16,338] [7:140197278750464] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061521410943464816_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop successfully, pid is 2899
[INFO] [2021-06-15 21:41:16,339] [7:140197278750464] - task_controller.py[line:255]: job 2021061521410943464816 task 2021061521410943464816_upload_0 0 on local 0 process 2864 kill success
[INFO] [2021-06-15 21:41:16,339] [7:140197278750464] - job_saver.py[line:71]: try to update job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status
[INFO] [2021-06-15 21:41:16,346] [7:140197278750464] - job_saver.py[line:76]: update job 2021061521410943464816 task 2021061521410943464816_upload_0 0 status update does not take effect: {'job_id': '2021061521410943464816', 'task_id': '2021061521410943464816_upload_0', 'task_version': 0, 'role': 'local', 'party_id': '0', 'party_status': 'success'}
[INFO] [2021-06-15 21:41:16,353] [7:140197278750464] - job_saver.py[line:81]: try to update job 2021061521410943464816 task 2021061521410943464816_upload_0 0
[WARNING] [2021-06-15 21:41:16,361] [7:140197278750464] - job_saver.py[line:86]: job 2021061521410943464816 task 2021061521410943464816_upload_0 0 update does not take effect
[INFO] [2021-06-15 21:41:16,371] [7:140197278750464] - job_saver.py[line:45]: try to update job 2021061521410943464816 status to success
[INFO] [2021-06-15 21:41:16,377] [7:140197278750464] - job_saver.py[line:56]: update job 2021061521410943464816 status does not take effect
[INFO] [2021-06-15 21:41:16,383] [7:140197562341120] - federated_scheduler.py[line:92]: stop job 2021061521410943464816 success
[INFO] [2021-06-15 21:41:16,383] [7:140197562341120] - dag_scheduler.py[line:448]: stop job 2021061521410943464816 with success successfully
[INFO] [2021-06-15 21:41:16,383] [7:140197562341120] - federated_scheduler.py[line:107]: try to clean job 2021061521410943464816
[INFO] [2021-06-15 21:41:16,393] [7:140196691556096] - job_controller.py[line:379]: Job 2021061521410943464816 on local 0 start to clean
[INFO] [2021-06-15 21:41:16,395] [7:140196691556096] - job_controller.py[line:382]: job 2021061521410943464816 on local 0 clean done
[INFO] [2021-06-15 21:41:16,398] [7:140197562341120] - federated_scheduler.py[line:110]: clean job 2021061521410943464816 success
[INFO] [2021-06-15 21:41:16,398] [7:140197562341120] - dag_scheduler.py[line:505]: Job 2021061521410943464816 finished with success, done
[INFO] [2021-06-15 21:41:16,398] [7:140197562341120] - dag_scheduler.py[line:325]: finish scheduling job 2021061521410943464816
[INFO] [2021-06-15 21:41:16,731] [2884:140395012302656] - session_utils.py[line:38]: start stop session 2021061521410943464816_upload_0_0_local_0
[INFO] [2021-06-15 21:41:16,732] [2884:140395012302656] - session_utils.py[line:47]: stop session 2021061521410943464816_upload_0_0_local_0 success
[INFO] [2021-06-15 21:41:16,929] [2888:139755585390400] - session_utils.py[line:38]: start stop session 2021061521410943464816_upload_0_0_local_0
[INFO] [2021-06-15 21:41:16,929] [2888:139755585390400] - session_utils.py[line:47]: stop session 2021061521410943464816_upload_0_0_local_0 success
[INFO] [2021-06-15 21:41:17,040] [2899:139778763536192] - session_utils.py[line:38]: start stop session 2021061521410943464816_upload_0_0_local_0
[INFO] [2021-06-15 21:41:17,041] [2899:139778763536192] - session_utils.py[line:47]: stop session 2021061521410943464816_upload_0_0_local_0 success
[INFO] [2021-06-15 21:41:18,547] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:41:20,579] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:41:22,633] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:41:24,668] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:41:26,729] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:41:28,785] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:41:30,821] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:41:32,869] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:41:34,939] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:41:36,981] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:41:39,029] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:41:41,093] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:41:43,143] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:41:45,198] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:41:47,255] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:41:49,301] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:41:51,356] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:41:53,418] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:41:55,451] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:41:57,509] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:41:59,576] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:42:01,618] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:42:03,650] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:42:05,705] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:42:07,763] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:42:09,824] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:42:11,871] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:42:13,919] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:42:15,979] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:42:18,038] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:42:20,086] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:42:22,134] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:42:24,189] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:42:26,229] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:42:28,266] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:42:30,320] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:42:32,380] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:42:34,435] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:42:36,479] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:42:38,539] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:42:40,719] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:42:42,785] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:42:44,842] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:42:46,898] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:42:48,954] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:42:51,024] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:42:53,070] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:42:55,108] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:42:57,157] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:42:59,220] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:43:01,277] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:43:03,323] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:43:05,377] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:43:07,436] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:43:09,488] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:43:11,533] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:43:13,577] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:43:15,630] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:43:17,676] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:43:19,732] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:43:21,767] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:43:23,806] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:43:25,872] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:43:27,916] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:43:29,990] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:43:32,031] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:43:34,096] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:43:36,144] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:43:38,208] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:43:40,261] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:43:42,323] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:43:44,371] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:43:46,430] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:43:48,482] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:43:50,518] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:43:52,585] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:43:54,654] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:43:56,723] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:43:58,776] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:44:00,828] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:44:02,879] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:44:04,948] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:44:06,991] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:44:09,045] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:44:11,100] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:44:13,150] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:44:15,205] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:44:17,263] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:44:19,321] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:44:21,361] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:44:23,420] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:44:25,476] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:44:27,548] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:44:29,608] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:44:31,644] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:44:33,695] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:44:35,746] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:44:37,798] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:44:39,848] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:44:41,907] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:44:43,964] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:44:46,018] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:44:48,080] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:44:50,138] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:44:52,172] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:44:54,234] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:44:56,318] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:44:58,365] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:00,418] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:02,474] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:04,535] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:06,628] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:08,677] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:10,717] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:12,758] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:14,806] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:16,854] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:18,907] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:20,959] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:22,998] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:25,056] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:27,110] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:29,166] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:31,218] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:33,268] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:35,326] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:37,375] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:39,431] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:41,482] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:43,527] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:45,579] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:47,632] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:49,697] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:51,757] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:53,819] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:55,880] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:57,938] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:45:59,993] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:46:02,050] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:46:04,102] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:46:06,154] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:46:08,208] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:46:10,259] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:46:12,313] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:46:14,363] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
