[INFO] [2021-06-13 21:26:12,787] [7:140265872402176] - dag_scheduler.py[line:40]: submit job, job_id 2021061321261244133411, body {'job_dsl': {'components': {'upload_0': {'module': 'Upload'}}}, 'job_runtime_conf': {'initiator': {'role': 'local', 'party_id': 0}, 'job_parameters': {'common': {'work_mode': 0, 'backend': 0}}, 'role': {'local': [0]}, 'component_parameters': {'role': {'local': {'0': {'upload_0': {'head': 1, 'name': 'default_credit_hetero_guest', 'partition': 16, 'namespace': 'experiment', 'file': '/fate/jobs/2021061321261244133411/fate_upload_tmp/default_credit_hetero_guest.csv', 'destroy': False}}}}}, 'dsl_version': 2}}
[INFO] [2021-06-13 21:26:12,811] [7:140266400880384] - job_controller.py[line:52]: job parameters:{'job_type': 'train', 'work_mode': 0, 'backend': 0, 'computing_engine': 'STANDALONE', 'federation_engine': 'STANDALONE', 'storage_engine': 'STANDALONE', 'engines_address': {}, 'federated_mode': 'SINGLE', 'task_parallelism': 1, 'computing_partitions': 4, 'federated_status_collect_type': 'PULL', 'model_id': 'local-0#model', 'model_version': '2021061321261244133411', 'eggroll_run': {}, 'spark_run': {}, 'rabbitmq_run': {}, 'pulsar_run': {}, 'adaptation_parameters': {'task_nodes': 1, 'task_cores_per_node': 4, 'task_memory_per_node': 0, 'request_task_cores': 4, 'if_initiator_baseline': True}}
[INFO] [2021-06-13 21:26:12,913] [7:140265872402176] - dag_scheduler.py[line:122]: submit job successfully, job id is 2021061321261244133411, model id is local-0#model
[INFO] [2021-06-13 21:26:14,688] [7:140266826163968] - federated_scheduler.py[line:39]: try to apply job 2021061321261244133411 resource
[INFO] [2021-06-13 21:26:14,707] [7:140265872402176] - resource_manager.py[line:176]: apply job 2021061321261244133411 resource(cores 4 memory 0) on local 0 successfully, remaining cores: 16 remaining memory: 0
[INFO] [2021-06-13 21:26:14,712] [7:140266826163968] - federated_scheduler.py[line:42]: apply job 2021061321261244133411 resource successfully
[INFO] [2021-06-13 21:26:14,712] [7:140266826163968] - dag_scheduler.py[line:279]: try to start job 2021061321261244133411 on initiator local 0
[INFO] [2021-06-13 21:26:14,727] [7:140265872402176] - job_controller.py[line:261]: try to start job 2021061321261244133411 on local 0
[INFO] [2021-06-13 21:26:14,728] [7:140265872402176] - job_saver.py[line:45]: try to update job 2021061321261244133411 status to running
[INFO] [2021-06-13 21:26:14,741] [7:140265872402176] - job_saver.py[line:48]: update job 2021061321261244133411 status successfully
[INFO] [2021-06-13 21:26:14,742] [7:140265872402176] - job_saver.py[line:61]: try to update job 2021061321261244133411
[INFO] [2021-06-13 21:26:14,755] [7:140265872402176] - job_saver.py[line:64]: job 2021061321261244133411 update successfully: {'job_id': '2021061321261244133411', 'role': 'local', 'party_id': 0, 'status': 'running', 'start_time': 1623619574728}
[INFO] [2021-06-13 21:26:14,755] [7:140265872402176] - job_controller.py[line:275]: start job 2021061321261244133411 on local 0 successfully
[INFO] [2021-06-13 21:26:14,758] [7:140266826163968] - dag_scheduler.py[line:292]: start job 2021061321261244133411 on initiator local 0
[INFO] [2021-06-13 21:26:14,769] [7:140266826163968] - dag_scheduler.py[line:247]: reset job 2021061321261244133411 ready signal True
[INFO] [2021-06-13 21:26:14,778] [7:140266826163968] - dag_scheduler.py[line:298]: scheduling job 2021061321261244133411
[INFO] [2021-06-13 21:26:14,779] [7:140266826163968] - task_scheduler.py[line:28]: scheduling job 2021061321261244133411 tasks
[INFO] [2021-06-13 21:26:14,794] [7:140266826163968] - task_scheduler.py[line:143]: job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status is waiting, calculate by task party status list: ['waiting']
[INFO] [2021-06-13 21:26:14,794] [7:140266826163968] - task_scheduler.py[line:80]: try to start job 2021061321261244133411 task 2021061321261244133411_upload_0 0 on local 0
[INFO] [2021-06-13 21:26:14,817] [7:140266826163968] - resource_manager.py[line:286]: task 2021061321261244133411_upload_0 0 apply resource successfully
[INFO] [2021-06-13 21:26:14,817] [7:140266826163968] - job_saver.py[line:71]: try to update job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status
[INFO] [2021-06-13 21:26:14,832] [7:140266826163968] - job_saver.py[line:74]: update job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status successfully: {'job_id': '2021061321261244133411', 'task_id': '2021061321261244133411_upload_0', 'task_version': 0, 'role': 'local', 'party_id': '0', 'status': 'running'}
[INFO] [2021-06-13 21:26:14,832] [7:140266826163968] - task_scheduler.py[line:93]: start job 2021061321261244133411 task 2021061321261244133411_upload_0 0 on local 0
[INFO] [2021-06-13 21:26:14,832] [7:140266826163968] - federated_scheduler.py[line:192]: job 2021061321261244133411 task 2021061321261244133411_upload_0 0 is running, sync to all party
[INFO] [2021-06-13 21:26:14,839] [7:140265872402176] - job_saver.py[line:71]: try to update job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status
[INFO] [2021-06-13 21:26:14,845] [7:140265872402176] - job_saver.py[line:76]: update job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status update does not take effect: {'job_id': '2021061321261244133411', 'task_id': '2021061321261244133411_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'status': 'running'}
[WARNING] [2021-06-13 21:26:14,854] [7:140266826163968] - federated_scheduler.py[line:260]: an error occurred while status/running the task to role local party 0: 
update task status failed
[INFO] [2021-06-13 21:26:14,854] [7:140266826163968] - federated_scheduler.py[line:197]: sync job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status running to all party failed: 
{'local': {0: {'retcode': 103, 'retmsg': 'update task status failed'}}}
[INFO] [2021-06-13 21:26:14,867] [7:140265872402176] - task_controller.py[line:71]: try to start job 2021061321261244133411 task 2021061321261244133411_upload_0 0 on local 0 executor subprocess
[INFO] [2021-06-13 21:26:14,870] [7:140265872402176] - task_controller.py[line:90]: use computing engine STANDALONE
[INFO] [2021-06-13 21:26:14,870] [7:140265872402176] - task_controller.py[line:145]: job 2021061321261244133411 task 2021061321261244133411_upload_0 0 on local 0 executor subprocess is ready
[INFO] [2021-06-13 21:26:14,870] [7:140265872402176] - job_utils.py[line:310]: start process command: /usr/local/bin/python /fate/python/fate_flow/operation/task_executor.py -j 2021061321261244133411 -n upload_0 -t 2021061321261244133411_upload_0 -v 0 -r local -p 0 -c /fate/jobs/2021061321261244133411/local/0/upload_0/2021061321261244133411_upload_0/0/task_parameters.json --run_ip 127.0.0.1 --job_server 127.0.0.1:9380
[INFO] [2021-06-13 21:26:14,879] [7:140265872402176] - job_utils.py[line:334]: start process command: /usr/local/bin/python /fate/python/fate_flow/operation/task_executor.py -j 2021061321261244133411 -n upload_0 -t 2021061321261244133411_upload_0 -v 0 -r local -p 0 -c /fate/jobs/2021061321261244133411/local/0/upload_0/2021061321261244133411_upload_0/0/task_parameters.json --run_ip 127.0.0.1 --job_server 127.0.0.1:9380 successfully, pid is 1738
[INFO] [2021-06-13 21:26:14,880] [7:140265872402176] - job_saver.py[line:81]: try to update job 2021061321261244133411 task 2021061321261244133411_upload_0 0
[INFO] [2021-06-13 21:26:14,900] [7:140265872402176] - job_saver.py[line:84]: job 2021061321261244133411 task 2021061321261244133411_upload_0 0 update successfully
[INFO] [2021-06-13 21:26:14,905] [7:140265872402176] - job_saver.py[line:71]: try to update job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status
[INFO] [2021-06-13 21:26:14,922] [7:140265872402176] - job_saver.py[line:74]: update job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status successfully: {'job_id': '2021061321261244133411', 'task_id': '2021061321261244133411_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'party_status': 'running', 'start_time': 1623619574880}
[INFO] [2021-06-13 21:26:14,927] [7:140265872402176] - task_controller.py[line:164]: job 2021061321261244133411 task 2021061321261244133411_upload_0 0 on local 0 executor subprocess start success
[INFO] [2021-06-13 21:26:14,934] [7:140266826163968] - task_scheduler.py[line:75]: finish scheduling job 2021061321261244133411 tasks
[INFO] [2021-06-13 21:26:14,934] [7:140266826163968] - dag_scheduler.py[line:310]: Job 2021061321261244133411 status is running, calculate by task status list: ['running']
[INFO] [2021-06-13 21:26:14,935] [7:140266826163968] - dag_scheduler.py[line:325]: finish scheduling job 2021061321261244133411
[INFO] [2021-06-13 21:26:16,931] [1738:140209896253248] - task_executor.py[line:56]: enter task process
[INFO] [2021-06-13 21:26:16,932] [1738:140209896253248] - task_executor.py[line:57]: Namespace(component_name='upload_0', config='/fate/jobs/2021061321261244133411/local/0/upload_0/2021061321261244133411_upload_0/0/task_parameters.json', job_id='2021061321261244133411', job_server='127.0.0.1:9380', party_id=0, role='local', run_ip='127.0.0.1', task_id='2021061321261244133411_upload_0', task_version=0)
[INFO] [2021-06-13 21:26:16,947] [7:140265872402176] - job_saver.py[line:81]: try to update job 2021061321261244133411 task 2021061321261244133411_upload_0 0
[INFO] [2021-06-13 21:26:16,968] [7:140265872402176] - job_saver.py[line:84]: job 2021061321261244133411 task 2021061321261244133411_upload_0 0 update successfully
[INFO] [2021-06-13 21:26:16,979] [7:140265872402176] - job_saver.py[line:71]: try to update job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status
[INFO] [2021-06-13 21:26:16,991] [7:140266826163968] - dag_scheduler.py[line:298]: scheduling job 2021061321261244133411
[INFO] [2021-06-13 21:26:16,993] [7:140266826163968] - task_scheduler.py[line:28]: scheduling job 2021061321261244133411 tasks
[INFO] [2021-06-13 21:26:17,000] [7:140265872402176] - job_saver.py[line:76]: update job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status update does not take effect: {'job_id': '2021061321261244133411', 'component_name': 'upload_0', 'task_id': '2021061321261244133411_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'run_ip': '127.0.0.1', 'run_pid': 1738, 'party_status': 'running'}
[INFO] [2021-06-13 21:26:17,031] [7:140266826163968] - job_saver.py[line:71]: try to update job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status
[INFO] [2021-06-13 21:26:17,037] [7:140266826163968] - job_saver.py[line:76]: update job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status update does not take effect: {'elapsed': None, 'end_time': None, 'job_id': '2021061321261244133411', 'party_id': '0', 'party_status': 'running', 'role': 'local', 'start_time': 1623619574880, 'status': 'running', 'task_id': '2021061321261244133411_upload_0', 'task_version': 0, 'update_time': 1623619572850}
[INFO] [2021-06-13 21:26:17,037] [7:140266826163968] - job_saver.py[line:81]: try to update job 2021061321261244133411 task 2021061321261244133411_upload_0 0
[INFO] [2021-06-13 21:26:17,052] [7:140266826163968] - job_saver.py[line:84]: job 2021061321261244133411 task 2021061321261244133411_upload_0 0 update successfully
[INFO] [2021-06-13 21:26:17,060] [7:140266826163968] - task_scheduler.py[line:143]: job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status is running, calculate by task party status list: ['running']
[INFO] [2021-06-13 21:26:17,061] [7:140266826163968] - task_scheduler.py[line:75]: finish scheduling job 2021061321261244133411 tasks
[INFO] [2021-06-13 21:26:17,062] [7:140266826163968] - dag_scheduler.py[line:310]: Job 2021061321261244133411 status is running, calculate by task status list: ['running']
[INFO] [2021-06-13 21:26:17,062] [7:140266826163968] - dag_scheduler.py[line:325]: finish scheduling job 2021061321261244133411
[INFO] [2021-06-13 21:26:17,846] [7:140266400880384] - job_saver.py[line:61]: try to update job 2021061321261244133411
[INFO] [2021-06-13 21:26:17,866] [7:140266400880384] - job_saver.py[line:64]: job 2021061321261244133411 update successfully: {'progress': 100.0, 'job_id': '2021061321261244133411', 'role': 'local', 'party_id': '0'}
[INFO] [2021-06-13 21:26:18,756] [7:140266400880384] - job_tracker.py[line:74]: save job 2021061321261244133411 component upload_0 on local 0 upload data_access metric data
[INFO] [2021-06-13 21:26:18,787] [7:140266400880384] - job_tracker.py[line:97]: save job 2021061321261244133411 component upload_0 on local 0 upload data_access metric meta
[INFO] [2021-06-13 21:26:18,862] [1738:140209896253248] - job_tracker.py[line:159]: task id 2021061321261244133411_upload_0 output data table is none
[INFO] [2021-06-13 21:26:18,869] [7:140266400880384] - job_saver.py[line:81]: try to update job 2021061321261244133411 task 2021061321261244133411_upload_0 0
[INFO] [2021-06-13 21:26:18,889] [7:140266400880384] - job_saver.py[line:84]: job 2021061321261244133411 task 2021061321261244133411_upload_0 0 update successfully
[INFO] [2021-06-13 21:26:18,896] [7:140266400880384] - job_saver.py[line:71]: try to update job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status
[INFO] [2021-06-13 21:26:18,914] [7:140266400880384] - job_saver.py[line:74]: update job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status successfully: {'job_id': '2021061321261244133411', 'component_name': 'upload_0', 'task_id': '2021061321261244133411_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'run_ip': '127.0.0.1', 'run_pid': 1738, 'party_status': 'success', 'end_time': 1623619578862, 'elapsed': 1930}
[INFO] [2021-06-13 21:26:18,933] [7:140266400880384] - job_saver.py[line:81]: try to update job 2021061321261244133411 task 2021061321261244133411_upload_0 0
[INFO] [2021-06-13 21:26:18,953] [7:140266400880384] - job_saver.py[line:84]: job 2021061321261244133411 task 2021061321261244133411_upload_0 0 update successfully
[INFO] [2021-06-13 21:26:18,960] [7:140266400880384] - job_saver.py[line:71]: try to update job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status
[INFO] [2021-06-13 21:26:18,967] [7:140266400880384] - job_saver.py[line:76]: update job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status update does not take effect: {'job_id': '2021061321261244133411', 'component_name': 'upload_0', 'task_id': '2021061321261244133411_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'run_ip': '127.0.0.1', 'run_pid': 1738, 'party_status': 'success', 'end_time': 1623619578862, 'elapsed': 1930}
[INFO] [2021-06-13 21:26:19,110] [7:140266826163968] - dag_scheduler.py[line:298]: scheduling job 2021061321261244133411
[INFO] [2021-06-13 21:26:19,111] [7:140266826163968] - task_scheduler.py[line:28]: scheduling job 2021061321261244133411 tasks
[INFO] [2021-06-13 21:26:19,142] [7:140266826163968] - job_saver.py[line:71]: try to update job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status
[INFO] [2021-06-13 21:26:19,150] [7:140266826163968] - job_saver.py[line:76]: update job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status update does not take effect: {'elapsed': 1930, 'end_time': 1623619578862, 'job_id': '2021061321261244133411', 'party_id': '0', 'party_status': 'success', 'role': 'local', 'start_time': 1623619574880, 'status': 'running', 'task_id': '2021061321261244133411_upload_0', 'task_version': 0, 'update_time': 1623619572850}
[INFO] [2021-06-13 21:26:19,150] [7:140266826163968] - job_saver.py[line:81]: try to update job 2021061321261244133411 task 2021061321261244133411_upload_0 0
[INFO] [2021-06-13 21:26:19,165] [7:140266826163968] - job_saver.py[line:84]: job 2021061321261244133411 task 2021061321261244133411_upload_0 0 update successfully
[INFO] [2021-06-13 21:26:19,173] [7:140266826163968] - task_scheduler.py[line:143]: job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status is success, calculate by task party status list: ['success']
[INFO] [2021-06-13 21:26:19,173] [7:140266826163968] - federated_scheduler.py[line:192]: job 2021061321261244133411 task 2021061321261244133411_upload_0 0 is success, sync to all party
[INFO] [2021-06-13 21:26:19,181] [7:140266400880384] - job_saver.py[line:71]: try to update job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status
[INFO] [2021-06-13 21:26:19,196] [7:140266400880384] - job_saver.py[line:74]: update job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status successfully: {'job_id': '2021061321261244133411', 'task_id': '2021061321261244133411_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'status': 'success'}
[INFO] [2021-06-13 21:26:19,214] [7:140266400880384] - resource_manager.py[line:286]: task 2021061321261244133411_upload_0 0 return resource successfully
[INFO] [2021-06-13 21:26:19,220] [7:140266400880384] - job_tracker.py[line:424]: clean task 2021061321261244133411_upload_0 0 on local 0
[ERROR] [2021-06-13 21:26:19,222] [7:140266400880384] - job_tracker.py[line:475]: namespace dir /fate/data/2021061321261244133411_upload_0_0_local_0 does not exist
Traceback (most recent call last):
  File "/fate/python/fate_flow/operation/job_tracker.py", line 437, in clean_task
    sess.computing.cleanup(namespace=computing_temp_namespace, name="*")
  File "/fate/python/fate_arch/computing/standalone/_csession.py", line 73, in cleanup
    return self._session.cleanup(name=name, namespace=namespace)
  File "/fate/python/fate_arch/_standalone.py", line 383, in cleanup
    raise EnvironmentError(f"namespace dir {namespace_dir} does not exist")
OSError: namespace dir /fate/data/2021061321261244133411_upload_0_0_local_0 does not exist
[INFO] [2021-06-13 21:26:19,234] [7:140266826163968] - federated_scheduler.py[line:195]: sync job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status success to all party success
[INFO] [2021-06-13 21:26:19,234] [7:140266826163968] - federated_scheduler.py[line:202]: try to stop job 2021061321261244133411 task 2021061321261244133411_upload_0 0
[INFO] [2021-06-13 21:26:19,245] [7:140266400880384] - job_utils.py[line:397]: try to stop job 2021061321261244133411 task 2021061321261244133411_upload_0 local 0 with success party status process pid:1738
[INFO] [2021-06-13 21:26:19,245] [7:140266400880384] - job_utils.py[line:400]: can not found job 2021061321261244133411 task 2021061321261244133411_upload_0 local 0 with success party status process pid:1738
[INFO] [2021-06-13 21:26:19,248] [7:140266400880384] - job_utils.py[line:424]: start run subprocess to stop task session 2021061321261244133411_upload_0_0_local_0
[INFO] [2021-06-13 21:26:19,249] [7:140266400880384] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061321261244133411_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop
[INFO] [2021-06-13 21:26:19,257] [7:140266400880384] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061321261244133411_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop successfully, pid is 1758
[INFO] [2021-06-13 21:26:19,258] [7:140266400880384] - task_controller.py[line:255]: job 2021061321261244133411 task 2021061321261244133411_upload_0 0 on local 0 process 1738 kill success
[INFO] [2021-06-13 21:26:19,258] [7:140266400880384] - job_saver.py[line:71]: try to update job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status
[INFO] [2021-06-13 21:26:19,264] [7:140266400880384] - job_saver.py[line:76]: update job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status update does not take effect: {'job_id': '2021061321261244133411', 'task_id': '2021061321261244133411_upload_0', 'task_version': 0, 'role': 'local', 'party_id': '0', 'party_status': 'success'}
[INFO] [2021-06-13 21:26:19,268] [7:140266400880384] - job_saver.py[line:81]: try to update job 2021061321261244133411 task 2021061321261244133411_upload_0 0
[WARNING] [2021-06-13 21:26:19,273] [7:140266400880384] - job_saver.py[line:86]: job 2021061321261244133411 task 2021061321261244133411_upload_0 0 update does not take effect
[INFO] [2021-06-13 21:26:19,287] [7:140266826163968] - federated_scheduler.py[line:206]: stop job 2021061321261244133411 task 2021061321261244133411_upload_0 0 success
[INFO] [2021-06-13 21:26:19,287] [7:140266826163968] - task_scheduler.py[line:75]: finish scheduling job 2021061321261244133411 tasks
[INFO] [2021-06-13 21:26:19,288] [7:140266826163968] - dag_scheduler.py[line:310]: Job 2021061321261244133411 status is success, calculate by task status list: ['success']
[INFO] [2021-06-13 21:26:19,288] [7:140266826163968] - federated_scheduler.py[line:78]: try to save job 2021061321261244133411 pipelined model
[INFO] [2021-06-13 21:26:19,294] [7:140266400880384] - job_controller.py[line:331]: job 2021061321261244133411 on local 0 start to save pipeline
[INFO] [2021-06-13 21:26:19,310] [7:140266400880384] - job_controller.py[line:374]: job 2021061321261244133411 on local 0 save pipeline successfully
[INFO] [2021-06-13 21:26:19,324] [7:140266826163968] - federated_scheduler.py[line:81]: save job 2021061321261244133411 pipelined model success
[INFO] [2021-06-13 21:26:19,324] [7:140266826163968] - federated_scheduler.py[line:68]: job 2021061321261244133411 is success, sync to all party
[INFO] [2021-06-13 21:26:19,330] [7:140266400880384] - job_saver.py[line:45]: try to update job 2021061321261244133411 status to success
[INFO] [2021-06-13 21:26:19,351] [7:140266400880384] - job_saver.py[line:48]: update job 2021061321261244133411 status successfully
[INFO] [2021-06-13 21:26:19,391] [7:140266400880384] - resource_manager.py[line:176]: return job 2021061321261244133411 resource(cores 4 memory 0) on local 0 successfully, remaining cores: 20 remaining memory: 0
[INFO] [2021-06-13 21:26:19,395] [7:140266826163968] - federated_scheduler.py[line:71]: sync job 2021061321261244133411 status success to all party success
[INFO] [2021-06-13 21:26:19,400] [7:140266826163968] - job_saver.py[line:45]: try to update job 2021061321261244133411 status to success
[INFO] [2021-06-13 21:26:19,405] [7:140266826163968] - job_saver.py[line:56]: update job 2021061321261244133411 status does not take effect
[INFO] [2021-06-13 21:26:19,405] [7:140266826163968] - job_saver.py[line:61]: try to update job 2021061321261244133411
[WARNING] [2021-06-13 21:26:19,409] [7:140266826163968] - job_saver.py[line:66]: job 2021061321261244133411 update does not take effect: {'job_id': '2021061321261244133411', 'role': 'local', 'party_id': '0', 'status': 'success'}
[INFO] [2021-06-13 21:26:19,410] [7:140266826163968] - dag_scheduler.py[line:502]: Job 2021061321261244133411 finished with success, do something...
[INFO] [2021-06-13 21:26:19,410] [7:140266826163968] - dag_scheduler.py[line:436]: request stop job 2021061321261244133411 with success
[INFO] [2021-06-13 21:26:19,414] [7:140266826163968] - dag_scheduler.py[line:445]: request stop job 2021061321261244133411 with success to all party
[INFO] [2021-06-13 21:26:19,415] [7:140266826163968] - federated_scheduler.py[line:88]: try to stop job 2021061321261244133411
[INFO] [2021-06-13 21:26:19,426] [7:140266400880384] - job_utils.py[line:397]: try to stop job 2021061321261244133411 task 2021061321261244133411_upload_0 local 0 with success party status process pid:1738
[INFO] [2021-06-13 21:26:19,426] [7:140266400880384] - job_utils.py[line:400]: can not found job 2021061321261244133411 task 2021061321261244133411_upload_0 local 0 with success party status process pid:1738
[INFO] [2021-06-13 21:26:19,428] [7:140266400880384] - job_utils.py[line:424]: start run subprocess to stop task session 2021061321261244133411_upload_0_0_local_0
[INFO] [2021-06-13 21:26:19,428] [7:140266400880384] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061321261244133411_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop
[INFO] [2021-06-13 21:26:19,436] [7:140266400880384] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061321261244133411_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop successfully, pid is 1762
[INFO] [2021-06-13 21:26:19,437] [7:140266400880384] - task_controller.py[line:255]: job 2021061321261244133411 task 2021061321261244133411_upload_0 0 on local 0 process 1738 kill success
[INFO] [2021-06-13 21:26:19,437] [7:140266400880384] - job_saver.py[line:71]: try to update job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status
[INFO] [2021-06-13 21:26:19,443] [7:140266400880384] - job_saver.py[line:76]: update job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status update does not take effect: {'job_id': '2021061321261244133411', 'task_id': '2021061321261244133411_upload_0', 'task_version': 0, 'role': 'local', 'party_id': '0', 'party_status': 'success'}
[INFO] [2021-06-13 21:26:19,448] [7:140266400880384] - job_saver.py[line:81]: try to update job 2021061321261244133411 task 2021061321261244133411_upload_0 0
[WARNING] [2021-06-13 21:26:19,452] [7:140266400880384] - job_saver.py[line:86]: job 2021061321261244133411 task 2021061321261244133411_upload_0 0 update does not take effect
[INFO] [2021-06-13 21:26:19,456] [7:140266400880384] - job_saver.py[line:45]: try to update job 2021061321261244133411 status to success
[INFO] [2021-06-13 21:26:19,461] [7:140266400880384] - job_saver.py[line:56]: update job 2021061321261244133411 status does not take effect
[INFO] [2021-06-13 21:26:19,466] [7:140266826163968] - federated_scheduler.py[line:92]: stop job 2021061321261244133411 success
[INFO] [2021-06-13 21:26:19,466] [7:140266826163968] - dag_scheduler.py[line:448]: stop job 2021061321261244133411 with success successfully
[INFO] [2021-06-13 21:26:19,466] [7:140266826163968] - federated_scheduler.py[line:107]: try to clean job 2021061321261244133411
[INFO] [2021-06-13 21:26:19,471] [7:140266400880384] - job_controller.py[line:379]: Job 2021061321261244133411 on local 0 start to clean
[INFO] [2021-06-13 21:26:19,471] [7:140266400880384] - job_controller.py[line:382]: job 2021061321261244133411 on local 0 clean done
[INFO] [2021-06-13 21:26:19,476] [7:140266826163968] - federated_scheduler.py[line:110]: clean job 2021061321261244133411 success
[INFO] [2021-06-13 21:26:19,476] [7:140266826163968] - dag_scheduler.py[line:505]: Job 2021061321261244133411 finished with success, done
[INFO] [2021-06-13 21:26:19,476] [7:140266826163968] - dag_scheduler.py[line:325]: finish scheduling job 2021061321261244133411
[INFO] [2021-06-13 21:26:19,520] [7:140266826163968] - dag_scheduler.py[line:298]: scheduling job 2021061321261244133411
[INFO] [2021-06-13 21:26:19,521] [7:140266826163968] - task_scheduler.py[line:28]: scheduling job 2021061321261244133411 tasks
[INFO] [2021-06-13 21:26:19,534] [7:140266826163968] - task_scheduler.py[line:143]: job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status is success, calculate by task party status list: ['success']
[INFO] [2021-06-13 21:26:19,534] [7:140266826163968] - task_scheduler.py[line:75]: finish scheduling job 2021061321261244133411 tasks
[INFO] [2021-06-13 21:26:19,534] [7:140266826163968] - dag_scheduler.py[line:310]: Job 2021061321261244133411 status is success, calculate by task status list: ['success']
[INFO] [2021-06-13 21:26:19,534] [7:140266826163968] - dag_scheduler.py[line:502]: Job 2021061321261244133411 finished with success, do something...
[INFO] [2021-06-13 21:26:19,535] [7:140266826163968] - dag_scheduler.py[line:436]: request stop job 2021061321261244133411 with success
[INFO] [2021-06-13 21:26:19,541] [7:140266826163968] - dag_scheduler.py[line:445]: request stop job 2021061321261244133411 with success to all party
[INFO] [2021-06-13 21:26:19,541] [7:140266826163968] - federated_scheduler.py[line:88]: try to stop job 2021061321261244133411
[INFO] [2021-06-13 21:26:19,561] [7:140266400880384] - job_utils.py[line:397]: try to stop job 2021061321261244133411 task 2021061321261244133411_upload_0 local 0 with success party status process pid:1738
[INFO] [2021-06-13 21:26:19,563] [7:140266400880384] - job_utils.py[line:400]: can not found job 2021061321261244133411 task 2021061321261244133411_upload_0 local 0 with success party status process pid:1738
[INFO] [2021-06-13 21:26:19,575] [7:140266400880384] - job_utils.py[line:424]: start run subprocess to stop task session 2021061321261244133411_upload_0_0_local_0
[INFO] [2021-06-13 21:26:19,576] [7:140266400880384] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061321261244133411_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop
[INFO] [2021-06-13 21:26:19,585] [7:140266400880384] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061321261244133411_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop successfully, pid is 1766
[INFO] [2021-06-13 21:26:19,586] [7:140266400880384] - task_controller.py[line:255]: job 2021061321261244133411 task 2021061321261244133411_upload_0 0 on local 0 process 1738 kill success
[INFO] [2021-06-13 21:26:19,586] [7:140266400880384] - job_saver.py[line:71]: try to update job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status
[INFO] [2021-06-13 21:26:19,591] [7:140266400880384] - job_saver.py[line:76]: update job 2021061321261244133411 task 2021061321261244133411_upload_0 0 status update does not take effect: {'job_id': '2021061321261244133411', 'task_id': '2021061321261244133411_upload_0', 'task_version': 0, 'role': 'local', 'party_id': '0', 'party_status': 'success'}
[INFO] [2021-06-13 21:26:19,596] [7:140266400880384] - job_saver.py[line:81]: try to update job 2021061321261244133411 task 2021061321261244133411_upload_0 0
[WARNING] [2021-06-13 21:26:19,600] [7:140266400880384] - job_saver.py[line:86]: job 2021061321261244133411 task 2021061321261244133411_upload_0 0 update does not take effect
[INFO] [2021-06-13 21:26:19,606] [7:140266400880384] - job_saver.py[line:45]: try to update job 2021061321261244133411 status to success
[INFO] [2021-06-13 21:26:19,613] [7:140266400880384] - job_saver.py[line:56]: update job 2021061321261244133411 status does not take effect
[INFO] [2021-06-13 21:26:19,619] [7:140266826163968] - federated_scheduler.py[line:92]: stop job 2021061321261244133411 success
[INFO] [2021-06-13 21:26:19,620] [7:140266826163968] - dag_scheduler.py[line:448]: stop job 2021061321261244133411 with success successfully
[INFO] [2021-06-13 21:26:19,620] [7:140266826163968] - federated_scheduler.py[line:107]: try to clean job 2021061321261244133411
[INFO] [2021-06-13 21:26:19,634] [7:140265872402176] - job_controller.py[line:379]: Job 2021061321261244133411 on local 0 start to clean
[INFO] [2021-06-13 21:26:19,635] [7:140265872402176] - job_controller.py[line:382]: job 2021061321261244133411 on local 0 clean done
[INFO] [2021-06-13 21:26:19,641] [7:140266826163968] - federated_scheduler.py[line:110]: clean job 2021061321261244133411 success
[INFO] [2021-06-13 21:26:19,642] [7:140266826163968] - dag_scheduler.py[line:505]: Job 2021061321261244133411 finished with success, done
[INFO] [2021-06-13 21:26:19,642] [7:140266826163968] - dag_scheduler.py[line:325]: finish scheduling job 2021061321261244133411
[INFO] [2021-06-13 21:26:20,028] [1758:140616973813568] - session_utils.py[line:38]: start stop session 2021061321261244133411_upload_0_0_local_0
[INFO] [2021-06-13 21:26:20,029] [1758:140616973813568] - session_utils.py[line:47]: stop session 2021061321261244133411_upload_0_0_local_0 success
[INFO] [2021-06-13 21:26:20,177] [1762:139802386036544] - session_utils.py[line:38]: start stop session 2021061321261244133411_upload_0_0_local_0
[INFO] [2021-06-13 21:26:20,178] [1762:139802386036544] - session_utils.py[line:47]: stop session 2021061321261244133411_upload_0_0_local_0 success
[INFO] [2021-06-13 21:26:20,260] [1766:140267691603776] - session_utils.py[line:38]: start stop session 2021061321261244133411_upload_0_0_local_0
[INFO] [2021-06-13 21:26:20,261] [1766:140267691603776] - session_utils.py[line:47]: stop session 2021061321261244133411_upload_0_0_local_0 success
[INFO] [2021-06-13 21:26:21,711] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:26:23,771] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:26:25,826] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:26:27,889] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:26:29,943] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:26:31,994] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:26:34,050] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:26:36,104] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:26:38,172] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:26:40,208] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:26:42,261] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:26:44,316] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:26:46,378] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:26:48,444] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:26:50,514] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:26:52,560] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:26:54,620] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:26:56,689] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:26:58,729] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:27:00,786] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:27:02,843] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:27:04,904] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:27:06,949] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:27:09,021] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:27:11,082] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:27:13,150] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:27:15,205] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:27:17,280] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:27:19,334] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:27:21,390] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:27:23,451] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:27:25,506] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:27:27,569] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:27:29,633] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:27:31,686] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:27:33,747] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:27:35,799] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:27:37,850] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:27:39,934] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:27:41,971] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:27:44,015] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:27:46,074] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:27:48,146] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:27:50,202] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:27:52,251] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:27:54,305] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:27:56,363] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:27:58,429] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:28:00,469] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:28:02,527] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:28:04,590] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:28:06,646] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:28:08,693] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:28:10,759] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:28:12,811] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:28:14,845] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:28:16,902] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:28:18,963] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:28:21,022] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:28:23,091] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:28:25,153] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:28:27,215] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:28:29,257] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:28:31,310] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:28:33,365] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:28:35,422] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:28:37,475] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:28:39,537] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:28:41,662] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:28:43,716] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:28:45,788] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:28:47,850] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:28:49,915] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:28:51,970] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:28:54,028] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:28:56,084] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:28:58,139] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:29:00,195] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:29:02,249] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:29:04,304] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:29:06,364] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:29:08,445] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:29:10,503] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:29:12,561] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:29:14,620] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:29:16,714] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:29:18,801] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:29:20,898] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:29:22,951] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:29:24,985] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:29:27,040] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:29:29,093] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:29:31,158] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:29:33,212] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:29:35,265] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:29:37,319] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:29:39,372] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:29:41,433] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:29:43,485] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:29:45,537] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:29:47,592] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:29:49,692] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:29:51,753] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:29:53,832] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:29:55,887] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:29:57,948] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:00,025] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:02,076] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:04,130] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:06,185] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:08,252] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:10,303] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:12,350] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:14,395] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:16,440] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:18,485] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:20,542] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:22,590] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:24,635] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:26,667] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:28,719] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:30,769] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:32,814] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:34,872] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:36,916] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:38,971] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:41,023] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:43,074] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:45,137] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:47,180] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:49,225] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:51,269] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:53,298] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:55,343] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:57,398] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:30:59,444] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:31:01,488] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:31:03,535] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:31:05,564] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:31:07,616] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:31:09,642] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:31:11,690] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:31:13,743] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:31:15,789] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:31:17,834] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
