[INFO] [2021-06-13 21:02:37,176] [7:140265889187584] - dag_scheduler.py[line:40]: submit job, job_id 202106132102371506761, body {'job_dsl': {'components': {'upload_0': {'module': 'Upload'}}}, 'job_runtime_conf': {'initiator': {'role': 'local', 'party_id': 0}, 'job_parameters': {'common': {'work_mode': 0, 'backend': 0}}, 'role': {'local': [0]}, 'component_parameters': {'role': {'local': {'0': {'upload_0': {'head': 1, 'name': 'breast_hetero_host', 'partition': 16, 'namespace': 'experiment', 'file': '/fate/jobs/202106132102371506761/fate_upload_tmp/breast_hetero_host.csv', 'destroy': False}}}}}, 'dsl_version': 2}}
[INFO] [2021-06-13 21:02:37,210] [7:140265880794880] - job_controller.py[line:52]: job parameters:{'job_type': 'train', 'work_mode': 0, 'backend': 0, 'computing_engine': 'STANDALONE', 'federation_engine': 'STANDALONE', 'storage_engine': 'STANDALONE', 'engines_address': {}, 'federated_mode': 'SINGLE', 'task_parallelism': 1, 'computing_partitions': 4, 'federated_status_collect_type': 'PULL', 'model_id': 'local-0#model', 'model_version': '202106132102371506761', 'eggroll_run': {}, 'spark_run': {}, 'rabbitmq_run': {}, 'pulsar_run': {}, 'adaptation_parameters': {'task_nodes': 1, 'task_cores_per_node': 4, 'task_memory_per_node': 0, 'request_task_cores': 4, 'if_initiator_baseline': True}}
[INFO] [2021-06-13 21:02:37,320] [7:140265889187584] - dag_scheduler.py[line:122]: submit job successfully, job id is 202106132102371506761, model id is local-0#model
[INFO] [2021-06-13 21:02:39,219] [7:140266826163968] - federated_scheduler.py[line:39]: try to apply job 202106132102371506761 resource
[INFO] [2021-06-13 21:02:39,247] [7:140265889187584] - resource_manager.py[line:176]: apply job 202106132102371506761 resource(cores 4 memory 0) on local 0 successfully, remaining cores: 16 remaining memory: 0
[INFO] [2021-06-13 21:02:39,252] [7:140266826163968] - federated_scheduler.py[line:42]: apply job 202106132102371506761 resource successfully
[INFO] [2021-06-13 21:02:39,253] [7:140266826163968] - dag_scheduler.py[line:279]: try to start job 202106132102371506761 on initiator local 0
[INFO] [2021-06-13 21:02:39,267] [7:140265889187584] - job_controller.py[line:261]: try to start job 202106132102371506761 on local 0
[INFO] [2021-06-13 21:02:39,267] [7:140265889187584] - job_saver.py[line:45]: try to update job 202106132102371506761 status to running
[INFO] [2021-06-13 21:02:39,289] [7:140265889187584] - job_saver.py[line:48]: update job 202106132102371506761 status successfully
[INFO] [2021-06-13 21:02:39,290] [7:140265889187584] - job_saver.py[line:61]: try to update job 202106132102371506761
[INFO] [2021-06-13 21:02:39,308] [7:140265889187584] - job_saver.py[line:64]: job 202106132102371506761 update successfully: {'job_id': '202106132102371506761', 'role': 'local', 'party_id': 0, 'status': 'running', 'start_time': 1623618159267}
[INFO] [2021-06-13 21:02:39,308] [7:140265889187584] - job_controller.py[line:275]: start job 202106132102371506761 on local 0 successfully
[INFO] [2021-06-13 21:02:39,313] [7:140266826163968] - dag_scheduler.py[line:292]: start job 202106132102371506761 on initiator local 0
[INFO] [2021-06-13 21:02:39,324] [7:140266826163968] - dag_scheduler.py[line:247]: reset job 202106132102371506761 ready signal True
[INFO] [2021-06-13 21:02:39,334] [7:140266826163968] - dag_scheduler.py[line:298]: scheduling job 202106132102371506761
[INFO] [2021-06-13 21:02:39,336] [7:140266826163968] - task_scheduler.py[line:28]: scheduling job 202106132102371506761 tasks
[INFO] [2021-06-13 21:02:39,355] [7:140266826163968] - task_scheduler.py[line:143]: job 202106132102371506761 task 202106132102371506761_upload_0 0 status is waiting, calculate by task party status list: ['waiting']
[INFO] [2021-06-13 21:02:39,355] [7:140266826163968] - task_scheduler.py[line:80]: try to start job 202106132102371506761 task 202106132102371506761_upload_0 0 on local 0
[INFO] [2021-06-13 21:02:39,371] [7:140266826163968] - resource_manager.py[line:286]: task 202106132102371506761_upload_0 0 apply resource successfully
[INFO] [2021-06-13 21:02:39,371] [7:140266826163968] - job_saver.py[line:71]: try to update job 202106132102371506761 task 202106132102371506761_upload_0 0 status
[INFO] [2021-06-13 21:02:39,387] [7:140266826163968] - job_saver.py[line:74]: update job 202106132102371506761 task 202106132102371506761_upload_0 0 status successfully: {'job_id': '202106132102371506761', 'task_id': '202106132102371506761_upload_0', 'task_version': 0, 'role': 'local', 'party_id': '0', 'status': 'running'}
[INFO] [2021-06-13 21:02:39,388] [7:140266826163968] - task_scheduler.py[line:93]: start job 202106132102371506761 task 202106132102371506761_upload_0 0 on local 0
[INFO] [2021-06-13 21:02:39,388] [7:140266826163968] - federated_scheduler.py[line:192]: job 202106132102371506761 task 202106132102371506761_upload_0 0 is running, sync to all party
[INFO] [2021-06-13 21:02:39,395] [7:140265889187584] - job_saver.py[line:71]: try to update job 202106132102371506761 task 202106132102371506761_upload_0 0 status
[INFO] [2021-06-13 21:02:39,403] [7:140265889187584] - job_saver.py[line:76]: update job 202106132102371506761 task 202106132102371506761_upload_0 0 status update does not take effect: {'job_id': '202106132102371506761', 'task_id': '202106132102371506761_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'status': 'running'}
[WARNING] [2021-06-13 21:02:39,414] [7:140266826163968] - federated_scheduler.py[line:260]: an error occurred while status/running the task to role local party 0: 
update task status failed
[INFO] [2021-06-13 21:02:39,414] [7:140266826163968] - federated_scheduler.py[line:197]: sync job 202106132102371506761 task 202106132102371506761_upload_0 0 status running to all party failed: 
{'local': {0: {'retcode': 103, 'retmsg': 'update task status failed'}}}
[INFO] [2021-06-13 21:02:39,427] [7:140265889187584] - task_controller.py[line:71]: try to start job 202106132102371506761 task 202106132102371506761_upload_0 0 on local 0 executor subprocess
[INFO] [2021-06-13 21:02:39,432] [7:140265889187584] - task_controller.py[line:90]: use computing engine STANDALONE
[INFO] [2021-06-13 21:02:39,432] [7:140265889187584] - task_controller.py[line:145]: job 202106132102371506761 task 202106132102371506761_upload_0 0 on local 0 executor subprocess is ready
[INFO] [2021-06-13 21:02:39,432] [7:140265889187584] - job_utils.py[line:310]: start process command: /usr/local/bin/python /fate/python/fate_flow/operation/task_executor.py -j 202106132102371506761 -n upload_0 -t 202106132102371506761_upload_0 -v 0 -r local -p 0 -c /fate/jobs/202106132102371506761/local/0/upload_0/202106132102371506761_upload_0/0/task_parameters.json --run_ip 127.0.0.1 --job_server 127.0.0.1:9380
[INFO] [2021-06-13 21:02:39,440] [7:140265889187584] - job_utils.py[line:334]: start process command: /usr/local/bin/python /fate/python/fate_flow/operation/task_executor.py -j 202106132102371506761 -n upload_0 -t 202106132102371506761_upload_0 -v 0 -r local -p 0 -c /fate/jobs/202106132102371506761/local/0/upload_0/202106132102371506761_upload_0/0/task_parameters.json --run_ip 127.0.0.1 --job_server 127.0.0.1:9380 successfully, pid is 202
[INFO] [2021-06-13 21:02:39,441] [7:140265889187584] - job_saver.py[line:81]: try to update job 202106132102371506761 task 202106132102371506761_upload_0 0
[INFO] [2021-06-13 21:02:39,469] [7:140265889187584] - job_saver.py[line:84]: job 202106132102371506761 task 202106132102371506761_upload_0 0 update successfully
[INFO] [2021-06-13 21:02:39,477] [7:140265889187584] - job_saver.py[line:71]: try to update job 202106132102371506761 task 202106132102371506761_upload_0 0 status
[INFO] [2021-06-13 21:02:39,500] [7:140265889187584] - job_saver.py[line:74]: update job 202106132102371506761 task 202106132102371506761_upload_0 0 status successfully: {'job_id': '202106132102371506761', 'task_id': '202106132102371506761_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'party_status': 'running', 'start_time': 1623618159441}
[INFO] [2021-06-13 21:02:39,507] [7:140265889187584] - task_controller.py[line:164]: job 202106132102371506761 task 202106132102371506761_upload_0 0 on local 0 executor subprocess start success
[INFO] [2021-06-13 21:02:39,514] [7:140266826163968] - task_scheduler.py[line:75]: finish scheduling job 202106132102371506761 tasks
[INFO] [2021-06-13 21:02:39,514] [7:140266826163968] - dag_scheduler.py[line:310]: Job 202106132102371506761 status is running, calculate by task status list: ['running']
[INFO] [2021-06-13 21:02:39,514] [7:140266826163968] - dag_scheduler.py[line:325]: finish scheduling job 202106132102371506761
[INFO] [2021-06-13 21:02:41,523] [202:140440643139392] - task_executor.py[line:56]: enter task process
[INFO] [2021-06-13 21:02:41,523] [202:140440643139392] - task_executor.py[line:57]: Namespace(component_name='upload_0', config='/fate/jobs/202106132102371506761/local/0/upload_0/202106132102371506761_upload_0/0/task_parameters.json', job_id='202106132102371506761', job_server='127.0.0.1:9380', party_id=0, role='local', run_ip='127.0.0.1', task_id='202106132102371506761_upload_0', task_version=0)
[INFO] [2021-06-13 21:02:41,541] [7:140265889187584] - job_saver.py[line:81]: try to update job 202106132102371506761 task 202106132102371506761_upload_0 0
[INFO] [2021-06-13 21:02:41,568] [7:140266826163968] - dag_scheduler.py[line:298]: scheduling job 202106132102371506761
[INFO] [2021-06-13 21:02:41,571] [7:140266826163968] - task_scheduler.py[line:28]: scheduling job 202106132102371506761 tasks
[INFO] [2021-06-13 21:02:41,577] [7:140265889187584] - job_saver.py[line:84]: job 202106132102371506761 task 202106132102371506761_upload_0 0 update successfully
[INFO] [2021-06-13 21:02:41,586] [7:140265889187584] - job_saver.py[line:71]: try to update job 202106132102371506761 task 202106132102371506761_upload_0 0 status
[INFO] [2021-06-13 21:02:41,600] [7:140265889187584] - job_saver.py[line:76]: update job 202106132102371506761 task 202106132102371506761_upload_0 0 status update does not take effect: {'job_id': '202106132102371506761', 'component_name': 'upload_0', 'task_id': '202106132102371506761_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'run_ip': '127.0.0.1', 'run_pid': 202, 'party_status': 'running'}
[INFO] [2021-06-13 21:02:41,620] [7:140266826163968] - job_saver.py[line:71]: try to update job 202106132102371506761 task 202106132102371506761_upload_0 0 status
[INFO] [2021-06-13 21:02:41,627] [7:140266826163968] - job_saver.py[line:76]: update job 202106132102371506761 task 202106132102371506761_upload_0 0 status update does not take effect: {'elapsed': None, 'end_time': None, 'job_id': '202106132102371506761', 'party_id': '0', 'party_status': 'running', 'role': 'local', 'start_time': 1623618159441, 'status': 'running', 'task_id': '202106132102371506761_upload_0', 'task_version': 0, 'update_time': 1623618157230}
[INFO] [2021-06-13 21:02:41,627] [7:140266826163968] - job_saver.py[line:81]: try to update job 202106132102371506761 task 202106132102371506761_upload_0 0
[INFO] [2021-06-13 21:02:41,644] [7:140266826163968] - job_saver.py[line:84]: job 202106132102371506761 task 202106132102371506761_upload_0 0 update successfully
[INFO] [2021-06-13 21:02:41,650] [7:140266826163968] - task_scheduler.py[line:143]: job 202106132102371506761 task 202106132102371506761_upload_0 0 status is running, calculate by task party status list: ['running']
[INFO] [2021-06-13 21:02:41,650] [7:140266826163968] - task_scheduler.py[line:75]: finish scheduling job 202106132102371506761 tasks
[INFO] [2021-06-13 21:02:41,651] [7:140266826163968] - dag_scheduler.py[line:310]: Job 202106132102371506761 status is running, calculate by task status list: ['running']
[INFO] [2021-06-13 21:02:41,651] [7:140266826163968] - dag_scheduler.py[line:325]: finish scheduling job 202106132102371506761
[INFO] [2021-06-13 21:02:42,145] [7:140267417118464] - job_saver.py[line:61]: try to update job 202106132102371506761
[INFO] [2021-06-13 21:02:42,172] [7:140267417118464] - job_saver.py[line:64]: job 202106132102371506761 update successfully: {'progress': 100.0, 'job_id': '202106132102371506761', 'role': 'local', 'party_id': '0'}
[INFO] [2021-06-13 21:02:42,408] [7:140267417118464] - job_tracker.py[line:74]: save job 202106132102371506761 component upload_0 on local 0 upload data_access metric data
[INFO] [2021-06-13 21:02:42,438] [7:140267417118464] - job_tracker.py[line:97]: save job 202106132102371506761 component upload_0 on local 0 upload data_access metric meta
[INFO] [2021-06-13 21:02:42,516] [202:140440643139392] - job_tracker.py[line:159]: task id 202106132102371506761_upload_0 output data table is none
[INFO] [2021-06-13 21:02:42,523] [7:140267417118464] - job_saver.py[line:81]: try to update job 202106132102371506761 task 202106132102371506761_upload_0 0
[INFO] [2021-06-13 21:02:42,543] [7:140267417118464] - job_saver.py[line:84]: job 202106132102371506761 task 202106132102371506761_upload_0 0 update successfully
[INFO] [2021-06-13 21:02:42,550] [7:140267417118464] - job_saver.py[line:71]: try to update job 202106132102371506761 task 202106132102371506761_upload_0 0 status
[INFO] [2021-06-13 21:02:42,569] [7:140267417118464] - job_saver.py[line:74]: update job 202106132102371506761 task 202106132102371506761_upload_0 0 status successfully: {'job_id': '202106132102371506761', 'component_name': 'upload_0', 'task_id': '202106132102371506761_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'run_ip': '127.0.0.1', 'run_pid': 202, 'party_status': 'success', 'end_time': 1623618162516, 'elapsed': 993}
[INFO] [2021-06-13 21:02:42,587] [7:140267417118464] - job_saver.py[line:81]: try to update job 202106132102371506761 task 202106132102371506761_upload_0 0
[INFO] [2021-06-13 21:02:42,607] [7:140267417118464] - job_saver.py[line:84]: job 202106132102371506761 task 202106132102371506761_upload_0 0 update successfully
[INFO] [2021-06-13 21:02:42,614] [7:140267417118464] - job_saver.py[line:71]: try to update job 202106132102371506761 task 202106132102371506761_upload_0 0 status
[INFO] [2021-06-13 21:02:42,620] [7:140267417118464] - job_saver.py[line:76]: update job 202106132102371506761 task 202106132102371506761_upload_0 0 status update does not take effect: {'job_id': '202106132102371506761', 'component_name': 'upload_0', 'task_id': '202106132102371506761_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'run_ip': '127.0.0.1', 'run_pid': 202, 'party_status': 'success', 'end_time': 1623618162516, 'elapsed': 993}
[INFO] [2021-06-13 21:02:43,692] [7:140266826163968] - dag_scheduler.py[line:298]: scheduling job 202106132102371506761
[INFO] [2021-06-13 21:02:43,694] [7:140266826163968] - task_scheduler.py[line:28]: scheduling job 202106132102371506761 tasks
[INFO] [2021-06-13 21:02:43,738] [7:140266826163968] - job_saver.py[line:71]: try to update job 202106132102371506761 task 202106132102371506761_upload_0 0 status
[INFO] [2021-06-13 21:02:43,745] [7:140266826163968] - job_saver.py[line:76]: update job 202106132102371506761 task 202106132102371506761_upload_0 0 status update does not take effect: {'elapsed': 993, 'end_time': 1623618162516, 'job_id': '202106132102371506761', 'party_id': '0', 'party_status': 'success', 'role': 'local', 'start_time': 1623618159441, 'status': 'running', 'task_id': '202106132102371506761_upload_0', 'task_version': 0, 'update_time': 1623618157230}
[INFO] [2021-06-13 21:02:43,746] [7:140266826163968] - job_saver.py[line:81]: try to update job 202106132102371506761 task 202106132102371506761_upload_0 0
[INFO] [2021-06-13 21:02:43,765] [7:140266826163968] - job_saver.py[line:84]: job 202106132102371506761 task 202106132102371506761_upload_0 0 update successfully
[INFO] [2021-06-13 21:02:43,773] [7:140266826163968] - task_scheduler.py[line:143]: job 202106132102371506761 task 202106132102371506761_upload_0 0 status is success, calculate by task party status list: ['success']
[INFO] [2021-06-13 21:02:43,774] [7:140266826163968] - federated_scheduler.py[line:192]: job 202106132102371506761 task 202106132102371506761_upload_0 0 is success, sync to all party
[INFO] [2021-06-13 21:02:43,782] [7:140267417118464] - job_saver.py[line:71]: try to update job 202106132102371506761 task 202106132102371506761_upload_0 0 status
[INFO] [2021-06-13 21:02:43,803] [7:140267417118464] - job_saver.py[line:74]: update job 202106132102371506761 task 202106132102371506761_upload_0 0 status successfully: {'job_id': '202106132102371506761', 'task_id': '202106132102371506761_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'status': 'success'}
[INFO] [2021-06-13 21:02:43,821] [7:140267417118464] - resource_manager.py[line:286]: task 202106132102371506761_upload_0 0 return resource successfully
[INFO] [2021-06-13 21:02:43,826] [7:140267417118464] - job_tracker.py[line:424]: clean task 202106132102371506761_upload_0 0 on local 0
[ERROR] [2021-06-13 21:02:44,126] [7:140267417118464] - job_tracker.py[line:475]: namespace dir /fate/data/202106132102371506761_upload_0_0_local_0 does not exist
Traceback (most recent call last):
  File "/fate/python/fate_flow/operation/job_tracker.py", line 437, in clean_task
    sess.computing.cleanup(namespace=computing_temp_namespace, name="*")
  File "/fate/python/fate_arch/computing/standalone/_csession.py", line 73, in cleanup
    return self._session.cleanup(name=name, namespace=namespace)
  File "/fate/python/fate_arch/_standalone.py", line 383, in cleanup
    raise EnvironmentError(f"namespace dir {namespace_dir} does not exist")
OSError: namespace dir /fate/data/202106132102371506761_upload_0_0_local_0 does not exist
[INFO] [2021-06-13 21:02:44,136] [7:140266826163968] - federated_scheduler.py[line:195]: sync job 202106132102371506761 task 202106132102371506761_upload_0 0 status success to all party success
[INFO] [2021-06-13 21:02:44,137] [7:140266826163968] - federated_scheduler.py[line:202]: try to stop job 202106132102371506761 task 202106132102371506761_upload_0 0
[INFO] [2021-06-13 21:02:44,147] [7:140267417118464] - job_utils.py[line:397]: try to stop job 202106132102371506761 task 202106132102371506761_upload_0 local 0 with success party status process pid:202
[INFO] [2021-06-13 21:02:44,147] [7:140267417118464] - job_utils.py[line:400]: can not found job 202106132102371506761 task 202106132102371506761_upload_0 local 0 with success party status process pid:202
[INFO] [2021-06-13 21:02:44,149] [7:140267417118464] - job_utils.py[line:424]: start run subprocess to stop task session 202106132102371506761_upload_0_0_local_0
[INFO] [2021-06-13 21:02:44,149] [7:140267417118464] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106132102371506761_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop
[INFO] [2021-06-13 21:02:44,157] [7:140267417118464] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106132102371506761_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop successfully, pid is 222
[INFO] [2021-06-13 21:02:44,158] [7:140267417118464] - task_controller.py[line:255]: job 202106132102371506761 task 202106132102371506761_upload_0 0 on local 0 process 202 kill success
[INFO] [2021-06-13 21:02:44,158] [7:140267417118464] - job_saver.py[line:71]: try to update job 202106132102371506761 task 202106132102371506761_upload_0 0 status
[INFO] [2021-06-13 21:02:44,163] [7:140267417118464] - job_saver.py[line:76]: update job 202106132102371506761 task 202106132102371506761_upload_0 0 status update does not take effect: {'job_id': '202106132102371506761', 'task_id': '202106132102371506761_upload_0', 'task_version': 0, 'role': 'local', 'party_id': '0', 'party_status': 'success'}
[INFO] [2021-06-13 21:02:44,168] [7:140267417118464] - job_saver.py[line:81]: try to update job 202106132102371506761 task 202106132102371506761_upload_0 0
[WARNING] [2021-06-13 21:02:44,175] [7:140267417118464] - job_saver.py[line:86]: job 202106132102371506761 task 202106132102371506761_upload_0 0 update does not take effect
[INFO] [2021-06-13 21:02:44,188] [7:140266826163968] - federated_scheduler.py[line:206]: stop job 202106132102371506761 task 202106132102371506761_upload_0 0 success
[INFO] [2021-06-13 21:02:44,188] [7:140266826163968] - task_scheduler.py[line:75]: finish scheduling job 202106132102371506761 tasks
[INFO] [2021-06-13 21:02:44,188] [7:140266826163968] - dag_scheduler.py[line:310]: Job 202106132102371506761 status is success, calculate by task status list: ['success']
[INFO] [2021-06-13 21:02:44,188] [7:140266826163968] - federated_scheduler.py[line:78]: try to save job 202106132102371506761 pipelined model
[INFO] [2021-06-13 21:02:44,193] [7:140267417118464] - job_controller.py[line:331]: job 202106132102371506761 on local 0 start to save pipeline
[INFO] [2021-06-13 21:02:44,205] [7:140267417118464] - job_controller.py[line:374]: job 202106132102371506761 on local 0 save pipeline successfully
[INFO] [2021-06-13 21:02:44,210] [7:140266826163968] - federated_scheduler.py[line:81]: save job 202106132102371506761 pipelined model success
[INFO] [2021-06-13 21:02:44,210] [7:140266826163968] - federated_scheduler.py[line:68]: job 202106132102371506761 is success, sync to all party
[INFO] [2021-06-13 21:02:44,222] [7:140267417118464] - job_saver.py[line:45]: try to update job 202106132102371506761 status to success
[INFO] [2021-06-13 21:02:44,236] [7:140267417118464] - job_saver.py[line:48]: update job 202106132102371506761 status successfully
[INFO] [2021-06-13 21:02:44,263] [7:140267417118464] - resource_manager.py[line:176]: return job 202106132102371506761 resource(cores 4 memory 0) on local 0 successfully, remaining cores: 20 remaining memory: 0
[INFO] [2021-06-13 21:02:44,266] [7:140266826163968] - federated_scheduler.py[line:71]: sync job 202106132102371506761 status success to all party success
[INFO] [2021-06-13 21:02:44,274] [7:140266826163968] - job_saver.py[line:45]: try to update job 202106132102371506761 status to success
[INFO] [2021-06-13 21:02:44,281] [7:140266826163968] - job_saver.py[line:56]: update job 202106132102371506761 status does not take effect
[INFO] [2021-06-13 21:02:44,282] [7:140266826163968] - job_saver.py[line:61]: try to update job 202106132102371506761
[WARNING] [2021-06-13 21:02:44,289] [7:140266826163968] - job_saver.py[line:66]: job 202106132102371506761 update does not take effect: {'job_id': '202106132102371506761', 'role': 'local', 'party_id': '0', 'status': 'success'}
[INFO] [2021-06-13 21:02:44,289] [7:140266826163968] - dag_scheduler.py[line:502]: Job 202106132102371506761 finished with success, do something...
[INFO] [2021-06-13 21:02:44,290] [7:140266826163968] - dag_scheduler.py[line:436]: request stop job 202106132102371506761 with success
[INFO] [2021-06-13 21:02:44,295] [7:140266826163968] - dag_scheduler.py[line:445]: request stop job 202106132102371506761 with success to all party
[INFO] [2021-06-13 21:02:44,295] [7:140266826163968] - federated_scheduler.py[line:88]: try to stop job 202106132102371506761
[INFO] [2021-06-13 21:02:44,307] [7:140267417118464] - job_utils.py[line:397]: try to stop job 202106132102371506761 task 202106132102371506761_upload_0 local 0 with success party status process pid:202
[INFO] [2021-06-13 21:02:44,308] [7:140267417118464] - job_utils.py[line:400]: can not found job 202106132102371506761 task 202106132102371506761_upload_0 local 0 with success party status process pid:202
[INFO] [2021-06-13 21:02:44,311] [7:140267417118464] - job_utils.py[line:424]: start run subprocess to stop task session 202106132102371506761_upload_0_0_local_0
[INFO] [2021-06-13 21:02:44,312] [7:140267417118464] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106132102371506761_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop
[INFO] [2021-06-13 21:02:44,319] [7:140267417118464] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106132102371506761_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop successfully, pid is 226
[INFO] [2021-06-13 21:02:44,320] [7:140267417118464] - task_controller.py[line:255]: job 202106132102371506761 task 202106132102371506761_upload_0 0 on local 0 process 202 kill success
[INFO] [2021-06-13 21:02:44,320] [7:140267417118464] - job_saver.py[line:71]: try to update job 202106132102371506761 task 202106132102371506761_upload_0 0 status
[INFO] [2021-06-13 21:02:44,324] [7:140267417118464] - job_saver.py[line:76]: update job 202106132102371506761 task 202106132102371506761_upload_0 0 status update does not take effect: {'job_id': '202106132102371506761', 'task_id': '202106132102371506761_upload_0', 'task_version': 0, 'role': 'local', 'party_id': '0', 'party_status': 'success'}
[INFO] [2021-06-13 21:02:44,329] [7:140267417118464] - job_saver.py[line:81]: try to update job 202106132102371506761 task 202106132102371506761_upload_0 0
[WARNING] [2021-06-13 21:02:44,337] [7:140267417118464] - job_saver.py[line:86]: job 202106132102371506761 task 202106132102371506761_upload_0 0 update does not take effect
[INFO] [2021-06-13 21:02:44,341] [7:140267417118464] - job_saver.py[line:45]: try to update job 202106132102371506761 status to success
[INFO] [2021-06-13 21:02:44,345] [7:140267417118464] - job_saver.py[line:56]: update job 202106132102371506761 status does not take effect
[INFO] [2021-06-13 21:02:44,351] [7:140266826163968] - federated_scheduler.py[line:92]: stop job 202106132102371506761 success
[INFO] [2021-06-13 21:02:44,351] [7:140266826163968] - dag_scheduler.py[line:448]: stop job 202106132102371506761 with success successfully
[INFO] [2021-06-13 21:02:44,352] [7:140266826163968] - federated_scheduler.py[line:107]: try to clean job 202106132102371506761
[INFO] [2021-06-13 21:02:44,358] [7:140267417118464] - job_controller.py[line:379]: Job 202106132102371506761 on local 0 start to clean
[INFO] [2021-06-13 21:02:44,358] [7:140267417118464] - job_controller.py[line:382]: job 202106132102371506761 on local 0 clean done
[INFO] [2021-06-13 21:02:44,362] [7:140266826163968] - federated_scheduler.py[line:110]: clean job 202106132102371506761 success
[INFO] [2021-06-13 21:02:44,362] [7:140266826163968] - dag_scheduler.py[line:505]: Job 202106132102371506761 finished with success, done
[INFO] [2021-06-13 21:02:44,362] [7:140266826163968] - dag_scheduler.py[line:325]: finish scheduling job 202106132102371506761
[INFO] [2021-06-13 21:02:44,394] [7:140266826163968] - dag_scheduler.py[line:298]: scheduling job 202106132102371506761
[INFO] [2021-06-13 21:02:44,395] [7:140266826163968] - task_scheduler.py[line:28]: scheduling job 202106132102371506761 tasks
[INFO] [2021-06-13 21:02:44,412] [7:140266826163968] - task_scheduler.py[line:143]: job 202106132102371506761 task 202106132102371506761_upload_0 0 status is success, calculate by task party status list: ['success']
[INFO] [2021-06-13 21:02:44,412] [7:140266826163968] - task_scheduler.py[line:75]: finish scheduling job 202106132102371506761 tasks
[INFO] [2021-06-13 21:02:44,412] [7:140266826163968] - dag_scheduler.py[line:310]: Job 202106132102371506761 status is success, calculate by task status list: ['success']
[INFO] [2021-06-13 21:02:44,412] [7:140266826163968] - dag_scheduler.py[line:502]: Job 202106132102371506761 finished with success, do something...
[INFO] [2021-06-13 21:02:44,412] [7:140266826163968] - dag_scheduler.py[line:436]: request stop job 202106132102371506761 with success
[INFO] [2021-06-13 21:02:44,420] [7:140266826163968] - dag_scheduler.py[line:445]: request stop job 202106132102371506761 with success to all party
[INFO] [2021-06-13 21:02:44,420] [7:140266826163968] - federated_scheduler.py[line:88]: try to stop job 202106132102371506761
[INFO] [2021-06-13 21:02:44,432] [7:140267417118464] - job_utils.py[line:397]: try to stop job 202106132102371506761 task 202106132102371506761_upload_0 local 0 with success party status process pid:202
[INFO] [2021-06-13 21:02:44,433] [7:140267417118464] - job_utils.py[line:400]: can not found job 202106132102371506761 task 202106132102371506761_upload_0 local 0 with success party status process pid:202
[INFO] [2021-06-13 21:02:44,435] [7:140267417118464] - job_utils.py[line:424]: start run subprocess to stop task session 202106132102371506761_upload_0_0_local_0
[INFO] [2021-06-13 21:02:44,436] [7:140267417118464] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106132102371506761_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop
[INFO] [2021-06-13 21:02:44,441] [7:140267417118464] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106132102371506761_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop successfully, pid is 230
[INFO] [2021-06-13 21:02:44,442] [7:140267417118464] - task_controller.py[line:255]: job 202106132102371506761 task 202106132102371506761_upload_0 0 on local 0 process 202 kill success
[INFO] [2021-06-13 21:02:44,442] [7:140267417118464] - job_saver.py[line:71]: try to update job 202106132102371506761 task 202106132102371506761_upload_0 0 status
[INFO] [2021-06-13 21:02:44,448] [7:140267417118464] - job_saver.py[line:76]: update job 202106132102371506761 task 202106132102371506761_upload_0 0 status update does not take effect: {'job_id': '202106132102371506761', 'task_id': '202106132102371506761_upload_0', 'task_version': 0, 'role': 'local', 'party_id': '0', 'party_status': 'success'}
[INFO] [2021-06-13 21:02:44,454] [7:140267417118464] - job_saver.py[line:81]: try to update job 202106132102371506761 task 202106132102371506761_upload_0 0
[WARNING] [2021-06-13 21:02:44,465] [7:140267417118464] - job_saver.py[line:86]: job 202106132102371506761 task 202106132102371506761_upload_0 0 update does not take effect
[INFO] [2021-06-13 21:02:44,482] [7:140267417118464] - job_saver.py[line:45]: try to update job 202106132102371506761 status to success
[INFO] [2021-06-13 21:02:44,489] [7:140267417118464] - job_saver.py[line:56]: update job 202106132102371506761 status does not take effect
[INFO] [2021-06-13 21:02:44,518] [7:140266826163968] - federated_scheduler.py[line:92]: stop job 202106132102371506761 success
[INFO] [2021-06-13 21:02:44,518] [7:140266826163968] - dag_scheduler.py[line:448]: stop job 202106132102371506761 with success successfully
[INFO] [2021-06-13 21:02:44,518] [7:140266826163968] - federated_scheduler.py[line:107]: try to clean job 202106132102371506761
[INFO] [2021-06-13 21:02:44,534] [7:140267417118464] - job_controller.py[line:379]: Job 202106132102371506761 on local 0 start to clean
[INFO] [2021-06-13 21:02:44,538] [7:140267417118464] - job_controller.py[line:382]: job 202106132102371506761 on local 0 clean done
[INFO] [2021-06-13 21:02:44,569] [7:140266826163968] - federated_scheduler.py[line:110]: clean job 202106132102371506761 success
[INFO] [2021-06-13 21:02:44,569] [7:140266826163968] - dag_scheduler.py[line:505]: Job 202106132102371506761 finished with success, done
[INFO] [2021-06-13 21:02:44,569] [7:140266826163968] - dag_scheduler.py[line:325]: finish scheduling job 202106132102371506761
[INFO] [2021-06-13 21:02:44,882] [222:139912076470080] - session_utils.py[line:38]: start stop session 202106132102371506761_upload_0_0_local_0
[INFO] [2021-06-13 21:02:44,882] [222:139912076470080] - session_utils.py[line:47]: stop session 202106132102371506761_upload_0_0_local_0 success
[INFO] [2021-06-13 21:02:45,175] [226:140056047388480] - session_utils.py[line:38]: start stop session 202106132102371506761_upload_0_0_local_0
[INFO] [2021-06-13 21:02:45,176] [226:140056047388480] - session_utils.py[line:47]: stop session 202106132102371506761_upload_0_0_local_0 success
[INFO] [2021-06-13 21:02:45,305] [230:140644341737280] - session_utils.py[line:38]: start stop session 202106132102371506761_upload_0_0_local_0
[INFO] [2021-06-13 21:02:45,306] [230:140644341737280] - session_utils.py[line:47]: stop session 202106132102371506761_upload_0_0_local_0 success
[INFO] [2021-06-13 21:02:46,914] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:02:49,131] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:02:51,626] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:02:53,879] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:02:55,931] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:02:57,981] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:03:00,032] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:03:02,091] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:03:04,141] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:03:06,188] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:03:08,240] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:03:10,310] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:03:12,389] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:03:14,440] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:03:16,495] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:03:18,547] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:03:20,618] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:03:23,343] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:03:25,626] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:03:28,692] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:03:31,033] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:03:34,233] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:03:36,552] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:03:39,757] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:03:42,060] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:03:45,254] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:03:47,518] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:03:49,786] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:03:52,403] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:03:54,657] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:03:58,730] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:04:01,087] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:04:03,551] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:04:07,205] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:04:10,135] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:04:12,463] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:04:14,770] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:04:17,061] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:04:19,888] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:04:22,129] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:04:24,372] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:04:26,638] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:04:28,888] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:04:31,365] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:04:33,669] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:04:35,951] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:04:39,983] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:04:42,501] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:04:44,809] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:04:47,158] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:04:49,566] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:04:51,849] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:04:54,102] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:04:56,486] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:04:58,846] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:05:01,963] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:05:04,344] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:05:06,808] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:05:09,092] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:05:12,589] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:05:14,912] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:05:17,687] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:05:23,396] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:05:29,480] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:05:31,564] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:05:33,608] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:05:35,661] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:05:37,717] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:05:39,762] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:05:41,815] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:05:43,879] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:05:45,938] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:05:48,063] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:05:50,152] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:05:52,226] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:05:54,266] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:05:56,323] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:05:58,387] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:06:00,450] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:06:02,487] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:06:04,541] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:06:06,603] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:06:08,651] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:06:10,759] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:06:12,853] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:06:14,938] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:06:16,998] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:06:19,060] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:06:21,114] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:06:23,173] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:06:25,215] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:06:27,277] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:06:29,329] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:06:31,395] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:06:33,448] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:06:35,516] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:06:37,576] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:06:39,632] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:06:41,697] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:06:43,757] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:06:45,833] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:06:47,891] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:06:49,944] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:06:51,996] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:06:54,071] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:06:56,127] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:06:58,186] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:07:00,248] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:07:02,301] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:07:04,362] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:07:06,414] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:07:08,475] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:07:10,531] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:07:12,590] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:07:14,657] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:07:16,721] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:07:18,778] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:07:20,833] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:07:22,885] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:07:24,943] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:07:26,996] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:07:29,051] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:07:31,100] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:07:33,173] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:07:35,244] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:07:37,313] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:07:39,369] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:07:41,413] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:07:43,446] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
