[INFO] [2021-06-13 22:10:59,455] [7:140266442843904] - dag_scheduler.py[line:40]: submit job, job_id 2021061322105944175233, body {'job_dsl': {'components': {'upload_0': {'module': 'Upload'}}}, 'job_runtime_conf': {'initiator': {'role': 'local', 'party_id': 0}, 'job_parameters': {'common': {'work_mode': 0, 'backend': 0}}, 'role': {'local': [0]}, 'component_parameters': {'role': {'local': {'0': {'upload_0': {'head': 1, 'name': 'breast_hetero_host', 'partition': 16, 'namespace': 'experiment', 'file': '/fate/jobs/2021061322105944175233/fate_upload_tmp/breast_hetero_host.csv', 'destroy': True}}}}}, 'dsl_version': 2}}
[INFO] [2021-06-13 22:10:59,468] [7:140265872402176] - job_controller.py[line:52]: job parameters:{'job_type': 'train', 'work_mode': 0, 'backend': 0, 'computing_engine': 'STANDALONE', 'federation_engine': 'STANDALONE', 'storage_engine': 'STANDALONE', 'engines_address': {}, 'federated_mode': 'SINGLE', 'task_parallelism': 1, 'computing_partitions': 4, 'federated_status_collect_type': 'PULL', 'model_id': 'local-0#model', 'model_version': '2021061322105944175233', 'eggroll_run': {}, 'spark_run': {}, 'rabbitmq_run': {}, 'pulsar_run': {}, 'adaptation_parameters': {'task_nodes': 1, 'task_cores_per_node': 4, 'task_memory_per_node': 0, 'request_task_cores': 4, 'if_initiator_baseline': True}}
[INFO] [2021-06-13 22:10:59,530] [7:140266442843904] - dag_scheduler.py[line:122]: submit job successfully, job id is 2021061322105944175233, model id is local-0#model
[INFO] [2021-06-13 22:11:01,320] [7:140266826163968] - federated_scheduler.py[line:39]: try to apply job 2021061322105944175233 resource
[INFO] [2021-06-13 22:11:01,348] [7:140266442843904] - resource_manager.py[line:176]: apply job 2021061322105944175233 resource(cores 4 memory 0) on local 0 successfully, remaining cores: 16 remaining memory: 0
[INFO] [2021-06-13 22:11:01,354] [7:140266826163968] - federated_scheduler.py[line:42]: apply job 2021061322105944175233 resource successfully
[INFO] [2021-06-13 22:11:01,354] [7:140266826163968] - dag_scheduler.py[line:279]: try to start job 2021061322105944175233 on initiator local 0
[INFO] [2021-06-13 22:11:01,370] [7:140266442843904] - job_controller.py[line:261]: try to start job 2021061322105944175233 on local 0
[INFO] [2021-06-13 22:11:01,370] [7:140266442843904] - job_saver.py[line:45]: try to update job 2021061322105944175233 status to running
[INFO] [2021-06-13 22:11:01,392] [7:140266442843904] - job_saver.py[line:48]: update job 2021061322105944175233 status successfully
[INFO] [2021-06-13 22:11:01,393] [7:140266442843904] - job_saver.py[line:61]: try to update job 2021061322105944175233
[INFO] [2021-06-13 22:11:01,414] [7:140266442843904] - job_saver.py[line:64]: job 2021061322105944175233 update successfully: {'job_id': '2021061322105944175233', 'role': 'local', 'party_id': 0, 'status': 'running', 'start_time': 1623622261370}
[INFO] [2021-06-13 22:11:01,414] [7:140266442843904] - job_controller.py[line:275]: start job 2021061322105944175233 on local 0 successfully
[INFO] [2021-06-13 22:11:01,419] [7:140266826163968] - dag_scheduler.py[line:292]: start job 2021061322105944175233 on initiator local 0
[INFO] [2021-06-13 22:11:01,431] [7:140266826163968] - dag_scheduler.py[line:247]: reset job 2021061322105944175233 ready signal True
[INFO] [2021-06-13 22:11:01,441] [7:140266826163968] - dag_scheduler.py[line:298]: scheduling job 2021061322105944175233
[INFO] [2021-06-13 22:11:01,443] [7:140266826163968] - task_scheduler.py[line:28]: scheduling job 2021061322105944175233 tasks
[INFO] [2021-06-13 22:11:01,464] [7:140266826163968] - task_scheduler.py[line:143]: job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status is waiting, calculate by task party status list: ['waiting']
[INFO] [2021-06-13 22:11:01,464] [7:140266826163968] - task_scheduler.py[line:80]: try to start job 2021061322105944175233 task 2021061322105944175233_upload_0 0 on local 0
[INFO] [2021-06-13 22:11:01,481] [7:140266826163968] - resource_manager.py[line:286]: task 2021061322105944175233_upload_0 0 apply resource successfully
[INFO] [2021-06-13 22:11:01,481] [7:140266826163968] - job_saver.py[line:71]: try to update job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status
[INFO] [2021-06-13 22:11:01,497] [7:140266826163968] - job_saver.py[line:74]: update job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status successfully: {'job_id': '2021061322105944175233', 'task_id': '2021061322105944175233_upload_0', 'task_version': 0, 'role': 'local', 'party_id': '0', 'status': 'running'}
[INFO] [2021-06-13 22:11:01,498] [7:140266826163968] - task_scheduler.py[line:93]: start job 2021061322105944175233 task 2021061322105944175233_upload_0 0 on local 0
[INFO] [2021-06-13 22:11:01,498] [7:140266826163968] - federated_scheduler.py[line:192]: job 2021061322105944175233 task 2021061322105944175233_upload_0 0 is running, sync to all party
[INFO] [2021-06-13 22:11:01,506] [7:140266442843904] - job_saver.py[line:71]: try to update job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status
[INFO] [2021-06-13 22:11:01,514] [7:140266442843904] - job_saver.py[line:76]: update job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status update does not take effect: {'job_id': '2021061322105944175233', 'task_id': '2021061322105944175233_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'status': 'running'}
[WARNING] [2021-06-13 22:11:01,527] [7:140266826163968] - federated_scheduler.py[line:260]: an error occurred while status/running the task to role local party 0: 
update task status failed
[INFO] [2021-06-13 22:11:01,527] [7:140266826163968] - federated_scheduler.py[line:197]: sync job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status running to all party failed: 
{'local': {0: {'retcode': 103, 'retmsg': 'update task status failed'}}}
[INFO] [2021-06-13 22:11:01,542] [7:140266442843904] - task_controller.py[line:71]: try to start job 2021061322105944175233 task 2021061322105944175233_upload_0 0 on local 0 executor subprocess
[INFO] [2021-06-13 22:11:01,548] [7:140266442843904] - task_controller.py[line:90]: use computing engine STANDALONE
[INFO] [2021-06-13 22:11:01,548] [7:140266442843904] - task_controller.py[line:145]: job 2021061322105944175233 task 2021061322105944175233_upload_0 0 on local 0 executor subprocess is ready
[INFO] [2021-06-13 22:11:01,548] [7:140266442843904] - job_utils.py[line:310]: start process command: /usr/local/bin/python /fate/python/fate_flow/operation/task_executor.py -j 2021061322105944175233 -n upload_0 -t 2021061322105944175233_upload_0 -v 0 -r local -p 0 -c /fate/jobs/2021061322105944175233/local/0/upload_0/2021061322105944175233_upload_0/0/task_parameters.json --run_ip 127.0.0.1 --job_server 127.0.0.1:9380
[INFO] [2021-06-13 22:11:01,556] [7:140266442843904] - job_utils.py[line:334]: start process command: /usr/local/bin/python /fate/python/fate_flow/operation/task_executor.py -j 2021061322105944175233 -n upload_0 -t 2021061322105944175233_upload_0 -v 0 -r local -p 0 -c /fate/jobs/2021061322105944175233/local/0/upload_0/2021061322105944175233_upload_0/0/task_parameters.json --run_ip 127.0.0.1 --job_server 127.0.0.1:9380 successfully, pid is 2300
[INFO] [2021-06-13 22:11:01,557] [7:140266442843904] - job_saver.py[line:81]: try to update job 2021061322105944175233 task 2021061322105944175233_upload_0 0
[INFO] [2021-06-13 22:11:01,575] [7:140266442843904] - job_saver.py[line:84]: job 2021061322105944175233 task 2021061322105944175233_upload_0 0 update successfully
[INFO] [2021-06-13 22:11:01,584] [7:140266442843904] - job_saver.py[line:71]: try to update job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status
[INFO] [2021-06-13 22:11:01,603] [7:140266442843904] - job_saver.py[line:74]: update job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status successfully: {'job_id': '2021061322105944175233', 'task_id': '2021061322105944175233_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'party_status': 'running', 'start_time': 1623622261557}
[INFO] [2021-06-13 22:11:01,611] [7:140266442843904] - task_controller.py[line:164]: job 2021061322105944175233 task 2021061322105944175233_upload_0 0 on local 0 executor subprocess start success
[INFO] [2021-06-13 22:11:01,617] [7:140266826163968] - task_scheduler.py[line:75]: finish scheduling job 2021061322105944175233 tasks
[INFO] [2021-06-13 22:11:01,618] [7:140266826163968] - dag_scheduler.py[line:310]: Job 2021061322105944175233 status is running, calculate by task status list: ['running']
[INFO] [2021-06-13 22:11:01,618] [7:140266826163968] - dag_scheduler.py[line:325]: finish scheduling job 2021061322105944175233
[INFO] [2021-06-13 22:11:03,505] [2300:140301080086336] - task_executor.py[line:56]: enter task process
[INFO] [2021-06-13 22:11:03,505] [2300:140301080086336] - task_executor.py[line:57]: Namespace(component_name='upload_0', config='/fate/jobs/2021061322105944175233/local/0/upload_0/2021061322105944175233_upload_0/0/task_parameters.json', job_id='2021061322105944175233', job_server='127.0.0.1:9380', party_id=0, role='local', run_ip='127.0.0.1', task_id='2021061322105944175233_upload_0', task_version=0)
[INFO] [2021-06-13 22:11:03,518] [7:140266442843904] - job_saver.py[line:81]: try to update job 2021061322105944175233 task 2021061322105944175233_upload_0 0
[INFO] [2021-06-13 22:11:03,536] [7:140266442843904] - job_saver.py[line:84]: job 2021061322105944175233 task 2021061322105944175233_upload_0 0 update successfully
[INFO] [2021-06-13 22:11:03,543] [7:140266442843904] - job_saver.py[line:71]: try to update job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status
[INFO] [2021-06-13 22:11:03,551] [7:140266442843904] - job_saver.py[line:76]: update job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status update does not take effect: {'job_id': '2021061322105944175233', 'component_name': 'upload_0', 'task_id': '2021061322105944175233_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'run_ip': '127.0.0.1', 'run_pid': 2300, 'party_status': 'running'}
[INFO] [2021-06-13 22:11:03,661] [7:140266826163968] - dag_scheduler.py[line:298]: scheduling job 2021061322105944175233
[INFO] [2021-06-13 22:11:03,664] [7:140266826163968] - task_scheduler.py[line:28]: scheduling job 2021061322105944175233 tasks
[INFO] [2021-06-13 22:11:03,704] [7:140266826163968] - job_saver.py[line:71]: try to update job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status
[INFO] [2021-06-13 22:11:03,712] [7:140266826163968] - job_saver.py[line:76]: update job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status update does not take effect: {'elapsed': None, 'end_time': None, 'job_id': '2021061322105944175233', 'party_id': '0', 'party_status': 'running', 'role': 'local', 'start_time': 1623622261557, 'status': 'running', 'task_id': '2021061322105944175233_upload_0', 'task_version': 0, 'update_time': 1623622259486}
[INFO] [2021-06-13 22:11:03,713] [7:140266826163968] - job_saver.py[line:81]: try to update job 2021061322105944175233 task 2021061322105944175233_upload_0 0
[INFO] [2021-06-13 22:11:03,731] [7:140266826163968] - job_saver.py[line:84]: job 2021061322105944175233 task 2021061322105944175233_upload_0 0 update successfully
[INFO] [2021-06-13 22:11:03,740] [7:140266826163968] - task_scheduler.py[line:143]: job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status is running, calculate by task party status list: ['running']
[INFO] [2021-06-13 22:11:03,740] [7:140266826163968] - task_scheduler.py[line:75]: finish scheduling job 2021061322105944175233 tasks
[INFO] [2021-06-13 22:11:03,740] [7:140266826163968] - dag_scheduler.py[line:310]: Job 2021061322105944175233 status is running, calculate by task status list: ['running']
[INFO] [2021-06-13 22:11:03,740] [7:140266826163968] - dag_scheduler.py[line:325]: finish scheduling job 2021061322105944175233
[INFO] [2021-06-13 22:11:04,167] [7:140266442843904] - job_saver.py[line:61]: try to update job 2021061322105944175233
[INFO] [2021-06-13 22:11:04,188] [7:140266442843904] - job_saver.py[line:64]: job 2021061322105944175233 update successfully: {'progress': 100.0, 'job_id': '2021061322105944175233', 'role': 'local', 'party_id': '0'}
[INFO] [2021-06-13 22:11:04,377] [7:140266442843904] - job_tracker.py[line:74]: save job 2021061322105944175233 component upload_0 on local 0 upload data_access metric data
[INFO] [2021-06-13 22:11:04,407] [7:140266442843904] - job_tracker.py[line:97]: save job 2021061322105944175233 component upload_0 on local 0 upload data_access metric meta
[INFO] [2021-06-13 22:11:04,467] [2300:140301080086336] - job_tracker.py[line:159]: task id 2021061322105944175233_upload_0 output data table is none
[INFO] [2021-06-13 22:11:04,474] [7:140266442843904] - job_saver.py[line:81]: try to update job 2021061322105944175233 task 2021061322105944175233_upload_0 0
[INFO] [2021-06-13 22:11:04,494] [7:140266442843904] - job_saver.py[line:84]: job 2021061322105944175233 task 2021061322105944175233_upload_0 0 update successfully
[INFO] [2021-06-13 22:11:04,502] [7:140266442843904] - job_saver.py[line:71]: try to update job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status
[INFO] [2021-06-13 22:11:04,522] [7:140266442843904] - job_saver.py[line:74]: update job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status successfully: {'job_id': '2021061322105944175233', 'component_name': 'upload_0', 'task_id': '2021061322105944175233_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'run_ip': '127.0.0.1', 'run_pid': 2300, 'party_status': 'success', 'end_time': 1623622264467, 'elapsed': 961}
[INFO] [2021-06-13 22:11:04,542] [7:140266442843904] - job_saver.py[line:81]: try to update job 2021061322105944175233 task 2021061322105944175233_upload_0 0
[INFO] [2021-06-13 22:11:04,566] [7:140266442843904] - job_saver.py[line:84]: job 2021061322105944175233 task 2021061322105944175233_upload_0 0 update successfully
[INFO] [2021-06-13 22:11:04,572] [7:140266442843904] - job_saver.py[line:71]: try to update job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status
[INFO] [2021-06-13 22:11:04,577] [7:140266442843904] - job_saver.py[line:76]: update job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status update does not take effect: {'job_id': '2021061322105944175233', 'component_name': 'upload_0', 'task_id': '2021061322105944175233_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'run_ip': '127.0.0.1', 'run_pid': 2300, 'party_status': 'success', 'end_time': 1623622264467, 'elapsed': 961}
[INFO] [2021-06-13 22:11:05,789] [7:140266826163968] - dag_scheduler.py[line:298]: scheduling job 2021061322105944175233
[INFO] [2021-06-13 22:11:05,791] [7:140266826163968] - task_scheduler.py[line:28]: scheduling job 2021061322105944175233 tasks
[INFO] [2021-06-13 22:11:05,822] [7:140266826163968] - job_saver.py[line:71]: try to update job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status
[INFO] [2021-06-13 22:11:05,829] [7:140266826163968] - job_saver.py[line:76]: update job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status update does not take effect: {'elapsed': 961, 'end_time': 1623622264467, 'job_id': '2021061322105944175233', 'party_id': '0', 'party_status': 'success', 'role': 'local', 'start_time': 1623622261557, 'status': 'running', 'task_id': '2021061322105944175233_upload_0', 'task_version': 0, 'update_time': 1623622259486}
[INFO] [2021-06-13 22:11:05,829] [7:140266826163968] - job_saver.py[line:81]: try to update job 2021061322105944175233 task 2021061322105944175233_upload_0 0
[INFO] [2021-06-13 22:11:05,854] [7:140266826163968] - job_saver.py[line:84]: job 2021061322105944175233 task 2021061322105944175233_upload_0 0 update successfully
[INFO] [2021-06-13 22:11:05,860] [7:140266826163968] - task_scheduler.py[line:143]: job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status is success, calculate by task party status list: ['success']
[INFO] [2021-06-13 22:11:05,861] [7:140266826163968] - federated_scheduler.py[line:192]: job 2021061322105944175233 task 2021061322105944175233_upload_0 0 is success, sync to all party
[INFO] [2021-06-13 22:11:05,868] [7:140266442843904] - job_saver.py[line:71]: try to update job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status
[INFO] [2021-06-13 22:11:05,885] [7:140266442843904] - job_saver.py[line:74]: update job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status successfully: {'job_id': '2021061322105944175233', 'task_id': '2021061322105944175233_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'status': 'success'}
[INFO] [2021-06-13 22:11:05,904] [7:140266442843904] - resource_manager.py[line:286]: task 2021061322105944175233_upload_0 0 return resource successfully
[INFO] [2021-06-13 22:11:05,911] [7:140266442843904] - job_tracker.py[line:424]: clean task 2021061322105944175233_upload_0 0 on local 0
[ERROR] [2021-06-13 22:11:05,913] [7:140266442843904] - job_tracker.py[line:475]: namespace dir /fate/data/2021061322105944175233_upload_0_0_local_0 does not exist
Traceback (most recent call last):
  File "/fate/python/fate_flow/operation/job_tracker.py", line 437, in clean_task
    sess.computing.cleanup(namespace=computing_temp_namespace, name="*")
  File "/fate/python/fate_arch/computing/standalone/_csession.py", line 73, in cleanup
    return self._session.cleanup(name=name, namespace=namespace)
  File "/fate/python/fate_arch/_standalone.py", line 383, in cleanup
    raise EnvironmentError(f"namespace dir {namespace_dir} does not exist")
OSError: namespace dir /fate/data/2021061322105944175233_upload_0_0_local_0 does not exist
[INFO] [2021-06-13 22:11:05,926] [7:140266826163968] - federated_scheduler.py[line:195]: sync job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status success to all party success
[INFO] [2021-06-13 22:11:05,926] [7:140266826163968] - federated_scheduler.py[line:202]: try to stop job 2021061322105944175233 task 2021061322105944175233_upload_0 0
[INFO] [2021-06-13 22:11:05,941] [7:140266442843904] - job_utils.py[line:397]: try to stop job 2021061322105944175233 task 2021061322105944175233_upload_0 local 0 with success party status process pid:2300
[INFO] [2021-06-13 22:11:05,941] [7:140266442843904] - job_utils.py[line:400]: can not found job 2021061322105944175233 task 2021061322105944175233_upload_0 local 0 with success party status process pid:2300
[INFO] [2021-06-13 22:11:05,946] [7:140266442843904] - job_utils.py[line:424]: start run subprocess to stop task session 2021061322105944175233_upload_0_0_local_0
[INFO] [2021-06-13 22:11:05,946] [7:140266442843904] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061322105944175233_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop
[INFO] [2021-06-13 22:11:05,954] [7:140266442843904] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061322105944175233_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop successfully, pid is 2320
[INFO] [2021-06-13 22:11:05,955] [7:140266442843904] - task_controller.py[line:255]: job 2021061322105944175233 task 2021061322105944175233_upload_0 0 on local 0 process 2300 kill success
[INFO] [2021-06-13 22:11:05,955] [7:140266442843904] - job_saver.py[line:71]: try to update job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status
[INFO] [2021-06-13 22:11:05,963] [7:140266442843904] - job_saver.py[line:76]: update job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status update does not take effect: {'job_id': '2021061322105944175233', 'task_id': '2021061322105944175233_upload_0', 'task_version': 0, 'role': 'local', 'party_id': '0', 'party_status': 'success'}
[INFO] [2021-06-13 22:11:05,971] [7:140266442843904] - job_saver.py[line:81]: try to update job 2021061322105944175233 task 2021061322105944175233_upload_0 0
[WARNING] [2021-06-13 22:11:05,979] [7:140266442843904] - job_saver.py[line:86]: job 2021061322105944175233 task 2021061322105944175233_upload_0 0 update does not take effect
[INFO] [2021-06-13 22:11:05,991] [7:140266826163968] - federated_scheduler.py[line:206]: stop job 2021061322105944175233 task 2021061322105944175233_upload_0 0 success
[INFO] [2021-06-13 22:11:05,991] [7:140266826163968] - task_scheduler.py[line:75]: finish scheduling job 2021061322105944175233 tasks
[INFO] [2021-06-13 22:11:05,991] [7:140266826163968] - dag_scheduler.py[line:310]: Job 2021061322105944175233 status is success, calculate by task status list: ['success']
[INFO] [2021-06-13 22:11:05,991] [7:140266826163968] - federated_scheduler.py[line:78]: try to save job 2021061322105944175233 pipelined model
[INFO] [2021-06-13 22:11:05,998] [7:140266442843904] - job_controller.py[line:331]: job 2021061322105944175233 on local 0 start to save pipeline
[INFO] [2021-06-13 22:11:06,014] [7:140266442843904] - job_controller.py[line:374]: job 2021061322105944175233 on local 0 save pipeline successfully
[INFO] [2021-06-13 22:11:06,019] [7:140266826163968] - federated_scheduler.py[line:81]: save job 2021061322105944175233 pipelined model success
[INFO] [2021-06-13 22:11:06,019] [7:140266826163968] - federated_scheduler.py[line:68]: job 2021061322105944175233 is success, sync to all party
[INFO] [2021-06-13 22:11:06,024] [7:140266442843904] - job_saver.py[line:45]: try to update job 2021061322105944175233 status to success
[INFO] [2021-06-13 22:11:06,041] [7:140266442843904] - job_saver.py[line:48]: update job 2021061322105944175233 status successfully
[INFO] [2021-06-13 22:11:06,074] [7:140266442843904] - resource_manager.py[line:176]: return job 2021061322105944175233 resource(cores 4 memory 0) on local 0 successfully, remaining cores: 20 remaining memory: 0
[INFO] [2021-06-13 22:11:06,077] [7:140266826163968] - federated_scheduler.py[line:71]: sync job 2021061322105944175233 status success to all party success
[INFO] [2021-06-13 22:11:06,084] [7:140266826163968] - job_saver.py[line:45]: try to update job 2021061322105944175233 status to success
[INFO] [2021-06-13 22:11:06,092] [7:140266826163968] - job_saver.py[line:56]: update job 2021061322105944175233 status does not take effect
[INFO] [2021-06-13 22:11:06,092] [7:140266826163968] - job_saver.py[line:61]: try to update job 2021061322105944175233
[WARNING] [2021-06-13 22:11:06,103] [7:140266826163968] - job_saver.py[line:66]: job 2021061322105944175233 update does not take effect: {'job_id': '2021061322105944175233', 'role': 'local', 'party_id': '0', 'status': 'success'}
[INFO] [2021-06-13 22:11:06,103] [7:140266826163968] - dag_scheduler.py[line:502]: Job 2021061322105944175233 finished with success, do something...
[INFO] [2021-06-13 22:11:06,103] [7:140266826163968] - dag_scheduler.py[line:436]: request stop job 2021061322105944175233 with success
[INFO] [2021-06-13 22:11:06,110] [7:140266826163968] - dag_scheduler.py[line:445]: request stop job 2021061322105944175233 with success to all party
[INFO] [2021-06-13 22:11:06,111] [7:140266826163968] - federated_scheduler.py[line:88]: try to stop job 2021061322105944175233
[INFO] [2021-06-13 22:11:06,126] [7:140266442843904] - job_utils.py[line:397]: try to stop job 2021061322105944175233 task 2021061322105944175233_upload_0 local 0 with success party status process pid:2300
[INFO] [2021-06-13 22:11:06,126] [7:140266442843904] - job_utils.py[line:400]: can not found job 2021061322105944175233 task 2021061322105944175233_upload_0 local 0 with success party status process pid:2300
[INFO] [2021-06-13 22:11:06,129] [7:140266442843904] - job_utils.py[line:424]: start run subprocess to stop task session 2021061322105944175233_upload_0_0_local_0
[INFO] [2021-06-13 22:11:06,130] [7:140266442843904] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061322105944175233_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop
[INFO] [2021-06-13 22:11:06,137] [7:140266442843904] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061322105944175233_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop successfully, pid is 2324
[INFO] [2021-06-13 22:11:06,138] [7:140266442843904] - task_controller.py[line:255]: job 2021061322105944175233 task 2021061322105944175233_upload_0 0 on local 0 process 2300 kill success
[INFO] [2021-06-13 22:11:06,138] [7:140266442843904] - job_saver.py[line:71]: try to update job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status
[INFO] [2021-06-13 22:11:06,143] [7:140266442843904] - job_saver.py[line:76]: update job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status update does not take effect: {'job_id': '2021061322105944175233', 'task_id': '2021061322105944175233_upload_0', 'task_version': 0, 'role': 'local', 'party_id': '0', 'party_status': 'success'}
[INFO] [2021-06-13 22:11:06,147] [7:140266442843904] - job_saver.py[line:81]: try to update job 2021061322105944175233 task 2021061322105944175233_upload_0 0
[WARNING] [2021-06-13 22:11:06,154] [7:140266442843904] - job_saver.py[line:86]: job 2021061322105944175233 task 2021061322105944175233_upload_0 0 update does not take effect
[INFO] [2021-06-13 22:11:06,163] [7:140266442843904] - job_saver.py[line:45]: try to update job 2021061322105944175233 status to success
[INFO] [2021-06-13 22:11:06,174] [7:140266442843904] - job_saver.py[line:56]: update job 2021061322105944175233 status does not take effect
[INFO] [2021-06-13 22:11:06,180] [7:140266826163968] - federated_scheduler.py[line:92]: stop job 2021061322105944175233 success
[INFO] [2021-06-13 22:11:06,180] [7:140266826163968] - dag_scheduler.py[line:448]: stop job 2021061322105944175233 with success successfully
[INFO] [2021-06-13 22:11:06,180] [7:140266826163968] - federated_scheduler.py[line:107]: try to clean job 2021061322105944175233
[INFO] [2021-06-13 22:11:06,184] [7:140266442843904] - job_controller.py[line:379]: Job 2021061322105944175233 on local 0 start to clean
[INFO] [2021-06-13 22:11:06,184] [7:140266442843904] - job_controller.py[line:382]: job 2021061322105944175233 on local 0 clean done
[INFO] [2021-06-13 22:11:06,189] [7:140266826163968] - federated_scheduler.py[line:110]: clean job 2021061322105944175233 success
[INFO] [2021-06-13 22:11:06,190] [7:140266826163968] - dag_scheduler.py[line:505]: Job 2021061322105944175233 finished with success, done
[INFO] [2021-06-13 22:11:06,190] [7:140266826163968] - dag_scheduler.py[line:325]: finish scheduling job 2021061322105944175233
[INFO] [2021-06-13 22:11:06,222] [7:140266826163968] - dag_scheduler.py[line:298]: scheduling job 2021061322105944175233
[INFO] [2021-06-13 22:11:06,224] [7:140266826163968] - task_scheduler.py[line:28]: scheduling job 2021061322105944175233 tasks
[INFO] [2021-06-13 22:11:06,241] [7:140266826163968] - task_scheduler.py[line:143]: job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status is success, calculate by task party status list: ['success']
[INFO] [2021-06-13 22:11:06,242] [7:140266826163968] - task_scheduler.py[line:75]: finish scheduling job 2021061322105944175233 tasks
[INFO] [2021-06-13 22:11:06,242] [7:140266826163968] - dag_scheduler.py[line:310]: Job 2021061322105944175233 status is success, calculate by task status list: ['success']
[INFO] [2021-06-13 22:11:06,243] [7:140266826163968] - dag_scheduler.py[line:502]: Job 2021061322105944175233 finished with success, do something...
[INFO] [2021-06-13 22:11:06,243] [7:140266826163968] - dag_scheduler.py[line:436]: request stop job 2021061322105944175233 with success
[INFO] [2021-06-13 22:11:06,252] [7:140266826163968] - dag_scheduler.py[line:445]: request stop job 2021061322105944175233 with success to all party
[INFO] [2021-06-13 22:11:06,252] [7:140266826163968] - federated_scheduler.py[line:88]: try to stop job 2021061322105944175233
[INFO] [2021-06-13 22:11:06,267] [7:140266442843904] - job_utils.py[line:397]: try to stop job 2021061322105944175233 task 2021061322105944175233_upload_0 local 0 with success party status process pid:2300
[INFO] [2021-06-13 22:11:06,267] [7:140266442843904] - job_utils.py[line:400]: can not found job 2021061322105944175233 task 2021061322105944175233_upload_0 local 0 with success party status process pid:2300
[INFO] [2021-06-13 22:11:06,270] [7:140266442843904] - job_utils.py[line:424]: start run subprocess to stop task session 2021061322105944175233_upload_0_0_local_0
[INFO] [2021-06-13 22:11:06,271] [7:140266442843904] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061322105944175233_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop
[INFO] [2021-06-13 22:11:06,279] [7:140266442843904] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061322105944175233_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop successfully, pid is 2328
[INFO] [2021-06-13 22:11:06,280] [7:140266442843904] - task_controller.py[line:255]: job 2021061322105944175233 task 2021061322105944175233_upload_0 0 on local 0 process 2300 kill success
[INFO] [2021-06-13 22:11:06,280] [7:140266442843904] - job_saver.py[line:71]: try to update job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status
[INFO] [2021-06-13 22:11:06,286] [7:140266442843904] - job_saver.py[line:76]: update job 2021061322105944175233 task 2021061322105944175233_upload_0 0 status update does not take effect: {'job_id': '2021061322105944175233', 'task_id': '2021061322105944175233_upload_0', 'task_version': 0, 'role': 'local', 'party_id': '0', 'party_status': 'success'}
[INFO] [2021-06-13 22:11:06,295] [7:140266442843904] - job_saver.py[line:81]: try to update job 2021061322105944175233 task 2021061322105944175233_upload_0 0
[WARNING] [2021-06-13 22:11:06,304] [7:140266442843904] - job_saver.py[line:86]: job 2021061322105944175233 task 2021061322105944175233_upload_0 0 update does not take effect
[INFO] [2021-06-13 22:11:06,310] [7:140266442843904] - job_saver.py[line:45]: try to update job 2021061322105944175233 status to success
[INFO] [2021-06-13 22:11:06,317] [7:140266442843904] - job_saver.py[line:56]: update job 2021061322105944175233 status does not take effect
[INFO] [2021-06-13 22:11:06,331] [7:140266826163968] - federated_scheduler.py[line:92]: stop job 2021061322105944175233 success
[INFO] [2021-06-13 22:11:06,331] [7:140266826163968] - dag_scheduler.py[line:448]: stop job 2021061322105944175233 with success successfully
[INFO] [2021-06-13 22:11:06,332] [7:140266826163968] - federated_scheduler.py[line:107]: try to clean job 2021061322105944175233
[INFO] [2021-06-13 22:11:06,355] [7:140266442843904] - job_controller.py[line:379]: Job 2021061322105944175233 on local 0 start to clean
[INFO] [2021-06-13 22:11:06,355] [7:140266442843904] - job_controller.py[line:382]: job 2021061322105944175233 on local 0 clean done
[INFO] [2021-06-13 22:11:06,361] [7:140266826163968] - federated_scheduler.py[line:110]: clean job 2021061322105944175233 success
[INFO] [2021-06-13 22:11:06,361] [7:140266826163968] - dag_scheduler.py[line:505]: Job 2021061322105944175233 finished with success, done
[INFO] [2021-06-13 22:11:06,361] [7:140266826163968] - dag_scheduler.py[line:325]: finish scheduling job 2021061322105944175233
[INFO] [2021-06-13 22:11:06,761] [2320:140012122937152] - session_utils.py[line:38]: start stop session 2021061322105944175233_upload_0_0_local_0
[INFO] [2021-06-13 22:11:06,761] [2320:140012122937152] - session_utils.py[line:47]: stop session 2021061322105944175233_upload_0_0_local_0 success
[INFO] [2021-06-13 22:11:07,119] [2324:139732179601216] - session_utils.py[line:38]: start stop session 2021061322105944175233_upload_0_0_local_0
[INFO] [2021-06-13 22:11:07,119] [2324:139732179601216] - session_utils.py[line:47]: stop session 2021061322105944175233_upload_0_0_local_0 success
[INFO] [2021-06-13 22:11:07,227] [2328:140225517479744] - session_utils.py[line:38]: start stop session 2021061322105944175233_upload_0_0_local_0
[INFO] [2021-06-13 22:11:07,227] [2328:140225517479744] - session_utils.py[line:47]: stop session 2021061322105944175233_upload_0_0_local_0 success
[INFO] [2021-06-13 22:11:08,412] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:11:10,457] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:11:12,504] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:11:14,558] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:11:16,601] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:11:18,651] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:11:20,699] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:11:22,737] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:11:24,800] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:11:26,845] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:11:28,884] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:11:30,931] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:11:32,988] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:11:35,033] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:11:37,079] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:11:39,130] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:11:41,187] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:11:43,237] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:11:45,283] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:11:47,325] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:11:49,367] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:11:51,419] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:11:53,468] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:11:55,515] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:11:57,570] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:11:59,645] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:12:01,693] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:12:03,738] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:12:05,785] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:12:07,830] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:12:09,890] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:12:11,935] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:12:13,979] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:12:16,020] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:12:18,066] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:12:20,143] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:12:22,193] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:12:24,245] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:12:26,271] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:12:28,318] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:12:30,364] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:12:32,425] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:12:34,471] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:12:36,520] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:12:38,565] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:12:40,610] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:12:42,654] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:12:44,700] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:12:46,751] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:12:48,796] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:12:50,862] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:12:52,907] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:12:54,950] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:12:56,997] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:12:59,042] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:13:01,090] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:13:03,142] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:13:05,187] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:13:07,242] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:13:09,301] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:13:11,351] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:13:13,395] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:13:15,470] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:13:17,520] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:13:19,565] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:13:21,612] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:13:23,656] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:13:25,684] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:13:27,733] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:13:29,784] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:13:31,829] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:13:33,879] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:13:35,921] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:13:37,975] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:13:40,023] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:13:42,067] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:13:44,112] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:13:46,157] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:13:48,200] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:13:50,243] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:13:52,288] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:13:54,352] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:13:56,388] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:13:58,439] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:00,483] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:02,552] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:04,599] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:06,648] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:08,698] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:10,740] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:12,792] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:14,847] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:16,895] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:18,948] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:21,007] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:23,044] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:25,094] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:27,147] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:29,203] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:31,252] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:33,297] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:35,335] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:37,374] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:39,417] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:41,462] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:43,507] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:45,552] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:47,596] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:49,645] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:51,682] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:53,726] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:55,770] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:57,814] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:14:59,852] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:15:01,910] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:15:03,954] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:15:05,992] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:15:08,062] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:15:10,105] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:15:12,175] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:15:14,220] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:15:16,294] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:15:18,345] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:15:20,396] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:15:22,441] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:15:24,474] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:15:26,520] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:15:28,583] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:15:30,628] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:15:32,675] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:15:34,732] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:15:36,776] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:15:38,829] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:15:40,875] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:15:42,919] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:15:44,964] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:15:47,008] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:15:49,075] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:15:51,133] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:15:53,193] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:15:55,223] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:15:57,269] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:15:59,298] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:16:01,351] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:16:03,404] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 22:16:05,462] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
