[INFO] [2021-06-15 21:17:07,720] [7:140198455301888] - dag_scheduler.py[line:40]: submit job, job_id 202106152117074319479, body {'job_dsl': {'components': {'upload_0': {'module': 'Upload'}}}, 'job_runtime_conf': {'initiator': {'role': 'local', 'party_id': 0}, 'job_parameters': {'common': {'backend': 0, 'work_mode': 0}}, 'role': {'local': [0]}, 'component_parameters': {'role': {'local': {'0': {'upload_0': {'partition': 16, 'file': '/fate/jobs/202106152117074319479/fate_upload_tmp/default_credit_hetero_host.csv', 'namespace': 'experiment', 'head': 1, 'name': 'default_credit_hetero_host', 'destroy': True}}}}}, 'dsl_version': 2}}
[INFO] [2021-06-15 21:17:07,738] [7:140196188256000] - job_controller.py[line:52]: job parameters:{'job_type': 'train', 'work_mode': 0, 'backend': 0, 'computing_engine': 'STANDALONE', 'federation_engine': 'STANDALONE', 'storage_engine': 'STANDALONE', 'engines_address': {}, 'federated_mode': 'SINGLE', 'task_parallelism': 1, 'computing_partitions': 4, 'federated_status_collect_type': 'PULL', 'model_id': 'local-0#model', 'model_version': '202106152117074319479', 'eggroll_run': {}, 'spark_run': {}, 'rabbitmq_run': {}, 'pulsar_run': {}, 'adaptation_parameters': {'task_nodes': 1, 'task_cores_per_node': 4, 'task_memory_per_node': 0, 'request_task_cores': 4, 'if_initiator_baseline': True}}
[INFO] [2021-06-15 21:17:07,809] [7:140198455301888] - dag_scheduler.py[line:122]: submit job successfully, job id is 202106152117074319479, model id is local-0#model
[INFO] [2021-06-15 21:17:09,624] [7:140197562341120] - federated_scheduler.py[line:39]: try to apply job 202106152117074319479 resource
[INFO] [2021-06-15 21:17:09,650] [7:140198455301888] - resource_manager.py[line:176]: apply job 202106152117074319479 resource(cores 4 memory 0) on local 0 successfully, remaining cores: 16 remaining memory: 0
[INFO] [2021-06-15 21:17:09,654] [7:140197562341120] - federated_scheduler.py[line:42]: apply job 202106152117074319479 resource successfully
[INFO] [2021-06-15 21:17:09,654] [7:140197562341120] - dag_scheduler.py[line:279]: try to start job 202106152117074319479 on initiator local 0
[INFO] [2021-06-15 21:17:09,670] [7:140198455301888] - job_controller.py[line:261]: try to start job 202106152117074319479 on local 0
[INFO] [2021-06-15 21:17:09,671] [7:140198455301888] - job_saver.py[line:45]: try to update job 202106152117074319479 status to running
[INFO] [2021-06-15 21:17:09,692] [7:140198455301888] - job_saver.py[line:48]: update job 202106152117074319479 status successfully
[INFO] [2021-06-15 21:17:09,692] [7:140198455301888] - job_saver.py[line:61]: try to update job 202106152117074319479
[INFO] [2021-06-15 21:17:09,705] [7:140198455301888] - job_saver.py[line:64]: job 202106152117074319479 update successfully: {'job_id': '202106152117074319479', 'role': 'local', 'party_id': 0, 'status': 'running', 'start_time': 1623791829671}
[INFO] [2021-06-15 21:17:09,705] [7:140198455301888] - job_controller.py[line:275]: start job 202106152117074319479 on local 0 successfully
[INFO] [2021-06-15 21:17:09,709] [7:140197562341120] - dag_scheduler.py[line:292]: start job 202106152117074319479 on initiator local 0
[INFO] [2021-06-15 21:17:09,722] [7:140197562341120] - dag_scheduler.py[line:247]: reset job 202106152117074319479 ready signal True
[INFO] [2021-06-15 21:17:09,728] [7:140197562341120] - dag_scheduler.py[line:298]: scheduling job 202106152117074319479
[INFO] [2021-06-15 21:17:09,730] [7:140197562341120] - task_scheduler.py[line:28]: scheduling job 202106152117074319479 tasks
[INFO] [2021-06-15 21:17:09,744] [7:140197562341120] - task_scheduler.py[line:143]: job 202106152117074319479 task 202106152117074319479_upload_0 0 status is waiting, calculate by task party status list: ['waiting']
[INFO] [2021-06-15 21:17:09,744] [7:140197562341120] - task_scheduler.py[line:80]: try to start job 202106152117074319479 task 202106152117074319479_upload_0 0 on local 0
[INFO] [2021-06-15 21:17:09,757] [7:140197562341120] - resource_manager.py[line:286]: task 202106152117074319479_upload_0 0 apply resource successfully
[INFO] [2021-06-15 21:17:09,757] [7:140197562341120] - job_saver.py[line:71]: try to update job 202106152117074319479 task 202106152117074319479_upload_0 0 status
[INFO] [2021-06-15 21:17:09,769] [7:140197562341120] - job_saver.py[line:74]: update job 202106152117074319479 task 202106152117074319479_upload_0 0 status successfully: {'job_id': '202106152117074319479', 'task_id': '202106152117074319479_upload_0', 'task_version': 0, 'role': 'local', 'party_id': '0', 'status': 'running'}
[INFO] [2021-06-15 21:17:09,769] [7:140197562341120] - task_scheduler.py[line:93]: start job 202106152117074319479 task 202106152117074319479_upload_0 0 on local 0
[INFO] [2021-06-15 21:17:09,769] [7:140197562341120] - federated_scheduler.py[line:192]: job 202106152117074319479 task 202106152117074319479_upload_0 0 is running, sync to all party
[INFO] [2021-06-15 21:17:09,777] [7:140198455301888] - job_saver.py[line:71]: try to update job 202106152117074319479 task 202106152117074319479_upload_0 0 status
[INFO] [2021-06-15 21:17:09,786] [7:140198455301888] - job_saver.py[line:76]: update job 202106152117074319479 task 202106152117074319479_upload_0 0 status update does not take effect: {'job_id': '202106152117074319479', 'task_id': '202106152117074319479_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'status': 'running'}
[WARNING] [2021-06-15 21:17:09,797] [7:140197562341120] - federated_scheduler.py[line:260]: an error occurred while status/running the task to role local party 0: 
update task status failed
[INFO] [2021-06-15 21:17:09,798] [7:140197562341120] - federated_scheduler.py[line:197]: sync job 202106152117074319479 task 202106152117074319479_upload_0 0 status running to all party failed: 
{'local': {0: {'retcode': 103, 'retmsg': 'update task status failed'}}}
[INFO] [2021-06-15 21:17:09,811] [7:140198455301888] - task_controller.py[line:71]: try to start job 202106152117074319479 task 202106152117074319479_upload_0 0 on local 0 executor subprocess
[INFO] [2021-06-15 21:17:09,816] [7:140198455301888] - task_controller.py[line:90]: use computing engine STANDALONE
[INFO] [2021-06-15 21:17:09,816] [7:140198455301888] - task_controller.py[line:145]: job 202106152117074319479 task 202106152117074319479_upload_0 0 on local 0 executor subprocess is ready
[INFO] [2021-06-15 21:17:09,816] [7:140198455301888] - job_utils.py[line:310]: start process command: /usr/local/bin/python /fate/python/fate_flow/operation/task_executor.py -j 202106152117074319479 -n upload_0 -t 202106152117074319479_upload_0 -v 0 -r local -p 0 -c /fate/jobs/202106152117074319479/local/0/upload_0/202106152117074319479_upload_0/0/task_parameters.json --run_ip 127.0.0.1 --job_server 127.0.0.1:9380
[INFO] [2021-06-15 21:17:09,825] [7:140198455301888] - job_utils.py[line:334]: start process command: /usr/local/bin/python /fate/python/fate_flow/operation/task_executor.py -j 202106152117074319479 -n upload_0 -t 202106152117074319479_upload_0 -v 0 -r local -p 0 -c /fate/jobs/202106152117074319479/local/0/upload_0/202106152117074319479_upload_0/0/task_parameters.json --run_ip 127.0.0.1 --job_server 127.0.0.1:9380 successfully, pid is 1923
[INFO] [2021-06-15 21:17:09,826] [7:140198455301888] - job_saver.py[line:81]: try to update job 202106152117074319479 task 202106152117074319479_upload_0 0
[INFO] [2021-06-15 21:17:09,848] [7:140198455301888] - job_saver.py[line:84]: job 202106152117074319479 task 202106152117074319479_upload_0 0 update successfully
[INFO] [2021-06-15 21:17:09,855] [7:140198455301888] - job_saver.py[line:71]: try to update job 202106152117074319479 task 202106152117074319479_upload_0 0 status
[INFO] [2021-06-15 21:17:09,873] [7:140198455301888] - job_saver.py[line:74]: update job 202106152117074319479 task 202106152117074319479_upload_0 0 status successfully: {'job_id': '202106152117074319479', 'task_id': '202106152117074319479_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'party_status': 'running', 'start_time': 1623791829826}
[INFO] [2021-06-15 21:17:09,880] [7:140198455301888] - task_controller.py[line:164]: job 202106152117074319479 task 202106152117074319479_upload_0 0 on local 0 executor subprocess start success
[INFO] [2021-06-15 21:17:09,887] [7:140197562341120] - task_scheduler.py[line:75]: finish scheduling job 202106152117074319479 tasks
[INFO] [2021-06-15 21:17:09,887] [7:140197562341120] - dag_scheduler.py[line:310]: Job 202106152117074319479 status is running, calculate by task status list: ['running']
[INFO] [2021-06-15 21:17:09,888] [7:140197562341120] - dag_scheduler.py[line:325]: finish scheduling job 202106152117074319479
[INFO] [2021-06-15 21:17:11,864] [1923:139697816266560] - task_executor.py[line:56]: enter task process
[INFO] [2021-06-15 21:17:11,864] [1923:139697816266560] - task_executor.py[line:57]: Namespace(component_name='upload_0', config='/fate/jobs/202106152117074319479/local/0/upload_0/202106152117074319479_upload_0/0/task_parameters.json', job_id='202106152117074319479', job_server='127.0.0.1:9380', party_id=0, role='local', run_ip='127.0.0.1', task_id='202106152117074319479_upload_0', task_version=0)
[INFO] [2021-06-15 21:17:11,881] [7:140198455301888] - job_saver.py[line:81]: try to update job 202106152117074319479 task 202106152117074319479_upload_0 0
[INFO] [2021-06-15 21:17:11,908] [7:140198455301888] - job_saver.py[line:84]: job 202106152117074319479 task 202106152117074319479_upload_0 0 update successfully
[INFO] [2021-06-15 21:17:11,915] [7:140198455301888] - job_saver.py[line:71]: try to update job 202106152117074319479 task 202106152117074319479_upload_0 0 status
[INFO] [2021-06-15 21:17:11,927] [7:140198455301888] - job_saver.py[line:76]: update job 202106152117074319479 task 202106152117074319479_upload_0 0 status update does not take effect: {'job_id': '202106152117074319479', 'component_name': 'upload_0', 'task_id': '202106152117074319479_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'run_ip': '127.0.0.1', 'run_pid': 1923, 'party_status': 'running'}
[INFO] [2021-06-15 21:17:11,948] [7:140197562341120] - dag_scheduler.py[line:298]: scheduling job 202106152117074319479
[INFO] [2021-06-15 21:17:11,950] [7:140197562341120] - task_scheduler.py[line:28]: scheduling job 202106152117074319479 tasks
[INFO] [2021-06-15 21:17:11,983] [7:140197562341120] - job_saver.py[line:71]: try to update job 202106152117074319479 task 202106152117074319479_upload_0 0 status
[INFO] [2021-06-15 21:17:11,991] [7:140197562341120] - job_saver.py[line:76]: update job 202106152117074319479 task 202106152117074319479_upload_0 0 status update does not take effect: {'elapsed': None, 'end_time': None, 'job_id': '202106152117074319479', 'party_id': '0', 'party_status': 'running', 'role': 'local', 'start_time': 1623791829826, 'status': 'running', 'task_id': '202106152117074319479_upload_0', 'task_version': 0, 'update_time': 1623791827758}
[INFO] [2021-06-15 21:17:11,991] [7:140197562341120] - job_saver.py[line:81]: try to update job 202106152117074319479 task 202106152117074319479_upload_0 0
[INFO] [2021-06-15 21:17:12,010] [7:140197562341120] - job_saver.py[line:84]: job 202106152117074319479 task 202106152117074319479_upload_0 0 update successfully
[INFO] [2021-06-15 21:17:12,017] [7:140197562341120] - task_scheduler.py[line:143]: job 202106152117074319479 task 202106152117074319479_upload_0 0 status is running, calculate by task party status list: ['running']
[INFO] [2021-06-15 21:17:12,018] [7:140197562341120] - task_scheduler.py[line:75]: finish scheduling job 202106152117074319479 tasks
[INFO] [2021-06-15 21:17:12,018] [7:140197562341120] - dag_scheduler.py[line:310]: Job 202106152117074319479 status is running, calculate by task status list: ['running']
[INFO] [2021-06-15 21:17:12,018] [7:140197562341120] - dag_scheduler.py[line:325]: finish scheduling job 202106152117074319479
[INFO] [2021-06-15 21:17:12,827] [7:140198455301888] - job_saver.py[line:61]: try to update job 202106152117074319479
[INFO] [2021-06-15 21:17:12,858] [7:140198455301888] - job_saver.py[line:64]: job 202106152117074319479 update successfully: {'progress': 100.0, 'job_id': '202106152117074319479', 'role': 'local', 'party_id': '0'}
[INFO] [2021-06-15 21:17:13,550] [7:140198455301888] - job_tracker.py[line:74]: save job 202106152117074319479 component upload_0 on local 0 upload data_access metric data
[INFO] [2021-06-15 21:17:13,579] [7:140198455301888] - job_tracker.py[line:97]: save job 202106152117074319479 component upload_0 on local 0 upload data_access metric meta
[INFO] [2021-06-15 21:17:13,647] [1923:139697816266560] - job_tracker.py[line:159]: task id 202106152117074319479_upload_0 output data table is none
[INFO] [2021-06-15 21:17:13,653] [7:140198455301888] - job_saver.py[line:81]: try to update job 202106152117074319479 task 202106152117074319479_upload_0 0
[INFO] [2021-06-15 21:17:13,674] [7:140198455301888] - job_saver.py[line:84]: job 202106152117074319479 task 202106152117074319479_upload_0 0 update successfully
[INFO] [2021-06-15 21:17:13,681] [7:140198455301888] - job_saver.py[line:71]: try to update job 202106152117074319479 task 202106152117074319479_upload_0 0 status
[INFO] [2021-06-15 21:17:13,700] [7:140198455301888] - job_saver.py[line:74]: update job 202106152117074319479 task 202106152117074319479_upload_0 0 status successfully: {'job_id': '202106152117074319479', 'component_name': 'upload_0', 'task_id': '202106152117074319479_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'run_ip': '127.0.0.1', 'run_pid': 1923, 'party_status': 'success', 'end_time': 1623791833647, 'elapsed': 1783}
[INFO] [2021-06-15 21:17:13,719] [7:140198455301888] - job_saver.py[line:81]: try to update job 202106152117074319479 task 202106152117074319479_upload_0 0
[INFO] [2021-06-15 21:17:13,739] [7:140198455301888] - job_saver.py[line:84]: job 202106152117074319479 task 202106152117074319479_upload_0 0 update successfully
[INFO] [2021-06-15 21:17:13,748] [7:140198455301888] - job_saver.py[line:71]: try to update job 202106152117074319479 task 202106152117074319479_upload_0 0 status
[INFO] [2021-06-15 21:17:13,756] [7:140198455301888] - job_saver.py[line:76]: update job 202106152117074319479 task 202106152117074319479_upload_0 0 status update does not take effect: {'job_id': '202106152117074319479', 'component_name': 'upload_0', 'task_id': '202106152117074319479_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'run_ip': '127.0.0.1', 'run_pid': 1923, 'party_status': 'success', 'end_time': 1623791833647, 'elapsed': 1783}
[INFO] [2021-06-15 21:17:14,061] [7:140197562341120] - dag_scheduler.py[line:298]: scheduling job 202106152117074319479
[INFO] [2021-06-15 21:17:14,063] [7:140197562341120] - task_scheduler.py[line:28]: scheduling job 202106152117074319479 tasks
[INFO] [2021-06-15 21:17:14,097] [7:140197562341120] - job_saver.py[line:71]: try to update job 202106152117074319479 task 202106152117074319479_upload_0 0 status
[INFO] [2021-06-15 21:17:14,104] [7:140197562341120] - job_saver.py[line:76]: update job 202106152117074319479 task 202106152117074319479_upload_0 0 status update does not take effect: {'elapsed': 1783, 'end_time': 1623791833647, 'job_id': '202106152117074319479', 'party_id': '0', 'party_status': 'success', 'role': 'local', 'start_time': 1623791829826, 'status': 'running', 'task_id': '202106152117074319479_upload_0', 'task_version': 0, 'update_time': 1623791827758}
[INFO] [2021-06-15 21:17:14,105] [7:140197562341120] - job_saver.py[line:81]: try to update job 202106152117074319479 task 202106152117074319479_upload_0 0
[INFO] [2021-06-15 21:17:14,131] [7:140197562341120] - job_saver.py[line:84]: job 202106152117074319479 task 202106152117074319479_upload_0 0 update successfully
[INFO] [2021-06-15 21:17:14,137] [7:140197562341120] - task_scheduler.py[line:143]: job 202106152117074319479 task 202106152117074319479_upload_0 0 status is success, calculate by task party status list: ['success']
[INFO] [2021-06-15 21:17:14,138] [7:140197562341120] - federated_scheduler.py[line:192]: job 202106152117074319479 task 202106152117074319479_upload_0 0 is success, sync to all party
[INFO] [2021-06-15 21:17:14,146] [7:140198455301888] - job_saver.py[line:71]: try to update job 202106152117074319479 task 202106152117074319479_upload_0 0 status
[INFO] [2021-06-15 21:17:14,164] [7:140198455301888] - job_saver.py[line:74]: update job 202106152117074319479 task 202106152117074319479_upload_0 0 status successfully: {'job_id': '202106152117074319479', 'task_id': '202106152117074319479_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'status': 'success'}
[INFO] [2021-06-15 21:17:14,182] [7:140198455301888] - resource_manager.py[line:286]: task 202106152117074319479_upload_0 0 return resource successfully
[INFO] [2021-06-15 21:17:14,189] [7:140198455301888] - job_tracker.py[line:424]: clean task 202106152117074319479_upload_0 0 on local 0
[ERROR] [2021-06-15 21:17:14,192] [7:140198455301888] - job_tracker.py[line:475]: namespace dir /fate/data/202106152117074319479_upload_0_0_local_0 does not exist
Traceback (most recent call last):
  File "/fate/python/fate_flow/operation/job_tracker.py", line 437, in clean_task
    sess.computing.cleanup(namespace=computing_temp_namespace, name="*")
  File "/fate/python/fate_arch/computing/standalone/_csession.py", line 73, in cleanup
    return self._session.cleanup(name=name, namespace=namespace)
  File "/fate/python/fate_arch/_standalone.py", line 383, in cleanup
    raise EnvironmentError(f"namespace dir {namespace_dir} does not exist")
OSError: namespace dir /fate/data/202106152117074319479_upload_0_0_local_0 does not exist
[INFO] [2021-06-15 21:17:14,204] [7:140197562341120] - federated_scheduler.py[line:195]: sync job 202106152117074319479 task 202106152117074319479_upload_0 0 status success to all party success
[INFO] [2021-06-15 21:17:14,204] [7:140197562341120] - federated_scheduler.py[line:202]: try to stop job 202106152117074319479 task 202106152117074319479_upload_0 0
[INFO] [2021-06-15 21:17:14,219] [7:140198455301888] - job_utils.py[line:397]: try to stop job 202106152117074319479 task 202106152117074319479_upload_0 local 0 with success party status process pid:1923
[INFO] [2021-06-15 21:17:14,219] [7:140198455301888] - job_utils.py[line:400]: can not found job 202106152117074319479 task 202106152117074319479_upload_0 local 0 with success party status process pid:1923
[INFO] [2021-06-15 21:17:14,223] [7:140198455301888] - job_utils.py[line:424]: start run subprocess to stop task session 202106152117074319479_upload_0_0_local_0
[INFO] [2021-06-15 21:17:14,223] [7:140198455301888] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106152117074319479_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop
[INFO] [2021-06-15 21:17:14,232] [7:140198455301888] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106152117074319479_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop successfully, pid is 1943
[INFO] [2021-06-15 21:17:14,232] [7:140198455301888] - task_controller.py[line:255]: job 202106152117074319479 task 202106152117074319479_upload_0 0 on local 0 process 1923 kill success
[INFO] [2021-06-15 21:17:14,232] [7:140198455301888] - job_saver.py[line:71]: try to update job 202106152117074319479 task 202106152117074319479_upload_0 0 status
[INFO] [2021-06-15 21:17:14,239] [7:140198455301888] - job_saver.py[line:76]: update job 202106152117074319479 task 202106152117074319479_upload_0 0 status update does not take effect: {'job_id': '202106152117074319479', 'task_id': '202106152117074319479_upload_0', 'task_version': 0, 'role': 'local', 'party_id': '0', 'party_status': 'success'}
[INFO] [2021-06-15 21:17:14,245] [7:140198455301888] - job_saver.py[line:81]: try to update job 202106152117074319479 task 202106152117074319479_upload_0 0
[WARNING] [2021-06-15 21:17:14,251] [7:140198455301888] - job_saver.py[line:86]: job 202106152117074319479 task 202106152117074319479_upload_0 0 update does not take effect
[INFO] [2021-06-15 21:17:14,261] [7:140197562341120] - federated_scheduler.py[line:206]: stop job 202106152117074319479 task 202106152117074319479_upload_0 0 success
[INFO] [2021-06-15 21:17:14,261] [7:140197562341120] - task_scheduler.py[line:75]: finish scheduling job 202106152117074319479 tasks
[INFO] [2021-06-15 21:17:14,262] [7:140197562341120] - dag_scheduler.py[line:310]: Job 202106152117074319479 status is success, calculate by task status list: ['success']
[INFO] [2021-06-15 21:17:14,262] [7:140197562341120] - federated_scheduler.py[line:78]: try to save job 202106152117074319479 pipelined model
[INFO] [2021-06-15 21:17:14,268] [7:140198455301888] - job_controller.py[line:331]: job 202106152117074319479 on local 0 start to save pipeline
[INFO] [2021-06-15 21:17:14,282] [7:140198455301888] - job_controller.py[line:374]: job 202106152117074319479 on local 0 save pipeline successfully
[INFO] [2021-06-15 21:17:14,286] [7:140197562341120] - federated_scheduler.py[line:81]: save job 202106152117074319479 pipelined model success
[INFO] [2021-06-15 21:17:14,286] [7:140197562341120] - federated_scheduler.py[line:68]: job 202106152117074319479 is success, sync to all party
[INFO] [2021-06-15 21:17:14,291] [7:140198455301888] - job_saver.py[line:45]: try to update job 202106152117074319479 status to success
[INFO] [2021-06-15 21:17:14,311] [7:140198455301888] - job_saver.py[line:48]: update job 202106152117074319479 status successfully
[INFO] [2021-06-15 21:17:14,352] [7:140198455301888] - resource_manager.py[line:176]: return job 202106152117074319479 resource(cores 4 memory 0) on local 0 successfully, remaining cores: 20 remaining memory: 0
[INFO] [2021-06-15 21:17:14,356] [7:140197562341120] - federated_scheduler.py[line:71]: sync job 202106152117074319479 status success to all party success
[INFO] [2021-06-15 21:17:14,361] [7:140197562341120] - job_saver.py[line:45]: try to update job 202106152117074319479 status to success
[INFO] [2021-06-15 21:17:14,367] [7:140197562341120] - job_saver.py[line:56]: update job 202106152117074319479 status does not take effect
[INFO] [2021-06-15 21:17:14,368] [7:140197562341120] - job_saver.py[line:61]: try to update job 202106152117074319479
[WARNING] [2021-06-15 21:17:14,373] [7:140197562341120] - job_saver.py[line:66]: job 202106152117074319479 update does not take effect: {'job_id': '202106152117074319479', 'role': 'local', 'party_id': '0', 'status': 'success'}
[INFO] [2021-06-15 21:17:14,374] [7:140197562341120] - dag_scheduler.py[line:502]: Job 202106152117074319479 finished with success, do something...
[INFO] [2021-06-15 21:17:14,374] [7:140197562341120] - dag_scheduler.py[line:436]: request stop job 202106152117074319479 with success
[INFO] [2021-06-15 21:17:14,380] [7:140197562341120] - dag_scheduler.py[line:445]: request stop job 202106152117074319479 with success to all party
[INFO] [2021-06-15 21:17:14,380] [7:140197562341120] - federated_scheduler.py[line:88]: try to stop job 202106152117074319479
[INFO] [2021-06-15 21:17:14,398] [7:140198455301888] - job_utils.py[line:397]: try to stop job 202106152117074319479 task 202106152117074319479_upload_0 local 0 with success party status process pid:1923
[INFO] [2021-06-15 21:17:14,399] [7:140198455301888] - job_utils.py[line:400]: can not found job 202106152117074319479 task 202106152117074319479_upload_0 local 0 with success party status process pid:1923
[INFO] [2021-06-15 21:17:14,404] [7:140198455301888] - job_utils.py[line:424]: start run subprocess to stop task session 202106152117074319479_upload_0_0_local_0
[INFO] [2021-06-15 21:17:14,405] [7:140198455301888] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106152117074319479_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop
[INFO] [2021-06-15 21:17:14,414] [7:140198455301888] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106152117074319479_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop successfully, pid is 1947
[INFO] [2021-06-15 21:17:14,414] [7:140198455301888] - task_controller.py[line:255]: job 202106152117074319479 task 202106152117074319479_upload_0 0 on local 0 process 1923 kill success
[INFO] [2021-06-15 21:17:14,415] [7:140198455301888] - job_saver.py[line:71]: try to update job 202106152117074319479 task 202106152117074319479_upload_0 0 status
[INFO] [2021-06-15 21:17:14,422] [7:140198455301888] - job_saver.py[line:76]: update job 202106152117074319479 task 202106152117074319479_upload_0 0 status update does not take effect: {'job_id': '202106152117074319479', 'task_id': '202106152117074319479_upload_0', 'task_version': 0, 'role': 'local', 'party_id': '0', 'party_status': 'success'}
[INFO] [2021-06-15 21:17:14,428] [7:140198455301888] - job_saver.py[line:81]: try to update job 202106152117074319479 task 202106152117074319479_upload_0 0
[WARNING] [2021-06-15 21:17:14,435] [7:140198455301888] - job_saver.py[line:86]: job 202106152117074319479 task 202106152117074319479_upload_0 0 update does not take effect
[INFO] [2021-06-15 21:17:14,443] [7:140198455301888] - job_saver.py[line:45]: try to update job 202106152117074319479 status to success
[INFO] [2021-06-15 21:17:14,453] [7:140198455301888] - job_saver.py[line:56]: update job 202106152117074319479 status does not take effect
[INFO] [2021-06-15 21:17:14,457] [7:140197562341120] - federated_scheduler.py[line:92]: stop job 202106152117074319479 success
[INFO] [2021-06-15 21:17:14,458] [7:140197562341120] - dag_scheduler.py[line:448]: stop job 202106152117074319479 with success successfully
[INFO] [2021-06-15 21:17:14,458] [7:140197562341120] - federated_scheduler.py[line:107]: try to clean job 202106152117074319479
[INFO] [2021-06-15 21:17:14,463] [7:140198455301888] - job_controller.py[line:379]: Job 202106152117074319479 on local 0 start to clean
[INFO] [2021-06-15 21:17:14,464] [7:140198455301888] - job_controller.py[line:382]: job 202106152117074319479 on local 0 clean done
[INFO] [2021-06-15 21:17:14,466] [7:140197562341120] - federated_scheduler.py[line:110]: clean job 202106152117074319479 success
[INFO] [2021-06-15 21:17:14,466] [7:140197562341120] - dag_scheduler.py[line:505]: Job 202106152117074319479 finished with success, done
[INFO] [2021-06-15 21:17:14,467] [7:140197562341120] - dag_scheduler.py[line:325]: finish scheduling job 202106152117074319479
[INFO] [2021-06-15 21:17:14,498] [7:140197562341120] - dag_scheduler.py[line:298]: scheduling job 202106152117074319479
[INFO] [2021-06-15 21:17:14,499] [7:140197562341120] - task_scheduler.py[line:28]: scheduling job 202106152117074319479 tasks
[INFO] [2021-06-15 21:17:14,524] [7:140197562341120] - task_scheduler.py[line:143]: job 202106152117074319479 task 202106152117074319479_upload_0 0 status is success, calculate by task party status list: ['success']
[INFO] [2021-06-15 21:17:14,524] [7:140197562341120] - task_scheduler.py[line:75]: finish scheduling job 202106152117074319479 tasks
[INFO] [2021-06-15 21:17:14,524] [7:140197562341120] - dag_scheduler.py[line:310]: Job 202106152117074319479 status is success, calculate by task status list: ['success']
[INFO] [2021-06-15 21:17:14,524] [7:140197562341120] - dag_scheduler.py[line:502]: Job 202106152117074319479 finished with success, do something...
[INFO] [2021-06-15 21:17:14,524] [7:140197562341120] - dag_scheduler.py[line:436]: request stop job 202106152117074319479 with success
[INFO] [2021-06-15 21:17:14,536] [7:140197562341120] - dag_scheduler.py[line:445]: request stop job 202106152117074319479 with success to all party
[INFO] [2021-06-15 21:17:14,536] [7:140197562341120] - federated_scheduler.py[line:88]: try to stop job 202106152117074319479
[INFO] [2021-06-15 21:17:14,562] [7:140198455301888] - job_utils.py[line:397]: try to stop job 202106152117074319479 task 202106152117074319479_upload_0 local 0 with success party status process pid:1923
[INFO] [2021-06-15 21:17:14,563] [7:140198455301888] - job_utils.py[line:400]: can not found job 202106152117074319479 task 202106152117074319479_upload_0 local 0 with success party status process pid:1923
[INFO] [2021-06-15 21:17:14,567] [7:140198455301888] - job_utils.py[line:424]: start run subprocess to stop task session 202106152117074319479_upload_0_0_local_0
[INFO] [2021-06-15 21:17:14,568] [7:140198455301888] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106152117074319479_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop
[INFO] [2021-06-15 21:17:14,577] [7:140198455301888] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 202106152117074319479_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop successfully, pid is 1951
[INFO] [2021-06-15 21:17:14,578] [7:140198455301888] - task_controller.py[line:255]: job 202106152117074319479 task 202106152117074319479_upload_0 0 on local 0 process 1923 kill success
[INFO] [2021-06-15 21:17:14,578] [7:140198455301888] - job_saver.py[line:71]: try to update job 202106152117074319479 task 202106152117074319479_upload_0 0 status
[INFO] [2021-06-15 21:17:14,585] [7:140198455301888] - job_saver.py[line:76]: update job 202106152117074319479 task 202106152117074319479_upload_0 0 status update does not take effect: {'job_id': '202106152117074319479', 'task_id': '202106152117074319479_upload_0', 'task_version': 0, 'role': 'local', 'party_id': '0', 'party_status': 'success'}
[INFO] [2021-06-15 21:17:14,591] [7:140198455301888] - job_saver.py[line:81]: try to update job 202106152117074319479 task 202106152117074319479_upload_0 0
[WARNING] [2021-06-15 21:17:14,596] [7:140198455301888] - job_saver.py[line:86]: job 202106152117074319479 task 202106152117074319479_upload_0 0 update does not take effect
[INFO] [2021-06-15 21:17:14,602] [7:140198455301888] - job_saver.py[line:45]: try to update job 202106152117074319479 status to success
[INFO] [2021-06-15 21:17:14,610] [7:140198455301888] - job_saver.py[line:56]: update job 202106152117074319479 status does not take effect
[INFO] [2021-06-15 21:17:14,615] [7:140197562341120] - federated_scheduler.py[line:92]: stop job 202106152117074319479 success
[INFO] [2021-06-15 21:17:14,615] [7:140197562341120] - dag_scheduler.py[line:448]: stop job 202106152117074319479 with success successfully
[INFO] [2021-06-15 21:17:14,615] [7:140197562341120] - federated_scheduler.py[line:107]: try to clean job 202106152117074319479
[INFO] [2021-06-15 21:17:14,634] [7:140196188256000] - job_controller.py[line:379]: Job 202106152117074319479 on local 0 start to clean
[INFO] [2021-06-15 21:17:14,634] [7:140196188256000] - job_controller.py[line:382]: job 202106152117074319479 on local 0 clean done
[INFO] [2021-06-15 21:17:14,638] [7:140197562341120] - federated_scheduler.py[line:110]: clean job 202106152117074319479 success
[INFO] [2021-06-15 21:17:14,639] [7:140197562341120] - dag_scheduler.py[line:505]: Job 202106152117074319479 finished with success, done
[INFO] [2021-06-15 21:17:14,639] [7:140197562341120] - dag_scheduler.py[line:325]: finish scheduling job 202106152117074319479
[INFO] [2021-06-15 21:17:14,921] [1943:140639530088256] - session_utils.py[line:38]: start stop session 202106152117074319479_upload_0_0_local_0
[INFO] [2021-06-15 21:17:14,922] [1943:140639530088256] - session_utils.py[line:47]: stop session 202106152117074319479_upload_0_0_local_0 success
[INFO] [2021-06-15 21:17:15,008] [1947:140500854904640] - session_utils.py[line:38]: start stop session 202106152117074319479_upload_0_0_local_0
[INFO] [2021-06-15 21:17:15,008] [1947:140500854904640] - session_utils.py[line:47]: stop session 202106152117074319479_upload_0_0_local_0 success
[INFO] [2021-06-15 21:17:15,267] [1951:140118825207616] - session_utils.py[line:38]: start stop session 202106152117074319479_upload_0_0_local_0
[INFO] [2021-06-15 21:17:15,268] [1951:140118825207616] - session_utils.py[line:47]: stop session 202106152117074319479_upload_0_0_local_0 success
[INFO] [2021-06-15 21:17:16,686] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:17:18,735] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:17:20,826] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:17:22,872] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:17:24,917] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:17:26,966] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:17:29,014] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:17:31,103] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:17:33,460] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:17:35,588] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:17:38,098] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:17:40,359] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:17:42,411] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:17:44,467] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:17:46,508] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:17:48,577] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:17:50,635] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:17:52,687] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:17:54,742] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:17:56,804] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:17:58,855] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:00,902] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:02,960] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:05,018] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:07,066] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:09,115] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:11,184] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:13,241] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:15,293] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:17,381] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:19,459] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:21,514] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:23,567] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:25,622] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:27,676] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:29,717] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:31,766] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:33,825] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:35,877] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:37,928] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:39,982] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:42,028] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:44,080] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:46,129] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:48,178] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:50,230] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:52,287] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:54,341] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:56,392] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:58,444] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:00,495] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:02,565] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:04,617] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:06,670] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:08,721] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:10,772] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:12,829] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:14,881] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:16,959] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:19,030] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:21,081] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:23,142] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:25,193] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:27,245] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:29,296] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:31,341] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:33,391] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:35,442] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:37,502] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:39,551] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:41,601] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:43,652] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:45,702] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:47,752] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:49,814] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:51,870] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:53,920] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:55,972] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:58,026] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:00,076] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:02,129] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:04,196] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:06,249] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:08,283] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:10,334] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:12,406] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:14,463] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:16,516] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:18,569] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:20,615] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:22,672] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:24,722] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:26,779] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:28,828] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:30,881] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:32,938] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:34,998] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:37,049] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:39,103] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:41,153] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:43,204] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:45,265] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:47,311] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:49,366] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:51,416] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:53,495] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:55,549] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:57,601] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:59,655] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:01,714] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:03,765] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:05,818] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:07,854] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:09,902] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:11,951] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:13,998] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:16,051] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:18,104] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:20,157] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:22,217] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:24,276] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:26,331] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:28,372] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:30,423] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:32,479] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:34,530] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:36,591] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:38,643] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:40,704] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:42,757] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:44,836] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:46,889] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:48,935] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:51,130] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:53,182] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:55,248] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:57,315] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:59,364] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:22:01,410] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:22:03,458] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:22:06,092] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:22:08,350] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:22:11,829] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
