[INFO] [2021-06-15 21:17:32,683] [7:140196188256000] - dag_scheduler.py[line:40]: submit job, job_id 2021061521173237628810, body {'job_dsl': {'components': {'upload_0': {'module': 'Upload'}}}, 'job_runtime_conf': {'initiator': {'role': 'local', 'party_id': 0}, 'job_parameters': {'common': {'backend': 0, 'work_mode': 0}}, 'role': {'local': [0]}, 'component_parameters': {'role': {'local': {'0': {'upload_0': {'partition': 16, 'file': '/fate/jobs/2021061521173237628810/fate_upload_tmp/default_credit_hetero_guest.csv', 'namespace': 'experiment', 'head': 1, 'name': 'default_credit_hetero_guest', 'destroy': True}}}}}, 'dsl_version': 2}}
[INFO] [2021-06-15 21:17:32,698] [7:140198455301888] - job_controller.py[line:52]: job parameters:{'job_type': 'train', 'work_mode': 0, 'backend': 0, 'computing_engine': 'STANDALONE', 'federation_engine': 'STANDALONE', 'storage_engine': 'STANDALONE', 'engines_address': {}, 'federated_mode': 'SINGLE', 'task_parallelism': 1, 'computing_partitions': 4, 'federated_status_collect_type': 'PULL', 'model_id': 'local-0#model', 'model_version': '2021061521173237628810', 'eggroll_run': {}, 'spark_run': {}, 'rabbitmq_run': {}, 'pulsar_run': {}, 'adaptation_parameters': {'task_nodes': 1, 'task_cores_per_node': 4, 'task_memory_per_node': 0, 'request_task_cores': 4, 'if_initiator_baseline': True}}
[INFO] [2021-06-15 21:17:32,758] [7:140196188256000] - dag_scheduler.py[line:122]: submit job successfully, job id is 2021061521173237628810, model id is local-0#model
[INFO] [2021-06-15 21:17:33,143] [7:140197562341120] - federated_scheduler.py[line:39]: try to apply job 2021061521173237628810 resource
[INFO] [2021-06-15 21:17:33,171] [7:140196188256000] - resource_manager.py[line:176]: apply job 2021061521173237628810 resource(cores 4 memory 0) on local 0 successfully, remaining cores: 16 remaining memory: 0
[INFO] [2021-06-15 21:17:33,175] [7:140197562341120] - federated_scheduler.py[line:42]: apply job 2021061521173237628810 resource successfully
[INFO] [2021-06-15 21:17:33,175] [7:140197562341120] - dag_scheduler.py[line:279]: try to start job 2021061521173237628810 on initiator local 0
[INFO] [2021-06-15 21:17:33,189] [7:140196188256000] - job_controller.py[line:261]: try to start job 2021061521173237628810 on local 0
[INFO] [2021-06-15 21:17:33,190] [7:140196188256000] - job_saver.py[line:45]: try to update job 2021061521173237628810 status to running
[INFO] [2021-06-15 21:17:33,210] [7:140196188256000] - job_saver.py[line:48]: update job 2021061521173237628810 status successfully
[INFO] [2021-06-15 21:17:33,210] [7:140196188256000] - job_saver.py[line:61]: try to update job 2021061521173237628810
[INFO] [2021-06-15 21:17:33,230] [7:140196188256000] - job_saver.py[line:64]: job 2021061521173237628810 update successfully: {'job_id': '2021061521173237628810', 'role': 'local', 'party_id': 0, 'status': 'running', 'start_time': 1623791853190}
[INFO] [2021-06-15 21:17:33,230] [7:140196188256000] - job_controller.py[line:275]: start job 2021061521173237628810 on local 0 successfully
[INFO] [2021-06-15 21:17:33,234] [7:140197562341120] - dag_scheduler.py[line:292]: start job 2021061521173237628810 on initiator local 0
[INFO] [2021-06-15 21:17:33,246] [7:140197562341120] - dag_scheduler.py[line:247]: reset job 2021061521173237628810 ready signal True
[INFO] [2021-06-15 21:17:33,256] [7:140197562341120] - dag_scheduler.py[line:298]: scheduling job 2021061521173237628810
[INFO] [2021-06-15 21:17:33,258] [7:140197562341120] - task_scheduler.py[line:28]: scheduling job 2021061521173237628810 tasks
[INFO] [2021-06-15 21:17:33,277] [7:140197562341120] - task_scheduler.py[line:143]: job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status is waiting, calculate by task party status list: ['waiting']
[INFO] [2021-06-15 21:17:33,278] [7:140197562341120] - task_scheduler.py[line:80]: try to start job 2021061521173237628810 task 2021061521173237628810_upload_0 0 on local 0
[INFO] [2021-06-15 21:17:33,295] [7:140197562341120] - resource_manager.py[line:286]: task 2021061521173237628810_upload_0 0 apply resource successfully
[INFO] [2021-06-15 21:17:33,295] [7:140197562341120] - job_saver.py[line:71]: try to update job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status
[INFO] [2021-06-15 21:17:33,312] [7:140197562341120] - job_saver.py[line:74]: update job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status successfully: {'job_id': '2021061521173237628810', 'task_id': '2021061521173237628810_upload_0', 'task_version': 0, 'role': 'local', 'party_id': '0', 'status': 'running'}
[INFO] [2021-06-15 21:17:33,314] [7:140197562341120] - task_scheduler.py[line:93]: start job 2021061521173237628810 task 2021061521173237628810_upload_0 0 on local 0
[INFO] [2021-06-15 21:17:33,314] [7:140197562341120] - federated_scheduler.py[line:192]: job 2021061521173237628810 task 2021061521173237628810_upload_0 0 is running, sync to all party
[INFO] [2021-06-15 21:17:33,321] [7:140196188256000] - job_saver.py[line:71]: try to update job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status
[INFO] [2021-06-15 21:17:33,329] [7:140196188256000] - job_saver.py[line:76]: update job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status update does not take effect: {'job_id': '2021061521173237628810', 'task_id': '2021061521173237628810_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'status': 'running'}
[WARNING] [2021-06-15 21:17:33,339] [7:140197562341120] - federated_scheduler.py[line:260]: an error occurred while status/running the task to role local party 0: 
update task status failed
[INFO] [2021-06-15 21:17:33,340] [7:140197562341120] - federated_scheduler.py[line:197]: sync job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status running to all party failed: 
{'local': {0: {'retcode': 103, 'retmsg': 'update task status failed'}}}
[INFO] [2021-06-15 21:17:33,352] [7:140196188256000] - task_controller.py[line:71]: try to start job 2021061521173237628810 task 2021061521173237628810_upload_0 0 on local 0 executor subprocess
[INFO] [2021-06-15 21:17:33,357] [7:140196188256000] - task_controller.py[line:90]: use computing engine STANDALONE
[INFO] [2021-06-15 21:17:33,358] [7:140196188256000] - task_controller.py[line:145]: job 2021061521173237628810 task 2021061521173237628810_upload_0 0 on local 0 executor subprocess is ready
[INFO] [2021-06-15 21:17:33,358] [7:140196188256000] - job_utils.py[line:310]: start process command: /usr/local/bin/python /fate/python/fate_flow/operation/task_executor.py -j 2021061521173237628810 -n upload_0 -t 2021061521173237628810_upload_0 -v 0 -r local -p 0 -c /fate/jobs/2021061521173237628810/local/0/upload_0/2021061521173237628810_upload_0/0/task_parameters.json --run_ip 127.0.0.1 --job_server 127.0.0.1:9380
[INFO] [2021-06-15 21:17:33,367] [7:140196188256000] - job_utils.py[line:334]: start process command: /usr/local/bin/python /fate/python/fate_flow/operation/task_executor.py -j 2021061521173237628810 -n upload_0 -t 2021061521173237628810_upload_0 -v 0 -r local -p 0 -c /fate/jobs/2021061521173237628810/local/0/upload_0/2021061521173237628810_upload_0/0/task_parameters.json --run_ip 127.0.0.1 --job_server 127.0.0.1:9380 successfully, pid is 1984
[INFO] [2021-06-15 21:17:33,367] [7:140196188256000] - job_saver.py[line:81]: try to update job 2021061521173237628810 task 2021061521173237628810_upload_0 0
[INFO] [2021-06-15 21:17:33,387] [7:140196188256000] - job_saver.py[line:84]: job 2021061521173237628810 task 2021061521173237628810_upload_0 0 update successfully
[INFO] [2021-06-15 21:17:33,394] [7:140196188256000] - job_saver.py[line:71]: try to update job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status
[INFO] [2021-06-15 21:17:33,412] [7:140196188256000] - job_saver.py[line:74]: update job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status successfully: {'job_id': '2021061521173237628810', 'task_id': '2021061521173237628810_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'party_status': 'running', 'start_time': 1623791853367}
[INFO] [2021-06-15 21:17:33,419] [7:140196188256000] - task_controller.py[line:164]: job 2021061521173237628810 task 2021061521173237628810_upload_0 0 on local 0 executor subprocess start success
[INFO] [2021-06-15 21:17:33,426] [7:140197562341120] - task_scheduler.py[line:75]: finish scheduling job 2021061521173237628810 tasks
[INFO] [2021-06-15 21:17:33,426] [7:140197562341120] - dag_scheduler.py[line:310]: Job 2021061521173237628810 status is running, calculate by task status list: ['running']
[INFO] [2021-06-15 21:17:33,427] [7:140197562341120] - dag_scheduler.py[line:325]: finish scheduling job 2021061521173237628810
[INFO] [2021-06-15 21:17:35,250] [1984:140346208028480] - task_executor.py[line:56]: enter task process
[INFO] [2021-06-15 21:17:35,251] [1984:140346208028480] - task_executor.py[line:57]: Namespace(component_name='upload_0', config='/fate/jobs/2021061521173237628810/local/0/upload_0/2021061521173237628810_upload_0/0/task_parameters.json', job_id='2021061521173237628810', job_server='127.0.0.1:9380', party_id=0, role='local', run_ip='127.0.0.1', task_id='2021061521173237628810_upload_0', task_version=0)
[INFO] [2021-06-15 21:17:35,273] [7:140196188256000] - job_saver.py[line:81]: try to update job 2021061521173237628810 task 2021061521173237628810_upload_0 0
[INFO] [2021-06-15 21:17:35,293] [7:140196188256000] - job_saver.py[line:84]: job 2021061521173237628810 task 2021061521173237628810_upload_0 0 update successfully
[INFO] [2021-06-15 21:17:35,300] [7:140196188256000] - job_saver.py[line:71]: try to update job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status
[INFO] [2021-06-15 21:17:35,308] [7:140196188256000] - job_saver.py[line:76]: update job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status update does not take effect: {'job_id': '2021061521173237628810', 'component_name': 'upload_0', 'task_id': '2021061521173237628810_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'run_ip': '127.0.0.1', 'run_pid': 1984, 'party_status': 'running'}
[INFO] [2021-06-15 21:17:35,497] [7:140197562341120] - dag_scheduler.py[line:298]: scheduling job 2021061521173237628810
[INFO] [2021-06-15 21:17:35,499] [7:140197562341120] - task_scheduler.py[line:28]: scheduling job 2021061521173237628810 tasks
[INFO] [2021-06-15 21:17:35,532] [7:140197562341120] - job_saver.py[line:71]: try to update job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status
[INFO] [2021-06-15 21:17:35,540] [7:140197562341120] - job_saver.py[line:76]: update job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status update does not take effect: {'elapsed': None, 'end_time': None, 'job_id': '2021061521173237628810', 'party_id': '0', 'party_status': 'running', 'role': 'local', 'start_time': 1623791853367, 'status': 'running', 'task_id': '2021061521173237628810_upload_0', 'task_version': 0, 'update_time': 1623791852713}
[INFO] [2021-06-15 21:17:35,540] [7:140197562341120] - job_saver.py[line:81]: try to update job 2021061521173237628810 task 2021061521173237628810_upload_0 0
[INFO] [2021-06-15 21:17:35,554] [7:140197562341120] - job_saver.py[line:84]: job 2021061521173237628810 task 2021061521173237628810_upload_0 0 update successfully
[INFO] [2021-06-15 21:17:35,560] [7:140197562341120] - task_scheduler.py[line:143]: job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status is running, calculate by task party status list: ['running']
[INFO] [2021-06-15 21:17:35,560] [7:140197562341120] - task_scheduler.py[line:75]: finish scheduling job 2021061521173237628810 tasks
[INFO] [2021-06-15 21:17:35,560] [7:140197562341120] - dag_scheduler.py[line:310]: Job 2021061521173237628810 status is running, calculate by task status list: ['running']
[INFO] [2021-06-15 21:17:35,560] [7:140197562341120] - dag_scheduler.py[line:325]: finish scheduling job 2021061521173237628810
[INFO] [2021-06-15 21:17:36,235] [7:140196188256000] - job_saver.py[line:61]: try to update job 2021061521173237628810
[INFO] [2021-06-15 21:17:36,255] [7:140196188256000] - job_saver.py[line:64]: job 2021061521173237628810 update successfully: {'progress': 100.0, 'job_id': '2021061521173237628810', 'role': 'local', 'party_id': '0'}
[INFO] [2021-06-15 21:17:36,958] [7:140196188256000] - job_tracker.py[line:74]: save job 2021061521173237628810 component upload_0 on local 0 upload data_access metric data
[INFO] [2021-06-15 21:17:36,986] [7:140196188256000] - job_tracker.py[line:97]: save job 2021061521173237628810 component upload_0 on local 0 upload data_access metric meta
[INFO] [2021-06-15 21:17:37,059] [1984:140346208028480] - job_tracker.py[line:159]: task id 2021061521173237628810_upload_0 output data table is none
[INFO] [2021-06-15 21:17:37,065] [7:140196188256000] - job_saver.py[line:81]: try to update job 2021061521173237628810 task 2021061521173237628810_upload_0 0
[INFO] [2021-06-15 21:17:37,085] [7:140196188256000] - job_saver.py[line:84]: job 2021061521173237628810 task 2021061521173237628810_upload_0 0 update successfully
[INFO] [2021-06-15 21:17:37,092] [7:140196188256000] - job_saver.py[line:71]: try to update job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status
[INFO] [2021-06-15 21:17:37,110] [7:140196188256000] - job_saver.py[line:74]: update job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status successfully: {'job_id': '2021061521173237628810', 'component_name': 'upload_0', 'task_id': '2021061521173237628810_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'run_ip': '127.0.0.1', 'run_pid': 1984, 'party_status': 'success', 'end_time': 1623791857059, 'elapsed': 1808}
[INFO] [2021-06-15 21:17:37,130] [7:140196188256000] - job_saver.py[line:81]: try to update job 2021061521173237628810 task 2021061521173237628810_upload_0 0
[INFO] [2021-06-15 21:17:37,148] [7:140196188256000] - job_saver.py[line:84]: job 2021061521173237628810 task 2021061521173237628810_upload_0 0 update successfully
[INFO] [2021-06-15 21:17:37,155] [7:140196188256000] - job_saver.py[line:71]: try to update job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status
[INFO] [2021-06-15 21:17:37,162] [7:140196188256000] - job_saver.py[line:76]: update job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status update does not take effect: {'job_id': '2021061521173237628810', 'component_name': 'upload_0', 'task_id': '2021061521173237628810_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'run_ip': '127.0.0.1', 'run_pid': 1984, 'party_status': 'success', 'end_time': 1623791857059, 'elapsed': 1808}
[INFO] [2021-06-15 21:17:37,607] [7:140197562341120] - dag_scheduler.py[line:298]: scheduling job 2021061521173237628810
[INFO] [2021-06-15 21:17:37,609] [7:140197562341120] - task_scheduler.py[line:28]: scheduling job 2021061521173237628810 tasks
[INFO] [2021-06-15 21:17:37,641] [7:140197562341120] - job_saver.py[line:71]: try to update job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status
[INFO] [2021-06-15 21:17:37,647] [7:140197562341120] - job_saver.py[line:76]: update job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status update does not take effect: {'elapsed': 1808, 'end_time': 1623791857059, 'job_id': '2021061521173237628810', 'party_id': '0', 'party_status': 'success', 'role': 'local', 'start_time': 1623791853367, 'status': 'running', 'task_id': '2021061521173237628810_upload_0', 'task_version': 0, 'update_time': 1623791852713}
[INFO] [2021-06-15 21:17:37,648] [7:140197562341120] - job_saver.py[line:81]: try to update job 2021061521173237628810 task 2021061521173237628810_upload_0 0
[INFO] [2021-06-15 21:17:37,672] [7:140197562341120] - job_saver.py[line:84]: job 2021061521173237628810 task 2021061521173237628810_upload_0 0 update successfully
[INFO] [2021-06-15 21:17:37,678] [7:140197562341120] - task_scheduler.py[line:143]: job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status is success, calculate by task party status list: ['success']
[INFO] [2021-06-15 21:17:37,678] [7:140197562341120] - federated_scheduler.py[line:192]: job 2021061521173237628810 task 2021061521173237628810_upload_0 0 is success, sync to all party
[INFO] [2021-06-15 21:17:37,685] [7:140196188256000] - job_saver.py[line:71]: try to update job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status
[INFO] [2021-06-15 21:17:37,707] [7:140196188256000] - job_saver.py[line:74]: update job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status successfully: {'job_id': '2021061521173237628810', 'task_id': '2021061521173237628810_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'status': 'success'}
[INFO] [2021-06-15 21:17:37,725] [7:140196188256000] - resource_manager.py[line:286]: task 2021061521173237628810_upload_0 0 return resource successfully
[INFO] [2021-06-15 21:17:37,732] [7:140196188256000] - job_tracker.py[line:424]: clean task 2021061521173237628810_upload_0 0 on local 0
[ERROR] [2021-06-15 21:17:37,734] [7:140196188256000] - job_tracker.py[line:475]: namespace dir /fate/data/2021061521173237628810_upload_0_0_local_0 does not exist
Traceback (most recent call last):
  File "/fate/python/fate_flow/operation/job_tracker.py", line 437, in clean_task
    sess.computing.cleanup(namespace=computing_temp_namespace, name="*")
  File "/fate/python/fate_arch/computing/standalone/_csession.py", line 73, in cleanup
    return self._session.cleanup(name=name, namespace=namespace)
  File "/fate/python/fate_arch/_standalone.py", line 383, in cleanup
    raise EnvironmentError(f"namespace dir {namespace_dir} does not exist")
OSError: namespace dir /fate/data/2021061521173237628810_upload_0_0_local_0 does not exist
[INFO] [2021-06-15 21:17:37,746] [7:140197562341120] - federated_scheduler.py[line:195]: sync job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status success to all party success
[INFO] [2021-06-15 21:17:37,747] [7:140197562341120] - federated_scheduler.py[line:202]: try to stop job 2021061521173237628810 task 2021061521173237628810_upload_0 0
[INFO] [2021-06-15 21:17:37,763] [7:140196188256000] - job_utils.py[line:397]: try to stop job 2021061521173237628810 task 2021061521173237628810_upload_0 local 0 with success party status process pid:1984
[INFO] [2021-06-15 21:17:37,763] [7:140196188256000] - job_utils.py[line:400]: can not found job 2021061521173237628810 task 2021061521173237628810_upload_0 local 0 with success party status process pid:1984
[INFO] [2021-06-15 21:17:37,768] [7:140196188256000] - job_utils.py[line:424]: start run subprocess to stop task session 2021061521173237628810_upload_0_0_local_0
[INFO] [2021-06-15 21:17:37,768] [7:140196188256000] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061521173237628810_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop
[INFO] [2021-06-15 21:17:37,777] [7:140196188256000] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061521173237628810_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop successfully, pid is 2004
[INFO] [2021-06-15 21:17:37,778] [7:140196188256000] - task_controller.py[line:255]: job 2021061521173237628810 task 2021061521173237628810_upload_0 0 on local 0 process 1984 kill success
[INFO] [2021-06-15 21:17:37,778] [7:140196188256000] - job_saver.py[line:71]: try to update job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status
[INFO] [2021-06-15 21:17:37,788] [7:140196188256000] - job_saver.py[line:76]: update job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status update does not take effect: {'job_id': '2021061521173237628810', 'task_id': '2021061521173237628810_upload_0', 'task_version': 0, 'role': 'local', 'party_id': '0', 'party_status': 'success'}
[INFO] [2021-06-15 21:17:37,799] [7:140196188256000] - job_saver.py[line:81]: try to update job 2021061521173237628810 task 2021061521173237628810_upload_0 0
[WARNING] [2021-06-15 21:17:37,806] [7:140196188256000] - job_saver.py[line:86]: job 2021061521173237628810 task 2021061521173237628810_upload_0 0 update does not take effect
[INFO] [2021-06-15 21:17:37,819] [7:140197562341120] - federated_scheduler.py[line:206]: stop job 2021061521173237628810 task 2021061521173237628810_upload_0 0 success
[INFO] [2021-06-15 21:17:37,819] [7:140197562341120] - task_scheduler.py[line:75]: finish scheduling job 2021061521173237628810 tasks
[INFO] [2021-06-15 21:17:37,819] [7:140197562341120] - dag_scheduler.py[line:310]: Job 2021061521173237628810 status is success, calculate by task status list: ['success']
[INFO] [2021-06-15 21:17:37,819] [7:140197562341120] - federated_scheduler.py[line:78]: try to save job 2021061521173237628810 pipelined model
[INFO] [2021-06-15 21:17:37,824] [7:140196188256000] - job_controller.py[line:331]: job 2021061521173237628810 on local 0 start to save pipeline
[INFO] [2021-06-15 21:17:37,837] [7:140196188256000] - job_controller.py[line:374]: job 2021061521173237628810 on local 0 save pipeline successfully
[INFO] [2021-06-15 21:17:37,841] [7:140197562341120] - federated_scheduler.py[line:81]: save job 2021061521173237628810 pipelined model success
[INFO] [2021-06-15 21:17:37,841] [7:140197562341120] - federated_scheduler.py[line:68]: job 2021061521173237628810 is success, sync to all party
[INFO] [2021-06-15 21:17:37,847] [7:140196188256000] - job_saver.py[line:45]: try to update job 2021061521173237628810 status to success
[INFO] [2021-06-15 21:17:37,867] [7:140196188256000] - job_saver.py[line:48]: update job 2021061521173237628810 status successfully
[INFO] [2021-06-15 21:17:37,905] [7:140196188256000] - resource_manager.py[line:176]: return job 2021061521173237628810 resource(cores 4 memory 0) on local 0 successfully, remaining cores: 20 remaining memory: 0
[INFO] [2021-06-15 21:17:37,910] [7:140197562341120] - federated_scheduler.py[line:71]: sync job 2021061521173237628810 status success to all party success
[INFO] [2021-06-15 21:17:37,919] [7:140197562341120] - job_saver.py[line:45]: try to update job 2021061521173237628810 status to success
[INFO] [2021-06-15 21:17:37,929] [7:140197562341120] - job_saver.py[line:56]: update job 2021061521173237628810 status does not take effect
[INFO] [2021-06-15 21:17:37,930] [7:140197562341120] - job_saver.py[line:61]: try to update job 2021061521173237628810
[WARNING] [2021-06-15 21:17:37,939] [7:140197562341120] - job_saver.py[line:66]: job 2021061521173237628810 update does not take effect: {'job_id': '2021061521173237628810', 'role': 'local', 'party_id': '0', 'status': 'success'}
[INFO] [2021-06-15 21:17:37,939] [7:140197562341120] - dag_scheduler.py[line:502]: Job 2021061521173237628810 finished with success, do something...
[INFO] [2021-06-15 21:17:37,939] [7:140197562341120] - dag_scheduler.py[line:436]: request stop job 2021061521173237628810 with success
[INFO] [2021-06-15 21:17:37,946] [7:140197562341120] - dag_scheduler.py[line:445]: request stop job 2021061521173237628810 with success to all party
[INFO] [2021-06-15 21:17:37,946] [7:140197562341120] - federated_scheduler.py[line:88]: try to stop job 2021061521173237628810
[INFO] [2021-06-15 21:17:37,970] [7:140196188256000] - job_utils.py[line:397]: try to stop job 2021061521173237628810 task 2021061521173237628810_upload_0 local 0 with success party status process pid:1984
[INFO] [2021-06-15 21:17:37,970] [7:140196188256000] - job_utils.py[line:400]: can not found job 2021061521173237628810 task 2021061521173237628810_upload_0 local 0 with success party status process pid:1984
[INFO] [2021-06-15 21:17:37,976] [7:140196188256000] - job_utils.py[line:424]: start run subprocess to stop task session 2021061521173237628810_upload_0_0_local_0
[INFO] [2021-06-15 21:17:37,977] [7:140196188256000] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061521173237628810_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop
[INFO] [2021-06-15 21:17:37,986] [7:140196188256000] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061521173237628810_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop successfully, pid is 2008
[INFO] [2021-06-15 21:17:37,988] [7:140196188256000] - task_controller.py[line:255]: job 2021061521173237628810 task 2021061521173237628810_upload_0 0 on local 0 process 1984 kill success
[INFO] [2021-06-15 21:17:37,988] [7:140196188256000] - job_saver.py[line:71]: try to update job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status
[INFO] [2021-06-15 21:17:38,001] [7:140196188256000] - job_saver.py[line:76]: update job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status update does not take effect: {'job_id': '2021061521173237628810', 'task_id': '2021061521173237628810_upload_0', 'task_version': 0, 'role': 'local', 'party_id': '0', 'party_status': 'success'}
[INFO] [2021-06-15 21:17:38,012] [7:140196188256000] - job_saver.py[line:81]: try to update job 2021061521173237628810 task 2021061521173237628810_upload_0 0
[WARNING] [2021-06-15 21:17:38,020] [7:140196188256000] - job_saver.py[line:86]: job 2021061521173237628810 task 2021061521173237628810_upload_0 0 update does not take effect
[INFO] [2021-06-15 21:17:38,027] [7:140196188256000] - job_saver.py[line:45]: try to update job 2021061521173237628810 status to success
[INFO] [2021-06-15 21:17:38,034] [7:140196188256000] - job_saver.py[line:56]: update job 2021061521173237628810 status does not take effect
[INFO] [2021-06-15 21:17:38,039] [7:140197562341120] - federated_scheduler.py[line:92]: stop job 2021061521173237628810 success
[INFO] [2021-06-15 21:17:38,040] [7:140197562341120] - dag_scheduler.py[line:448]: stop job 2021061521173237628810 with success successfully
[INFO] [2021-06-15 21:17:38,040] [7:140197562341120] - federated_scheduler.py[line:107]: try to clean job 2021061521173237628810
[INFO] [2021-06-15 21:17:38,047] [7:140196188256000] - job_controller.py[line:379]: Job 2021061521173237628810 on local 0 start to clean
[INFO] [2021-06-15 21:17:38,047] [7:140196188256000] - job_controller.py[line:382]: job 2021061521173237628810 on local 0 clean done
[INFO] [2021-06-15 21:17:38,051] [7:140197562341120] - federated_scheduler.py[line:110]: clean job 2021061521173237628810 success
[INFO] [2021-06-15 21:17:38,052] [7:140197562341120] - dag_scheduler.py[line:505]: Job 2021061521173237628810 finished with success, done
[INFO] [2021-06-15 21:17:38,053] [7:140197562341120] - dag_scheduler.py[line:325]: finish scheduling job 2021061521173237628810
[INFO] [2021-06-15 21:17:38,178] [7:140197562341120] - dag_scheduler.py[line:298]: scheduling job 2021061521173237628810
[INFO] [2021-06-15 21:17:38,187] [7:140197562341120] - task_scheduler.py[line:28]: scheduling job 2021061521173237628810 tasks
[INFO] [2021-06-15 21:17:38,226] [7:140197562341120] - task_scheduler.py[line:143]: job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status is success, calculate by task party status list: ['success']
[INFO] [2021-06-15 21:17:38,226] [7:140197562341120] - task_scheduler.py[line:75]: finish scheduling job 2021061521173237628810 tasks
[INFO] [2021-06-15 21:17:38,226] [7:140197562341120] - dag_scheduler.py[line:310]: Job 2021061521173237628810 status is success, calculate by task status list: ['success']
[INFO] [2021-06-15 21:17:38,226] [7:140197562341120] - dag_scheduler.py[line:502]: Job 2021061521173237628810 finished with success, do something...
[INFO] [2021-06-15 21:17:38,226] [7:140197562341120] - dag_scheduler.py[line:436]: request stop job 2021061521173237628810 with success
[INFO] [2021-06-15 21:17:38,232] [7:140197562341120] - dag_scheduler.py[line:445]: request stop job 2021061521173237628810 with success to all party
[INFO] [2021-06-15 21:17:38,232] [7:140197562341120] - federated_scheduler.py[line:88]: try to stop job 2021061521173237628810
[INFO] [2021-06-15 21:17:38,247] [7:140196188256000] - job_utils.py[line:397]: try to stop job 2021061521173237628810 task 2021061521173237628810_upload_0 local 0 with success party status process pid:1984
[INFO] [2021-06-15 21:17:38,247] [7:140196188256000] - job_utils.py[line:400]: can not found job 2021061521173237628810 task 2021061521173237628810_upload_0 local 0 with success party status process pid:1984
[INFO] [2021-06-15 21:17:38,251] [7:140196188256000] - job_utils.py[line:424]: start run subprocess to stop task session 2021061521173237628810_upload_0_0_local_0
[INFO] [2021-06-15 21:17:38,251] [7:140196188256000] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061521173237628810_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop
[INFO] [2021-06-15 21:17:38,262] [7:140196188256000] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061521173237628810_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop successfully, pid is 2019
[INFO] [2021-06-15 21:17:38,262] [7:140196188256000] - task_controller.py[line:255]: job 2021061521173237628810 task 2021061521173237628810_upload_0 0 on local 0 process 1984 kill success
[INFO] [2021-06-15 21:17:38,263] [7:140196188256000] - job_saver.py[line:71]: try to update job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status
[INFO] [2021-06-15 21:17:38,267] [7:140196188256000] - job_saver.py[line:76]: update job 2021061521173237628810 task 2021061521173237628810_upload_0 0 status update does not take effect: {'job_id': '2021061521173237628810', 'task_id': '2021061521173237628810_upload_0', 'task_version': 0, 'role': 'local', 'party_id': '0', 'party_status': 'success'}
[INFO] [2021-06-15 21:17:38,272] [7:140196188256000] - job_saver.py[line:81]: try to update job 2021061521173237628810 task 2021061521173237628810_upload_0 0
[WARNING] [2021-06-15 21:17:38,279] [7:140196188256000] - job_saver.py[line:86]: job 2021061521173237628810 task 2021061521173237628810_upload_0 0 update does not take effect
[INFO] [2021-06-15 21:17:38,287] [7:140196188256000] - job_saver.py[line:45]: try to update job 2021061521173237628810 status to success
[INFO] [2021-06-15 21:17:38,295] [7:140196188256000] - job_saver.py[line:56]: update job 2021061521173237628810 status does not take effect
[INFO] [2021-06-15 21:17:38,300] [7:140197562341120] - federated_scheduler.py[line:92]: stop job 2021061521173237628810 success
[INFO] [2021-06-15 21:17:38,300] [7:140197562341120] - dag_scheduler.py[line:448]: stop job 2021061521173237628810 with success successfully
[INFO] [2021-06-15 21:17:38,300] [7:140197562341120] - federated_scheduler.py[line:107]: try to clean job 2021061521173237628810
[INFO] [2021-06-15 21:17:38,306] [7:140196188256000] - job_controller.py[line:379]: Job 2021061521173237628810 on local 0 start to clean
[INFO] [2021-06-15 21:17:38,307] [7:140196188256000] - job_controller.py[line:382]: job 2021061521173237628810 on local 0 clean done
[INFO] [2021-06-15 21:17:38,310] [7:140197562341120] - federated_scheduler.py[line:110]: clean job 2021061521173237628810 success
[INFO] [2021-06-15 21:17:38,310] [7:140197562341120] - dag_scheduler.py[line:505]: Job 2021061521173237628810 finished with success, done
[INFO] [2021-06-15 21:17:38,310] [7:140197562341120] - dag_scheduler.py[line:325]: finish scheduling job 2021061521173237628810
[INFO] [2021-06-15 21:17:38,460] [2004:139844283266880] - session_utils.py[line:38]: start stop session 2021061521173237628810_upload_0_0_local_0
[INFO] [2021-06-15 21:17:38,461] [2004:139844283266880] - session_utils.py[line:47]: stop session 2021061521173237628810_upload_0_0_local_0 success
[INFO] [2021-06-15 21:17:38,649] [2008:140466169661248] - session_utils.py[line:38]: start stop session 2021061521173237628810_upload_0_0_local_0
[INFO] [2021-06-15 21:17:38,650] [2008:140466169661248] - session_utils.py[line:47]: stop session 2021061521173237628810_upload_0_0_local_0 success
[INFO] [2021-06-15 21:17:38,781] [2019:140707034113856] - session_utils.py[line:38]: start stop session 2021061521173237628810_upload_0_0_local_0
[INFO] [2021-06-15 21:17:38,781] [2019:140707034113856] - session_utils.py[line:47]: stop session 2021061521173237628810_upload_0_0_local_0 success
[INFO] [2021-06-15 21:17:40,363] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:17:42,415] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:17:44,470] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:17:46,511] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:17:48,584] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:17:50,639] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:17:52,691] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:17:54,746] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:17:56,808] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:17:58,859] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:00,906] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:02,964] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:05,022] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:07,071] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:09,119] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:11,190] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:13,246] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:15,297] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:17,386] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:19,466] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:21,519] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:23,571] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:25,626] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:27,680] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:29,719] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:31,769] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:33,830] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:35,880] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:37,932] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:39,986] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:42,033] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:44,083] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:46,132] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:48,182] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:50,234] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:52,290] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:54,346] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:56,397] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:18:58,448] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:00,499] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:02,569] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:04,621] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:06,673] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:08,724] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:10,777] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:12,834] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:14,885] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:16,965] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:19,035] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:21,085] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:23,146] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:25,197] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:27,249] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:29,300] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:31,344] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:33,396] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:35,446] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:37,505] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:39,555] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:41,605] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:43,656] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:45,705] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:47,757] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:49,819] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:51,874] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:53,924] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:55,976] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:19:58,030] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:00,080] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:02,133] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:04,199] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:06,254] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:08,286] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:10,338] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:12,415] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:14,466] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:16,521] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:18,574] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:20,617] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:22,676] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:24,726] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:26,782] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:28,831] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:30,885] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:32,942] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:35,003] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:37,053] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:39,107] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:41,157] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:43,208] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:45,270] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:47,318] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:49,370] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:51,419] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:53,501] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:55,553] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:57,605] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:20:59,659] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:01,718] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:03,769] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:05,822] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:07,856] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:09,905] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:11,955] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:14,001] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:16,055] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:18,106] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:20,161] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:22,222] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:24,279] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:26,336] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:28,374] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:30,427] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:32,484] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:34,534] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:36,596] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:38,649] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:40,709] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:42,764] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:44,841] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:46,892] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:48,939] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:51,133] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:53,187] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:55,253] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:57,318] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:21:59,368] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:22:01,413] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:22:03,462] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:22:06,096] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:22:08,360] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:22:11,833] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:22:14,471] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:22:16,528] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:22:18,588] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:22:20,646] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:22:22,707] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:22:24,773] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:22:26,822] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:22:28,881] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:22:31,469] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:22:33,696] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-15 21:22:37,412] [7:140197562341120] - dag_scheduler.py[line:193]: the number of updates has been exceeded
