[INFO] [2021-06-13 21:40:46,711] [7:140265872402176] - dag_scheduler.py[line:40]: submit job, job_id 2021061321404638910521, body {'job_dsl': {'components': {'upload_0': {'module': 'Upload'}}}, 'job_runtime_conf': {'initiator': {'role': 'local', 'party_id': 0}, 'job_parameters': {'common': {'work_mode': 0, 'backend': 0}}, 'role': {'local': [0]}, 'component_parameters': {'role': {'local': {'0': {'upload_0': {'head': 1, 'name': 'default_credit_hetero_guest', 'partition': 16, 'namespace': 'experiment', 'file': '/fate/jobs/2021061321404638910521/fate_upload_tmp/default_credit_hetero_guest.csv', 'destroy': True}}}}}, 'dsl_version': 2}}
[INFO] [2021-06-13 21:40:46,725] [7:140266400880384] - job_controller.py[line:52]: job parameters:{'job_type': 'train', 'work_mode': 0, 'backend': 0, 'computing_engine': 'STANDALONE', 'federation_engine': 'STANDALONE', 'storage_engine': 'STANDALONE', 'engines_address': {}, 'federated_mode': 'SINGLE', 'task_parallelism': 1, 'computing_partitions': 4, 'federated_status_collect_type': 'PULL', 'model_id': 'local-0#model', 'model_version': '2021061321404638910521', 'eggroll_run': {}, 'spark_run': {}, 'rabbitmq_run': {}, 'pulsar_run': {}, 'adaptation_parameters': {'task_nodes': 1, 'task_cores_per_node': 4, 'task_memory_per_node': 0, 'request_task_cores': 4, 'if_initiator_baseline': True}}
[INFO] [2021-06-13 21:40:46,803] [7:140265872402176] - dag_scheduler.py[line:122]: submit job successfully, job id is 2021061321404638910521, model id is local-0#model
[INFO] [2021-06-13 21:40:47,375] [7:140266826163968] - federated_scheduler.py[line:39]: try to apply job 2021061321404638910521 resource
[INFO] [2021-06-13 21:40:47,402] [7:140265872402176] - resource_manager.py[line:176]: apply job 2021061321404638910521 resource(cores 4 memory 0) on local 0 successfully, remaining cores: 16 remaining memory: 0
[INFO] [2021-06-13 21:40:47,407] [7:140266826163968] - federated_scheduler.py[line:42]: apply job 2021061321404638910521 resource successfully
[INFO] [2021-06-13 21:40:47,407] [7:140266826163968] - dag_scheduler.py[line:279]: try to start job 2021061321404638910521 on initiator local 0
[INFO] [2021-06-13 21:40:47,423] [7:140265872402176] - job_controller.py[line:261]: try to start job 2021061321404638910521 on local 0
[INFO] [2021-06-13 21:40:47,423] [7:140265872402176] - job_saver.py[line:45]: try to update job 2021061321404638910521 status to running
[INFO] [2021-06-13 21:40:47,443] [7:140265872402176] - job_saver.py[line:48]: update job 2021061321404638910521 status successfully
[INFO] [2021-06-13 21:40:47,443] [7:140265872402176] - job_saver.py[line:61]: try to update job 2021061321404638910521
[INFO] [2021-06-13 21:40:47,465] [7:140265872402176] - job_saver.py[line:64]: job 2021061321404638910521 update successfully: {'job_id': '2021061321404638910521', 'role': 'local', 'party_id': 0, 'status': 'running', 'start_time': 1623620447423}
[INFO] [2021-06-13 21:40:47,465] [7:140265872402176] - job_controller.py[line:275]: start job 2021061321404638910521 on local 0 successfully
[INFO] [2021-06-13 21:40:47,471] [7:140266826163968] - dag_scheduler.py[line:292]: start job 2021061321404638910521 on initiator local 0
[INFO] [2021-06-13 21:40:47,483] [7:140266826163968] - dag_scheduler.py[line:247]: reset job 2021061321404638910521 ready signal True
[INFO] [2021-06-13 21:40:47,502] [7:140266826163968] - dag_scheduler.py[line:298]: scheduling job 2021061321404638910521
[INFO] [2021-06-13 21:40:47,504] [7:140266826163968] - task_scheduler.py[line:28]: scheduling job 2021061321404638910521 tasks
[INFO] [2021-06-13 21:40:47,525] [7:140266826163968] - task_scheduler.py[line:143]: job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status is waiting, calculate by task party status list: ['waiting']
[INFO] [2021-06-13 21:40:47,525] [7:140266826163968] - task_scheduler.py[line:80]: try to start job 2021061321404638910521 task 2021061321404638910521_upload_0 0 on local 0
[INFO] [2021-06-13 21:40:47,540] [7:140266826163968] - resource_manager.py[line:286]: task 2021061321404638910521_upload_0 0 apply resource successfully
[INFO] [2021-06-13 21:40:47,541] [7:140266826163968] - job_saver.py[line:71]: try to update job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status
[INFO] [2021-06-13 21:40:47,556] [7:140266826163968] - job_saver.py[line:74]: update job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status successfully: {'job_id': '2021061321404638910521', 'task_id': '2021061321404638910521_upload_0', 'task_version': 0, 'role': 'local', 'party_id': '0', 'status': 'running'}
[INFO] [2021-06-13 21:40:47,556] [7:140266826163968] - task_scheduler.py[line:93]: start job 2021061321404638910521 task 2021061321404638910521_upload_0 0 on local 0
[INFO] [2021-06-13 21:40:47,556] [7:140266826163968] - federated_scheduler.py[line:192]: job 2021061321404638910521 task 2021061321404638910521_upload_0 0 is running, sync to all party
[INFO] [2021-06-13 21:40:47,564] [7:140265872402176] - job_saver.py[line:71]: try to update job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status
[INFO] [2021-06-13 21:40:47,572] [7:140265872402176] - job_saver.py[line:76]: update job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status update does not take effect: {'job_id': '2021061321404638910521', 'task_id': '2021061321404638910521_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'status': 'running'}
[WARNING] [2021-06-13 21:40:47,583] [7:140266826163968] - federated_scheduler.py[line:260]: an error occurred while status/running the task to role local party 0: 
update task status failed
[INFO] [2021-06-13 21:40:47,583] [7:140266826163968] - federated_scheduler.py[line:197]: sync job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status running to all party failed: 
{'local': {0: {'retcode': 103, 'retmsg': 'update task status failed'}}}
[INFO] [2021-06-13 21:40:47,597] [7:140265872402176] - task_controller.py[line:71]: try to start job 2021061321404638910521 task 2021061321404638910521_upload_0 0 on local 0 executor subprocess
[INFO] [2021-06-13 21:40:47,603] [7:140265872402176] - task_controller.py[line:90]: use computing engine STANDALONE
[INFO] [2021-06-13 21:40:47,603] [7:140265872402176] - task_controller.py[line:145]: job 2021061321404638910521 task 2021061321404638910521_upload_0 0 on local 0 executor subprocess is ready
[INFO] [2021-06-13 21:40:47,603] [7:140265872402176] - job_utils.py[line:310]: start process command: /usr/local/bin/python /fate/python/fate_flow/operation/task_executor.py -j 2021061321404638910521 -n upload_0 -t 2021061321404638910521_upload_0 -v 0 -r local -p 0 -c /fate/jobs/2021061321404638910521/local/0/upload_0/2021061321404638910521_upload_0/0/task_parameters.json --run_ip 127.0.0.1 --job_server 127.0.0.1:9380
[INFO] [2021-06-13 21:40:47,612] [7:140265872402176] - job_utils.py[line:334]: start process command: /usr/local/bin/python /fate/python/fate_flow/operation/task_executor.py -j 2021061321404638910521 -n upload_0 -t 2021061321404638910521_upload_0 -v 0 -r local -p 0 -c /fate/jobs/2021061321404638910521/local/0/upload_0/2021061321404638910521_upload_0/0/task_parameters.json --run_ip 127.0.0.1 --job_server 127.0.0.1:9380 successfully, pid is 1978
[INFO] [2021-06-13 21:40:47,613] [7:140265872402176] - job_saver.py[line:81]: try to update job 2021061321404638910521 task 2021061321404638910521_upload_0 0
[INFO] [2021-06-13 21:40:47,643] [7:140265872402176] - job_saver.py[line:84]: job 2021061321404638910521 task 2021061321404638910521_upload_0 0 update successfully
[INFO] [2021-06-13 21:40:47,654] [7:140265872402176] - job_saver.py[line:71]: try to update job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status
[INFO] [2021-06-13 21:40:47,675] [7:140265872402176] - job_saver.py[line:74]: update job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status successfully: {'job_id': '2021061321404638910521', 'task_id': '2021061321404638910521_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'party_status': 'running', 'start_time': 1623620447613}
[INFO] [2021-06-13 21:40:47,685] [7:140265872402176] - task_controller.py[line:164]: job 2021061321404638910521 task 2021061321404638910521_upload_0 0 on local 0 executor subprocess start success
[INFO] [2021-06-13 21:40:47,692] [7:140266826163968] - task_scheduler.py[line:75]: finish scheduling job 2021061321404638910521 tasks
[INFO] [2021-06-13 21:40:47,692] [7:140266826163968] - dag_scheduler.py[line:310]: Job 2021061321404638910521 status is running, calculate by task status list: ['running']
[INFO] [2021-06-13 21:40:47,692] [7:140266826163968] - dag_scheduler.py[line:325]: finish scheduling job 2021061321404638910521
[INFO] [2021-06-13 21:40:49,754] [7:140266826163968] - dag_scheduler.py[line:298]: scheduling job 2021061321404638910521
[INFO] [2021-06-13 21:40:49,756] [7:140266826163968] - task_scheduler.py[line:28]: scheduling job 2021061321404638910521 tasks
[INFO] [2021-06-13 21:40:49,788] [7:140266826163968] - job_saver.py[line:71]: try to update job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status
[INFO] [2021-06-13 21:40:49,794] [7:140266826163968] - job_saver.py[line:76]: update job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status update does not take effect: {'elapsed': None, 'end_time': None, 'job_id': '2021061321404638910521', 'party_id': '0', 'party_status': 'running', 'role': 'local', 'start_time': 1623620447613, 'status': 'running', 'task_id': '2021061321404638910521_upload_0', 'task_version': 0, 'update_time': 1623620446747}
[INFO] [2021-06-13 21:40:49,794] [7:140266826163968] - job_saver.py[line:81]: try to update job 2021061321404638910521 task 2021061321404638910521_upload_0 0
[INFO] [2021-06-13 21:40:49,821] [7:140266826163968] - job_saver.py[line:84]: job 2021061321404638910521 task 2021061321404638910521_upload_0 0 update successfully
[INFO] [2021-06-13 21:40:49,829] [7:140266826163968] - task_scheduler.py[line:143]: job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status is running, calculate by task party status list: ['running']
[INFO] [2021-06-13 21:40:49,830] [7:140266826163968] - task_scheduler.py[line:75]: finish scheduling job 2021061321404638910521 tasks
[INFO] [2021-06-13 21:40:49,830] [7:140266826163968] - dag_scheduler.py[line:310]: Job 2021061321404638910521 status is running, calculate by task status list: ['running']
[INFO] [2021-06-13 21:40:49,830] [7:140266826163968] - dag_scheduler.py[line:325]: finish scheduling job 2021061321404638910521
[INFO] [2021-06-13 21:40:49,928] [1978:140226325247808] - task_executor.py[line:56]: enter task process
[INFO] [2021-06-13 21:40:49,928] [1978:140226325247808] - task_executor.py[line:57]: Namespace(component_name='upload_0', config='/fate/jobs/2021061321404638910521/local/0/upload_0/2021061321404638910521_upload_0/0/task_parameters.json', job_id='2021061321404638910521', job_server='127.0.0.1:9380', party_id=0, role='local', run_ip='127.0.0.1', task_id='2021061321404638910521_upload_0', task_version=0)
[INFO] [2021-06-13 21:40:49,944] [7:140265872402176] - job_saver.py[line:81]: try to update job 2021061321404638910521 task 2021061321404638910521_upload_0 0
[INFO] [2021-06-13 21:40:49,970] [7:140265872402176] - job_saver.py[line:84]: job 2021061321404638910521 task 2021061321404638910521_upload_0 0 update successfully
[INFO] [2021-06-13 21:40:49,978] [7:140265872402176] - job_saver.py[line:71]: try to update job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status
[INFO] [2021-06-13 21:40:49,985] [7:140265872402176] - job_saver.py[line:76]: update job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status update does not take effect: {'job_id': '2021061321404638910521', 'component_name': 'upload_0', 'task_id': '2021061321404638910521_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'run_ip': '127.0.0.1', 'run_pid': 1978, 'party_status': 'running'}
[INFO] [2021-06-13 21:40:51,009] [7:140265872402176] - job_saver.py[line:61]: try to update job 2021061321404638910521
[INFO] [2021-06-13 21:40:51,036] [7:140265872402176] - job_saver.py[line:64]: job 2021061321404638910521 update successfully: {'progress': 100.0, 'job_id': '2021061321404638910521', 'role': 'local', 'party_id': '0'}
[INFO] [2021-06-13 21:40:51,890] [7:140266826163968] - dag_scheduler.py[line:298]: scheduling job 2021061321404638910521
[INFO] [2021-06-13 21:40:51,893] [7:140265872402176] - job_tracker.py[line:74]: save job 2021061321404638910521 component upload_0 on local 0 upload data_access metric data
[INFO] [2021-06-13 21:40:51,894] [7:140266826163968] - task_scheduler.py[line:28]: scheduling job 2021061321404638910521 tasks
[INFO] [2021-06-13 21:40:51,931] [7:140265872402176] - job_tracker.py[line:97]: save job 2021061321404638910521 component upload_0 on local 0 upload data_access metric meta
[INFO] [2021-06-13 21:40:51,946] [7:140266826163968] - job_saver.py[line:71]: try to update job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status
[INFO] [2021-06-13 21:40:51,953] [7:140266826163968] - job_saver.py[line:76]: update job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status update does not take effect: {'elapsed': None, 'end_time': None, 'job_id': '2021061321404638910521', 'party_id': '0', 'party_status': 'running', 'role': 'local', 'start_time': 1623620447613, 'status': 'running', 'task_id': '2021061321404638910521_upload_0', 'task_version': 0, 'update_time': 1623620446747}
[INFO] [2021-06-13 21:40:51,954] [7:140266826163968] - job_saver.py[line:81]: try to update job 2021061321404638910521 task 2021061321404638910521_upload_0 0
[INFO] [2021-06-13 21:40:51,991] [7:140266826163968] - job_saver.py[line:84]: job 2021061321404638910521 task 2021061321404638910521_upload_0 0 update successfully
[INFO] [2021-06-13 21:40:51,994] [7:140266826163968] - task_scheduler.py[line:143]: job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status is running, calculate by task party status list: ['running']
[INFO] [2021-06-13 21:40:51,995] [7:140266826163968] - task_scheduler.py[line:75]: finish scheduling job 2021061321404638910521 tasks
[INFO] [2021-06-13 21:40:51,995] [7:140266826163968] - dag_scheduler.py[line:310]: Job 2021061321404638910521 status is running, calculate by task status list: ['running']
[INFO] [2021-06-13 21:40:51,995] [7:140266826163968] - dag_scheduler.py[line:325]: finish scheduling job 2021061321404638910521
[INFO] [2021-06-13 21:40:52,019] [1978:140226325247808] - job_tracker.py[line:159]: task id 2021061321404638910521_upload_0 output data table is none
[INFO] [2021-06-13 21:40:52,026] [7:140265872402176] - job_saver.py[line:81]: try to update job 2021061321404638910521 task 2021061321404638910521_upload_0 0
[INFO] [2021-06-13 21:40:52,041] [7:140265872402176] - job_saver.py[line:84]: job 2021061321404638910521 task 2021061321404638910521_upload_0 0 update successfully
[INFO] [2021-06-13 21:40:52,047] [7:140265872402176] - job_saver.py[line:71]: try to update job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status
[INFO] [2021-06-13 21:40:52,063] [7:140265872402176] - job_saver.py[line:74]: update job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status successfully: {'job_id': '2021061321404638910521', 'component_name': 'upload_0', 'task_id': '2021061321404638910521_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'run_ip': '127.0.0.1', 'run_pid': 1978, 'party_status': 'success', 'end_time': 1623620452019, 'elapsed': 2091}
[INFO] [2021-06-13 21:40:52,079] [7:140265872402176] - job_saver.py[line:81]: try to update job 2021061321404638910521 task 2021061321404638910521_upload_0 0
[INFO] [2021-06-13 21:40:52,094] [7:140265872402176] - job_saver.py[line:84]: job 2021061321404638910521 task 2021061321404638910521_upload_0 0 update successfully
[INFO] [2021-06-13 21:40:52,099] [7:140265872402176] - job_saver.py[line:71]: try to update job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status
[INFO] [2021-06-13 21:40:52,103] [7:140265872402176] - job_saver.py[line:76]: update job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status update does not take effect: {'job_id': '2021061321404638910521', 'component_name': 'upload_0', 'task_id': '2021061321404638910521_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'run_ip': '127.0.0.1', 'run_pid': 1978, 'party_status': 'success', 'end_time': 1623620452019, 'elapsed': 2091}
[INFO] [2021-06-13 21:40:54,038] [7:140266826163968] - dag_scheduler.py[line:298]: scheduling job 2021061321404638910521
[INFO] [2021-06-13 21:40:54,040] [7:140266826163968] - task_scheduler.py[line:28]: scheduling job 2021061321404638910521 tasks
[INFO] [2021-06-13 21:40:54,072] [7:140266826163968] - job_saver.py[line:71]: try to update job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status
[INFO] [2021-06-13 21:40:54,080] [7:140266826163968] - job_saver.py[line:76]: update job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status update does not take effect: {'elapsed': 2091, 'end_time': 1623620452019, 'job_id': '2021061321404638910521', 'party_id': '0', 'party_status': 'success', 'role': 'local', 'start_time': 1623620447613, 'status': 'running', 'task_id': '2021061321404638910521_upload_0', 'task_version': 0, 'update_time': 1623620446747}
[INFO] [2021-06-13 21:40:54,080] [7:140266826163968] - job_saver.py[line:81]: try to update job 2021061321404638910521 task 2021061321404638910521_upload_0 0
[INFO] [2021-06-13 21:40:54,107] [7:140266826163968] - job_saver.py[line:84]: job 2021061321404638910521 task 2021061321404638910521_upload_0 0 update successfully
[INFO] [2021-06-13 21:40:54,114] [7:140266826163968] - task_scheduler.py[line:143]: job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status is success, calculate by task party status list: ['success']
[INFO] [2021-06-13 21:40:54,115] [7:140266826163968] - federated_scheduler.py[line:192]: job 2021061321404638910521 task 2021061321404638910521_upload_0 0 is success, sync to all party
[INFO] [2021-06-13 21:40:54,123] [7:140265872402176] - job_saver.py[line:71]: try to update job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status
[INFO] [2021-06-13 21:40:54,143] [7:140265872402176] - job_saver.py[line:74]: update job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status successfully: {'job_id': '2021061321404638910521', 'task_id': '2021061321404638910521_upload_0', 'task_version': '0', 'role': 'local', 'party_id': '0', 'status': 'success'}
[INFO] [2021-06-13 21:40:54,159] [7:140265872402176] - resource_manager.py[line:286]: task 2021061321404638910521_upload_0 0 return resource successfully
[INFO] [2021-06-13 21:40:54,168] [7:140265872402176] - job_tracker.py[line:424]: clean task 2021061321404638910521_upload_0 0 on local 0
[ERROR] [2021-06-13 21:40:54,171] [7:140265872402176] - job_tracker.py[line:475]: namespace dir /fate/data/2021061321404638910521_upload_0_0_local_0 does not exist
Traceback (most recent call last):
  File "/fate/python/fate_flow/operation/job_tracker.py", line 437, in clean_task
    sess.computing.cleanup(namespace=computing_temp_namespace, name="*")
  File "/fate/python/fate_arch/computing/standalone/_csession.py", line 73, in cleanup
    return self._session.cleanup(name=name, namespace=namespace)
  File "/fate/python/fate_arch/_standalone.py", line 383, in cleanup
    raise EnvironmentError(f"namespace dir {namespace_dir} does not exist")
OSError: namespace dir /fate/data/2021061321404638910521_upload_0_0_local_0 does not exist
[INFO] [2021-06-13 21:40:54,190] [7:140266826163968] - federated_scheduler.py[line:195]: sync job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status success to all party success
[INFO] [2021-06-13 21:40:54,190] [7:140266826163968] - federated_scheduler.py[line:202]: try to stop job 2021061321404638910521 task 2021061321404638910521_upload_0 0
[INFO] [2021-06-13 21:40:54,208] [7:140265872402176] - job_utils.py[line:397]: try to stop job 2021061321404638910521 task 2021061321404638910521_upload_0 local 0 with success party status process pid:1978
[INFO] [2021-06-13 21:40:54,209] [7:140265872402176] - job_utils.py[line:400]: can not found job 2021061321404638910521 task 2021061321404638910521_upload_0 local 0 with success party status process pid:1978
[INFO] [2021-06-13 21:40:54,214] [7:140265872402176] - job_utils.py[line:424]: start run subprocess to stop task session 2021061321404638910521_upload_0_0_local_0
[INFO] [2021-06-13 21:40:54,214] [7:140265872402176] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061321404638910521_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop
[INFO] [2021-06-13 21:40:54,228] [7:140265872402176] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061321404638910521_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop successfully, pid is 1999
[INFO] [2021-06-13 21:40:54,230] [7:140265872402176] - task_controller.py[line:255]: job 2021061321404638910521 task 2021061321404638910521_upload_0 0 on local 0 process 1978 kill success
[INFO] [2021-06-13 21:40:54,231] [7:140265872402176] - job_saver.py[line:71]: try to update job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status
[INFO] [2021-06-13 21:40:54,240] [7:140265872402176] - job_saver.py[line:76]: update job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status update does not take effect: {'job_id': '2021061321404638910521', 'task_id': '2021061321404638910521_upload_0', 'task_version': 0, 'role': 'local', 'party_id': '0', 'party_status': 'success'}
[INFO] [2021-06-13 21:40:54,249] [7:140265872402176] - job_saver.py[line:81]: try to update job 2021061321404638910521 task 2021061321404638910521_upload_0 0
[WARNING] [2021-06-13 21:40:54,254] [7:140265872402176] - job_saver.py[line:86]: job 2021061321404638910521 task 2021061321404638910521_upload_0 0 update does not take effect
[INFO] [2021-06-13 21:40:54,266] [7:140266826163968] - federated_scheduler.py[line:206]: stop job 2021061321404638910521 task 2021061321404638910521_upload_0 0 success
[INFO] [2021-06-13 21:40:54,266] [7:140266826163968] - task_scheduler.py[line:75]: finish scheduling job 2021061321404638910521 tasks
[INFO] [2021-06-13 21:40:54,266] [7:140266826163968] - dag_scheduler.py[line:310]: Job 2021061321404638910521 status is success, calculate by task status list: ['success']
[INFO] [2021-06-13 21:40:54,267] [7:140266826163968] - federated_scheduler.py[line:78]: try to save job 2021061321404638910521 pipelined model
[INFO] [2021-06-13 21:40:54,272] [7:140265872402176] - job_controller.py[line:331]: job 2021061321404638910521 on local 0 start to save pipeline
[INFO] [2021-06-13 21:40:54,287] [7:140265872402176] - job_controller.py[line:374]: job 2021061321404638910521 on local 0 save pipeline successfully
[INFO] [2021-06-13 21:40:54,292] [7:140266826163968] - federated_scheduler.py[line:81]: save job 2021061321404638910521 pipelined model success
[INFO] [2021-06-13 21:40:54,292] [7:140266826163968] - federated_scheduler.py[line:68]: job 2021061321404638910521 is success, sync to all party
[INFO] [2021-06-13 21:40:54,297] [7:140265872402176] - job_saver.py[line:45]: try to update job 2021061321404638910521 status to success
[INFO] [2021-06-13 21:40:54,314] [7:140265872402176] - job_saver.py[line:48]: update job 2021061321404638910521 status successfully
[INFO] [2021-06-13 21:40:54,343] [7:140265872402176] - resource_manager.py[line:176]: return job 2021061321404638910521 resource(cores 4 memory 0) on local 0 successfully, remaining cores: 20 remaining memory: 0
[INFO] [2021-06-13 21:40:54,347] [7:140266826163968] - federated_scheduler.py[line:71]: sync job 2021061321404638910521 status success to all party success
[INFO] [2021-06-13 21:40:54,354] [7:140266826163968] - job_saver.py[line:45]: try to update job 2021061321404638910521 status to success
[INFO] [2021-06-13 21:40:54,362] [7:140266826163968] - job_saver.py[line:56]: update job 2021061321404638910521 status does not take effect
[INFO] [2021-06-13 21:40:54,362] [7:140266826163968] - job_saver.py[line:61]: try to update job 2021061321404638910521
[WARNING] [2021-06-13 21:40:54,369] [7:140266826163968] - job_saver.py[line:66]: job 2021061321404638910521 update does not take effect: {'job_id': '2021061321404638910521', 'role': 'local', 'party_id': '0', 'status': 'success'}
[INFO] [2021-06-13 21:40:54,369] [7:140266826163968] - dag_scheduler.py[line:502]: Job 2021061321404638910521 finished with success, do something...
[INFO] [2021-06-13 21:40:54,369] [7:140266826163968] - dag_scheduler.py[line:436]: request stop job 2021061321404638910521 with success
[INFO] [2021-06-13 21:40:54,376] [7:140266826163968] - dag_scheduler.py[line:445]: request stop job 2021061321404638910521 with success to all party
[INFO] [2021-06-13 21:40:54,376] [7:140266826163968] - federated_scheduler.py[line:88]: try to stop job 2021061321404638910521
[INFO] [2021-06-13 21:40:54,389] [7:140265872402176] - job_utils.py[line:397]: try to stop job 2021061321404638910521 task 2021061321404638910521_upload_0 local 0 with success party status process pid:1978
[INFO] [2021-06-13 21:40:54,389] [7:140265872402176] - job_utils.py[line:400]: can not found job 2021061321404638910521 task 2021061321404638910521_upload_0 local 0 with success party status process pid:1978
[INFO] [2021-06-13 21:40:54,391] [7:140265872402176] - job_utils.py[line:424]: start run subprocess to stop task session 2021061321404638910521_upload_0_0_local_0
[INFO] [2021-06-13 21:40:54,392] [7:140265872402176] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061321404638910521_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop
[INFO] [2021-06-13 21:40:54,399] [7:140265872402176] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061321404638910521_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop successfully, pid is 2003
[INFO] [2021-06-13 21:40:54,399] [7:140265872402176] - task_controller.py[line:255]: job 2021061321404638910521 task 2021061321404638910521_upload_0 0 on local 0 process 1978 kill success
[INFO] [2021-06-13 21:40:54,399] [7:140265872402176] - job_saver.py[line:71]: try to update job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status
[INFO] [2021-06-13 21:40:54,403] [7:140265872402176] - job_saver.py[line:76]: update job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status update does not take effect: {'job_id': '2021061321404638910521', 'task_id': '2021061321404638910521_upload_0', 'task_version': 0, 'role': 'local', 'party_id': '0', 'party_status': 'success'}
[INFO] [2021-06-13 21:40:54,408] [7:140265872402176] - job_saver.py[line:81]: try to update job 2021061321404638910521 task 2021061321404638910521_upload_0 0
[WARNING] [2021-06-13 21:40:54,413] [7:140265872402176] - job_saver.py[line:86]: job 2021061321404638910521 task 2021061321404638910521_upload_0 0 update does not take effect
[INFO] [2021-06-13 21:40:54,418] [7:140265872402176] - job_saver.py[line:45]: try to update job 2021061321404638910521 status to success
[INFO] [2021-06-13 21:40:54,425] [7:140265872402176] - job_saver.py[line:56]: update job 2021061321404638910521 status does not take effect
[INFO] [2021-06-13 21:40:54,430] [7:140266826163968] - federated_scheduler.py[line:92]: stop job 2021061321404638910521 success
[INFO] [2021-06-13 21:40:54,430] [7:140266826163968] - dag_scheduler.py[line:448]: stop job 2021061321404638910521 with success successfully
[INFO] [2021-06-13 21:40:54,430] [7:140266826163968] - federated_scheduler.py[line:107]: try to clean job 2021061321404638910521
[INFO] [2021-06-13 21:40:54,436] [7:140265872402176] - job_controller.py[line:379]: Job 2021061321404638910521 on local 0 start to clean
[INFO] [2021-06-13 21:40:54,437] [7:140265872402176] - job_controller.py[line:382]: job 2021061321404638910521 on local 0 clean done
[INFO] [2021-06-13 21:40:54,442] [7:140266826163968] - federated_scheduler.py[line:110]: clean job 2021061321404638910521 success
[INFO] [2021-06-13 21:40:54,442] [7:140266826163968] - dag_scheduler.py[line:505]: Job 2021061321404638910521 finished with success, done
[INFO] [2021-06-13 21:40:54,442] [7:140266826163968] - dag_scheduler.py[line:325]: finish scheduling job 2021061321404638910521
[INFO] [2021-06-13 21:40:54,495] [7:140266826163968] - dag_scheduler.py[line:298]: scheduling job 2021061321404638910521
[INFO] [2021-06-13 21:40:54,497] [7:140266826163968] - task_scheduler.py[line:28]: scheduling job 2021061321404638910521 tasks
[INFO] [2021-06-13 21:40:54,512] [7:140266826163968] - task_scheduler.py[line:143]: job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status is success, calculate by task party status list: ['success']
[INFO] [2021-06-13 21:40:54,512] [7:140266826163968] - task_scheduler.py[line:75]: finish scheduling job 2021061321404638910521 tasks
[INFO] [2021-06-13 21:40:54,512] [7:140266826163968] - dag_scheduler.py[line:310]: Job 2021061321404638910521 status is success, calculate by task status list: ['success']
[INFO] [2021-06-13 21:40:54,512] [7:140266826163968] - dag_scheduler.py[line:502]: Job 2021061321404638910521 finished with success, do something...
[INFO] [2021-06-13 21:40:54,512] [7:140266826163968] - dag_scheduler.py[line:436]: request stop job 2021061321404638910521 with success
[INFO] [2021-06-13 21:40:54,525] [7:140266826163968] - dag_scheduler.py[line:445]: request stop job 2021061321404638910521 with success to all party
[INFO] [2021-06-13 21:40:54,525] [7:140266826163968] - federated_scheduler.py[line:88]: try to stop job 2021061321404638910521
[INFO] [2021-06-13 21:40:54,542] [7:140265872402176] - job_utils.py[line:397]: try to stop job 2021061321404638910521 task 2021061321404638910521_upload_0 local 0 with success party status process pid:1978
[INFO] [2021-06-13 21:40:54,543] [7:140265872402176] - job_utils.py[line:400]: can not found job 2021061321404638910521 task 2021061321404638910521_upload_0 local 0 with success party status process pid:1978
[INFO] [2021-06-13 21:40:54,545] [7:140265872402176] - job_utils.py[line:424]: start run subprocess to stop task session 2021061321404638910521_upload_0_0_local_0
[INFO] [2021-06-13 21:40:54,545] [7:140265872402176] - job_utils.py[line:310]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061321404638910521_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop
[INFO] [2021-06-13 21:40:54,553] [7:140265872402176] - job_utils.py[line:334]: start process command: python3 /fate/python/fate_flow/utils/session_utils.py -j 2021061321404638910521_upload_0_0_local_0 --computing STANDALONE --federation STANDALONE --storage STANDALONE -c stop successfully, pid is 2007
[INFO] [2021-06-13 21:40:54,553] [7:140265872402176] - task_controller.py[line:255]: job 2021061321404638910521 task 2021061321404638910521_upload_0 0 on local 0 process 1978 kill success
[INFO] [2021-06-13 21:40:54,554] [7:140265872402176] - job_saver.py[line:71]: try to update job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status
[INFO] [2021-06-13 21:40:54,564] [7:140265872402176] - job_saver.py[line:76]: update job 2021061321404638910521 task 2021061321404638910521_upload_0 0 status update does not take effect: {'job_id': '2021061321404638910521', 'task_id': '2021061321404638910521_upload_0', 'task_version': 0, 'role': 'local', 'party_id': '0', 'party_status': 'success'}
[INFO] [2021-06-13 21:40:54,572] [7:140265872402176] - job_saver.py[line:81]: try to update job 2021061321404638910521 task 2021061321404638910521_upload_0 0
[WARNING] [2021-06-13 21:40:54,578] [7:140265872402176] - job_saver.py[line:86]: job 2021061321404638910521 task 2021061321404638910521_upload_0 0 update does not take effect
[INFO] [2021-06-13 21:40:54,585] [7:140265872402176] - job_saver.py[line:45]: try to update job 2021061321404638910521 status to success
[INFO] [2021-06-13 21:40:54,596] [7:140265872402176] - job_saver.py[line:56]: update job 2021061321404638910521 status does not take effect
[INFO] [2021-06-13 21:40:54,603] [7:140266826163968] - federated_scheduler.py[line:92]: stop job 2021061321404638910521 success
[INFO] [2021-06-13 21:40:54,603] [7:140266826163968] - dag_scheduler.py[line:448]: stop job 2021061321404638910521 with success successfully
[INFO] [2021-06-13 21:40:54,604] [7:140266826163968] - federated_scheduler.py[line:107]: try to clean job 2021061321404638910521
[INFO] [2021-06-13 21:40:54,625] [7:140266400880384] - job_controller.py[line:379]: Job 2021061321404638910521 on local 0 start to clean
[INFO] [2021-06-13 21:40:54,625] [7:140266400880384] - job_controller.py[line:382]: job 2021061321404638910521 on local 0 clean done
[INFO] [2021-06-13 21:40:54,630] [7:140266826163968] - federated_scheduler.py[line:110]: clean job 2021061321404638910521 success
[INFO] [2021-06-13 21:40:54,630] [7:140266826163968] - dag_scheduler.py[line:505]: Job 2021061321404638910521 finished with success, done
[INFO] [2021-06-13 21:40:54,630] [7:140266826163968] - dag_scheduler.py[line:325]: finish scheduling job 2021061321404638910521
[INFO] [2021-06-13 21:40:54,935] [1999:140669232092992] - session_utils.py[line:38]: start stop session 2021061321404638910521_upload_0_0_local_0
[INFO] [2021-06-13 21:40:54,936] [1999:140669232092992] - session_utils.py[line:47]: stop session 2021061321404638910521_upload_0_0_local_0 success
[INFO] [2021-06-13 21:40:55,083] [2003:140054450607936] - session_utils.py[line:38]: start stop session 2021061321404638910521_upload_0_0_local_0
[INFO] [2021-06-13 21:40:55,083] [2003:140054450607936] - session_utils.py[line:47]: stop session 2021061321404638910521_upload_0_0_local_0 success
[INFO] [2021-06-13 21:40:55,234] [2007:140397442402112] - session_utils.py[line:38]: start stop session 2021061321404638910521_upload_0_0_local_0
[INFO] [2021-06-13 21:40:55,234] [2007:140397442402112] - session_utils.py[line:47]: stop session 2021061321404638910521_upload_0_0_local_0 success
[INFO] [2021-06-13 21:40:56,682] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:40:58,725] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:41:00,771] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:41:02,817] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:41:04,883] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:41:06,933] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:41:08,982] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:41:11,046] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:41:13,098] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:41:15,147] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:41:17,246] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:41:19,307] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:41:21,400] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:41:23,439] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:41:25,506] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:41:27,560] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:41:29,628] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:41:31,680] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:41:33,729] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:41:35,792] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:41:37,864] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:41:39,935] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:41:41,989] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:41:44,048] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:41:46,123] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:41:48,198] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:41:50,250] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:41:52,304] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:41:54,358] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:41:56,415] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:41:58,467] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:42:00,520] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:42:02,565] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:42:04,611] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:42:06,648] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:42:08,708] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:42:10,760] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:42:12,823] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:42:14,894] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:42:16,947] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:42:19,007] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:42:21,060] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:42:23,124] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:42:25,176] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:42:27,228] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:42:29,295] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:42:31,344] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:42:33,386] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:42:35,436] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:42:37,487] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:42:39,537] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:42:41,593] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:42:43,643] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:42:45,690] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:42:47,731] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:42:49,783] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:42:51,842] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:42:53,891] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:42:55,933] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:42:57,985] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:00,031] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:02,082] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:04,146] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:06,203] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:08,241] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:10,298] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:12,350] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:14,430] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:16,483] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:18,518] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:20,571] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:22,621] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:24,682] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:26,731] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:28,780] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:30,831] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:32,886] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:34,939] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:37,000] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:39,049] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:41,098] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:43,152] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:45,206] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:47,268] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:49,317] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:51,385] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:53,439] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:55,492] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:57,562] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:43:59,600] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:44:01,638] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:44:03,737] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:44:05,784] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:44:07,841] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:44:09,891] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:44:11,943] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:44:14,003] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:44:16,064] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:44:18,127] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:44:20,181] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:44:22,234] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:44:24,285] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:44:26,316] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:44:28,366] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:44:30,432] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:44:32,493] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:44:34,544] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:44:36,595] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:44:38,652] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:44:40,696] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:44:42,748] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:44:44,799] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:44:46,867] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:44:48,907] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:44:50,951] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:44:53,014] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:44:55,067] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:44:57,145] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:44:59,193] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:45:01,293] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:45:03,341] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:45:05,391] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:45:07,473] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:45:09,528] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:45:11,581] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:45:13,660] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:45:15,702] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:45:17,753] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:45:19,794] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:45:21,855] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:45:23,893] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:45:25,955] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:45:28,003] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:45:30,054] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:45:32,112] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:45:34,164] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:45:36,211] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:45:38,265] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:45:40,293] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:45:42,347] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:45:44,400] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:45:46,463] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:45:48,507] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:45:50,552] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
[INFO] [2021-06-13 21:45:52,602] [7:140266826163968] - dag_scheduler.py[line:193]: the number of updates has been exceeded
